### ISSUE TITLE
this.client.setValue and PhantomJS causes CommandErrorWebdriverIO CommandError (Promise never resolved with an truthy value)

### ISSUE THREAD

**Issue by samhatoum** [xolvio/chimp#100]
_From @abecks on August 20, 2015 16:29_

```js
this.When(/^I set "([^"]*)" to "([^"]*)"$/, function(selector, value, callback) {
    return this.client.setValue(selector, value);
  });
```

Runs perfectly when Chimp is using Chrome to test. However, after switching to PhantomJS, I receive the error:

```js
[chimp] Detected an unhandledRejection.
[chimp][hooks] Reason:
[chimp][hooks] CommandErrorWebdriverIO CommandError (Promise never resolved with an truthy value)
[chimp][hooks] This usually happens when WebdriverIO assertions fail or timeout.
```

Is there any way I could debug this further?

_Copied from original issue: xolvio/meteor-cucumber#199_

**Comment by samhatoum** [comment]
it's likely that phantom is not loading the page for some reason. You can try peaking at the view by taking a screenshot

Another option is to run a `phantom --webdriver 4444` server in debug mode and then using the HUB_PORT env var to 4444.

**Comment by samhatoum** [comment]
_From @ibussieres on October 5, 2015 14:54_

I am having a similar issue, @abecks, dis you resolve this ?

**Comment by samhatoum** [comment]
try the synchronous style instead (default on the latest update). See here https://chimp.readme.io/docs/synchronous-tests

**Comment by ibussieres** [comment]
ˆ This worked for me, by the way.
