### ISSUE TITLE
Signing in successfully but not remaining signed in when navigating

### ISSUE THREAD

**Issue by samhatoum** [xolvio/chimp#101]
_From @philipobrien on August 20, 2015 10:47_

Here is my feature file

```cucumber
Background:
    Given The processor analyst is signed in

  @dev
  Scenario: A processor analyst can view long term predictions
    When The processor analyst navigates to "/dashboard"
    Then The processor analyst should see the heading "Long Term Prediction"
```

and my step definitions

```js
this.Given(/^The processor analyst is signed in$/, function (callback) {
            this.client.
                url(process.env.ROOT_URL).
                waitForExist('.at-pwd-form').
                waitForVisible('.at-pwd-form').
                setValue('input#at-field-email', 'me@mail.com').
                setValue('input#at-field-password', 'mypassword').
                submitForm('#at-pwd-form').
                call(callback);
        });

        this.When(/^The processor analyst navigates to "([^"]*)"$/, function (arg1, callback) {
            this.client.
                url(url.resolve(process.env.ROOT_URL, arg1)). // process.env.ROOT_URL points to the app
                waitForExist("body *").
                call(callback);
        });

        this.Then(/^The processor analyst should see the heading "([^"]*)"$/, function (arg1, callback) {
            this.client.
                waitForExist('body *'). // WebdriverIO chain-able promise magic
                waitForExist('#long-term-prediction', 100).
                getTitle().should.become(arg1);
        });
```

the login is successful and although the navigation to `/dashboard` *seems* successful, i.e. it passes, none of the elements that should be on that page become visible. Instead the `useraccounts` **at-pwd-form** is visible, which suggests I have been logged out again. 

The actual error in the logs is

```console
[chimp] Detected an unhandledRejection.
[chimp][hooks] Reason:
[chimp][hooks] CommandErrorWebdriverIO CommandError (Promise never resolved with an truthy value)
[chimp][hooks] This usually happens when WebdriverIO assertions fail or timeout.
HINT: Check the step AFTER [When The processor analyst navigates to "/dashboard"] (/features/processor/processor_view_prediction.feature: >12)
```

If I change the 2nd step to this 

```js
this.When(/^The processor analyst navigates to "([^"]*)"$/, function (arg1, callback) {
            this.client.
                waitForExist('#long-term-prediction').
                call(callback);
        });
```
then that step passes. It seems to be an issue with the use of `url(url.resolve(process.env.ROOT_URL, arg1))`

_Copied from original issue: xolvio/meteor-cucumber#198_

**Comment by samhatoum** [comment]
_From @nicolsondsouza on September 3, 2015 12:41_

+1

**Comment by philcruz** [comment]
I think I'm hitting a similar issue. Though in my case, the user fills out the registration form with username password, the form is submitted. Looking at the database I can see the new user is created. But the last step where a certain menu item should appear when logged in doesn't appear. I can see this in the Chrome browser as well. If I then manually login myself it works as expected. 

    (function () {

	'use strict';

	module.exports = function () {

		this.Given(/^I am not logged in$/, function () {
			client.url(process.env.ROOT_URL);
		});

		this.When(/^I go to the registration form$/, function () {
			client.url( process.env.ROOT_URL + 'sign-up');
		});

		this.When(/^I fill in the form$/, function () {
			client.setValue('#at-field-username', 'cucumbertest1');
			client.setValue('#at-field-email', 'cucumbertest1@gmail.com');
			client.setValue('#at-field-password', 'letmein');
			client.setValue('#at-field-password_again', 'letmein');
		});

		this.When(/^I click the button "([^"]*)"$/, function (arg1) {
			client.click('#at-btn');
			client.url( process.env.ROOT_URL + 'projects');
		});

		this.Then(/^I should see a menu called "([^"]*)"$/, function (expectedLinkText) {
			client.waitForExist('#project-dropdown');
			expect(client.getText('#project-dropdown')).toEqual(expectedLinkText);
		});

	}

    })();

What could be the issue?

**Comment by samhatoum** [comment]
@philcruz sorry for the 6month delay. Any luck with this?

**Comment by philcruz** [comment]
I don't recall resolving this but I'm not currently working on the project so it's not an issue for me.

**Comment by samhatoum** [comment]
ok thanks. Closing
