### ISSUE TITLE
Where to find documentation for this.client, this.browser, this.server

### ISSUE THREAD

**Issue by samhatoum** [xolvio/chimp#107]
_From @abecks on August 14, 2015 19:18_

Just starting out with Cucumber. I've read the Meteor Testing Manual, but the API for this.client, this.server and this.browser are unknown to me. Where would I find the documentation for these APIs?

_Copied from original issue: xolvio/meteor-cucumber#190_

**Comment by samhatoum** [comment]
_From @Sanjo on August 14, 2015 20:15_

this.client and this.browser are aliases (the same). They reference to a WebdriverIO instance. You can find the API [here](http://webdriver.io/api.html).

this.server is a DDP connection. You can use this.server.call and this.server.apply the same way as Meteor.call and Meteor.apply.

You can find all the available documentation here:

* https://velocity.readme.io/docs/getting-started-with-cucumber
* https://chimp.readme.io/

Please let us know if you have other unanswered questions.

I keep this issue open, because we need to improve the documentation.

**Comment by samhatoum** [comment]
_From @abecks on August 14, 2015 21:31_

This is great. Thanks.

I do have a question about chaining the ``then`` method from ``this.client``:

```
this.Given(/^I am not logged in$/, function(callback) {
    // Navigate to the application
    this.client
      .url(process.env.ROOT_URL)
      .executeAsync(function(done) {
        Meteor.logout();
        done();
      }).then(callback);
  });
```

causes the test to fail:
```
    Given I am not logged in      # features/login/login.feature:11
      [object Object]
```

But it works like this:
```
this.Given(/^I am not logged in$/, function(callback) {
    // Navigate to the application
    this.client
      .url(process.env.ROOT_URL)
      .executeAsync(function(done) {
        Meteor.logout();
        done();
      }).then(function(){
        callback();
      });
  });
```

Is the signature for ``then`` not compatible with ``callback`` because ``callback`` is expecting an error object as the first argument? And ``then`` is just returning an object from Selenium but not necessarily an error? Is this the correct usage of ``then``?

Would this be better usage:
```
this.Given(/^I am not logged in$/, function(callback) {
    // Navigate to the application
    return this.client
      .url(process.env.ROOT_URL)
      .executeAsync(function(done) {
        Meteor.logout();
        done();
      });
  });
```


I keep coming across this error:
````
[chimp] Detected an unhandledRejection.
[chimp][hooks] Reason:
[chimp][hooks] NoSuchElement
[chimp][hooks] An element could not be located on the page using the given search parameters.
[chimp] Finished running async processes with errors
[chimp] run complete with errors Cucumber steps failed
```

But I really have no idea whats causing it. For example, it happens with the following:
```
this.When(/^I submit the login form$/, function(callback) {
    return this.client
      .setValue('input[name=username]', 'admin')
      .setValue('input[name=password]', '1234')
      .executeAsync(function(done) {
        $("#loginForm").submit();
        done();
      });
  });
```
I believe there is an error with one of the setValue methods, so they don't appear to be chainable? When used individually they return the proper error to Cucumber, when chained, they return the generic error above.

Some common patterns would be very useful. It took me a couple hours to get up to speed on some re-usable tests:

```
  this.When(/^I navigate to "([^"]*)"$/, function(path, callback) {
    return this.client.url(process.env.ROOT_URL + path);
  });

  this.Then(/^I should see the element "([^"]*)"$/, function(selector, callback) {
    return this.client.waitForExist(selector, 5000);
  });
```

**Comment by abecks** [comment]
Hey @samhatoum what is happening here? Is chimp the new home for the cucumber testing package? Should I be switching anything?

I noticed that this repo is not Meteor specific yet some of my issues may be.

**Comment by samhatoum** [comment]
Hey!

I've merged chimp and meteor-cucumber into one repo, since they share the same code.

Soon I will also rename xolvio:cucumber to xolvio:chimp

Please file any meteor issues on the chimp repo as well

**Comment by samhatoum** [comment]
> Should I be switching anything?

@abecks you don't need to do anything, it just makes our release process easier

**Comment by samhatoum** [comment]
@albecks with regards to your second query, the latest version of chimp/meteor-cucumber no longer uses the `then` syntax by default and is not synchronous. Have you tried it and did that fix your issues?

**Comment by abecks** [comment]
Hey @samhatoum,

I'm trying to revive my tests after all of the updates to Meteor and Chimp/Cucumber. I'm getting confused over all of the tech involved. Can you clarify the layers of tech?

* Chimp is an abstraction of Selenium + Jasmine/Cucumber
* Jasmine/Cucumber are testing libraries
* Selenium is the browser controller
* Webdriver IO is an abstraction of Selenium for node

I think a graphic that broke down the different layers of tech involved would help beginners adopt this suite more. As it stands, it's pretty confusing to learn if you haven't done any TDD before.

Heres a test that worked on Meteor 1.0 and now fails with the new updates:
```js
  this.Given(/^I am not logged in$/, function(callback) {
    // Navigate to the application
    return this.client
      .url(process.env.ROOT_URL)
      .executeAsync(function(done) {
        Meteor.logout();
        done();
      });
  });
```

and the error:
```
Object #<Object> has no method 'executeAsync'
```

I still see the method listed in the WebdriverIO API, so I'm assuming that I need to rewrite these tests? Looking at your awesome new tutorial at https://chimp.readme.io/docs/tutorial suggests to me that I need to replace my ``this.client`` with ``browser``.  Is there a similar variable for running commands on the server?

**Comment by abecks** [comment]
I just found the migration guide. Looks like the documentation is starting to come together! I think I can take it from here. Thanks @samhatoum I think this issue can be closed now.
