### ISSUE TITLE
Examples of common uses in documentation

### ISSUE THREAD

**Issue by samhatoum** [xolvio/chimp#110]
_From @jonlachlan on June 29, 2015 5:47_

As someone new to tests, I found the documentation for this package to be quite confusing. It took me a long time to figure out which components were part of each bit of code -- and therefore it was difficult to know which APIs to reference. For example, I have never used nor have I heard of WebdriverIO, and based on the docs I know that "it is auto-configured with PhantomJS", but I don't know that it's an API for selecting and querying the DOM. It would be helpful to state what WebdriverIO is doing for you. At least point people to http://webdriver.io/api.html and say that it is used for selecting and querying page elements. 

It is also confusing as a newcomer that many lines of step code have first WebdriverIO selection functions, and then Chai assertions. Again, it's about knowing which APIs to reference.

It would also be helpful to have some examples that show the most common ways of querying the DOM using WebdriverIO -- such as click, getText, getAttribute, setValue, waitForExist, pause -- and the most common ways of making assertions using Chai -- such as should.match and should.be (and the promis-ified equivalents, should.eventually.match and should.become)

Some other "pitfalls" that added many hours to my quest for passing cucumber tests:
- Scenarios need to have the `@dev` flag in order to be run by default
- Snapshots appear in the tests/cucumber/.snapshots folder (again, needs the `@dev` flag)
- After a Chai function such as `should.become('my text')`, use `and.notify(callback)`. After a WebdriverIO function such as `click('#my-element')`, use the "traditional" `call(callback)`.

I'm sure that all of the components would be too hard for me to set up by myself, so I'm super appreciative of this package. I just hope the docs for this package become more welcoming to newcomers, as Meteor is generally.

_Copied from original issue: xolvio/meteor-cucumber#150_

**Comment by samhatoum** [comment]
Thank you so much for posting this. I'm in the process of redoing the docs and this is invaluable for me

appreciate it a lot!

**Comment by ramijarrar** [comment]
@samhatoum The [cheat sheet](https://chimp.readme.io/docs/cheat-sheet) now probably covers this pretty well?

**Comment by samhatoum** [comment]
Indeed it does. Thanks
