### ISSUE TITLE
Restricts logging of whitelisted ENVs during debug mode

### ISSUE THREAD

**Issue by samhatoum** [xolvio/chimp#129]
_From @rhyslbw on September 27, 2015 6:45_

Fixes a security issue where previously all ENVs would be logged during debug mode, potentially exposing sensitive data. This fix introduces a whitelist and uses Underscore pick to filter the process.env object.

_Copied from original issue: xolvio/meteor-cucumber/pull/213_

**Comment by rhyslbw** [comment]
https://github.com/xolvio/chimp/pull/134
