### ISSUE TITLE
Phantom, HTTPS, and reports

### ISSUE THREAD

**Issue by sgrover** [xolvio/chimp#130]
I have two issues I'm looking for help/guideance on.  I've checked the documentation and Google but am not finding the right info yet.
1. How do I generate an HTML report?  If I set the command line "format" option to html (i.e. --format=html), I am getting errors.  It looks like the html formatter is not available with a standard chimp install.  Is there another package I need or a trick I'm not aware of?  The goal is to provide a summary report that can be used for trend analysis.  (My reporting knowledge may not be adequate here...)
2. When I set my browser to phantomjs, none of my pages are loading.  The site is using HTTPS.  Google tells me there are some options to pass to phantom (ignore-ssl-errors, ssl-protocol=any), but I do not see a way to tell Chimp to pass those arguments.  Including them on the command line does not make any difference.  

So, I'm looking for some guidance on how/where to change the configuration that Chimp uses to talk with Phantom and Cucumber.  

Thanks for any tips/links/suggestions.  (still learning my way around the Node way of doing things!)

**Comment by BernsteinA** [comment]
bump. +1
requesting `ignore-ssl-errors`

**Comment by PierreCBSI** [comment]
I'm in a similar situation, trying to generate a html report but struggling with the commandline args.... What's the solution?

**Comment by samhatoum** [comment]
You can use this tool to generate a junit report from the cucumber json
https://github.com/stjohnjohnson/cucumber-junit

**Comment by samhatoum** [comment]
@sgrover sorry for the long delays. We now support a custom config file so you should be able to do it. check out chimp.readme.io

**Comment by vigneshmanogar** [comment]
Thanks for the great tool guys. 

I have one issue. Tests work fine when using phantomJS on my production server. But fail when using phantomJS on my localhost. 'Browser.getUrl' seems to return 'about:blank'. I am assuming that it could be because of ssl issues. Below, related section from my configuration file.

```
      // - - - - WEBDRIVER-IO  - - - -
      webdriverio: {
            desiredCapabilities: {
                  javascriptEnabled: true,
                  acceptSslCerts: true
            },
            logLevel: 'verbose',
            // logOutput: null,
            host: '127.0.0.1',
            port: 4444,
            path: '/wd/hub',
            baseUrl: null,
            coloredLogs: true,
            screenshotPath: './fails',
            waitforTimeout: 500,
            waitforInterval: 250,
      },

```

Can you let me know if this is the right way of using it..? Thanks again.

**Comment by eriben** [comment]
Added a Pull Request for the SSL issue, when running PhantomJS over localhost:

https://github.com/xolvio/chimp/pull/402

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy
https://github.com/TheBrainFamily/chimpy/issues
