### ISSUE TITLE
Cannot understand how the test session is killed

### ISSUE THREAD

**Issue by dusual** [xolvio/chimp#135]
I am trying to run BDD tests using chimp. However I can't understand how the session is killed / ends once the tests are done.

It seems I need to add one of the watchTags otherwise I get this

PASSED cucumber : No specs were run => @dev,@watch,@focus not detected

however when they are added:

1 scenario (1 passed)
3 steps (3 passed)

[chimp][hooks] Starting AfterFeatures
[chimp][hooks] Ending browser session

[chimp][session-manager] watch / server mode are true, not killing session

[chimp][hooks] Ended browser sessions
[chimp][hooks] Finished AfterFeatures

[chimp][cucumber] Closed with code 0
[chimp][cucumber] Cucumber not in a stopping state
[chimp] Finished running async processes
[chimp] interrupting
[chimp] 2 processes to interrupt
[chimp][cucumber] interrupting cucumber
[chimp][cucumber] kill called on cucumber process with pid 4467
[chimp][cucumber] checking if process exists
[chimp][cucumber] cucumber process does not exists, ignoring
[chimp][selenium] interrupt called
[chimp][selenium] interrupt is not killing selenium because clean-selenium-server not set
[chimp] Finished interrupting processes
[chimp] run complete

Note:
[chimp][session-manager] watch / server mode are true, not killing session

How do I kill the session if it requires to be in watch mode to run?

**Comment by samhatoum** [comment]
What's your use-case?

**Comment by dusual** [comment]
I think I might have been slightly confused. I was trying to explicitly kill the browser session because it was not getting killed automatically after the tests were done running. But then I saw this log and thought this might have been the reason why the browser session was not killed. Might have been something to do with problems initiating the browser in couple of other jasmine tests that i was running.

**Comment by samhatoum** [comment]
I see. Happy to help! Can I close this now?
