### ISSUE TITLE
Screenshots always captured in development

### ISSUE THREAD

**Issue by nhantamdo** [xolvio/chimp#136]
Using xolvio:cucumber@0.19.3_1
I've set SAVE_SCREENSHOTS=1 SAVE_SCREENSHOTS_ON_ERROR=1 but the screenshosts are always captured regardless of passed/failed tests.
I want to save screenshots only on failed tests. Is there a documents on all of the env variables?

Thanks,

**Comment by samhatoum** [comment]
This was a bug that's not fixed. Will update the docs with the description of env vars soon

**Comment by SierraGolf** [comment]
confirmed
