### ISSUE TITLE
Performance: Velocity downgrading meteor version on every mirror start 

### ISSUE THREAD

**Issue by workflow** [xolvio/chimp#144]
Hi,

I was wondering whether the downgrade of meteor happening here:

`[cucumber.log] => Using velocity:METEOR@1.2.0.2_1 as requested (overriding Meteor 1.2.1)`

...is a requirement/design decision? Is there a flag somewhere to just use the current release?

The problem is that this downgrading process takes quite long, and does not get cached.

Here's an example that runs for almost 5 minutes on CircleCI, on every run:

```
export CUCUMBER_SCREENSHOTS_DIR="$CIRCLE_ARTIFACTS/screenshots/chrome"
export CUCUMBER_JSON_OUTPUT="$CIRCLE_TEST_REPORTS/chrome.cucumber"
export SELENIUM_BROWSER="chrome"
node ./tests/ci/velocity.js
Starting Meteor
[velocity] is in continuous integration mode
** You are using the appcache package but the total size of the
** cached resources is 27.8MB.
**
** This is over the recommended maximum of 5 MB and may break your
** app in some browsers! See http://docs.meteor.com/#appcache
** for more information and fixes.

Kadira: completed instrumenting the app
[velocity] cucumber is starting a mirror at http://localhost:43980/.
[velocity] *** Meteor Tools is installing *** 
This takes a few minutes the first time.
[velocity] You can see the mirror logs at: tail -f /home/ubuntu/dropz/web/.meteor/local/log/cucumber.log
[cucumber.log] => Using velocity:METEOR@1.2.0.2_1 as requested (overriding Meteor 1.2.1)
[cucumber.log] 
[cucumber.log] 
[cucumber.log] Changes to your project's package version selections:
[cucumber.log] 
[cucumber.log] accounts-base           downgraded from 1.2.2 to 1.2.1
[cucumber.log] accounts-oauth          downgraded from 1.1.8 to 1.1.7
[cucumber.log] accounts-password       downgraded from 1.1.4 to 1.1.3
[cucumber.log] autoupdate              downgraded from 1.2.4 to 1.2.3
[cucumber.log] check                   downgraded from 1.1.0 to 1.0.6
[cucumber.log] coffeescript            downgraded from 1.0.11 to 1.0.10
[cucumber.log] ddp-common              downgraded from 1.2.2 to 1.2.1
[cucumber.log] ddp-server              downgraded from 1.2.2 to 1.2.1
[cucumber.log] ecmascript              downgraded from 0.1.6 to 0.1.5
[cucumber.log] ecmascript-collections  added, version 0.1.6
[cucumber.log] ecmascript-runtime      removed from your project
[cucumber.log] email                   downgraded from 1.0.8 to 1.0.7
[cucumber.log] less                    downgraded from 2.5.1 to 2.5.0_3
[cucumber.log] meteor                  downgraded from 1.1.10 to 1.1.9
[cucumber.log] mongo                   downgraded from 1.1.3 to 1.1.2
[cucumber.log] promise                 downgraded from 0.5.1 to 0.5.0
[cucumber.log] random                  downgraded from 1.0.5 to 1.0.4
[cucumber.log] reactive-dict           downgraded from 1.1.3 to 1.1.2
[cucumber.log] standard-minifiers      downgraded from 1.0.2 to 1.0.1
[cucumber.log] templating              downgraded from 1.1.5 to 1.1.4
[cucumber.log] webapp                  downgraded from 1.2.3 to 1.2.2
[cucumber.log] 
[cucumber.log] [velocity] is in continuous integration mode
[cucumber.log] ** You are using the appcache package but the total size of the
[cucumber.log] ** cached resources is 27.7MB.
[cucumber.log] **
[cucumber.log] ** This is over the recommended maximum of 5 MB and may break your
[cucumber.log] ** app in some browsers! See http://docs.meteor.com/#appcache
[cucumber.log] ** for more information and fixes.
[cucumber.log] 
[cucumber.log] Kadira: completed instrumenting the app
[cucumber.log] [velocity] Mirror has established connection with Velocity.
[cucumber.log] [xolvio:cucumber] Cucumber is running
```

...even after running 
```
    - node ./tests/ci/velocity.js:
        environment:
          INSTALL_DEPENDENCIES: true
``` 

as in the Letterpress example.

Now I could cache the `1.2.0.2_1` release to speed it up, but smells like a somewhat hard-to-maintain hack...

**Comment by samhatoum** [comment]
The mirrors run in a Meteor track that we need to keep up-to-date with every meteor release. We just haven't got around to doing that yet for the latest Meteor. @Sanjo usually does it, I should probably learn :)

**Comment by Sanjo** [comment]
I have just released velocity:core 0.10.8 that uses Meteor 1.2.1 for mirrors.

**Comment by workflow** [comment]
:bow:

Thank you!

**Comment by amarakgec** [comment]
=> App running at: http://localhost:51961/
   Type Control-C twice to stop.

[velocity] Mirror has established connection with Velocity.
[xolvio:cucumber] Cucumber is running
[selenium] [Error: Could not request headers from http://selenium-release.storage.googleapis.com/2.47/IEDriverServer_Win32_2.47.0.zip: Error: connect ETIMEDOUT]
[chimp] Finished running async processes with errors
[chimp] run complete with errors [Error: Could not request headers from http://selenium-release.storage.googleapis.com/2.47/IEDriverServer_Win32_2.47.0.zip: Error: connect ETIMEDOUT]
[chimp] Could not get Cucumber Results from run result:
[ undefined, [ undefined ] ]
[xolvio:cucumber] Bad response from Chimp server.
{ statusCode: 200,
  content: '',
  headers: 
   { 'content-type': 'application/json; charset=utf-8',
     'cache-control': 'no-cache',
     'content-length': '0',
     date: 'Tue, 13 Dec 2016 11:11:01 GMT',
     connection: 'keep-alive' },
  data: null }


before 30 days its working fine but today is given error how to resolved it

**Comment by samhatoum** [comment]
Velocity is dead. Long live Chimp!

Head over to chimps.com

>
