### ISSUE TITLE
Defining custom or renaming globals

### ISSUE THREAD

**Issue by lorensr** [xolvio/chimp#146]
Hey Sam, I like the sync format! Would prefer not having to type `browser.` so much – can I put `b = browser` somewhere? 

Sidenote –

http://www.meteortesting.com/chapter/letterpress1

says to use `client`, but it's undefined for me. `browser` works.

**Comment by samhatoum** [comment]
just define global.b = global.browser in a before hook

**Comment by samhatoum** [comment]
I also fixed h undefined isuue ysterday. Are you running that version?

thanks for reporting

**Comment by lorensr** [comment]
Thank you kindly 😊 Just missed it, was on `.4_1`. Fixed now.

Where do screenshots go? Looks like they should be on by default w/ meteor+phantom?

`meteor --screenshotsOnError=true --screenshotsPath="tests/cucumber/.screenshots/"` 

isn't recognized. Perhaps this page could say how to pass options for meteor:

https://chimp.readme.io/docs/command-line-options

**Comment by lorensr** [comment]
Also, a search bar would be helpful for http://www.meteortesting.com/ book, so I could eg search for "screenshot"

**Comment by lorensr** [comment]
Nevermind, a Chrome window started appearing when tests are run, so I can see the browser state. Very useful.
