### ISSUE TITLE
FR: Given a Scenario

### ISSUE THREAD

**Issue by lorensr** [xolvio/chimp#147]
I have a user-signup Scenario, and then I want to use that DB state for two different action flows. Currently I'm doing:
```
Scenario
  [copy all the whens from user-signup Scenario]
  When ..
  Then action A is complete

Scenario
  [copy all the whens from user-signup Scenario]
  When ..
  Then action B is complete
```
I'd like to do something like:

```
Background
  Given user-signup Scenario

Scenario
  When ..
  Then action A is complete

Scenario
  When ..
  Then action B is complete
```
Note that I don't want to write a method that sets up the user data, because it's complex and varying based on 3rd party API calls (so I can't just insert static records).

http://stackoverflow.com/questions/33602690/can-i-reference-a-scenario-in-another-scenario

**Comment by SierraGolf** [comment]
imho this is really more a cucumber related topic and not a feature request for chimp.

why don't you move your step code into re-usable functions and create some high-level steps which aggregate those function calls?

**Comment by samhatoum** [comment]
@SierraGolf is correct, this is a Cucumber issue not a Chimp one. You might find a lot of resistance however on reusing steps. You are using executable specs as test scripts and they are not the same.

I'm just releasing a new version of Chimp (0.20.0) that allows you to use Mocha to write e2e tests, which will be perfect for your use-case.
