### ISSUE TITLE
New version not working

### ISSUE THREAD

**Issue by myknbani** [xolvio/chimp#148]
I basically created a new project adding only the `xolvio:cucumber` package, and a new Chrome window is never opened.  I tried updating to Chrome 46 and still the same error.

It's not working with Firefox 38 as well, and I'm waiting for the download of Firefox 42 to try if it works with other browsers.  Things were working fine in the previous version of Chimp.

I'm using LInux, Netrunner (Arch-based) rolling distro.

[versions.txt](https://github.com/xolvio/chimp/files/31698/versions.txt)
[packages.txt](https://github.com/xolvio/chimp/files/31699/packages.txt)

[cucumber.log.txt](https://github.com/xolvio/chimp/files/31700/cucumber.log.txt)

I still feel warm and fuzzy being able to see the browser acting by itself, but as a workaround I am using phantomjs.

I can also confirm that undoing the package update via Git makes the tests run again.  It works with `xolvio:cucumber@0.19.4_1`

**Comment by myknbani** [comment]
As a side note, I can no longer install an old version of this package in a fresh project like so:
It always adds the latest cucumber, which does not work on my machine (only?) :D

```
meteor add xolvio:cucumber@0.19.3_1
                                              
Changes to your project's package version selections:
                                              
amplify                 added, version 1.0.0  
less                    added, version 2.5.1
simple:json-routes      added, version 1.0.4
velocity:html-reporter  added, version 0.9.1
velocity:shim           added, version 0.1.0
xolvio:cucumber         added, version 0.19.5_1
```

**Comment by myknbani** [comment]
Having the old version cached in my PC, I edited the `.meteor/versions` file (>_<) and changed the last line into `xolvio:cucumber@0.19.4_1`.  I'm switching the version back and forth and confirmed that `0.19.5` is really broken on my end.

I also cannot see anything from the post-0.19.4 commits that introduces a new version of Chrome Driver or Selenium.

**Comment by samhatoum** [comment]
Can you try going to the 0.19.5_1 package dir in ~/.meteor, navigating to the node modules, finding selenium-server and starting it from there ([see here](https://www.npmjs.com/package/selenium-standalone)) with debug

Then go to `http://localhost:4444/wd/hub` and trying to start a chrome browser. 

This might show us some more detail on the error

**Comment by myknbani** [comment]
Would I be doing it correctly like this?

```
[mikenbani@valar-morghulis bin]$ pwd
/home/mikenbani/.meteor/packages/xolvio_cucumber/0.19.5_1/npm/node_modules/chimp/node_modules/selenium-standalone/bin
[mikenbani@valar-morghulis bin]$ ls -lh
total 8.0K
-rwxr-xr-x 1 mikenbani users 2.4K 11.11.2015 11:40 selenium-standalone*
-rwxr-xr-x 1 mikenbani users  200 11.11.2015 11:40 start-selenium*
[mikenbani@valar-morghulis bin]$ ./selenium-standalone start --debug
```

I can start a new session from there, and it even opens a new chrome window without fail.

However, when I run `meteor` on my project, it doesn't work.  It creates a new SessionManager and fails to start the browser.  I was thinking it would reuse the existing one.

**Comment by samhatoum** [comment]
see here https://code.google.com/p/chromedriver/issues/detail?id=1112

**Comment by myknbani** [comment]
Hmm that issue seems to be because they have a headless server??  I'm just using a normal Linux desktop.

One thing I can see is that my 0.19.4 and 0.19.5 packages contain the same build of ChromeDriver (same md5sum).  So it must be something in my machine.

I have even tried renaming the symbolic link to the 0.19.5 chimp package just so it would redownload stuff.  Hehe.  I'm still investigating.

**Comment by samhatoum** [comment]
I think we found the issue, it's to do with the environment variables being whitelisted in the latest version Please try 0.20.0_1

**Comment by myknbani** [comment]
Thank you very much Sam.  And thank you to xolv.io for spearheading Meteor testing.  

0.20.0_1 working good!

Just a side note:   The latest version has the usual "No compatible binary build found for this package." on a plain `meteor update`.  It finds 0.20.2_1.

**Comment by samhatoum** [comment]
you might have tried to do it while I was updating. Try the latest again and hopefully it should work

**Comment by ffxsam** [comment]
I'm getting this error too, while trying to update.

```
While checking for xolvio:cucumber@0.20.2_1:
error: No compatible binary build found for this package. Contact the package
author and ask them to publish it for your platform.
```

I'm on Mac OS 10.10.5.

**Comment by myknbani** [comment]
0.20.2_1 works great!  Thanks!
