### ISSUE TITLE
CI: Best Practice for Speeding up Build

### ISSUE THREAD

**Issue by workflow** [xolvio/chimp#151]
It looks like the examples from https://github.com/xolvio/Letterpress no longer work well in current releases.

Perhaps time for an update?

Let me know if I can help in any way.

**Comment by workflow** [comment]
Hmm looks like it was just me messing up things at this late hour, however an update on the subject would still be welcome :)

Why is it taking almost 5 minutes on CircleCI to fire up the mirror even after cache, and is there something we can do about it?

**Comment by samhatoum** [comment]
If your'e just using Chimp and not the rest of Velocity, you can start your meteor app without Velocity on Circle and then start Chimp as a node process and pass it a `--ddp=http://localhost:3000` option

It will likely be much faster

**Comment by samhatoum** [comment]
Thanks for offering to help! I may take you up on that when I get time to know what needs to be updated!

**Comment by workflow** [comment]
Running chimp in standalone mode sounds promising, but I wasn't successful at getting it to run so far.

1. Ran into https://github.com/xolvio/chimp/issues/153 and successfully fixed it with the workaround provided by @Temaruk

2. After that, running my tests with `./node_modules/.bin/chimp --ddp=http://localhost:3000` yields

  ```
Scenario Outline: Add tale                                         # features/Investor/contributing-content/add-tale.feature:7
    Before 
      Error: Method not found [404]
    Given I am a user                                                # features/Investor/contributing-content/add-tale.feature:9

(::) failed steps (::)

Error: Method not found [404]


  ```

  Disabling every and all `Before` hooks, I'm at

  ```
  Scenario Outline: Add tale                                         # features/Investor/contributing-content/add-tale.feature:7
    Given I am a user                                                # features/Investor/contributing-content/add-tale.feature:9
      Error: Method not found [404]

  ```
  ...for every step of every scenario.

  Those tests are all fine when run with the latest `xolvio:cucumber`

3. This is not related to CI, but to running chimp in local development with `--watch`, which would be awesome to speed up as well! :) Am I correct in assuming that without velocity there will be no mirror, hence the tests will be potentially destructive on the app that it connects to with `--ddp`? I can't seem to find documentation on that anywhere yet.

**Comment by samhatoum** [comment]
Do you have some fixtures under `/tests/cucumber/fixtures`? If so, these will need to be moved to a fixture package [like this](https://github.com/xolvio/Letterpress/tree/master/app/packages/fixtures)

**Comment by samhatoum** [comment]
hey @workflow 

check out https://github.com/xolvio/whirlwind

that should speed things up

also, there's quite a lot of issues in this thread. I'm going to close is and ask you nicely to create new ones for the individual issues you're still having. Thanks!

**Comment by workflow** [comment]
Cool!
