### ISSUE TITLE
Error: Custom EJSON type Astronomy is not defined

### ISSUE THREAD

**Issue by zvictor** [xolvio/chimp#152]
# Problem

When trying to run tests using Astronomy, it raises `Error: Custom EJSON type Astronomy is not defined`.

# Scenario

A minimal reproducible scenario can be found at https://github.com/zvictor/astronomy-EJSON-bug.

Logs:
 [.meteor/local/log/cucumber.log](https://github.com/zvictor/astronomy-EJSON-bug/blob/master/.meteor/local/log/cucumber.log)
 [.meteor/versions](https://github.com/zvictor/astronomy-EJSON-bug/blob/master/.meteor/versions)
 [.meteor/packages](https://github.com/zvictor/astronomy-EJSON-bug/blob/master/.meteor/packages)

# Debugging
* In normal server/client & methods/calls operations everything works fine.

<img width="241" alt="screen shot 2015-11-12 at 12 01 21" src="https://cloud.githubusercontent.com/assets/181076/11116910/fc862d90-8935-11e5-9ef0-fb55160afc51.png">

* While in Velocity, the server fetches the right data and fail right after, when trying to send it to the client (nodejs in this case).

![screen shot 2015-11-12 at 12 01 58](https://cloud.githubusercontent.com/assets/181076/11116912/00f7ef80-8936-11e5-9a2a-4c9fa715af26.png)

----

**Note**: It has also been posted in [jagi/meteor-astronomy#187](https://github.com/jagi/meteor-astronomy/issues/187)

**Comment by samhatoum** [comment]
you can try running with chimp outside the Meteor context, using the npm method:

https://chimp.readme.io/docs/getting-started-with-meteor-cucumber

**Comment by zvictor** [comment]
I removed `xolvio:cucumber` from the packages list, then I ran `meteor` and `chimp --ddp=http://localhost:3000` and I got the same error.

**Comment by samhatoum** [comment]
did you try to do a `meteor reset` when you used chimp?

**Comment by zvictor** [comment]
Yes, and I keep getting this error. I will try to follow the structure of `automated-testing-best-practices` and see what is different there that is not throwing this error.

**Comment by zvictor** [comment]
I can see that you are manually calling `raw` there, whenever you want to transfer something from the server to the test environment. It makes sense, but it creates a habit of writing code for tests in a different way than you would normally do, which is not something we would like to encourage.

In order to have all your server calls automatically converted to raw format, I created an expansion for the backdoor package. That's all what you need to run:

`meteor add quadric:backdoor-raw`

I am facing some problems while trying to test it, though. All kind of help is appreciated at https://github.com/quadric/meteor-backdoor-raw/issues

Thanks!

**Comment by zvictor** [comment]
I revisited this issue and I found a better way to workaround it.

That's my `tests/features/step_definitions/domain/support/reset.js` file.

```js
/* globals ddp: false */

global.Testing = global.Testing || {};
Testing.flags = {
  initiated: false
};

module.exports = function () {

  this.Before(function BeforeAll() {
    if (Testing.flags.initiated) {
      return;
    }

    const EJSON = ddp._original.EJSON;
    EJSON.addType('Astronomy', json => {
      return EJSON.parse(json.values);
    });

    client.url(process.env.ROOT_URL);
    Testing.flags.initiated = true;
  });

};
```

**Comment by samhatoum** [comment]
Awesome, thanks for posting back
