### ISSUE TITLE
Feature request: support for Meteor Hot Code Push via DDP subscription (example provided)

### ISSUE THREAD

**Issue by timbotnik** [xolvio/chimp#155]
With the non-velocity version of Chimp, it would be great to have tests automatically watch a Meteor app for Hot Code Push.  I've provided an example of how to do this using the existing DDP publication provided by the core `autoupdate` package, which is probably the best way to trigger a re-run of the tests.

Example node app here: https://github.com/timbotnik/meteor-autoupdate-watcher

**Comment by samhatoum** [comment]
Ooooh! That's a neat idea! Saves us filewatching the app codebase all together. 

Implementation notes:
1. Factor out the DDP connection initialization out of the chimp-helper and initialize before the watch mode kicks off
2. add a subscription to the autoupdate in the [watch mode](
https://github.com/xolvio/chimp/blob/develop/lib/chimp.js#L120)

**Comment by shrop** [comment]
+1

**Comment by samhatoum** [comment]
this ons is next :)

**Comment by shrop** [comment]
right on!

**Comment by ShockiTV** [comment]
+1

**Comment by Alino** [comment]
+1

**Comment by samhatoum** [comment]
This is implemented in v0.22.0 - get the latest. Ask, and you shall receive :)

**Comment by Alino** [comment]
nice, thank you

**Comment by timbotnik** [comment]
Awesome, thanks @samhatoum!

**Comment by samhatoum** [comment]
thank you @timbotnik for the inspiration and code example

**Comment by ShockiTV** [comment]
thx
There is 1 thing tho - with debugOnly we cannot export any Object.
So server.execute cannot call the fixture as easily as described in manual.

**Comment by ShockiTV** [comment]
So maybe it would be nice to mention it in fixture package part, that according to https://github.com/meteor/meteor/issues/3639
You need to use something like Package[“myApp:fixtures”].Fixtures to reach fixtures, if you are exporting them as Fixtures object from debugOnly, as it will not be available under global namespace directly.
Or something like that.

**Comment by shrop** [comment]
Thakns @samhatoum and everyone who contributed to this!

**Comment by shrop** [comment]
I confirm that v0.22.0 is working properly, rerunning tests after new Meteor builds are complete.

I am running chimp like this: `chimp --watch --watchSource=/path/to/meteor/root --ddp=http://localhost:3000`

**Comment by ShockiTV** [comment]
@shrop why watch meteor source? DDP will force reload when server is ready (not when just file change as yours) correctly anyway. I start it from cucumber dir with just watch and ddp.
