### ISSUE TITLE
Can we have a configuration file for chimp?

### ISSUE THREAD

**Issue by devinchen** [xolvio/chimp#156]
Please, take this into consideration.
It's painful to set a long options in command line

**Comment by samhatoum** [comment]
agreed. It will definitely come soon in the form of a chimp.json file

**Comment by devinchen** [comment]
@samhatoum Thank you~

**Comment by laran** [comment]
+1

**Comment by samhatoum** [comment]
I've got it working locally, so that's good progress. Very soon now :)

**Comment by samhatoum** [comment]
will be released in 0.28.0
