### ISSUE TITLE
using xolvio:cucumber without separate test window

### ISSUE THREAD

**Issue by natecox** [xolvio/chimp#157]
Is there any way to prevent the separate chrome window from opening up in response to tests being run? I'd love to just use phantomjs as a headless solution instead, but I can't seem to find any documentation on changing this.

**Comment by samhatoum** [comment]
`chimp --browser=phantomjs` ;)

Just be aware that many problem you will encounter with testing a modern app will be down to PhantomJS's lack of support for modern features

**Comment by natecox** [comment]
ok... but where I do put that inside of my meteor install? I'm not calling `chimp` anywhere manually when I use the `xolvio:cucumber` meteor package.

**Comment by samhatoum** [comment]
oh, for Meteor you set this environment variable `SELENIUM_BROWSER=phantomjs meteor`

**Comment by natecox** [comment]
ok, got it. Thanks.
