### ISSUE TITLE
Simulate multiple users in Cucumber/Velocity at the same time

### ISSUE THREAD

**Issue by haunguyen90** [xolvio/chimp#158]
is there a way to simulate multiple users in Cucumber/Velocity at the same time?
Ideally we’d like multiple browsers

**Comment by samhatoum** [comment]
There is a new branch on here that allows exactly that. It's not complete yet, but you can start with it if you're brave!

**Comment by samhatoum** [comment]
It's called multidriver

**Comment by lgandecki** [comment]
Hey @haunguyen90 ! 

I just pushed a little change that should let you use the multidriver branch of chimp.

What you need to do is to clone chimp to some directory, switch to multidriver branch, do npm install from it, and then:

set
``export CHIMP_PATH=/PathToChimp/chimp/bin/chimp`` (this has to point at the chimp binary in your fork)

``export CUCUMBER_BROWSERS=2``

Then start your step_definition file like so:

``
module.exports = function() {
    var browsers;

function getBrowserFor(person) {
        return (person === 'Both') ? browser : browsers[person];
    }
    var url = require('url');

   this.Given(/^There (is|are) (one|two) user(s)?$/, function () {
        browsers.Alice = browser.browsers[0];
        browsers.Bob = browser.browsers[1];
        this.server.call('reset');
    });


    this.When(/^([^ ]*) go(?:es)? to "([^"]*)"$/, function (person, relativePath) {
        getBrowserFor(person).url(url.resolve(process.env.ROOT_URL, relativePath));
    });
``

And use features like so:

 Given There are two users
    When Both go to "/"
    And Both go to "/focus"
    Then Bob goes to "/notFocus"
    And Alice goes to "/stillNotFocus"
(..)

This way you can start writing your tests... getBrowserFor and the ugliness with setting global browsers object will be refactored into chimp, 


Please let me know if you have any questions or problems!

**Comment by haunguyen90** [comment]
@samhatoum @lgandecki  thank you very much. I'll go a head with that.

**Comment by lgandecki** [comment]
Two more tips.. export forceSessionKill=true to make sure the browsers don't stick around after the tests are done. 
Also, if you have weird problems export SELENIUM_BROWSER=chrome as phantomjs proved to be problematic with complex reactive UIs.

**Comment by samhatoum** [comment]
@haunguyen90 did this work for you?

**Comment by lgandecki** [comment]
For anyone reading this, Api has changed a bit.
Browser.browsers is now browser.instances. That's a change in the given section in the example code.

**Comment by JoeyAndres** [comment]
@lgandecki 

Suppose I have the following:

```javascript
var foo_browser = browser.instances[0];
foo_browser.waitUntil(function() {
   console.log('bar');
});
```

console.log('bar') was never called. Wrapping it in a try/catch blog and printing the error it says, '[Error: Can't wait without a fibre]`. This doesn't occur when ```var foo_browser = browser;```

**Comment by samhatoum** [comment]
Hey @JoeyAndres 

Can you please open a new issue?

**Comment by haunguyen90** [comment]
@samhatoum Yeah. it works for me.

**Comment by mario-ortiz** [comment]
Hello Guys, is this branch already merged on master?, or is the same process?. Haven't tried to be honest.

**Comment by lgandecki** [comment]
Not yet, but we do have the newest 0.30.0 chimp merged with multibranch functionality. I just updated it. You can clone chimp, switch to branch multidriver, do npm install and use chimp from there. If you use chimp in package.json somewhere just do:

    "chimp": "git://github.com/xolvio/chimp.git#multidriver"

**Comment by mario-ortiz** [comment]
Guys, not sure what am I doing wrong, but browser.instances is undefined, so this is failing

browsers.Alice = browser.instances[0];

The error I get is "cannot read property 0 of undefined"

This is my package.json

"dependencies": {
    "chimp": "git://github.com/xolvio/chimp.git#multidriver",
   ...
}

I removed the chimp folder inside node_modules to be sure it was being installed from scratch.

I also added the 2 env variables:
CUCUMBER_BROWSERS=2
CHIMP_PATH=/path/to/chimp/bin

And finally the code I have in my step definition
var browsers = {};
browsers.Alice = browser.instances[0];
browsers.Bob = browser.instances[1];
browsers.Alice.url('http://google.com');

The Chrome browser opens, but as soon as it opens it closes. 

Any thoughts?

**Comment by mario-ortiz** [comment]
I think I found the problem, let me check and I'll let you know

**Comment by mario-ortiz** [comment]
Ok, my first problem was that I had a custom chimp file, so I updated it to the new version with multibrowser, now it creates 2 browser. But now I have another problem. Right here :

In my custom chimp.js file

var localBrowser = remoteSession(webdriverOptions);
cb(null, localBrowser); 

I did a console log and webdriverOptions has information. But the error its here

xolvio-sync-webdriverio\node_modules\xolvio-fiber-utils\index.js

This line:
var result = fn.apply(self, newArgs);

In my case, fn is undefined

WOrth mentioning that my custom chimp.js file it's pretty much the same as the original, I just added a couple desiredCapabilities to webdriverIO, besides that its exactly the same. My previoys one was working no problems.

I'm attaching the file anyways if needed.



[chimp.zip](https://github.com/xolvio/chimp/files/221404/chimp.zip)

**Comment by lgandecki** [comment]
Could you maybe push this to a forked github repository? It'd be easier to take a look and compare the code. 
We do use this feature heavily and it works like a charm so if you feel like you need this functionality I think we can get it to work :)

One quick though - try removing the whole node_modules and then do npm install after having the custom line for chimp. (it probably won't help but worth a shot, multidriver chimp also requires a different version of xolvio-sync-webdriverio, one that has multidriver capability)

**Comment by lgandecki** [comment]
it might be also worth a shot to try just that branch, see if it works for you, and then apply your changes there, step by step and seeing when (or if) it brakes

**Comment by mario-ortiz** [comment]
Working now thank you, I was making a reference to the wrong module.
