### ISSUE TITLE
Package.json makes Chimp fail to start

### ISSUE THREAD

**Issue by PEM--** [xolvio/chimp#160]
I'm on OSX 10.11. My `node` (5.1.0) command has been installed using  `brew` within `/usr/loca/bin` and my `npm` (3.3.12) command has been update using the classical `npm -g update npm`.

In my test folder, I've created a `package.json` file to ease `chimp`'s launch with a `run` script. Unfortunately, when I do this, `chimp` fails to start with the following message as it tries to guess where my `npm` is:
```bash
[chimp] stderr: /bin/sh: /usr/local/Cellar/node/5.1.0/bin/npm: No such file or directory

npm install error { [Error: Command failed: /bin/sh -c "/usr/local/Cellar/node/5.1.0/bin/npm" install
/bin/sh: /usr/local/Cellar/node/5.1.0/bin/npm: No such file or directory
]
  killed: false,
  code: 127,
  signal: null,
  cmd: '/bin/sh -c "/usr/local/Cellar/node/5.1.0/bin/npm" install' }
{ [Error: Command failed: /bin/sh -c "/usr/local/Cellar/node/5.1.0/bin/npm" install
/bin/sh: /usr/local/Cellar/node/5.1.0/bin/npm: No such file or directory
]
  killed: false,
  code: 127,
  signal: null,
  cmd: '/bin/sh -c "/usr/local/Cellar/node/5.1.0/bin/npm" install' }
```

**Comment by samhatoum** [comment]
Hey, see here: 
https://github.com/xolvio/chimp/issues/149

**Comment by PEM--** [comment]
OK, thanks.
