### ISSUE TITLE
Use browser.sessionStorage() will return `Invalid Command Method`

### ISSUE THREAD

**Issue by devinchen** [xolvio/chimp#162]
Here's my steps :

1. Add browser.sessionStorage() funciton inside `webdriver-steps.js` under step definitions folder
2. run `./bin/chimp --browser=phantomjs` under Chimp folder

**Comment by Sanjo** [comment]
PhantomJS doesn't support session storage. Maybe PhantomJS 2. Not sure. I recommend to use Chrome.
