### ISSUE TITLE
Bad response from Chimp server.

### ISSUE THREAD

**Issue by scottire** [xolvio/chimp#164]
I am trying to set up Cucumber on my laptop. I am getting this error
""""[xolvio:cucumber] Bad response from Chimp server.""" I have updated Java on my laptop and I can't seem to find any help online. Anyone have any suggestions to get this sorted? 
If there's more info I can provide or if I have posted this in the wrong place, please let me know.

```[xolvio:cucumber] Bad response from Chimp server.
{ statusCode: 200,
  content: '',
  headers: 
   { 'content-type': 'application/json; charset=utf-8',
     'cache-control': 'no-cache',
     'content-length': '0',
     date: 'Sun, 29 Nov 2015 00:00:11 GMT',
     connection: 'keep-alive' },
  data: null }```

**Comment by samhatoum** [comment]
did you update the JRE or the JDK? You need the JDK

**Comment by scottire** [comment]
Oh great. That sorted it! Thanks
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html 
For those that arrive here.

**Comment by samhatoum** [comment]
Welcome!
