### ISSUE TITLE
Recursive/glob pattern file search?

### ISSUE THREAD

**Issue by sbacic** [xolvio/chimp#166]
I've found chimp to be a fascinating tool but have been unpleasantly surprised to learn (after some debugging) that --path doesn't search for files recursively. I've made a crude "yank and tuck" solution that meets my needs and was wondering whether to go through the trouble of writing tests and submitting a proper pull request?

Do you guys have something like this already in the pipeline or...?

**Comment by Sanjo** [comment]
I think we can fix this. Can you help me to pinpoint the limitation.

* Do all specs get executed initially? If not that is probably a limitation of cucumberjs: https://github.com/cucumber/cucumber-js#requiring-support-files
* If it is just about detecting changes (file watching)?

**Comment by sbacic** [comment]
I've made a pull request with the fix:
https://github.com/xolvio/chimp/pull/168

This issue is related to mocha, not cucumber. It was detecting the changes but the tests were never added to mocha. This should fix it. 

I haven't written any tests but from what I can tell it's working properly now.

**Comment by JoeChapman** [comment]
+1

**Comment by samhatoum** [comment]
@sbacic thank you, I'm hoping to get some time to work on Chimp this weekend and will get this in.

**Comment by JoeChapman** [comment]
Hi, I have a commit I would like to PR to make this bug go away. Can I get write permissions please?

**Comment by Sanjo** [comment]
@JoeChapman Just fork the repository, create a branch with the fix and then open a pull request on this repository.

**Comment by samhatoum** [comment]
fixed in a PR
