### ISSUE TITLE
Is there a way to save Velocity html report to a file?

### ISSUE THREAD

**Issue by diegolaguna** [xolvio/chimp#167]
I'm running Cucumber tests on a Docker machine running Ubuntu Server 14.04 and using PhantomJS. 

I'm running the tests with this command:
SELENIUM_BROWSER=phantomjs VELOCITY_CI=1 meteor 

The tests are completed successfully, I can see the console report, but I would like to have the html report saved into a file. Is there a way to achieve that?

**Comment by samhatoum** [comment]
Your best bet is to create a json report then use a third party reporter to convert to html

**Comment by Sanjo** [comment]
For the reporter, you can start with https://github.com/meteor-velocity/console-reporter and do something else here: https://github.com/meteor-velocity/console-reporter/blob/master/main.js#L28-L31

**Comment by diegolaguna** [comment]
Thanks for your help!! it's finally working, currently I'm running the test with:

SELENIUM_BROWSER=phantomjs CUCUMBER_FORMAT=json CUCUMBER_JSON_OUTPUT=/home/developer/results.cucumber meteor --once --test

and for the report formatting, I added the cucumber-reports plugin to my Jenkins CI instance.
