### ISSUE TITLE
Chrome not reachable

### ISSUE THREAD

**Issue by devarashetty** [xolvio/chimp#170]
With the following code in cucumber .feature file , 

' this.When( /^ I navigate to vehicle add page$ / , function ( ) {
      tasks.nav(widgets.VehicleUpsert.path);
    }); '

I am getting the below error : 

' Error: chrome not reachable
  at Object.tasks.nav (features/_support/tasks/nav.js:6:13)
  at World.<anonymous> (features/VehicleUpsert/vehicle-upsert.js:12:13) '

please let me know what causing this

**Comment by samhatoum** [comment]
https://github.com/xolvio/chimp/blob/develop/CONTRIBUTING.md
