### ISSUE TITLE
[xolvio:cucumber] No features found. Be sure to annotate scenarios you want to run in watch mode with the @dev,@watch,@focus tag

### ISSUE THREAD

**Issue by namirsab** [xolvio/chimp#172]
Hey!
I'm having  a really weird issue.
I have features, actually they appear in the VelocityTestFiles collection. They appear also in the Html Reporter. But when i run my app, even if I have `@watch` or `@dev` tags, it says this. I've tried everything but i don't know what to do.
It's anybody that knows why something like this could happen?
@samhatoum 
Even when I run the --test flag, which should execute all the tests, it says that i have no tests marked as `@dev` or `@focus` or `@dev`.
This is really weird.

**Comment by samhatoum** [comment]
what does your directory structure look like?

**Comment by samhatoum** [comment]
did you get this working @namirsab ?

**Comment by namirsab** [comment]
No sorry, I was busy, I will send the folder structure asap. But its the typical one

**Comment by samhatoum** [comment]
Hey, we decommisoned xolvio:cucumber  - please use chimp :+1:
