### ISSUE TITLE
Is there an example mocha support?

### ISSUE THREAD

**Issue by pixtur** [xolvio/chimp#174]
I'm trying to setup chimp with meteor and mocha, but when writing tests, I immediately run into async-problems. In the following example...

    describe('#login', function(done) {
        it('#login should work', function (done) {
            browser.url(url_startpage);
            browser.setValue('input#login-email', 'bla@bla.com');
            browser.setValue('input#login-password', 'blabla');
            browser.click('input[type=submit]');
            expect(browser.getText('h1')).to.equal(Welcome');
            done();
       });
    });

... the 2nd browser.setValue() fails with:

     Uncaught NoSuchElement: An element could not be located on the page using the given search parameters.
      at Object.Future.wait (/usr/local/lib/node_modules/chimp/node_modules/fibers/future.js:420:15)
      at Object.<anonymous> (/usr/local/lib/node_modules/chimp/node_modules/xolvio-fiber-utils/index.js:48:19)
      at Context.<anonymous> (features/mocha-spec.js:28:21)
      at /usr/local/lib/node_modules/chimp/lib/mocha/mocha-fiberized-ui.js:21:14
      - - - - -
      at setValue("input#login-password", "blabla") - staleElementRetry.js:7:27
      at elementIdValue("88", "blabla") - setValue.js:53:7

After playing a bit more with this, I noticed that I frequently get warnings like:

    RuntimeError: stale element reference: element is not attached to the page document 
        at elementIdValue("36", "bla@bla.com") - setValue.js:53:7 

I'm not sure why the webdriver creates all that stale elements or how to prevent it.

The examples on http://webdriver.io/ suggest chaining the statements or using the .then() method which is not defined for all functions of the browser-object. Can you give me any suggestions or examples on how to do this with chimp?

thanks a lot
tom

**Comment by samhatoum** [comment]
Hey Tom

Try to wait for the element to exist first

**Comment by samhatoum** [comment]
You don't need to use `.then` because Webdriver.io is synchronous in chimp

**Comment by pixtur** [comment]
Hi Sam,

thanks for you quick answer. Good to know that chimp is fully synchronous. I spent some more time on the test and got it stable by waiting for the elements. I finally figured out, that I can get rid off the stale-error-message by resetting the test properly by using before()  and beforeEach() correctly.

**Comment by samhatoum** [comment]
awesome
