### ISSUE TITLE
bad response from Chimp server

### ISSUE THREAD

**Issue by philcruz** [xolvio/chimp#176]
Added xolvio:cucumber to a simple project. I run meteor and I'm seeing this in the cucumber.log

		=> Started your app.

		=> App running at: http://localhost:49889/
		   Type Control-C twice to stop.

		[velocity] Mirror has established connection with Velocity.
		[xolvio:cucumber] Cucumber is running
		[chimp] Could not get Cucumber Results from run result:
		[xolvio:cucumber] Bad response from Chimp server.
		[ undefined, [ undefined ] ]
		{ statusCode: 200,
		  content: '',
		  headers: 
		   { 'content-type': 'application/json; charset=utf-8',
		     'cache-control': 'no-cache',
		     'content-length': '0',
		     date: 'Mon, 07 Dec 2015 22:17:44 GMT',
		     connection: 'keep-alive' },
		  data: null }

and the sample tests don't run. 

What could be the issue?

**Comment by samhatoum** [comment]
looks like you don't have the jdk installed. Be sure to get the oracle one

Have a look here
https://chimp.readme.io/docs/getting-started#1-install

**Comment by samhatoum** [comment]
Did that fix it for you?

**Comment by philcruz** [comment]
I was able to run tests in another project a little while back so didn't know why it wasn't running here...but yeah, checking for the jdk it got hosed somehow..re-installing fixed it. Thanks for the quick response.
