### ISSUE TITLE
Support Jasmine

### ISSUE THREAD

**Issue by Sanjo** [xolvio/chimp#178]

**Comment by ashersz** [comment]
I migrated from xolvio:cucumber to chimp. I have also jasmine tests. When I run the cucumber test with chimp I have the velocity frame covering 2/3 of my browser window and most of the click tests don't work. I added the following to my launch command
VELOCITY=0 \
JASMINE_CLIENT_UNIT=0 \
JASMINE_CLIENT_INTEGRATION=0 \
JASMINE_SERVER_UNIT=0 \
JASMINE_SERVER_INTEGRATION=0 \
but it does not help. How can I disable the jasmine test while running chimp? Or force the velocity frame to be minimised to a button.

**Comment by laran** [comment]
+1

**Comment by Menda** [comment]
+1

**Comment by samhatoum** [comment]
@Sanjo I think we can use the @watch tag with this:
https://github.com/jasmine/jasmine-npm/blob/master/lib/filters/console_spec_filter.js

That way Jasmine will work the same as cucumber/mocha

This way `fit` and `fdescribe` can still be useful for local scoping
