### ISSUE TITLE
Tests passing locally but failing on CodeShip

### ISSUE THREAD

**Issue by philcruz** [xolvio/chimp#187]
I have several tests set up on my app which run fine on multiple local dev environments (Windows and Mac). I'm trying to set up continuous integration/deployment using CodeShip but the tests are failing. The logs show

    PASSED jasmine-client-unit : check shared helpers:shared helpers => confirms versionIsDraft
    PASSED jasmine-client-integration : template:layout => shows Login link
    PASSED jasmine-client-integration : logging in:user functions => confirms the user is logged in
    PASSED cucumber : Create a new project:A user should be able to create, read, update and delete     projects. => Given I am logged in as the default user
    PASSED cucumber : Create a new project:A user should be able to create, read, update and delete projects. => When I click the project menu
    FAILED cucumber : Create a new project:A user should be able to create, read, update and delete    projects. => And I click the new project menu item
    RuntimeError: no such element: Unable to locate element:    {"method":"id","selector":"createNewProjectMenuItem"}  ...
    at World.<anonymous> (/tests/cucumber/features/step_definitions/project_steps.js:22:16)
    ...

a snippet from project_steps.js

    this.Given(/^I am logged in as the default user$/, function () {
			this.client.url(process.env.ROOT_URL);
			this.AuthenticationHelper.logout();
			this.AuthenticationHelper.login();
			this.client.waitForExist('#project-dropdown');
		});

		this.When(/^I click the project menu$/, function () {
			this.client.waitForExist('#project-dropdown');
			this.client.click('#project-dropdown');
			this.client.waitForExist('#createNewProjectMenuItem')
			this.client.pause(1000);
		});

		this.When(/^I click the new project menu item$/, function () {
			this.client.click('#createNewProjectMenuItem');
			this.client.pause(1000);
		});

and the authentication help file looks like

    module.exports = function () {

	this.Before(function () {

		this.AuthenticationHelper = {
			login: function () {
				browser.url( process.env.ROOT_URL + 'sign-in');
				browser.waitForExist('#at-field-username_and_email');
				browser.setValue('#at-field-username_and_email', 'apitheory');
				browser.pause(1000);
				browser.setValue('#at-field-password', 'letmein');
				browser.click('#at-btn');
			},

			logout: function () {
				browser.executeAsync(function (done) {
					Meteor.logout(done);
				});
				browser.pause(1000);
			},

			createAccount: function (profile) {
				profile = profile || {
					periodEnd: Math.floor(new Date().getTime() / 1000)
				};

				return server.call('fixtures/createAccount', {
					email: 'me@example.com',
					password: 'letme1n',
					profile: profile
				});
			},

			createAccountAndLogin : function(profile) {
				this.createAccount(profile);
				this.login();
			}
		};

	});
    };

What could be the issue?

**Comment by samhatoum** [comment]
cloud CI servers run slower than local machines, you have to ensure you always wait for elements properly. try waiting for the element to exist before the click it inside the last step

**Comment by philcruz** [comment]
Yeah, that was it. I thought that if one of the elements on the page was there then all the others should. Need to waitForExist() for each element it seems, for cloud/CI servers anyway. 

Thanks!
