### ISSUE TITLE
Xolvio:Cucumber with meteor & coffeescript

### ISSUE THREAD

**Issue by RedMage** [xolvio/chimp#190]
Hello

First, thank you for building this wonderful tool set. Tools like this are exactly what the Meteor and Node communities need to become truly great. That's what these tools are.

Now for the question:
I have a very simple Meteor project I created with one or two templates and a few collections defined. the xolvio:cucumber package was working fine. However, after I converted the application to jade/styles/coffeescript, it says that my collections are undefined. Specifically, when it gets to running the first fixture option it says Market --one of my collections, is undefined. Is there any sort of tags or configuration I must be aware of for the mirror application to be aware of the coffeescript changes?

**Comment by samhatoum** [comment]
Thank you for the kind words. We just decommissioned xolvio:cucumber and we are only working on chimp now. 

Don't worry, it has first-class Meteor support. Have a look here:
https://chimp.readme.io/docs/migrating-from-xolviocucumber-to-chimp

Try it, and let me know if you still have this issue

**Comment by RedMage** [comment]
Such timing! It's like you're developer who is operating reactively! 

Thank you for the information. I will migrate and look to use coffeescript with it.

**Comment by samhatoum** [comment]
hehe, be sure to come back and close this if it works!

**Comment by RedMage** [comment]
Converting to using chimp to test my meteor application was painless. The documentation was thorough and helpful.
