### ISSUE TITLE
migration manual from xolvio:cucumber to chimp, is not clear

### ISSUE THREAD

**Issue by Alino** [xolvio/chimp#191]
Hi, I tried to follow this manual https://chimp.readme.io/docs/migrating-from-xolviocucumber-to-chimp
but I am not able to perform the migration :(

I created fixtures package.
I am running localhost:3000 with meteor and I am running chimp --watch --ddp=http://localhost:3000

But I really don't know where should I move hooks.js
```
module.exports = function () {
    this.Before(function () {
        server.execute(MYFUNC);
    });
};
```

chimp gives me reference errors that MYFUNC is not defined.
So the question is:
Where should I define MYFUNC ?
How do I get Meteor context to MYFUNC?

I have the same problem not only with hooks.js but also fixtures.js
I Don't know how to get Meteor context. I have xolvio:backdoor installed but I don't know how to use it

**Comment by samhatoum** [comment]
how did you have it before?

**Comment by Alino** [comment]
Before the migration I had this in my hook.js
```
module.exports = function () {
    this.Before(function () {
        server.call('reset');
    });
};
```

and this in my fixtures.js
```
Meteor.methods({
    'reset': function () {
        console.log("dopice!!!");
        console.log(Meteor.settings);
        console.log(HTTP);
        console.log("going to run reset!!!");
        SearchedQueries.remove({});
        MasterProducts.remove({});
    }
});
```

and it worked.

**Comment by Alino** [comment]
Now I understand.
I changed my hooks.js to this:
```
module.exports = function () {
    this.Before(function () {
        var reset = function() { Kuknito.Fixtures.reset() };
        server.execute(reset);
    });
};
```
and fixtures.js
```
Kuknito.Fixtures = {
    'reset': function () {
        console.log("dopice!!!");
        console.log(Meteor.settings);
        console.log(HTTP);
        console.log("going to run reset!!!");
        SearchedQueries.remove({});
        MasterProducts.remove({});
    };
};
```

**Comment by Sanjo** [comment]
You don't really need to change your code. server.call is still available and works as before. But both styles, that you have posted, work.

**Comment by firrae** [comment]
I had the same thing happen and was confused as to what the documentation was telling me. I eventually reverted back to server.call as a test and it worked so I assumed it was just a mistype on the documentation. I would never have thought to do what @Alino did.

@Sanjo @samhatoum are there current plans to phase out server.call completely? If so what is the time frame so I can plan to convert my tests over before it happens?

**Comment by Sanjo** [comment]
@firrae No, server.call and server.apply will be kept. server.execute is just an addition.

**Comment by samhatoum** [comment]
my bad, I will change the docs.

**Comment by samhatoum** [comment]
@Alino you can still do what you did before, no change needed

**Comment by firrae** [comment]
Thanks for the clarification.

**Comment by Alino** [comment]
thank you, I guess this should be closed know.
