### ISSUE TITLE
Inject the assertion library into the Meteor context

### ISSUE THREAD

**Issue by samhatoum** [xolvio/chimp#194]
When using `server.execute` / `client.execute`, it would be nice to have the framework assertion library injected into the client/server so that users can assert within the contextual calls, rather than have to return the results and assert in the test context

**Comment by ramijarrar** [comment]
+1

**Comment by Menda** [comment]
Big +1 for this, I was fighting with that and realised there is no feature for that!

      it('should validate successfuly', function () {
        server.execute(function() {
          assert(true);
        });
      });

**Comment by Menda** [comment]
@samhatoum Can you give any tip on how to implement this? Is there something done before which is similar? I'm pretty new to JS, but I can try to implement it.

For me it looks like pretty difficult, as we just connect through DDP to meteor instance and server and test client are totally decoupled components.

**Comment by ramijarrar** [comment]
@Menda Keep in mind that you can already implement this functionality right now by returning a value from the execute function and running the assertion on that instead. This feature is really a matter of syntactical sugar more than anything else.

If you are still interested in taking a go at this, you should probably start by doing some reading into the [backdoor package](https://github.com/xolvio/meteor-backdoor) that is used right now to execute arbitrary code on the server. You are most likely going to add your code directly here or at least interface with that package to accomplish something similar.

**Comment by Sanjo** [comment]
I will publish a Meteor package for xolvio-jasmine-expect shortly. With that you can expect inside the server.execute block and the test fails and failing expectations. The assertion libraries just throw errors.

**Comment by Sanjo** [comment]
Here is the package: https://github.com/xolvio/meteor-jasmine-expect#xolviojasmine-expect. Just add it to your app and execute the code snippet from the readme before the tests run (on server startup or before hook).

If you use another assertion library, e.g. chai, you can just mimic what I have done in the package.
