### ISSUE TITLE
ignore screenshots when using --watch

### ISSUE THREAD

**Issue by shrop** [xolvio/chimp#197]
Example chimp command line: `$ chimp --watch --watchSource=<meteor-app-root> --screenshotsOnError=true --ddp=http://localhost:3000`

When running the above, chimp will go into a loop and continue to rerun all tests because it detects that screenshots are being added to `<meteor-app-root>/tests/cucumber/`. 

More or less thinking this through out loud. The best way to prevent may be to set a path for screenshots outside of the app source tree. An alternative is to run chimp without `--watch` mode. 

Another option is to ignore png files in tests folders when watching.

Thoughts? thanks!

**Comment by samhatoum** [comment]
Sorry I missed this! You can set the screenshots path with that switch. I really need to get the --help done :)

**Comment by samhatoum** [comment]
it would be a wise thing for us to do as well to ignore the screenshots produced when the are in the same dir, but it's not urgent I guess

**Comment by shrop** [comment]
Right on! That makes sense :)

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy
https://github.com/TheBrainFamily/chimpy/issues
