### ISSUE TITLE
Set timeoutsImplicitWait to 3 seconds by default

### ISSUE THREAD

**Issue by samhatoum** [xolvio/chimp#199]
http://webdriver.io/api/protocol/timeoutsImplicitWait.html

This may save having to run `waitForExists` for everything

**Comment by GaryAlway** [comment]
We found that setting timeoutsImplicitWait in the chimp config file has no effect and we were forced to set it programatically

**Comment by samhatoum** [comment]
Did you try to set it in here?
https://github.com/xolvio/chimp/blob/master/dist/bin/default.js#L49

**Comment by GaryAlway** [comment]
We are still using v0.30 with the old config format for webdriver IO.
We tried the latest version but found some other issues

**Comment by samhatoum** [comment]
ah, thanks for reporting. Let us know if we can help with the issues. Would love to hear about them

**Comment by GaryAlway** [comment]
sure, here's one ;-)
https://github.com/xolvio/chimp/issues/318

**Comment by Sanjo** [comment]
The timeoutsImplicitWait option has been removed from the chimp config file.
