### ISSUE TITLE
Feature request: arbitrary desiredcapabilities as command line args

### ISSUE THREAD

**Issue by BernsteinA** [xolvio/chimp#200]
(As command line args or variables, I guess, until we get #156 )
Specifically, I'd like to set tunnel-identifier for use with Sauce Labs.
Am handling the creation of the tunnel elsewhere, and that might be out of scope for Chimp.

**Comment by samhatoum** [comment]
I think it's a reasonable ask to be able to configure the tools that chimp is starting. #156 is indeed the way forward, I'll keep this open in case we get to it first

**Comment by BernsteinA** [comment]
@samhatoum quick fix for the specific feature I needed: https://github.com/stitchmedia/chimp/commit/82693f8991c4e15bb3c452812c6c0047f88e84d7

**Comment by ramijarrar** [comment]
Even though #156 has now been addressed, I think this issue is still very relevant.

There are many chimp options at the moment which only serve to fill gaps in the desired capabilities - and many more remain in order to even approach complete coverage (largely BrowserStack/Sauce Labs specific). Supporting something like this would eliminate the maintenance burden that comes with this e.g #283, #234, etc.

**Comment by samhatoum** [comment]
:+1:  this should be easy to do now, I'll do it soon

**Comment by ramijarrar** [comment]
@samhatoum Great

**Comment by ramijarrar** [comment]
Any updates on this? I'm stuck on version 0.25.1 until this or #283 are resolved 

(and some of the latest additions look really good :smile:)

**Comment by Sanjo** [comment]
This is already supported via this feature: [Custom WebDriver configuring](https://chimp.readme.io/v1.0/docs/custom-webdriver-configuration). I have just added the documentation for it.

Exposing this via the chimp options file, may also be something that we can do additionally.

**Comment by ramijarrar** [comment]
@Sanjo How does this fit in with the command line options -  in other words, what would happen if I used this custom webdriver config along with options like 'platform' or 'version' from the command line?
