### ISSUE TITLE
Path is not being passd to the DDP connection

### ISSUE THREAD

**Issue by jiku** [xolvio/chimp#202]
I'm trying to get Chimp working with a Meteor app that has a path in the ROOT_URL. The app is started with something like

`ROOT_URL=http://dev.jiku/appname meteor --port 9999`

Then Chimp starts with

`chimp --ddp=http://dev.jiku:9999 --watch` or `chimp --ddp=http://dev.jiku:9999/appname --watch`

and outputs

```
[chimp] Running...
=> Your Meteor application has errors. Waiting for file change.
```

While the app is working fine at `http://dev.jiku:9999/appname`.

Chimp works by omitting the /appname, but with the app assuming http://dev.jiku:9999/appname as the base URI, it's partially crippled. Removing the path in dev works around it to an extent, but there are still a few things that won't get loaded, won't work, etc.

Tried a few of the other command line options, etc, but can't seem to figure it out. Often getting the #189 error. Any ideas?

**Comment by samhatoum** [comment]
Not yet, I admittedly haven't tried to run an app on a pathname. How can I replicate locally?

**Comment by jiku** [comment]
[Here's](https://github.com/jiku/chimp-issue-202-root-url-with-path) a repro attempt. Maybe too minimal but I think it covers the issue. Nvm that I swiped the tests from letterpress. :)

**Comment by jazeee** [comment]
Just a comment - @jiku - Your bug submission uses a TCP port that is larger than 65535.
TCP ports are limited to 16 bit: http://stackoverflow.com/questions/113224/what-is-the-largest-tcp-ip-network-port-number-allowable-for-ipv4
You bug report is probably quite valid, but I believe 212121 is invalid for a TCP port.

**Comment by jiku** [comment]
Yeah I just typed something. Updating to 9999, to match the repro. Thanks! Glad to know it's a widely shared issue. ;)

**Comment by samhatoum** [comment]
Is this issue still happening for you guys?

**Comment by jazeee** [comment]
I haven't tried since January this year. It was occurring at that time.

**Comment by samhatoum** [comment]
ok thanks. I'm going to close until someone else complains :)

**Comment by rws-github** [comment]
I'm having a similar/same issue. If the ROOT_URL has a path, no value seems to work for ddp passed to chimp.

Shouldn't the original server start be:

ROOT_URL=http://dev.jiku:9999/appname meteor --port 9999

**Comment by rws-github** [comment]
Given an app running behind nginx with port 443 routed to 3000 with foo.com routed to 127.0.0.1

ROOT_URL=https://foo.com/my-app meteor

What should --ddp be?

**Comment by samhatoum** [comment]
Hey

We use this ddp library in chimp: https://github.com/oortcloud/node-ddp-client

I'd try to get it working without Chimp first using the node-ddp library, then try the same in chimp. 

Would love to hear back how you get on

**Comment by rws-github** [comment]
Thanks for the tip. I used the client and got something that connects. It looks like I need to modify the connection options in chimp at:  https://github.com/xolvio/chimp/blob/52263be76050b4babfb45c0a91bc45000c658dfd/src/lib/ddp.js#L41-L54

I changed it to:
```
DDP.prototype._getOptions = function () {
  if (this.url.pathname) {
    return {
      host: this.url.hostname,
      port: this.url.port,
      ssl: this.url.protocol === 'https:',
      path: this.url.pathname,
      // TODO extract all options
      autoReconnect: true,
      autoReconnectTimer: 500,
      maintainCollections: true,
      ddpVersion: '1',
      useSockJs: false // useSockJs must be false when path is used
    };
  } else {
    return {
      host: this.url.hostname,
      port: this.url.port,
      ssl: this.url.protocol === 'https:',
      // TODO extract all options
      autoReconnect: true,
      autoReconnectTimer: 500,
      maintainCollections: true,
      ddpVersion: '1',
      useSockJs: true
    };
  }
};
```

and set `--ddp=http://localhost:3000/my-app/websocket` and it works!

**Comment by samhatoum** [comment]
oh nice! Thanks for the the update. We just need to extract the `path` for DDP connections. I'll reopen this ticket
