### ISSUE TITLE
Permission denied error message from selenium

### ISSUE THREAD

**Issue by derwaldgeist** [xolvio/chimp#203]
I'm on MacOS and installed chimp using npm, as described in the docs. But when I am trying to run it using the ```chimp``` command, I get this message:

```
[chimp] Running...
[selenium] { [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/chimp/node_modules/selenium-standalone/.selenium']
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/local/lib/node_modules/chimp/node_modules/selenium-standalone/.selenium' }
{ [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/chimp/node_modules/selenium-standalone/.selenium']
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/local/lib/node_modules/chimp/node_modules/selenium-standalone/.selenium' }
```

**Comment by samhatoum** [comment]
did you install as sudo? that can cause these issues. Try installing without sudo, and if you still have trouble, try this method:

Try this method: https://chimp.readme.io/v1.0/docs/installation#section-alternative-installation

I've updated the docs :)

**Comment by derwaldgeist** [comment]
Installing it without sudo did not work, I got this result:

```
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/chimp
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
/usr/local/lib
└── chimp@0.22.1 

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "chimp"
npm ERR! node v4.2.1
npm ERR! npm  v3.3.9
npm ERR! path /usr/local/lib/node_modules/chimp
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/chimp'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/chimp']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/chimp' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/waldgeist/npm-debug.log
```

**Comment by derwaldgeist** [comment]
I now tried the local install. It seemed to work, although I got a warning message after npm install:
```
npm WARN ENOENT ENOENT: no such file or directory, open '/Users/waldgeist/Documents/Development/htdocs/aiddogs/webapp/package.json'
npm WARN EPACKAGEJSON webapp No description
npm WARN EPACKAGEJSON webapp No repository field.
npm WARN EPACKAGEJSON webapp No README data
npm WARN EPACKAGEJSON webapp No license field.
```
My packages.json was just containing {}. Maybe that's the reason for this.

But when I tried to run chimp as explained in the docs, I got this error message:
```
localhost:webapp waldgeist$ ./node_modules/.bin/chimp
[chimp] Running...
selenium-standalone installation [====================] 100% 0.0s[chimp][cucumber] Directory features does not exist. Not running
```

**Comment by samhatoum** [comment]
The last message is fine, you just need to add a features directory under tests and put cucumber feature files in there.

Or if you want Mocha, use the `--mocha` flag and put test files in the tests directory.

Let me see about the global issue. I can't replicate it locally

**Comment by derwaldgeist** [comment]
Ah, ok. Thanks for that additional info. I thought it was an error, because it said "Not running". :-)

I will try out the ```mocha``` path now, since my app is too small for BDD and I "just" want to use chimp for some model class unit tests, to get started with the whole testing thing...

If there's anything I can do to help you in tracking down the global installation problem, let me know.

**Comment by samhatoum** [comment]
Hey @derwaldgeist 

for mocha, you can use this:

```
chimp --mocha --path=tests
```

For the EJSON problem, you need to remove the `package.json` from your meteor app. Check this folder structure for how you can do it:

https://github.com/xolvio/automated-testing-best-practices/

For the global problem, I got it. You need to change permissions on this directory:
`/usr/local/lib/node_modules/chimp/node_modules/selenium-standalone/.selenium`

you can do 
```
chmod 777 /usr/local/lib/node_modules/chimp/node_modules/selenium-standalone/.selenium
```

777 is very broad access, so feel free to adjust to something lower if you care!

**Comment by samhatoum** [comment]
let me know if I can close this :)

**Comment by programthis** [comment]
@samhatoum  I believe this line "chmod 777 /usr/local/lib/node_modules/chimp/node_modules/selenium-standalone/.selenium" should be "chmod 777 /usr/local/lib/node_modules/chimp/node_modules/selenium-standalone/" as the error seems to occur when trying to create the file ".selenium"

**Comment by samhatoum** [comment]
awesome thank you for the update

another thing that works is to zap the whole directory then try to `npm install` without sudo

**Comment by james1293** [comment]
@samhatoum : does "zap the whole directory" mean this?

`chmod 777 /usr/local/lib/node_modules`

**Comment by samhatoum** [comment]
it means `rm -rf` in my dictionary :)
