### ISSUE TITLE
json output always null.

### ISSUE THREAD

**Issue by mario-ortiz** [xolvio/chimp#206]
Hello, I'm new to Chimp and I'm having some problems trying to create the json report. I add the flags:
--format=json
--jsonOutput=file.json
--saveScreenshots=true
--attachScreenshotsToReport=true
--screenshotsOnError=true

I run my tests but the file.json is created empty everytime, just 1 line and it says null. I'm running version 0.20.2. I'm not sure if there is something else I should do, couldn't find much documentation about it.

**Comment by mario-ortiz** [comment]
Not sure what I did, but it's working now. So closing the Issue

**Comment by samhatoum** [comment]
Great :)
