### ISSUE TITLE
Velocity Mirror doesn't work with meteor 1.2.1 ?

### ISSUE THREAD

**Issue by Kacembouraoui** [xolvio/chimp#213]
i used Mocha to test my project and i hadn't results in the mocha iframe when i upgraded the version of meteor from 1.2.0.1 to 1.2.1 . I used the following example  in github : https://github.com/meteor-velocity/velocity-examples/tree/master/leaderboard-mocha . I had the same difficulty with my own project when i upgrade the version of meteor

**Comment by Sanjo** [comment]
The velocity mirrors work with Meteor 1.2.1. Please provide more details, in which situation it doesn't work as you would expect and how this is related to Chimp.

**Comment by Kacembouraoui** [comment]
i had not  also the results : failed or success of the mocha tests .

**Comment by samhatoum** [comment]
@Kacembouraoui 

https://github.com/xolvio/chimp/blob/develop/CONTRIBUTING.md

**Comment by Kacembouraoui** [comment]
@samhatoum 

Thank you , i will rewrite the bug  more clearly and below  the correct folder . I hope you can help me :)

**Comment by Sanjo** [comment]
Try `meteor add velocity:core@0.10.9`. This will update velocity:core to the latest version that works with Meteor 1.2.1.

**Comment by samhatoum** [comment]
Hey there. I don't think Velocity related issues below here. Either post in the mike:mocha repo please, or in sanjo:jasmine
