### ISSUE TITLE
DOM not ready before expects run

### ISSUE THREAD

**Issue by areim3r** [xolvio/chimp#215]
Just going off the example from the documentation, if I run this via:
chimp --mocha --browser=firefox

```javascript
describe('Chimp Mocha', function() {
  describe('Page title', function () {
    it('should be set by the Meteor method @watch', function () {
      browser.url('http://www.google.com');
      expect(browser.getText('h1')).to.equal('Google');
    });
  });
});
```
I get:
__Uncaught AssertionError: expected '' to equal 'Google'__

If however, I wrap the expect in a setTimeout with 0ms delay, it works as expected, like so:

```javascript
describe('Chimp Mocha', function() {
  describe('Page title', function () {
    it('should be set by the Meteor method @watch', function () {
      browser.url('http://www.google.com');
      setTimeout(function(){
        expect(browser.getText('h1')).to.equal('Google');
      }, 0);
    });
  });
});
```

am I missing something here or is this expected behavior? It seems the DOM is not ready when the expect code is run.

**Comment by areim3r** [comment]
ah nevermind this works as intended from the example in the repo:

```javascript
browser.url('http://google.com'); // SETUP
var title = browser.getTitle();   // EXECUTE
expect(title).to.equal('Google'); // VERIFY
```

maybe update the chimp.readme.io documentation to reflect this? because as it stands now the example I followed from there doesn't seem to work.

**Comment by Sanjo** [comment]
I have changed the example to get the title instead of the header. As you said, the DOM state seems not to be ready right after the page is loaded. I think `browser.waitForText('h1')` could be used to wait for the header to load.
