### ISSUE TITLE
Reuse cucumber steps:

### ISSUE THREAD

**Issue by JoeyAndres** [xolvio/chimp#217]
When I wrote acceptance tests for a php project, we can do the following:

```php
return array(
            new Given('I go to the current course activity completion report'),
            new Given('I hover "' . $this->escape($xpath) . '" "xpath_element"')
        );
```

This got rid of code redundancy.

I have google this thing for a while and can't find a solution. Currently, my solution is in my ```step_defs.js``` I have the following:

```javascript
this.Then(/^"([^"]*)" should be in the session page$/, user_should_be_in_session_page);
```

And in my ```helpers.js``` I have the following:

```javascript
global.user_should_be_in_session_page = function(user) {
    // Check for page elements that must exist in host session page.
    user_should_see_selector(user, "//button[contains(text(), 'Create Question')]");
    user_should_see_selector(user, "//button[contains(text(), 'Archived Questions')]");
    user_should_see_selector(user, "//button[contains(text(), 'End Session')]");
    user_should_read_text(user, "Session Code:");
    user_should_read_text(user, "Logged-in students:");
    user_should_read_text(user, "Question count:");
};
```

I separate the function that does the work so that I can reuse it. The function in the example above reused other helper functions.

This is not a bug, _I'm just asking the best practices for dealing with this problem_. Also, a place I can link to in case people read my code, in case they were wondering why they can't do the same thing with the php behat tests.

**Comment by samhatoum** [comment]
Thanks for sharing this. It's a cucumber decisions not to allow step reuse, where behat does. What you've suggested is indeed the right way to do it.

**Comment by JoeyAndres** [comment]
I should add that using jasmine cucumber is much more efficient and self documenting. Imagine assigning an ugly selector to a well named variable.
