### ISSUE TITLE
Question: How to specify npm dependencies for cucumber step definitions

### ISSUE THREAD

**Issue by workflow** [xolvio/chimp#218]
Howdy,

apologies in advance if I just missed it in the docs somewhere: So `xolvio:cucumber` iirc had support for a `package.json` file under `tests/cucumber` which would auto-`npm install` any npm dependencies needed inside those crunchy cucumber steps.

Is there a similar mechanism available with chimp?

Thanks for the great work and generous community support as always. Just migrated over to chimp and it's beautiful!

**Comment by samhatoum** [comment]
awesome to hear and thanks :)

you can just define a package.json at a level above the features and have access to the modules that way. We do that in the automated testing best practices repo

**Comment by samhatoum** [comment]
I turned off auto npm install as it was slowing startup time down and when working outside Meteor, npm is the norm and devs know how to handle it :)

**Comment by workflow** [comment]
Fair enough, thx :)
