### ISSUE TITLE
server.call() and server.execute() does not return userId

### ISSUE THREAD

**Issue by jirikrepl** [xolvio/chimp#219]
Hi, I have mocha test which registers some user. Then I want to get his userId. I cannot get anything from  methods ```server.call(), server.execute(), client.execute()``` mentioned [in documentation](https://chimp.readme.io/docs/getting-started-with-meteor-cucumber#section-call-a-ddp-method).

When I start test, database is cleared, new user is registered and code should return his userId. It returns null.

I also tried comment-out all code beside one responsible for returning userId. Then the test did nothing with UI. Only mention methods were run. User was logged in from previous test run, but still same null output.

    // in mocha-spec.js

    describe('meld user accounts', function () {

        beforeEach(function () {
            browser.goTo('/');
            browser.pressMenuButton();
            browser.pressButton('Sign In');
        });

        it('should sign up user by email @watch', function () {
            browser.followLink('Register');
            browser.setValue('#at-field-email', 'meteor.nedatluj@gmail.com');
            browser.setValue('#at-field-password', 'qwerty');
            browser.pressButton('Register');

            var userId = server.call('getUser');
            console.log(userId); // returns null

            var getUserId = function() {
                return Meteor.userId();
            };
            var result = server.execute(getUserId);
            console.log(result); // returns null

            result = browser.execute(getUserId);
            console.log(result); // returns { state: 'success',  sessionId: 'cd071191-0ae8-479b-b8ef45a2ccdb3f00',  hCode: 20805550,  value: null,  class: 'org.openqa.selenium.remote.Response',  status: 0 }
        });
    });

Inside fixtures.js

    (function () {
        'use strict';
        
        Meteor.methods({        
            getUser: function() {
                // return 1234; // this works                
                return Meteor.userId();
            }
        });
    })();

**Comment by Sanjo** [comment]
Hi, the server instance has a separate DDP connection. It's not the same DDP connection as the browser has to the server. Therefore you need to login first with:

```js
server.call('login', {
        user: {email: user.email},
        password: user.password
      });
```

You can logout with:

```
server.call('logout');
```

If you reset your database, you need to logout before. Otherwise it messes up the DDP connection.

**Comment by jirikrepl** [comment]
Thank you sir. Works like a charm.

BTW where can I read about those different DDP connections? Thank you
