### ISSUE TITLE
Add some getting started docs for BrowserStack

### ISSUE THREAD

**Issue by AGoliath** [xolvio/chimp#223]
I´ve played with the code as of PR #212 
It works great, but there is a little lack of documentation on the whole BrowserStack integration thing.

Things that come to mind that need to be documented:

- What parameters need to be documented for it to work at all (e.g. where to get the value for the --key parameter you need to add to the chimp call)?
- How to use specific BrowserStack features, e.g. which chimp parameter maps to which BrowserStack API parameter. 
- How to add the natural language test infos to the BrowserStack output

I´ve added this issue and intend to contribute the docs for that (and maybe some minor code changes as well for more comfy integration), but feel free to chime in.

**Comment by ramijarrar** [comment]
https://chimp.readme.io/docs/using-saucelabs-browserstack-seleniumgrid

I think that article should be enough from Chimp's end. BrowserStack/Sauce Labs provide their own docs on mapping specific features to capabilities.
