### ISSUE TITLE
ReferenceError: module is not defined

### ISSUE THREAD

**Issue by chathuraa** [xolvio/chimp#225]
Hi Sam,

After updating the step definition I get an error. "ReferenceError: module is not defined" . Am i missing anything?

Thanks,

**Comment by samhatoum** [comment]
where are your step definitions?

**Comment by chathuraa** [comment]
/features/support/step_defs.js

**Comment by samhatoum** [comment]
Put the features folder in a tests folder

**Comment by chathuraa** [comment]
Its coming up saying "Directory features does not exist."

**Comment by samhatoum** [comment]
Hey man. I'm happy to help, but you also got to read the docs! http://chimp.readme.io

Pass chimp the `--path=./tests/features` option

**Comment by chathuraa** [comment]
Hey Sam, Thanks, I thought it only needed for mocha. My apologies.

**Comment by samhatoum** [comment]
no probs :) you can also run chimp from within `/tests`and that will work

check out the scripts over here:
https://github.com/xolvio/automated-testing-best-practices/

under the `.scripts` folder
