### ISSUE TITLE
Drawbacks migrating from xolvio/cucumber

### ISSUE THREAD

**Issue by bjarketrux** [xolvio/chimp#229]
Hi
I just want to confirm the following drawbacks (perhaps fixes) when migrating from xolvio/cucumber to chimp.

1. Using Velocity HTML reporter for unit/integration tests will interfere when running meteor in dev mode.
This is because the velocity window will be shown while the UI tests are executed. I guess a fix to this is to run meteor in production mode, but then you need to restart meteor whenever you want to run UI tests.
EDIT: Cannot run in production mode, because then the debugOnly fixtures package will not be loaded. Guess I need to run without the HTML Reporter.
EDIT2: I can use VELOCITY=0 then the window won't pop up

2. No mirrors = development data will be erased or interfere with tests.
Running chimp against your development meteor will override data (if you have fixtures). You can do a meteor reset after UI test to reset your development environment.

Any comments or suggestions on how to make development more smooth?
Thanks

**Comment by danimbrogno** [comment]
@samhatoum has provided an [automated testing best practices repository](https://github.com/xolvio/automated-testing-best-practices) which demonstrates a solution to this issue.

The approach involves having a node script that is in charge of booting up your meteor application under the ideal settings for development. It provides a mechanism for you to run your tests against a parallel mirror if you so desire.

I highly suggest you check out his approach, I've implemented it myself and am pretty happy with the result.

**Comment by bjarketrux** [comment]
Thanks @danimbrogno. I will check it out.
