### ISSUE TITLE
Getting variables of a Meteor app

### ISSUE THREAD

**Issue by Menda** [xolvio/chimp#232]
I don't know if this is not the use case of this framework, but I'm trying to make some unit tests with Mocha to test a collection I did. I have in `project/tests/unit/server/test-collections.js` this content:

    describe('Manufacturers', function() {
      it('is inserted successfuly @focus', function () {
        Manufacturers.insert({name: "Ferrari", description: "A luxurious manufacturer"}, function(error, result) {});
      });
    });

However, I'm getting this error:

    ReferenceError: Manufacturers is not defined

I also try in that file to `console.log(Meteor);`, getting the same `not defined` error. Is it not possible to test the way I do the app?

I use **METEOR@1.2.1** and the following command:

    $ chimp --ddp=http://localhost:3000 --watch --mocha  --path=tests

Thanks and greetings,
Rafa.

**Comment by samhatoum** [comment]
Hey

If you want to run code on the server, you have to do it like this:

```javascript
server.execute(function() {
  Manufacturers.insert(...)
});
```

**Comment by Menda** [comment]
OK, works! It wasn't clear for me when I read the documentation, I'm pretty newbie.

Thanks Sam :+1:
