### ISSUE TITLE
Chai is not being included even --chai is used

### ISSUE THREAD

**Issue by Menda** [xolvio/chimp#233]
Hi again, I'm running against problems.

It seems chai is not being included, even though I run the server with `--chai`:

    $ chimp --ddp=http://localhost:3000 --mocha --chai --path=tests --watch --debug
    [chimp][ddp-watcher] Connected
    [chimp] Watching features with tagged with @dev,@watch,@focus
    [chimp] watcher ready, running for the first time
    [chimp] rerunning

    [chimp] Running...
    [chimp] interrupting
    [chimp] no processes to interrupt
    [chimp][selenium] Selenium object created
    [chimp][selenium] Start
    [chimp][selenium] Installing Selenium + drivers if needed
    [chimp][ddp-watcher] ADDED to meteor_autoupdate_clientVersions:  sPegp777s9Ts9uTwh
    [chimp][ddp-watcher] ADDED to meteor_autoupdate_clientVersions:  version
    [chimp][ddp-watcher] ADDED to meteor_autoupdate_clientVersions:  version-cordova
    [chimp][ddp-watcher] ADDED to meteor_autoupdate_clientVersions:  version-refreshable
    [chimp][ddp-watcher] meteor_autoupdate_clientVersions ready:
    [chimp][ddp-watcher] [object Object]

    [chimp][selenium] hub can be seen at http://localhost:62924/wd/hub
    [chimp][session-manager] options are { host: 'localhost',
      port: '62924',
      browser: 'chrome',
      deviceName: undefined }
    [chimp][session-manager] created a new SessionManager { host: 'localhost',
      port: '62924',
      browser: 'chrome',
      deviceName: undefined }
    [chimp][mocha] Running...

    [chimp][helper] Using the chai-expect assertion library
    [chimp][ddp] creating DDP wrapper
    [chimp][ddp] Connecting to DDP server { host: 'localhost',
      port: '3000',
      ssl: false,
      autoReconnect: true,
      autoReconnectTimer: 500,
      maintainCollections: true,
      ddpVersion: '1',
      useSockJs: true }
    [chimp][helper] getting browser
    [chimp][session-manager] options are { host: 'localhost',
      port: '62924',
      browser: 'chrome',
      deviceName: undefined }
    [chimp][session-manager] created a new SessionManager { host: 'localhost',
      port: '62924',
      browser: 'chrome',
      deviceName: undefined }
    [chimp][helper] custom chimp.js not found, loading defaults
    [chimp][helper] webdriverOptions are  {"waitforTimeout":10000,"timeoutsImplicitWait":3000,"desiredCapabilities":{"browserName":"chrome","platform":"ANY","name":"","chromeOptions":{},"applicationCacheEnabled":false},"host":"localhost","port":"62924","logLevel":"silent","sync":true}
    [chimp][session-manager] creating webdriver remote
    [chimp][session-manager] checking connection to selenium server
    [chimp][session-manager] Connection to the to selenium server verified
    [chimp][session-manager] requesting sessions from http://localhost:62924/wd/hub/sessions
    [chimp][session-manager] received data {"state":"success","sessionId":null,"hCode":1985261687,"value":[],"class":"org.openqa.selenium.remote.Response","status":0}
    [chimp][session-manager] Did not find any open selenium sessions, not reusing a session
    [chimp][session-manager] monkey patching the browser object
    [chimp][helper] init browser
    [chimp][session-manager] initializing browser
    [chimp][helper] init browser callback
    [chimp][helper] set timeoutsAsyncScript
    [chimp][helper] setup DDP
    [chimp][helper] connecting via DDP to http://localhost:3000
    [chimp][helper] connecting via DDP had no error

And here my example:

    describe('Manufacturers', function() {
      it('schema is inserted successfuly @dev', function () {
        server.execute(function() {
          expect(false).to.equal(false);
        });
      });
    });

With the error:

    1) Account Holder initialization event @dev should create an account with a balance of 0:
       Uncaught TypeError: undefined is not a function
        at Context.<anonymous> (tests/components/models/account-holder-spec.js:4:20)
        at /usr/local/lib/node_modules/chimp/lib/mocha/mocha-fiberized-ui.js:21:14

Any guess? Do I need to install some extra?
Thanks again.

**Comment by Menda** [comment]
However I realised that not using the server.execute, runs fine:

    describe('Manufacturers', function() {
      it('schema is inserted successfuly @dev', function () {
        expect(false).to.equal(false);
      });
    });

What can be the problem?

**Comment by samhatoum** [comment]
`to.be` or not `toBe`, [that is the question](https://en.m.wikipedia.org/wiki/To_be,_or_not_to_be) ;)

**Comment by Menda** [comment]
Thanks again!
