### ISSUE TITLE
Support Sync WebdriverCSS 

### ISSUE THREAD

**Issue by nichite** [xolvio/chimp#236]
The feature of wrapping asynchronous methods with wrapAsync doesn't seem to work properly on the webdrivercss command for taking css diff screenshots. The call to the function looks like this:

``` javascript
browser.webdrivercss('body', {
          name: 'body',
          elem: 'body'
        }, function (err, res){
          assert.ifError(err);
          assert.ok(res.body.isWithinMisMatchTolerance);
        });
```

It looks to be in the standard style where the last argument is a cb that takes err, res as arguments. According to what I've read, `wrapAsync` should be able to handle this.

I've wrapped the function to be synchronous like this:

``` javascript
var cssSync = wrapAsync(browser.webdrivercss);

var res = cssSync('body', {
    name: 'body',
    elem: 'body'
  });

assert.ok(res.body.isWithinMisMatchTolerance);
```

Still, whenever I run this I get the error: `Can't wait without a fiber`.

I've also tried passing in `browser` or `this` as contexts, just in case. No dice.

Thoughts?

**Comment by Sanjo** [comment]
The async wrapping should happen automatically for added webdriver commands.

So if it would work, this should be enough:

```js
var result = browser.webdrivercss('body', {
  name: 'body',
  elem: 'body'
});

assert.ok(result.body.isWithinMisMatchTolerance);
```

Can you try this? If it doesn't work, I need to debug it.

**Comment by nichite** [comment]
My testing shows that this way does not work either--thinking back, that's why I tried to wrap it myself in the first place. It's giving me the same error, `Can't wait without a fiber`.

I'm using `webdriverio@3.4.0` and `webdrivercss@2.0.0-beta-rc1`. Other versions of webdrivercss aren't compatible with webdriverio v 3.0+. Could that be causing compatibility issues?

**Comment by Sanjo** [comment]
You pass the client/browser instance from Chimp to webdrivercss, right?

**Comment by nichite** [comment]
Correct, earlier in my code I have:

```javascript
var webdrivercss = require('webdrivercss');
[...] // Other stuff
webdrivercss.init(browser, {
          screenshotRoot: 'screenshots',
          failedComparisonRoot: 'diffs',
          misMatchTolerance: 0.05,
          screenWidth: [320,480,640,1024]
        });
```

as per the example on webdriver's npm page.

**Comment by Sanjo** [comment]
Ok. So probably some asynchronous code in webdrivercss that is not wrapped automatically with wrapAsync causes the callback to not be in the fiber. To fix that we need to create a sync-webdrivercss package that patches the webdrivercss package, to work with fibers. Like we did with webdriver already (https://github.com/xolvio/sync-webdriverio). Or a fork of webdrivercss, if the patching is too hard.

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy
https://github.com/TheBrainFamily/chimpy/issues
