### ISSUE TITLE
Logging not appearing anywhere

### ISSUE THREAD

**Issue by Menda** [xolvio/chimp#237]
Trying to execute on tests `console.log()` on the test doesn't work at all and does not print into the Chimp's open console. Also doesn't write any log file into `.meteor`.

Even though it's debuggeable with node-inspector, this is a much quicker and user-friendly way to make it.

Thanks.

**Comment by samhatoum** [comment]
sorry I missed this. where are you doing the console.log()? They should definitely appear in the chimp console window

**Comment by Menda** [comment]
Hi again. Maybe it was a bug in the version I used, but right now I confirm that putting a log in my `defs.py` like this:

```
  this.Given(/^I have visited the homepage$/, function() {
    console.log('Hi dev!');
    browser.url(process.env.ROOT_URL);
  });
````

Prints message without any problem. I close the issue.
Thanks!
