### ISSUE TITLE
@watch produces SyntaxError in mocha tests

### ISSUE THREAD

**Issue by laran** [xolvio/chimp#238]
This test:

    (function() {
        "use strict";

        @watch
        describe('Chimp Mocha', function() {
          describe('Page title', function () {
            it('should be set by the Meteor method @watch', function () {
              browser.url('http://www.google.com');
              expect(browser.getTitle()).to.equal('Google');
            });
          });
        });    
    })();

Produces this error:

    [chimp][mocha] Running...
    /Users/laran/workspace/foo/tests/features/accounts/join.js:4
        @watch
        ^

    SyntaxError: Unexpected token ILLEGAL
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:373:25)
        at Object.Module._extensions..js (module.js:404:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at /usr/local/lib/node_modules/chimp/node_modules/mocha/lib/mocha.js:216:27
        at Array.forEach (native)
        at Mocha.loadFiles (/usr/local/lib/node_modules/chimp/node_modules/mocha/lib/mocha.js:213:14)
        at Mocha.run (/usr/local/lib/node_modules/chimp/node_modules/mocha/lib/mocha.js:453:10)
        at Object.<anonymous> (/usr/local/lib/node_modules/chimp/lib/mocha/mocha-wrapper.js:34:9)
        at Module._compile (module.js:397:26)
        at Object.Module._extensions..js (module.js:404:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
    [chimp][mocha] Closed with code 1
    [chimp][mocha] Mocha not in a stopping state
    [chimp] Finished running async processes with errors
    [chimp] run complete with errors Mocha failed
    [chimp] finished rerun

It's not clear to me from the documentation whether or not this is supported in mocha tests (or will be in jasmine tests in the future). I wonder if it's only supported in cucumber tests.

What I would like to see is the tag supported on the `describe` and the `it`.

I'm running in meteor and here's my list of packages:

    accounts-facebook           1.0.6  Login service for Facebook accounts
    accounts-google             1.0.6  Login service for Google accounts
    accounts-password           1.1.4  Password support for accounts
    aldeed:simple-schema        1.5.3  A simple schema validation object with reactivity. Used by collection2 and autoform.
    blaze-html-templates        1.0.1  Compile HTML templates into reactive UI with Meteor Blaze
    dburles:collection-helpers  1.0.4  Transform your collections with helpers that you define
    ecmascript                  0.1.6* Compiler plugin that supports ES2015+ in all .js files
    email                       1.0.8  Send email messages
    es5-shim                    4.1.14  Shims and polyfills to improve ECMAScript 5 support
    fortawesome:fontawesome     4.5.0  Font Awesome (official): 500+ scalable vector icons, customizable via CSS, Retina friendly
    insecure                    1.0.4  (For prototyping only) Allow all database writes from the client
    iron:router                 1.0.12  Routing specifically designed for Meteor
    jquery                      1.11.4  Manipulate the DOM using CSS selectors
    juliancwirko:s-alert        3.1.4  Simple and fancy notifications / alerts / errors for Meteor
    matb33:collection-hooks     0.8.1  Extends Mongo.Collection with before/after hooks for insert/update/remove/find/findOne
    meteor-base                 1.0.1  Packages that every Meteor app needs
    meteorhacks:ssr             2.2.0  Server Side Rendering for Meteor with Blaze
    mobile-experience           1.0.1  Packages for a great mobile user experience
    momentjs:moment             2.11.1  Moment.js (official): parse, validate, manipulate, and display dates - official Meteor...
    mongo                       1.1.3  Adaptor for using MongoDB and Minimongo over DDP
    reactive-var                1.0.6  Reactive variable
    service-configuration       1.0.5  Manage the configuration for third-party services
    session                     1.1.1  Session variable
    standard-minifiers          1.0.2  Standard minifiers used with Meteor apps by default.
    tracker                     1.0.9  Dependency tracker to allow reactive callbacks
    twbs:bootstrap              3.3.6  The most popular front-end framework for developing responsive, mobile first projects o...
    underscore                  1.0.4  Collection of small helpers: _.map, _.each, ...
    zimme:active-route          2.3.2  Active route helpers

How do I utilize tags in mocha tests?

**Comment by samhatoum** [comment]
Put the watch inside the `describe` or `it` string, like:

```
it('should be set by the Meteor method @watch')
```

**Comment by laran** [comment]
Gotcha! Suggested an improvement to the documentation. Thanks!

**Comment by samhatoum** [comment]
Thank you!
