### ISSUE TITLE
Why are calls to browser in mocha tests NOT chainable like they are in normal webdriver?

### ISSUE THREAD

**Issue by laran** [xolvio/chimp#239]
In the docs it seems that you can chain calls like this:

    browser.url('http://www.google.com').setValue('input[name=q]',chimp).click("=Google Search")

But in my mocha tests invoked with chimp I have to separate the calls:

    browser.url('http://www.google.com');
    browser.setValue('input[name=q]','chimp');
    browser.click("=Google Search");

Am I missing something? Or is this accurate. And if so, why can't the calls be chained?

**Comment by samhatoum** [comment]
Which docs?

Chimp is synchronous. Chaining is not possible since some synchronous methods like `getTitle` for example return a value.

If you use `--sync=false` then you can chain, but you lose synchronous :)

You have to choose I'm afraid!

**Comment by samhatoum** [comment]
It's possible to get methods that don't return a value to return the browser object and therefore be chainable, but that creates confusion due to inconsistency.

**Comment by laran** [comment]
Sounds perfectly reasonable. This might be made more obvious from the start with some docs and examples using mocha. Most of the samples that I've seen so far use Cucumber, the automated testing best practices repo being probably the biggest example.

Thank you for answering so quickly!
