### ISSUE TITLE
jQuery and external library support

### ISSUE THREAD

**Issue by laran** [xolvio/chimp#241]
I'm testing a meteor app. jQuery is included in meteor. So when I go to write tests it seems natural to refer to jquery through $. But it isn't available in my tests.

I also tried `cd tests; npm init; npm install jquery --save` and including `var $ = require('jquery')` at the top of tests/mySpec.js. But I get `Uncaught Error: jQuery requires a window with a document`.

I could use browser.something to get the element. But jquery would be much more powerful. Support for libraries like lodash or underscore would also be valuable.

So, what's the recommendation for how to do this stuff?

**Comment by danborufka** [comment]
Since you are already using jQuery in your meteor app you would just need to execute the according JavaScript inside the browser window using `browser.execute` like e.g.:

````js
var itemCount = browser.execute(function() {
        return $('.item').removeClass('active').length;
});
````

**Comment by Sanjo** [comment]
You can use any npm package in your step definitions. Just use `npm install` and `require(...)` as usual.
Step definition code runs in a node.js process by default. With client.execute you can execute some code in the current web page context, as danborufka has shown.
