### ISSUE TITLE
Selenium browser.keys() not working in Safari

### ISSUE THREAD

**Issue by wirsingj** [xolvio/chimp#242]
Hey,  I have some cucumber/selenium tests that work fine in every browser but Safari..    

In safari the commands:  browser.url, and browser.setValue work fine, but browser.keys is throwing an error.

Error: Unknown command: {"id":"tjapbs6daxpe","name":"sendKeysToActiveElement","parameters":{"value":[""]}} (WARNING: The server did not provide any stacktrace information)

The key being sent is 'Enter'

I'm using Safari Webdriver 2.48.0.

**Comment by Sanjo** [comment]
Hi, I think the correct place to report and fix this issue is in webdriver.io: https://github.com/webdriverio/webdriverio/issues. Chimp is just using webdriver.io.
