### ISSUE TITLE
Chimp test are failing on CodeShip 

### ISSUE THREAD

**Issue by chetan-jadhav** [xolvio/chimp#250]
### Overview
We are using CodeShip for continuous integration, and while running tests on CodeShip few of the test cases are failing. We are not able to find a reason behind it. When we try to run on local machine all test cases are working fine.
We tried adding delay in steps and also we have waitForExist() in each steps.

### Steps we are following commands while running test cases
`Xvfb :1 -screen 0 1024x768x24 2>/dev/null &`
`export DISPLAY=:1.0`
`chimp --browser=chrome`

Please give us pointer, we are not sure what we are doing wrong.

**Comment by samhatoum** [comment]
Can you isolate to a single test case and post it here please?
