### ISSUE TITLE
Meteor is not defined

### ISSUE THREAD

**Issue by thomasvanlankveld** [xolvio/chimp#251]
The following:

```javascript
function getUser() {
  return Meteor.user();
}
var user = client.execute(getUser);
```

gives

```
    Dan kan ik inloggen als bus met naam "Bus 1" en wachtwoord "asdfghjk"    # tests/features/beheerder/busAccountAanmaken.feature:12
      Error: unknown error: Meteor is not defined
        at World.<anonymous> (tests/features/beheerder/adminStepDefinitions.js:35:23)
```

I get a similar error when calling `server.execute()` unless I include `meteor-base` in `.meteor/packages`:

```
(::) failed steps (::)

Error: Error in server.executeReferenceError: Meteor is not defined
  at World.<anonymous> (tests/features/beheerder/adminStepDefinitions.js:34:12)

ReferenceError: Meteor is not defined
  @ login (evalmachine.<anonymous>:2:10)
  @ [object Object].Meteor.methods.xolvio/backdoor (server.js:10:54)
  @ maybeAuditArgumentChecks (livedata_server.js:1698:12)
  @ livedata_server.js:708:19
  @ [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
  @ livedata_server.js:706:40
  @ [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
  @ livedata_server.js:704:46
  @ tryCallTwo (/Users/thomasvanlankveld/.meteor/packages/promise/.0.5.1.1wchp76++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
  @ doResolve (/Users/thomasvanlankveld/.meteor/packages/promise/.0.5.1.1wchp76++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)

Failing scenarios:
tests/features/beheerder/busAccountAanmaken.feature:9 # Scenario: Eerste bus account
```

The second tripped me up when trying a package-only architecture, which involves `api.imply()`ing `meteor-base`. (no external dependencies `.meteor/packages`)

**Comment by samhatoum** [comment]
Are you navigating to the app first for `client.execute`?

**Comment by samhatoum** [comment]
Using `client.url('http://localhost:3000")`

**Comment by thomasvanlankveld** [comment]
Ah, that solves the client error! I assumed connection would be established by passing the `--ddp=http://localhost:3000` flag, as described in [Using Chimp with Meteor](https://chimp.readme.io/docs/getting-started-with-meteor-cucumber), which does not mention `client.url`

**Comment by samhatoum** [comment]
Thanks for letting me know, that page is updated

**Comment by thomasvanlankveld** [comment]
Ok, I though I had this but it seems I don't.

Still getting `Error: unknown error: Meteor is not defined` on `client.execute`, even after connecting with `client.url('http://localhost:3000')`.

Should I have more packages in `.meteor/packages`? I have:

```
meteor-base
mongo
```

I'd also be very happy with a way to get published data without using `client.execute`. I'm building a DDP API, so the only reason I'm using `client.execute` is to fetch data from subscriptions:

```javascript
function getHomeId(name) {
  Meteor.subscribe('/register/homes');
  var Homes = new Mongo.Collection('homes');
  return Homes.findOne({name: name})._id;
}
```

I'm just starting the project now, but it feels like I'm going to have to build the data part of a client app later on to keep my test suite maintainable. (which I'm [not sure](http://stackoverflow.com/questions/35011294/extending-cucumber-world-for-chimp-tests) how to do yet)

**Comment by samhatoum** [comment]
You can use the ddp connection from within the cucumber steps. The `server` object is actually a [DDP connection](https://github.com/oortcloud/node-ddp-client). It has the ability to [authenticate](https://github.com/oortcloud/node-ddp-client#authentication) and also [subscribe (see example)](https://github.com/oortcloud/node-ddp-client#example).

You can use this DDP connection to do all the work without touching the client.

**Comment by thomasvanlankveld** [comment]
Thank you for the quick response!

I'm going to submit a bunch of subscription-related issues that I ran into; I've kind of found a way to continue so it's not super urgent :)
