### ISSUE TITLE
Coffeescript files not detected

### ISSUE THREAD

**Issue by yogiben** [xolvio/chimp#257]
Googling around, it seemed like using coffeescript would be supported, however, when switching a `.js` file to its `.coffee` equivalent, it seems like it's no longer picked up. Changing the file does not trigger a rerun.

Using cucumber.

I see in the `package.json` there is no `coffeescript` dependency. Is this on the roadmap?

**Comment by samhatoum** [comment]
is this for mocha or cukes?

**Comment by yogiben** [comment]
Cucumber.

```
module.exports = function() {
  this.Given('I have visited $path', function(path) {
    var url;
    url = 'http://localhost:3000' + path;
    browser.url(url);
  });
};
```

to

```
@module.exports = ->
  @Given 'I have visited $path', (path) ->
    url = 'http://localhost:3000' + path
    browser.url url
```

**Comment by samhatoum** [comment]
For the current version of Chimp, I think `--coffee` will do the trick

For the upcoming ES6 supporting version, it will use this instead:
https://github.com/cucumber/cucumber-js#transpilers

**Comment by yogiben** [comment]
Unfortunately running `chimp --ddp=http://localhost:3000 --watch --coffee` does not solve the problem.

I'll stick with good ol' fashioned JS until the next release.

> ~~Changing the file does not trigger a rerun~~

Changing file does trigger rerun.

**Comment by samhatoum** [comment]
oh, sorry I missed the last part. You can add an additional `--watchSource=<dir>/*.coffee`

**Comment by yogiben** [comment]
Still not working: `chimp --ddp=http://localhost:3000 --watch --coffee --watchSource=./*.coffee`

Should there not be a coffeescript npm dependency?

https://github.com/xolvio/chimp/search?utf8=%E2%9C%93&q=coffee

**Comment by Sanjo** [comment]
Was the bug report for 0.25.1 or 0.26.0-rc.0? I have just release 0.26.0. That should you allow you to get CoffeeScript support via https://github.com/cucumber/cucumber-js#transpilers. We also support ES2015 by default now.

**Comment by yogiben** [comment]
Upgraded to 0.26.0.

`chimp --ddp=http://localhost:3100 --watch --compiler coffee:features`

Produces
```
[chimp] Running...
/Users/gringo/.nvm/versions/node/v4.2.2/lib/node_modules/chimp/node_modules/cucumber/lib/cucumber/parser.js:21
          throw e;
          ^

Error: Lexing error on line 1: '@module.exports = ->'. See http://wiki.github.com/cucumber/gherkin/lexingerror for more information.
path: /Users/gringo/dev/bitcoin/bitwala/app/tests/features/defs.coffee
    at Lexer.scan (/Users/gringo/.nvm/versions/node/v4.2.2/lib/node_modules/chimp/node_modules/gherkin/lib/gherkin/lexer/en.js:1008:13)
    at GherkinLexer.scan (/Users/gringo/.nvm/versions/node/v4.2.2/lib/node_modules/chimp/node_modules/cucumber/lib/cucumber/gherkin_lexer.js:25:11)
    at Object.parse (/Users/gringo/.nvm/versions/node/v4.2.2/lib/node_modules/chimp/node_modules/cucumber/lib/cucumber/parser.js:18:17)
    at Object.getFeatures (/Users/gringo/.nvm/versions/node/v4.2.2/lib/node_modules/chimp/node_modules/cucumber/lib/cucumber/runtime.js:38:35)
    at Object.start (/Users/gringo/.nvm/versions/node/v4.2.2/lib/node_modules/chimp/node_modules/cucumber/lib/cucumber/runtime.js:11:27)
    at Object.run (/Users/gringo/.nvm/versions/node/v4.2.2/lib/node_modules/chimp/node_modules/cucumber/lib/cucumber/cli.js:60:15)
    at Object.<anonymous> (/Users/gringo/.nvm/versions/node/v4.2.2/lib/node_modules/chimp/dist/lib/cucumberjs/cucumber-wrapper.js:78:5)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
```

Running from `tests` directory with following file structure
```
└── features
    ├── defs.coffee
    └── visitors
        ├── QuickPay.feature
        ├── QuickPay.js
        ├── Visit\ Homepage.feature
        └── Visit\ Homepage.js
```

**Comment by Sanjo** [comment]
@yogiben How it should work is:

```
npm install coffee-scripts --save
```

then you add the option `--compiler=coffee:coffee-script/register` to Chimp.

**Comment by rohithb** [comment]
Hi I tried this but I got an error  ` Cannot find module 'lodash'`.   
So I installed `loaddash`, then I got this error  

```
/home/rohith/projects/codeWays/tests/features/node_modules/chimp/dist/__mocks__/bluebird.js:3
jest.autoMockOff();
^

ReferenceError: jest is not defined
```

**Comment by topleft** [comment]
+1
