### ISSUE TITLE
Run a command once, before test suite

### ISSUE THREAD

**Issue by yogiben** [xolvio/chimp#264]
I want my `fixtures/resetDatabase` & `fixtures/createData` to run once, before chimp starts to execute. 

Using `Meteor.startup` doesn't work when using `@watch` locally, as the app is not always restarted.

Using `this.Before` executes before every test.

**Comment by samhatoum** [comment]
try the `BeforeFeatures` hook - but I would highly recommend that each scenario has a completely fresh clean slate to work from. The data you create should only be as much as is needed for the scenario, no more and no less. The issue you'll face is the difficulty in maintaining the single data source that `createData` uses.

**Comment by yogiben** [comment]
Thanks
