### ISSUE TITLE
How to use external libraries, such as underscore, in chimp cucumber

### ISSUE THREAD

**Issue by yogiben** [xolvio/chimp#265]
What are the best practices for adding external libraries?
```
var emails = server.call('emailStub/getEmails');
var email = _.findWhere(emails, {recipient: 'satoshi@bitwa.la'});
```

**Comment by Sanjo** [comment]
The standard node.js way. E.g. `npm install underscore --save-dev` (assuming, you already have a package.json, otherwise create one with `npm init`). And then you can just require it in your step definition files with: `var _ = require('underscore')`.
