### ISSUE TITLE
server.subscribe halts execution

### ISSUE THREAD

**Issue by thomasvanlankveld** [xolvio/chimp#266]
When the test runner hits `server.subscribe('stuff')`, it halts.

Running `chimp --watch --ddp="http://localhost:3000" --path=tests`, using the files in [this gist](https://gist.github.com/thomasvanlankveld/891f706284d96ee34239), results in:

```
[chimp] Running...

Feature: publish


  @watch
  Scenario: test         # tests/features/test.feature:4
    Given "thing"        # tests/features/test.feature:5

```

It just stops there.

I can continue execution by manually calling the callback as documented in the [`node-ddp-client`](https://github.com/oortcloud/node-ddp-client#example) docs:

```javascript
server.subscribe('stuff', [], function() {
  callback();
});
```

This is confusing since Chimp promotes a synchronous style. I would expect `server.subscribe` to work synchronously. Also the solution above can not be found in the Chimp documentation, since it [doesn't explain](https://chimp.readme.io/docs/tutorial) how to use `callback`, and it [doesn't mention](https://chimp.readme.io/docs/getting-started-with-meteor-cucumber) that `server` is really `node-ddp-client` under the hood.

**Comment by thomasvanlankveld** [comment]
Tried wrapping `server.subscribe`:

```javascript
var func = wrapAsync(server.subscribe);
func('stuff');
```

and

```javascript
var obj = wrapAsyncObject(server, ['subscribe']);
obj.subscribe('stuff');
```

To get around #289, but no change. (I guess Chimp already did this somewhere)

**Comment by Sanjo** [comment]
subscribe takes two arguments. When you pass both arguments it probably works. Not sure if wrapAsyncObject supports callbacks, but I think so.

**Comment by lgandecki** [comment]
This should be fixed now in the xolvio-ddp client. npm update in chimp solves the problem for the gist above - thanks for making this so easy to reproduce. 
Make sure chimp uses xolvio-ddp at 0.12.1 version
