### ISSUE TITLE
Collections not available on server object

### ISSUE THREAD

**Issue by thomasvanlankveld** [xolvio/chimp#267]
After subscribing to a publication, I can access the received like such (replace `stepDefs.js` in [this gist](https://gist.github.com/thomasvanlankveld/891f706284d96ee34239)):

```javascript
module.exports = function() {

  this.Given(/^"([^"]*)"$/, function (name) {
    server.execute(function(thing) { Stuff.insert(thing) }, { name: name })
  });

  this.When(/^I look at stuff$/, function (callback) {
    server.subscribe('stuff', [], function() {
      callback();
    });
  });

  this.Then(/^I see "([^"]*)"$/, function (name) {
    var stuff = server._original.collections.stuff;
    var thing = Object.keys(stuff).filter(function(key) {
      return stuff[key].name === name;
    })[0];

    expect(thing).toBeDefined();
  });

};
```

However, the underscore in `_original` makes me imagine I shouldn't be using this.

Querying with `server.execute(function() { return Stuff.findOne(); });` won't do, because this operates on the server collection, bypassing the pubsub.

**Comment by Sanjo** [comment]
It's fine to use it like that. See also https://github.com/xolvio/chimp/issues/268#issuecomment-182130559.
