### ISSUE TITLE
Server object doubling as backdoor is confusing

### ISSUE THREAD

**Issue by thomasvanlankveld** [xolvio/chimp#268]
After subscribing to a publication, I would expect `Stuff.findOne` in the following to query a dataset based on what is received from the publication: (replace `stepDefs.js` in [this gist](https://gist.github.com/thomasvanlankveld/891f706284d96ee34239))

```javascript
module.exports = function() {

  this.Given(/^"([^"]*)"$/, function (name) {
    server.execute(function(thing) { Stuff.insert(thing) }, { name: name })
  });

  this.When(/^I look at stuff$/, function () {
    server.subscribe('stuff', [], function() {
      callback();
    });
  });

  this.Then(/^I see "([^"]*)"$/, function (name) {
    var thing = server.execute(function() { return Stuff.findOne(); } );
    expect(thing.name).toBe(name);
  });

};
```

However, in this case `server.execute` executes code on the actual server, which means the test will also pass if I don't subscribe.

**Comment by Sanjo** [comment]
The server.subscribe comes from https://github.com/xolvio/node-ddp-client. To access the subscribed objects, you need to use `server.collections.stuff` I think (see example in [README](https://github.com/xolvio/node-ddp-client.)). I have never used it, so I don't know if it works. Also don't forget to clean up the subscriptions after the scenario via after hook.
