### ISSUE TITLE
MiniMongo queries returned with client.execute have result on 'value' propery

### ISSUE THREAD

**Issue by thomasvanlankveld** [xolvio/chimp#269]
When querying MiniMongo collections using `client.execute`, I do not get the result directly but instead I need to fetch it using `.value`: (replace `stepDefs.js` in [this gist](https://gist.github.com/thomasvanlankveld/891f706284d96ee34239))

```javascript
module.exports = function() {

  this.Given(/^"([^"]*)"$/, function (name) {
    server.execute(function(thing) { Stuff.insert(thing) }, { name: name })
  });

  this.When(/^I look at stuff$/, function () {
    client.url('http://localhost:3000');
    client.execute(function() { Meteor.subscribe('stuff'); });
  });

  this.Then(/^I see "([^"]*)"$/, function (name) {
    var thing = client.execute(function() { return Stuff.findOne(); }).value;
    expect(thing.name).toBe(name);
  });

};
```

**Comment by ramijarrar** [comment]
The result of ```client.execute``` is always contained in the 'value' property (nothing to do with Minimongo queries). That function is not actually provided by Chimp but comes [prebuilt](http://webdriver.io/api/protocol/execute.html) with WebdriverIO which communicates with the Selenium server. The other properties that you see are part of Selenium's response message which is documented in-detail [here](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol). You can generally ignore this information, but it would not be appropriate for Chimp to strip it out.

If you really want to avoid constantly reading the 'value' property then you can add a helper in your Cucumber World/Mocha context which provides some syntactic sugar.

**Comment by thomasvanlankveld** [comment]
Thanks for clarifying!

I noticed this `.value` being necessary in more places. I don't mind typing it, but [Chimp's documentation](https://chimp.readme.io/docs/getting-started-with-meteor-cucumber#section-in-the-client-context) doesn't mention it. (which means the example code is actually wrong)

**Comment by Sanjo** [comment]
I have clarified the code example on the documentation page.
