### ISSUE TITLE
@critical matching definitions throw errors

### ISSUE THREAD

**Issue by area** [xolvio/chimp#272]
When running

    chimp --browser=chrome --path=./features/ -r=./features/step_definitions/domain/ --ddp=http://localhost:3000

My tests pass. However, if I try and add some critical rules...

```
chimp --browser=chrome --path=./features/ -r=./features/step_definitions/domain/ --criticalSteps=./features/step_definitions/critical/ --ddp=http://localhost:3000
  <snip>
The following steps have multiple matching definitions:

"they login" matches:
/^they login$/ # features/step_definitions/domain/login.js:21
/^they login$/ # features/step_definitions/critical/login.js:7

"they should be logged in" matches:
/^they should be logged in$/ # features/step_definitions/domain/login.js:44
/^they should be logged in$/ # features/step_definitions/critical/login.js:20
```

These multiple matching definitions are by design, of course.

**Comment by Sanjo** [comment]
Sam just introduced --domainSteps some hours ago (0.28.1) to pass the domain steps and fix this problem.

So it's now:

```
chimp --browser=chrome --path=./features/ --domainSteps=./features/step_definitions/domain/ --criticalSteps=./features/step_definitions/critical/ --ddp=http://localhost:3000
```

**Comment by area** [comment]
For the critical tests, it now doesn't see the step that is the same in domain tests and the critical tests. Do I have to separate them out now, rather than allow them to be overwritten? i.e. is it now:

The `-r` flag now contains a path to common step definitions
The `--domainSteps` flag now contains step definitions exclusive to domain tests
The `--criticalSteps` flag now contains step definitions exclusive to critical tests

**Comment by Sanjo** [comment]
Yes, exactly. You can also extract out common code into functions and put them into the support folder and just call those functions in your step definitions for domain and critical.

**Comment by area** [comment]
That feels like a bit of a shame - I now have to decide when I'm writing my steps whether the test in question is going to be critical or not, rather than just overwriting the relevant steps when I add the label. Or move the step definitions when I decide the test is critical, which admittedly will now be easier with the recommendation for missing steps to be in separate files.

That said, all that is just personal preference, and arguably that decision should be made at the outset anyway! Thanks for your patience with me getting this straightened out.

**Comment by samhatoum** [comment]
That was my preference also, but then Cucumber stopped supporting multiple step defs, so we were forced. 

Then I realized the value of doing it this way, which is that the domain steps can load the domain model files directly without a running server context (like Meteor), and they will be hyper fast. I'm updating the automated-testing-best-practices repo to do this
