### ISSUE TITLE
Meteor hot code reload does not seem to get detected

### ISSUE THREAD

**Issue by garrickajo** [xolvio/chimp#274]
I'm just getting started with Chimp, and maybe I'm not understanding what the hot code reload is supposed to do.

I started a Meteor app locally, as generated from one of their examples; localmarket. I create some tests using cucumber, and everything is working as expected.

To test the hot code reload, I then insert some records into mongo. I've verified that the app in the chimp window shows the new record. Shouldn't the tests be re-running at this point? I've tried

`chimp --ddp=http://localhost:3000 --watch`

`chimp --ddp=http://localhost:3000 --watch --watchSource=../localmarket`

Thanks

**Comment by Sanjo** [comment]
Hot code reload only reruns the tests when you change some code in one of the application files.
Your data setup should be part of your automated specs.

**Comment by garrickajo** [comment]
Thanks for the clarification.
