### ISSUE TITLE
Chimp should automatically watch any directories it is provided

### ISSUE THREAD

**Issue by samhatoum** [xolvio/chimp#275]
Currently, chimp only watches the feature directory. If `--domainSteps`, `--criticalSteps` or `--require` are used, they are not automatically watched. They should be

**Comment by adamdawkins** [comment]
Shouldn't this also watch the mocha directories if we've pointed them elsewhere?

E.g. I have a feature direction for cucumber, but have tests in client/**/tests for a Mantra app, not in features. Is it possible to watch those too?

**Comment by adamdawkins** [comment]
Don't worry about my comment above, doing the Mocha stuff differently. I think my current issue is the same as yours, the step definitions files don't trigger a re-test!

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy
https://github.com/TheBrainFamily/chimpy/issues
