### ISSUE TITLE
Disable the DDP connection & Browser initializaiton when running pure domain tests

### ISSUE THREAD

**Issue by samhatoum** [xolvio/chimp#277]
Running domain tests independently of Meteor will force users to keep application and infrastructure concerns out of the domain.

Domain modules can be loaded into Cucumber without the browser at all. If we need to run.

Perhaps we can have a `--pure` option for this

**Comment by DanielDornhardt** [comment]
Hi, I like the idea a lot, I'm trying testing my domain using chimp and cucumber at the moment and the startup- and initialization - time for chimp / each rerun seems a bit slow, I think skipping the Browser initialization could improve that?

At the same time, why disable the DDP connection? I think this is required to run tests of the domain code using server methods / xolvio:backdoor etc., or is it not?

How could I import / test my domain code without the DDP connection?

**Comment by samhatoum** [comment]
I think we should run them in parallel in watch mode. In most cases, the domain tests run before the browser even has a chance to go to a URL! 

The reason to disable the DDP for domain tests, is for keeping the domain honest. I've found that I can focus a lot more on the domain logic if I'm sure I don't have Meteor loaded at all. So just using import and require and using the Cucumber context to hold any state required for a test. This ensures all state that is required is setup in memory in the before/background steps. The benefit here is separation of concerns on steroids. It really forces you to separate infrastructure / framework from the domain model. If you have any dependencies, like repositories, you can use test doubles in the cucumber context also.

I'm very happy that you're doing this, please join our [xolv.io/community](http://xolv.io/community) as I'd be interested to hear how you get on with it.

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy
https://github.com/TheBrainFamily/chimpy/issues
