### ISSUE TITLE
cannot use meteor packages in a test

### ISSUE THREAD

**Issue by ahmedhagii** [xolvio/chimp#278]
Hi,

This is probably silly, but I spent hours and couldn't figure this out. I'm trying to use a meteor package 'faker' in my test but always fail to do so. here's what I get:

```
 1 failing

  1) Test @watch sample test:
     Uncaught ReferenceError: faker is not defined
      at Context.<anonymous> (tests/unit/jobSpec.js:6:17)
      at /usr/local/lib/node_modules/chimp/dist/lib/mocha/mocha-fiberized-ui.js:23:14
```

and my test is:

```
describe("Test", function () {
	it("@watch sample test", function () {
		var name = faker.name.findName();
	});
});
```

any help would be appreciated. Thanks.

**Comment by ahmedhagii** [comment]
also when I try to call 'Meteor' right away in a test, it gives me:

`Uncaught ReferenceError: Meteor is not defined`

is the something I should do first?

**Comment by ramijarrar** [comment]
You're not running that code in the Meteor context, you should wrap it in server.execute or browser.execute

**Comment by ahmedhagii** [comment]
@ramijarrar thanks for your answer
