### ISSUE TITLE
ES6 not working with Mocha

### ISSUE THREAD

**Issue by samhatoum** [xolvio/chimp#279]
First referenced here. We don't actually pass in the compiler to Mocha as we use the JS API to run Mocha. We might need to run in a babelified node env.

Referenced here: https://github.com/meteor/todos/issues/15

**Comment by tizmagik** [comment]
Has this issue been resolved? I'm still seeing errors trying to run tests written in ES6. Happy to submit a separate issue too, if needed.

test-spec.js
```js
describe('test suite', () => {
  it('runs' () => {
    expect(true);
  })
})
```

```
$ chimp --mocha --debug

/Users/dev/ws/sample/node_modules/chimp/dist/lib/mocha/mocha-wrapper.js:62
  throw e;
  ^


SyntaxError: /Users/dev/ws/sample/e2e/test-spec.js: Unexpected token (2:15)
  1 | describe('test suite', () => {
> 2 |   it('runs' () => {
    |                ^
  3 |     expect(true);
  4 |   })
  5 | })
...
```
