### ISSUE TITLE
Support loading config from package.json

### ISSUE THREAD

**Issue by samhatoum** [xolvio/chimp#280]
This is a good idea for frameworks like Meteor

Requested here: https://github.com/meteor/todos/issues/15

Another option to use a config file with Meteor is to put the config file under `.config/chimp.js` so that Meteor ignores the dot directory, then pass the file to Chimp as the first param, like this:

`chimp .config/chimp.json <other options>`

**Comment by Sanjo** [comment]
There are a lot other ways to prevent Meteor from loading the config file as app file:

* Put the config file in the imports/ folder (Meteor 1.3)
* Name the config file, so it starts with a dot (also works with a parent folder with dot)
* Put the Meteor app in a subdirectory of the repository. E.g. src/.

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy
https://github.com/TheBrainFamily/chimpy/issues
