### ISSUE TITLE
Unspecified tunnel identifier is set to 'false'

### ISSUE THREAD

**Issue by ramijarrar** [xolvio/chimp#283]
This issue is not present in earlier releases (0.25.1) so there appears to be some regression in the later releases.

**Comment by ramijarrar** [comment]
I had a look through the current defaults and there doesn't appear to be anything new in there which could be causing this. I would suspect that this issue has something to do with changes to the interpretation of options?

**Comment by samhatoum** [comment]
How does it happen?

**Comment by ramijarrar** [comment]
The error I am getting on Sauce Labs is ```No active tunnel found for identifier 'false'``` so it appears that chimp is passing in a string 'false' for tunnel identifier (or it is being interpreted that way) in all cases a value of null is the correct default.

**Comment by Sanjo** [comment]
I think this will be fixes with the changes that I have done in: https://github.com/xolvio/chimp/pull/284, where I change the default value of tunnelIdentifier to null.

**Comment by ramijarrar** [comment]
@Sanjo I see you have merged the PR, can you bump the version so I can test it? (I noticed pulling from github no longer works)

**Comment by Sanjo** [comment]
Should be fixed with 0.30.0. Can you test it and close this issue when it's working.
Also installing Chimp from GitHub should work again starting with https://github.com/xolvio/chimp/commit/14ea380272db5129d366fff540a6e59fb2d5ca87.

**Comment by ramijarrar** [comment]
It doesn't look like this has fixed it 0.30.0 has fixed it, getting this now ```No active tunnel found for identifier 'null'```

**Comment by Sanjo** [comment]
Ok, seems to be that 'null' is a string instead of just `null`.

**Comment by ramijarrar** [comment]
I'm not sure what has changed in the way the options are interpreted but this wasn't an issue. The simplest solution for now would be to add conditionals before the statements are pulled from ```process.env```.

**Comment by Sanjo** [comment]
@ramijarrar I have a WiP branch to fix the general typing problem. Can you try it. https://github.com/xolvio/chimp/tree/options-types-problem-fix

**Comment by ramijarrar** [comment]
Same issue unfortunately. 

Here are the webdriver options from my debug output:

```[chimp][helper] webdriverOptions are  {"waitforTimeout":10000,"timeoutsImplicitWait":3000,"desiredCapabilities":{"browserName":"safari","platform":"OS X 10.11","name":"XXX","chromeOptions"{},"applicationCacheEnabled":false,"tunnelIdentifier":"null","browserstack.local":"false"},"user":"XXX","key":"XXX","host":"ondemand.saucelabs.com","port":"80","logLevel":"silent","sync":true}```

**Comment by ramijarrar** [comment]
This issue is no longer relevant in the latest version of Chimp.
