### ISSUE TITLE
Error: Can't wait without a fiber

### ISSUE THREAD

**Issue by thomasvanlankveld** [xolvio/chimp#289]
When I initiate an asynchronous operation in the callback of `server.subscribe` (#266), like calling a Meteor method with `server.call`, the console prints:

```
    Als ik vervoer aanvraag voor "Frits" naar "Koetshuis" # tests/features/verzorger/vervoerAanvragen.feature:12
      Error: Can't wait without a fiber
```

**Comment by Sanjo** [comment]
You can use `global.wrapAsync(function (callback) { ... })` (the `global.` is optional)
