### ISSUE TITLE
How or where can I find mocks/stubs/spies to use them?

### ISSUE THREAD

**Issue by Menda** [xolvio/chimp#293]
Hi, I would like to do unit tests for the server side and test some Meteor.method that I created. At the moment, I can do everything regarding unit testing with Moka, but I would like to be able to mock (stub) and/or spy methods (`spyOn()`) in order to proper test. I think it can be done with Jasmine, but there's no support here at all, and velocity is supposed to be discontinued, plus I don't want to use other testing framework.

Which is the easiest way to get this functionality at this date?

My example:

    describe('playersExist', function () {
      it('should return false when no players exist', function () {
        var cursor = {
          count: function () {
          return 0;
        }
      };
      spyOn(Players, 'find').and.returnValue(cursor);
        expect(PlayersService.playersExist()).toBe(false);
      });
    });

Thanks a lot.

**Comment by samhatoum** [comment]
Hey 

Chimp is not a unit testing framework. Meteor 1.3 will support unit testing modes with spies etc, and sanjo:jasmine will be update when Meteor 1.3 is released
