### ISSUE TITLE
Allow the user to specify a BeforeFeatures and AfterFeatures hook

### ISSUE THREAD

**Issue by Sanjo** [xolvio/chimp#30]
Currently Cucumber can only have one BeforeFeatures and one AfterFeatures hook. Because Chimp uses them, the user cannot specify one.

Also the Chimp BeforeFeatures hook should be executed before the user registered hooks.
The Chimp AfterFeatures hook should be executed after the user registered hooks.

**Comment by samhatoum** [comment]
This is kind-of supported here:

https://github.com/xolvio/chimp/blob/develop/lib/cucumberjs/hooks.js#L135

**Comment by samhatoum** [comment]
You can do this now
