### ISSUE TITLE
using chimp selenium-standalone will always use the x64 driver for IE

### ISSUE THREAD

**Issue by haleagar** [xolvio/chimp#308]
* What component is this issue related to (eg The JSON report):

selenium-standalone

* Expected behaviour 

ability to pass drivers.ie.arch=ia32 to selenium-standalone to indicate which drivers to download and use.

* Actual behaviour:

There is no way to configure selenium-standalone
Even in you run selenium-standalone and have it download the correct drivers first, when you run chimp it will download and use the x64.
This is an issue because IE10 and 11 64 bit have a problem with the send key, where it takes 3-6 seconds per key and automation is not possible.   (64 bit versions of ie 9 and previous work with x64 driver, but ie 10 and 11 only with 32 bit.)  

Optimal would be to include an option in the config so that user can specify version, but it appears defaulting to 32bit will work in all circumstances.  (unclear why selenium-standalone defaults to x64)

* Steps to reproduce the problem (preferably a reproducable repository):

configure chimp to use internet explorer on windows 64 bit 7,8, or 10 and use setValue()
 
* Version of Chimp, Node and Operating System:

Chimp 0.9.4
Node 5.4.0
Windows 7

**Comment by Sanjo** [comment]
Thanks for making us aware of this issue. The ia32 driver is now used. Let me know if this still doesn't fix your issue. A release of this will follow shortly.
