### ISSUE TITLE
Enhancement to support WebdriverIO 4.x?

### ISSUE THREAD

**Issue by kwright1** [xolvio/chimp#309]
Is there a plan in the pipeline to support WebdriverIO 4.x?  It seems like a substantial overhaul on their part and the API docs and examples on their site are all referencing more than a few methods and functions that only work in 4.0

**Comment by Sanjo** [comment]
Yes. I mainly waited for the [changelog](https://github.com/webdriverio/webdriverio/blob/master/CHANGELOG.md). It's now there, so I can tackle this soon.

**Comment by Sanjo** [comment]
Shipped with 0.32.0
