### ISSUE TITLE
JSON report only contains "null" when using 0.31.1

### ISSUE THREAD

**Issue by ricoli** [xolvio/chimp#318]
* What component is this issue related to (eg The JSON report):
The JSON report
* Expected behaviour 
For json to be inside after execution
* Actual behaviour:
the JSON report only contains "null"
* Steps to reproduce the problem (preferably a reproducable repository):
I'm running this with the same config as in 0.30.0 (which worked fine - json is written on the output file), but it fails in 0.31.1 ("null" is written to the output file):
```
const url = process.env.BASE_URL || 'localhost'
const port = process.env.BASE_URL_PORT || '8080'

const options = {
  // - - - - CUCUMBER - - - -
  path: 'test/e2e/features/',
  format: 'pretty',
  tags: ['~@Draft', '~@manual'],
  jsonOutput: '/project/reports/bdd/bdd-report.json',

  // - - - - SELENIUM  - - - -
  browser: 'chrome',

  // - - - - WEBDRIVER-IO  - - - -
  webdriverio: {
    baseUrl: url + ':' + port
  }
}

module.exports = options
```
* Version of Chimp, Node and Operating System:
chimp 0.31.1, node 5.3, ubuntu 14.04
* Console / Log Output:
```
[chimp][hooks] Finished AfterFeatures

[chimp][cucumber] Closed with code 2
[chimp][cucumber] Cucumber not in a stopping state
[chimp][cucumber] Ensuring directory exists /project/reports/bdd
[chimp][cucumber] Writing json results to /project/reports/bdd/bdd-report.json
[chimp][cucumber] Finished writing results
```

**Comment by Sanjo** [comment]
I could reproduce it with 0.31.1, but it worked already with master. So can you try 0.32.0 please and let me know if it also now works for you again.

**Comment by workflow** [comment]
Working here on 0.33.1
