### ISSUE TITLE
Can't run only @watch or @focus scenarios

### ISSUE THREAD

**Issue by adrienjoly** [xolvio/chimp#319]
* What component is this issue related to (eg The JSON report): 
Chimp's default task runner with color stdout output

* Expected behaviour :
Run only @focus scenarios, when some were selected from my feature files.

* Actual behaviour: 
All scenarios are tested, even in --watch mode.

* Steps to reproduce the problem (preferably a reproducable repository): 
Sorry, it's on a private repo

* Version of Chimp, Node and Operating System: 
0.26 on Mac El Capitan

**Comment by samhatoum** [comment]
Hey, are you using Mocha? Cucumber? Can you share the feature file / test file you're using to help us debug?

**Comment by adrienjoly** [comment]
Sorry for the lack of details...

I'm using Cucumber, connected to a Meteor instance (thru ddp).

I cannot share the feature file (private), but it looks like this:

```
Feature: Blablabla

  Scenario: Bla
    Given Blou
    Then Bah

  @watch
  Scenario: Bouh
    Given Beh
    Then Blabla

Feature: Blablou

  Scenario: Beh
    Given Blah
    When Bim
    Then Paf
```

=> When I run `chimp --path=tests --ddp=http://localhost:3100 --watch`, I expect just the second scenario to run, like it used to be (with chimp v0.24). In reality, all scenarios are run. Same if I replace `watch` by `focus`, in my feature file or in my chimp command.

**Comment by Sanjo** [comment]
Hi, multiple features in one file is not supported. After you have extracted the features into separate files, the watch tags should work correctly. I'm not sure why Cucumber doesn't throw a parsing error.

**Comment by adrienjoly** [comment]
Oh, I didn't know that!

I will definitely try that today! Thank you for your reply, Jonas!

On Mon, Apr 4, 2016 at 9:55 PM Jonas Aschenbrenner <notifications@github.com>
wrote:

> Hi, multiple features in one file is not supported. After you have
> extracted the features into separate files, the watch tags should work
> correctly. I'm not sure why Cucumber doesn't throw a parsing error.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/xolvio/chimp/issues/319#issuecomment-205468520>
>
-- 
Adrien Joly
adrienjoly.com
