### ISSUE TITLE
Increase TimeOut....

### ISSUE THREAD

**Issue by mario-ortiz** [xolvio/chimp#320]
Hello Guys, maybe there is a way to solve this just haven't found anything in the documentation.

Currently I'm running a step that takes a little bit over 60 seconds, and even when the framework keeps adding information to the inputs, it crashes after 60 seconds saying that the step exceeded the timeout. Is there any way to increase it for steps that take over 60 seconds?

this is the exact error
"Error: Step timed out after 60000 milliseconds"

**Comment by ramijarrar** [comment]
Are you using Mocha?

**Comment by mario-ortiz** [comment]
Thank you ramijarrar, but I'm not using Mocha, seems to be a CucumberJS thing, just not sure if its possible to set a different timeout thru chimp configuration

**Comment by mario-ortiz** [comment]
Easier than I thought, just need to send the timeout on the step definition, something like this:

this.Given('The step text', {timeout: 65 * 1000}, function(){
}
