### ISSUE TITLE
Help with connecting to saucelab with Chimp

### ISSUE THREAD

**Issue by opuzaman** [xolvio/chimp#321]
Hi, i am trying to connect my tests in Chimp framework to Saucelab, And i am new with chimp framework. Can anyone please help me set up the connection, may be a step by step instruction?
Thanks

**Comment by ramijarrar** [comment]
Something like this will work:

```sh
chimp --ddp="http://localhost:3000" --host="ondemand.saucelabs.com" 
      --port="80" --key="$SELENIUM_GRID_KEY" --user="$SELENIUM_GRID_USER" 
      --name="foo" --browser="chrome" --version="latest" --platform="Windows 7"
```

**Comment by ramijarrar** [comment]
You can setup the connection with these options in your config file (or from the command line):

```js
user: "SAUCE_USER",
key: "SAUCE_KEY",
port: 80,
host: "ondemand.saucelabs.com"
name: "foo"
```

**Comment by samhatoum** [comment]
Thank you @ramijarrar , added your comments here:
https://chimp.readme.io/v1.0/docs/using-saucelabs-browserstack-seleniumgrid

**Comment by ramijarrar** [comment]
@samhatoum Beat me to it, suggested some changes to make the examples a little clearer.
