### ISSUE TITLE
Security issue with hapi

### ISSUE THREAD

**Issue by LeZuse** [xolvio/chimp#322]
* What component is this issue related to (eg The JSON report):
`hapi` dependency
* Expected behaviour 
Use patched version of hapi >=11.0.0
* Actual behaviour:
Using vulnerable version
* Version of Chimp, Node and Operating System:
chimp 0.31.1, hapi 8.8.0

See https://nodesecurity.io/advisories/45

**Comment by samhatoum** [comment]
Hey, thanks for sharing this.

HAPI is only used internally by Chimp and is not intended for any public hosting. I think we can safely close this. Let me know if you see any specific security concerns.
