### ISSUE TITLE
browser.newWindow() throws an error on desktop

### ISSUE THREAD

**Issue by Marinale** [xolvio/chimp#324]
* What component is this issue related to (eg The JSON report):
WebdriverIO

* Expected behaviour 
Open a new window

* Actual behaviour:
Throws an error

* Steps to reproduce the problem (preferably a reproducable repository):
After updating to a new version 0.31.1, the following test case throws an error:
```
it('test case', () => {
	browser.url('http://google.com');
	browser.newWindow('http://github.com');
});
```
Tried to run the same code on version 0.30.1 and it works well.

* Version of Chimp, Node and Operating System:
Chimp 0.31.1
Node v5.7.0,
OS X El Capitan, Version 10.11.4,
Chrome version: 49.0.2623.110 (64-bit)

* Console / Log Output:
```
Uncaught CommandError: newWindow command is not supported on mobile platforms
	at Object.Future.wait (node_modules/fibers/future.js:449:15)
	at Object.<anonymous> (node_modules/xolvio-fiber-utils/index.js:48:19)
	at Context.<anonymous> (test-case.js:21:13)
	at node_modules/chimp/dist/lib/mocha/mocha-fiberized-ui.js:23:14
```

**Comment by samhatoum** [comment]
Looks like this is a webdriver.io issue. See here:
https://github.com/webdriverio/webdriverio/blob/3fbbc3fc276d970d37adbf184ade7d8579c6c11d/lib/commands/newWindow.js#L63
