### ISSUE TITLE
issue with waitForExist function 

### ISSUE THREAD

**Issue by ofthewood** [xolvio/chimp#328]
I don't understand why the waitForExist in this code does not work. 
```
    this.Then(/^I see the  client creation form$/, function (label) {
        this.client.pause(500);
        this.client.setValue("#user_lastName", 'test validation');
        this.client.waitForExist("#user_lastName",2000);
    });

```
Result with chimp 0.9.4 / windows 7 : 
    _Then I see the  client creation form                # features\support\create a client.js:31
      Error: Step timed out after 60000 milliseconds_

The setValue is well done but  waitForExist ends timed out after 60000  non 2000 milliseconds ???
Result is the same without the setvalue line. 

is it an issue ?

**Comment by samhatoum** [comment]
Hi. Are you on chimp 0.9.4? We are on version 0.33.0 and don't support the old one. Please upgrade and we can try to help

**Comment by ofthewood** [comment]
sorry , it was 0.33.0 . 
I found the pb : timeout  was caused  by unappropriate function parameter
