### ISSUE TITLE
Clarify which assertion library is default for each framework

### ISSUE THREAD

**Issue by themeteorchef** [xolvio/chimp#329]
This may be an oversight on my part, but I'm noticing that inside of a Mocha-based test, I can write my assertion using Chai syntax like this (without passing the `--chai` flag when running):

```
expect( getBook.title ).to.equal( 'Seeking Wisdom' );
```

However, in a Cucumber-based test, I can only use Mocha's assertion syntax like this by default:

```
expect( getBook.title ).toEqual( bookTitle );
```

In the Cucumber test, if I use the Chai version (i.e., do not pass the `--chai` flag when running tests) of this my test fails (I get a `TypeError: Cannot read property 'equal' of undefined` when using `.to.equal`). Using the Mocha syntax works as expected.

Is it assumed that Chai is available by default in Mocha-based tests?

**Comment by Sanjo** [comment]
Yeah, right now Chai is the default for Mocha and for Jasmine and Cucumber the default is the Jasmine expect (http://jasmine.github.io/2.4/introduction.html).

**Comment by themeteorchef** [comment]
Cool, thanks :)
