### ISSUE TITLE
Deprecate and remove chimp-widgets

### ISSUE THREAD

**Issue by Sanjo** [xolvio/chimp#333]
WebDriver.io 4 has built in [page objects support](https://github.com/webdriverio/webdriverio/tree/master/examples/pageobject) very similar to what chimp-widgets suggested. So we can deprecate and remove chimp-widgets.

**Comment by tikolakin** [comment]
It seems logical, thoughts?

**Comment by samhatoum** [comment]
I think so also. The new page objects are awesome in practice.

**Comment by janmyler** [comment]
Hi, coming from [Chimp Widgets docs](https://chimp.readme.io/docs/chimp-widgets), does this mean I can use the WebDriver.io 4 PO support with the synchronous style?

**Comment by samhatoum** [comment]
Yes you can @janmyler - we should probably kill the Chimp Widgets as per the issue title. 

Anyone have any objections?

**Comment by joscha** [comment]
More infos about POs via ES6: http://webdriver.io/guide/testrunner/pageobjects.html
