### ISSUE TITLE
Is it possible to run 2 local chimp-instances - 1 in ``--watch`` and 1 as a local CI-loop?

### ISSUE THREAD

**Issue by thebarty** [xolvio/chimp#334]
Hi guys,

I am using chimp with meteor and have a working setup. I can run chimp using either ``chimp --ddp=http://localhost:3000 --watch --mocha --path=tests`` or ``chimp --ddp=http://localhost:3000 --mocha --path=tests --browser=phantomjs``.

During development I'd love to have 2 chimp-instances running for a nice local development-experience:
1) **fast-development-instance** using "@watch & chrome-browser": This should be my develpment chimp giving me instant feedback on the current tests (marked with @watch) that I am working on.
2) **slow-full-test-instance** using ``--browser=phantomjs`` and continously checking ALL tests after a code-change in phantomjs. Of course this will be MUCH slower, but I will always get feedback if other tests (=NOT marked with @watch) are failing/passing.

**Any ideas how to get 2) running? Is this possible?**
_I guess I need have a ``--watch mode`` for this that runs **ALL tests** (and NOT only the ones tagged with @watch)_

Thanks for your tips
Barty

**Comment by Sanjo** [comment]
Try to pass --watchTags="" to run all tests in watch mode. I haven't tested it myself.
Also you have to consider if you can run two test suits at the same time against your app (fixture resetting, data collisions).

**Comment by thebarty** [comment]
@Sanjo: Yeah man!!! This works really fine and running all those meteor and chimp instances really make make macbook scream.... "meine Lüftung hört garnicht mehr auf zu pusten"!! Thanks for your help!

**Comment by thebarty** [comment]
Hi guys,

after upgrading to the latest chimp ( I hadn't upgraded for ages ), I am experiencing a when trying to run multiple meteor instances of my app.

Do you guys have any idea how to solve this? It is NOT chimp giving this error, but the connected meteor instances are...  essentially before I ran up to 4 instances of meteor in parallel (all connected with individual chimp-instances) and now - due to this error - I can only run 1 instance.. which totally sucks as my tests run ages.

Any ideas?

This is the error
```
{ [Error: ENFILE: file table overflow, scandir '/private/var/folders/j3/hmkt_82519vbmq40ccj1c97c0000gn/T/meteor-test-runaqmgxz']
  errno: -23,
  code: 'ENFILE',
  syscall: 'scandir',
  path: '/private/var/folders/j3/hmkt_82519vbmq40ccj1c97c0000gn/T/meteor-test-runaqmgxz' }
node.js:420                                   
        callback();
        ^

Error: ENFILE: file table overflow, open 
....
```

**Comment by dheerajbhaskar** [comment]
hey @thebarty , were you able to run the two instances of chimp, at least in the earlier version of chimp?

I'll do some testing at my end and report back if I get it working :)

**Comment by dheerajbhaskar** [comment]
I'm able to run two instances of chimp manually in separate commandline (cmd.exe) windows

Now I can see the usefulness of a setup like yours, how are you running a "CI-loop" @thebarty ? :)

**Comment by dheerajbhaskar** [comment]
Here's a .travis.yml I'm considering using for reference. I'm thinking of running a gitlab ci runner on my local

https://github.com/xolvio/qualityfaster/blob/master/.travis.yml

**Comment by dheerajbhaskar** [comment]
What @Sanjo said said just started making sense to me. I will try that

**Comment by dheerajbhaskar** [comment]
What Sanjo suggested works, I can confirm. Thanks :)
