### ISSUE TITLE
Best practise: Throw own errors for detailed error message?

### ISSUE THREAD

**Issue by thebarty** [xolvio/chimp#336]
Is it ok to throw my own Errors (instead of using chai ``expected``) in order to give a really informative error message to the test-user, meaning that he MIGHT NOT even have to dig in the code to understand what went wrong?

Example code:
``
// chimp.acceptance.test.js

// lets say we need to do a really complex check to find out if something is valid or invalid
let valid = false
for (element of browser.elements()) {
  if (thingsWentWell) {
    valid = true
  }
}

// now we want to build a great error-message in order to save time when later examining the error
if (!valid) {
  const errorMessage = 'constructed error message with a lot of detailed info to quickly understand what went wrong (without digging code)'
  throw new Error(errorMessage)
  // An alternativ might be this
  expect(valid, errorMessage).to.equal(true)
  //  https://github.com/chaijs/chai/issues/81
  //  ... but for me this still feels like hacking chai.
}
```

**Comment by Sanjo** [comment]
I think when a test fails, you always need to look at the test code. So I would suggest to make the test as easy to understand as possible, using page objects, functions, comments.

Technically throwing an error works, chai does basically also just throw an error.
