### ISSUE TITLE
What's the best way to access module definitions in Meteor 1.3 server code?

### ISSUE THREAD

**Issue by shilman** [xolvio/chimp#337]
#####  Expected/Actual behaviour

Running all of the following from the root of my meteor project with the command:
```
chimp --ddp=http://localhost:3000 --mocha --path=tests/chimp
```

First attempt (preferred method?) gives me error `Cannot find module 'meteor/mongo'`:
```
import {Funds} from '../../server/collections'

describe( 'Server exec without globals', () => {
  it('should execute', () => {
    const vfinx = server.execute(() => Funds.findOne({symbol: 'VFINX'})
    console.log('vfinx', vfinx)
  })
})
```

Second attempt gives me error `Error in server.executeReferenceError: require is not defined`:
```
describe( 'Server exec without globals', () => {
  it('should execute', () => {
    const vfinx = server.execute(() => {
      const {Funds} = require('../../server/collections')
      return Funds.findOne({symbol: 'VFINX'})
    })
    console.log('vfinx', vfinx)
  })
})
```

Third attempt for the hell of it gives me `ReferenceError: Funds is not defined` as expected:
```
describe( 'Server exec without globals', () => {
  it('should execute', () => {
    const vfinx = server.execute(() => Funds.findOne({symbol: 'VFINX'})
    console.log('vfinx', vfinx)
  })
})
```

Final attempt working but still depends on global variables, and also requires adding `meteor add dburles:mongo-collection-instances`:

```
describe( 'Server exec without globals', () => {
  it('should execute', () => {
    const vfinx = server.execute(() => Mongo.Collection.get('funds').findOne({symbol: 'VFINX'}))
    console.log('vfinx', vfinx)
  })
})
```

##### Steps to reproduce the problem

See above! Can provide a repo if necessary.

(Preferably a repository and easy reproduction steps)

#####  Used version

* Chimp: 0.33.1
* Node.js: v0.12.2
* Operation system: OS X 10.11.4

#####  Console / Log Output

(Upload long logs to [Gist](https://gist.github.com/) and link it here)

See above!

**Comment by Sanjo** [comment]
Update xolvio:backdoor to 0.2.0 with `meteor update xolvio:backdoor` (was just released).

Then require should work with absolute paths in server.execute, (/ is the app root) like:

```
describe( 'Server exec without globals', () => {
  it('should execute', () => {
    const vfinx = server.execute(() => {
      const {Funds} = require('/server/collections')
      return Funds.findOne({symbol: 'VFINX'})
    })
    console.log('vfinx', vfinx)
  })
})
```

**Comment by shilman** [comment]
Thanks @Sanjo. This works beautifully now!

**Comment by Pushplaybang** [comment]
Is this in the documentation?  just ran into this.. @shilman @Sanjo

**Comment by Pushplaybang** [comment]
For anyone else bumping into this, for named exports do this in chimp:

```js
const orders = require('/imports/orders/').orders;
```
