### ISSUE TITLE
meteor npm run chimp-watch fails on first run (ReferenceError: Symbol is not defined)

### ISSUE THREAD

**Issue by Oizor** [xolvio/chimp#338]
When running `meteor npm run chimp-watch` the console spits out [this error](https://gist.github.com/anonymous/4a8e2dbfee3ea997d12378f1996d9253). Simultaneously with the error a chrome window pops up pointing to 'data:,'. (not sure there is a connection though). The process does not terminate, and after changing and saving the test file it reruns correctly without errors.

##### Steps to reproduce the problem
I followed the [Meteor Guide article](http://guide.meteor.com/testing.html#acceptance-testing):
package.json:
```
{
  "scripts": {
    "chimp-watch": "chimp --ddp=http://localhost:3000 --watch --mocha --path=tests",
    "chimp-test": "chimp --mocha --path=tests"
  }
}
```
`meteor npm run chimp-watch`

My test looks as follows:
```
describe('A test', function () {
  it('runs @watch', function () {

    assert.equal(true, true);
  });
});
```

#####  Used version

* Chimp: 2.14.22
* Meteor 1.3.1
* Node.js: v0.12.13 (but when installing with `meteor npm install --global chimp` I get a lot of [deprecated warnings](https://gist.github.com/Oizor/602fb073a6226434c3ef2aa79c0068ee) suggesting it's using node v0.10.43 (I assume because meteor runs on this version of node (?))`
* Operation system: OS X El Capitan (v10.11.1

**Comment by Oizor** [comment]
When running in Codeship the same error pops up when running `meteor npm run chimp-test`

**Comment by Sanjo** [comment]
It seems that the recently added dependency to wdio sync has made the package incompatible with node < 4. Please use node.js 4 or 5 for Chimp for now.

**Comment by Oizor** [comment]
Thx. It worked using V5 and not using the meteor command (I guess meteor forces the V0.10 version):
`npm install --global chimp`
and then 
`npm run chimp-watch` (with the same package.json as in the first post)
