### ISSUE TITLE
Share support files between Mocha and Cucumber

### ISSUE THREAD

**Issue by wizonesolutions** [xolvio/chimp#339]
So basically I wanted to symlink our domain support files to the Mocha folder so that I could reuse some task helpers, fixture helpers, etc. Fixtures we can work around by properly making a `debugOnly` fixtures package in Meteor, but things like tasks (reusable functions to control the browser and such) aren't as easy since they are client-side.

#####  Expected behaviour

Symlinks are loaded in normal order.

#####  Actual behaviour

Files under symlinked directories don't get loaded.

##### Steps to reproduce the problem

1. Make a Meteor app.
1. Create a `tests/steps/domain/support` folder.
1. Create a file in it that logs something to the console.
1. Create a `tests/mocha/lib` folder.
1. Symlink: `tests/steps/domain/support` as `tests/mocha/lib/support`.

#####  Used version

* Chimp: 0.30.1
* Node.js: 4.4.0
* Operating system: Mac OS X 10.11.4

**Comment by Sanjo** [comment]
Hi, you can use `import ... from '../any/path'` to load any JavaScript files from any location. So you can put your reused helpers under tests/helpers for example and just import them, where you need them.

I would also recommend to upgrade to the latest Chimp, which is 0.33.1.

> Files under symlinked directories don't get loaded.

I will look into that eventually.

**Comment by Sanjo** [comment]
I had a quick look and we just use glob. So

> Files under symlinked directories don't get loaded.

won't fix. But the cleaner solution is the one that I have outlined in https://github.com/xolvio/chimp/issues/339#issuecomment-212004898 anyway.

**Comment by wizonesolutions** [comment]
Worked great! Thanks.
