### ISSUE TITLE
Insert content with cucumber step definition

### ISSUE THREAD

**Issue by sagannotcarl** [xolvio/chimp#342]
#####  Expected behaviour
I have been trying to create a step definition to insert some content into one of my collections. Thanks in advance for any guidance or suggestions.

I first tried to use the examples in https://github.com/xolvio/automated-testing-best-practices but I couldn't follow along with all the different nested files. I think I'm looking for something generally simpler than that repo is describing.

I thought I was close following this comment from a few days ago: https://github.com/xolvio/chimp/issues/337#issuecomment-210882801

Adapting it to an insert I tried:
````
    And a task with the following fields:
      | text | Add test profiles |
````
and
````
  this.Given(/^a task with the following fields:$/, function (table) {
    const data = table.rowsHash();
    const tasks = server.execute((data) => {
      const {Tasks} = require('/imports/api/tasks');
      return Tasks.insert(data);
    });
  });
````
I was expecting this to insert the ````data```` object into the ````Tasks```` collection.

I also tried different variations on ````server.call('tasks.insert');```` but without success.

#####  Actual behaviour

I got the error: 
````
Error: Error in server.executeError: insert requires an argument
````
(see the rest of the console below.)

##### Steps to reproduce the problem

I am using the todo app as a model so adding these steps to that repo should reproduce the error.

#####  Used version

* Chimp: 0.33.1
* Node.js: v0.12.6
* Operation system: OSX 10.11.4
* xolvio:backdoor: 0.2.0

#####  Console / Log Output
````
And a task with the following fields:                                                                      # tests/features/support/step_definitions.js:38
      | text | Add test profiles |
      Error: Error in server.executeError: insert requires an argument
      Error: insert requires an argument
        @ [object Object].insert (packages/mongo/collection.js:449:11)
        @ evalmachine.<anonymous>:6:20
        @ [object Object].xolvioBackdoor (packages/xolvio:backdoor/server.js:15:29)
        @ maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
        @ packages/ddp-server/livedata_server.js:711:19
        @ [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
        @ packages/ddp-server/livedata_server.js:709:40
        @ [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
        @ packages/ddp-server/livedata_server.js:707:46
        @ tryCallTwo (/Users/colinsagan/.meteor/packages/promise/.0.6.7.19c08o1++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
````

**Comment by Sanjo** [comment]
To pass data (arguments) into the function that is executed on the server, you need to do it like this:

```js
this.Given(/^a task with the following fields:$/, function (table) {
    const data = table.rowsHash();
    const tasks = server.execute((data) => {
      const {Tasks} = require('/imports/api/tasks');
      return Tasks.insert(data);
    }, data);
  });
```

**Comment by sagannotcarl** [comment]
Perfect, thanks!
