### ISSUE TITLE
How can I provide my own chromedriver binary OR where is the chromedriver installed on Linux?

### ISSUE THREAD

**Issue by remygendron** [xolvio/chimp#343]
Hello there. Really nice experience with Chimp/Cucumber. Everything runs smoothly on OS X.

However, I will be running my CI on Snap-CI. That's our preferred platform and we already use it for other projects in Java. That's why I'm not on Circle or Travis.

Snap however requires that you use a patched version of chromedriver that they provide. Hence my question. Can I override the chromedriver used by Chimp? I see the following in my logs when Chimp is starting:

[chimp][selenium.stderr] Setting system property webdriver.chrome.driver to /var/snap-ci/repo/node_modules/chimp/node_modules/selenium-standalone/.selenium/chromedriver/2.20-x64-chromedriver

Any recommended way to override this in my Chimp config. There's no config parameter related to the driver.

Thank you very much!

**Comment by samhatoum** [comment]
couple of options.

you can start `chromedriver` outside of chimp, the provide chimp with `host` and `port`.

or you can also tell Chimp to tell Webdriver.io to use a custom binary by putting this in the config:

```
desiredCapabilities: {
  browserName: 'chrome' 
  chromeOptions: {binary: '/path/to/custom/binary'}
}
```

**Comment by remygendron** [comment]
Thank you a bunch. Will try it right now. Amazing support! :-)

R.

On Thu, May 5, 2016 at 10:15 AM Sam Hatoum <notifications@github.com> wrote:

> couple of options.
>
> you can start chromedriver outside of chimp, the provide chimp with host
> and port.
>
> or you can also tell Chimp to tell Webdriver.io to use a custom binary by
> putting this in the config:
>
> desiredCapabilities: {
>   browserName: 'chrome'
>   chromeOptions: {binary: '/path/to/custom/binary'}
> }
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/xolvio/chimp/issues/343#issuecomment-217164612>
>
-- 
Rémy Gendron
Ingeno / Be the Revolution

418 809-8585
remy.gendron@ingeno.ca
remy.gendron (Skype)
http://ingeno.ca

**Comment by abecks** [comment]
Isn't the `binary` option for specifying the path to a custom Chrome binary? Not the ChromeDriver? How would we specify a different ChromeDriver binary for use with chimp?

**Comment by rsshilli** [comment]
I've had to update mine on windows a few times.  It'll be a pretty similar process on Linux.  Here's what I do:

    which chimp

This will tell you where chimp is installed.  For me, on windows, it was: 

   %appdata%\nvm\v6.10.3\chimp.cmd

So in the node_modules directory, find chimp:

   cd node_modules\chimp

Uninstall the older chromedriver and install a new one:

    npm uninstall chromedriver --save
    npm install chromedriver --save

There, now run chimp and everything should be fine.

**Comment by Windso** [comment]
What does the config look like for using Chromedriver started outside of Chimp? When I start Chromedriver I am given the port, but not the host.

**Comment by samhatoum** [comment]
just provide the host and port to your started chromedriver and chimp will use that

**Comment by Windso** [comment]
When I specify the host, port, and browser to connect to Chromedriver started outside of Chimp, this happens
```
[chimp][session-manager] could not connect to the server, retrying (1/30)
[chimp][session-manager] checking connection to selenium server
[chimp][session-manager] could not connect to the server, retrying (2/30)
[chimp][session-manager] checking connection to selenium server
....
[chimp][session-manager] could not connect to the server, retrying (29/30)
[chimp][session-manager] checking connection to selenium server
[chimp][session-manager] watch mode is false, not reusing a session
[chimp][hooks] init browser
[chimp][hooks] init browser callback
[chimp][session-manager] could not connect to the server, retrying (30/30)
[chimp][helper] setupBrowserAndDDP had error
{ Error: connect ECONNREFUSED 192.168.158.63:9515
    at initBrowser (node_modules/chimp/dist/lib/chimp-helper.js:189:43)
    at Object.setupBrowserAndDDP (node_modules/chimp/dist/lib/chimp-helper.js:264:7)
    at node_modules/chimp/dist/lib/cucumberjs/hooks.js:22:24
    at node_modules/meteor-promise/fiber_pool.js:43:40
  message: 'connect ECONNREFUSED 192.168.158.63:9515',
  type: 'RuntimeError',
  seleniumStack: 
   { status: -1,
     type: 'ECONNREFUSED',
     message: 'Couldn\'t connect to selenium server',
     orgStatusMessage: 'connect ECONNREFUSED 192.168.158.63:9515' } }
 ```
If I start Chromedriver outside of Chimp, is it required that I also start Selenium outside of Chimp?
