### ISSUE TITLE
Chrome window running the tests gets focused repeatedly

### ISSUE THREAD

**Issue by wormyy** [xolvio/chimp#344]
#####  Expected behaviour
Chrome window should be running the tests in background.

#####  Actual behaviour
While developing (with `npm start`), the chrome window running the tests gets focused repeatedly and is brought to the foreground again immediately after being unfocused. This makes it almost impossible to do anything on the computer while the tests are running.

##### Steps to reproduce the problem

`npm start`

#####  Used version

* Chimp: 0.33.1
* Node.js: v5.9.1
* Operation system: OS X El Capitan 10.11.4

**Comment by zvictor** [comment]
Just a clarification: `npm start` in this case comes from `xolvio/automated-testing-best-practices`
