### ISSUE TITLE
Chrome driver not being killed on Windows on exit

### ISSUE THREAD

**Issue by samhatoum** [xolvio/chimp#345]
##### Expected behaviour

When CTRL-C is pressed on a running Chimp process, any open Chrome processes should die with it.
##### Actual behaviour

Opening the task manager shows the chromedriver is still open
##### Steps to reproduce the problem

Start chimp in watch mode, press CTRL-C

(Preferably a repository and easy reproduction steps)
##### Used version
- Chimp: 0.33.1
- Node.js: 
- Operation system: Windows 10

**Comment by Sanjo** [comment]
Also happens on Mac OS X I think.

**Comment by PierreCBSI** [comment]
not seeing this issue happen on Ubuntu 16.04 using chimp 0.34.1.... ctrl-c effectively shuts down chimp and browser, and all chrome processes as seen in the gnome system monitor.
