### ISSUE TITLE
JSON output for cucumber is empty following successful passing tests

### ISSUE THREAD

**Issue by smysnk** [xolvio/chimp#347]
#####  Expected behaviour
JSON output contains successful test cases and steps so that the JSON output file can be used to log test executions for products like [http://confluence.xpand-addons.com/display/XRAY/Import+Execution+Results](XRAY).

#####  Actual behaviour
JSON output contains an empty array "[]"

##### Steps to reproduce the problem

Pass all cucumber tests.

#####  Used version

* Chimp: 0.33.1
* Node.js :v5.6.0
* Operation system: osx

**Comment by smysnk** [comment]
Might be an actual cucumber.js issue now that I think about it.

**Comment by samhatoum** [comment]
Hey. Try to create a simple repo with a simple cucumber test that just does a console.log or something, and run it both with chimp and with cucumber.js directly - that will be all telling!

**Comment by erabonza** [comment]
Started seeing this as well on our CI job, but intermittent (happens 30% of the time).  Output to console looks fine, but the json report is null.

**Comment by samhatoum** [comment]
could you please provide some debug logs when it happens? would help us a lot

**Comment by smysnk** [comment]
For sure, will try and get some here shortly.

**Comment by samhatoum** [comment]
what's your definition of shortly? :p
