### ISSUE TITLE
Hitting [ENTER] in console window does not continue the tests

### ISSUE THREAD

**Issue by brucejo75** [xolvio/chimp#351]
#####  Expected behaviour
I am debugging a specific test.  I added a `browser.debug()` statement.
When the `browser.debug()` statement is hit I expect to continue the test by pressing [ENTER] in the console window.

#####  Actual behaviour
Hitting [ENTER] does nothing

##### Steps to reproduce the problem
ran:
`chimp --ddp=http://localhost:3000 --mocha --chai --path=tests`

with this as the only test:
```
describe.only("Test Debug continue", function suiteDebugContinue() {
  it("Verifies browser.debug() will continue", function tBrowserDebug() {
    browser.debug();
    done();
  });
});
```

This is output to the console window:
```
> chimp --ddp=http://localhost:3000 --mocha --chai --path=tests


[chimp] Running...


  Login Tests


[16:24:23]  DEBUG       queue has stopped, you can now go into the browser
[16:24:23]  DEBUG       continue by pressing the [ENTER] key ...
```

I press [ENTER] in the console window and nothing happens.
#####  Used version

* Chimp: 0.33.1
* Node.js: v5.8.0
* Operation system: **Windows 10**
* Meteor: 1.3.2.4

#####  Console / Log Output

N/A (see above)

**Comment by Sanjo** [comment]
If I remember correctly, I had fixed this for Cucumber once. So if it still works for Cucumber, we just need to do the same thing for Mocha and Jasmine.

**Comment by brucejo75** [comment]
Hi @Sanjo,

I am new to Git, open source, javascript... (basically you name it :-)).  I found where the code needs to changed (see below).  I used this as an excuse to create my first pull request, but it failed to push the branch.  I think I may need privileges?

### My steps

1. I did a clone of chimp on my desktop and ran `npm install`.
2. I found the code change you made to `cucumber.js` for v22.1.
3. I made similar code changes for both mocha and jasmine.
4. Verified it works for **mocha** on my machine (using meteor test).
5. I ran `npm run testonly`, it did not get very far.  It hung after the world-spec.js test and it failed 2 earlier tests because I am running on a windows machine and the file path compares had trouble with `\` vs `/`.  Maybe the other failures are because I am running on Windows 10?
6. created a branch `fix-browser-debug-continue`, committed my changes.
7. Attempted to push my branch to chimp, but I got this error:
`fatal: Authentication failed for 'https://github.com/xolvio/chimp/'`

-- I assume that I do not have rights to push to your project?
-- see code changes below, pretty simple...


### git show
```
commit e5fdb53285e723b4164ba3fb8bb77b009d7295c6
Author: brucejo <brucejo.wk@outlook.com>
Date:   Mon May 2 14:05:03 2016 -0700

    Piped stdin to Mocha & Jasmine like Cucumber. Enables [ENTER] to continue.

diff --git a/src/lib/jasmine/jasmine.js b/src/lib/jasmine/jasmine.js
index 50cd2a7..df87292 100644
--- a/src/lib/jasmine/jasmine.js
+++ b/src/lib/jasmine/jasmine.js
@@ -63,6 +63,7 @@ Jasmine.prototype.start = function (callback) {

   self.child = cp.fork(path.join(__dirname, 'jasmine-wrapper.js'), [], opts);

+  process.stdin.pipe(this.child.stdin);
   self.child.stdout.pipe(process.stdout);
   self.child.stderr.pipe(process.stderr);

diff --git a/src/lib/mocha/mocha.js b/src/lib/mocha/mocha.js
index 8fc5961..a8ad8ef 100644
--- a/src/lib/mocha/mocha.js
+++ b/src/lib/mocha/mocha.js
@@ -65,6 +65,7 @@ Mocha.prototype.start = function (callback) {
     '--color'
   ], opts);

+  process.stdin.pipe(this.child.stdin);
   self.child.stdout.pipe(process.stdout);
   self.child.stderr.pipe(process.stderr);
'''

**Comment by Sanjo** [comment]
Hi @brucejo75, you need to fork chimp. Then you can push your branch and open a pull request. See https://help.github.com/articles/fork-a-repo/#propose-changes-to-someone-elses-project. Thanks for contributing.

**Comment by brucejo75** [comment]
Cool!
Thanks for pointing me in the right direction.  I submitted the request and all tests passed.
