### ISSUE TITLE
Jasmine expect custom matchers for Cucumber mode

### ISSUE THREAD

**Issue by tahaykNSM** [xolvio/chimp#363]
Hello there, 
I have been using Chimp for a while and it is amazing , but now I'm stuck in a situation where I want to add a custom jasmine expectation and I can't find a way to do it with Chimp, any help or documentation would be so grate, and Thanks :smile:

**Comment by Sanjo** [comment]
You can do it like described here: http://jasmine.github.io/2.4/custom_matcher.html.

```js
beforeAll(function() {
  jasmine.addMatchers(customMatchers);
});
```

**Comment by tahaykNSM** [comment]
I don't know what I'm doing wrong,
I always get  `ReferenceError: beforeAll is not defined`.
I tried the same lines of code in `this.Before()` and I got `ReferenceError: jasmine is not defined`.
I'm using Chimp for my acceptance tests with this config file:
```

var config = {
    // - - - - CHIMP - - - -
    watch: true,

    // - - - - METEOR - - - -
    activate_ddp: true,
    ddp_protocol: "http",
    ddp_address: 'localhost',
    ddp_port: 3000,

    // - - - - CUCUMBER - - - -
    acceptance_tests_path: 'tests/acceptance',

    screenshotsOnError: false,
    screenshotsPath: '.screenshots',

    // - - - - SELENIUM  - - - -
    browser: 'chrome' //'phantomjs' 'firefox' 'chrome',
};


module.exports = {
    // - - - - CHIMP - - - -
    watch: config.watch,
    watchTags: '@dev,@watch,@focus',
    watchWithPolling: false,
    criticalSteps: null,
    criticalTag: '@critical',
    server: false,
    serverPort: 8060,
    serverHost: 'localhost',
    sync: true,
    offline: false,

    // - - - - CUCUMBER - - - -
    path: config.acceptance_tests_path,
    format: 'pretty',
    tags: '~@ignore',
    singleSnippetPerFile: true,
    recommendedFilenameSeparator: '_',
    chai: false,
    screenshotsOnError: config.screenshotsOnError,
    screenshotsPath: config.screenshotsPath,
    captureAllStepScreenshots: true,
    saveScreenshotsToDisk: config.screenshotsOnError,
    saveScreenshotsToReport: true,
    jsonOutput: null,

    // - - - - SELENIUM  - - - -
    browser: config.browser,
    platform: 'ANY',
    name: '',
    user: '',
    key: '',
    port: null,
    host: null,
    deviceName: null,

    // - - - - WEBDRIVER-IO  - - - -
    baseUrl: null,
    timeoutsAsyncScript: 10000,
    timeoutsImplicitWait: 3000,
    waitForTimeout: 10000,
    chromeBin: null,
    chromeArgs: null,
    chromeNoSandbox: false,

    // - - - - SESSION-MANAGER  - - - -
    noSessionReuse: false,
    browserstackLocal: false,
    tunnelIdentifier: null,

    // - - - - SIMIAN  - - - -
    simianResultEndPoint: 'api.simian.io/v1.0/result',
    simianAccessToken: false,
    simianResultBranch: null,
    simianRepositoryId: null,

    // - - - - MOCHA  - - - -
    mocha: false,
    // 'path: './tests',
    mochaTimeout: 60000,
    mochaReporter: 'spec',
    mochaSlow: 10000,

    // - - - - METEOR  - - - -
    ddp: config.activate_ddp ? config.ddp_protocol + "://" + config.ddp_address + ":" + config.ddp_port : false, 

    // - - - - PHANTOM  - - - -
    phantom_w: 1280,
    phantom_h: 1024,

    // - - - - DEBUGGING  - - - -
    log: 'info',
    debug: false,
    seleniumDebug: null,
    webdriverLogLevel: null,
    debugCucumber: null,
    debugBrkCucumber: null,
    debugMocha: null,
    debugBrkMocha: null,
};
```

**Comment by samhatoum** [comment]
Where are you putting the `before All`?

**Comment by tahaykNSM** [comment]
I'm pustting it in` [my project]/tests/acceptance/pre and post functions.js`

```
.
├── client
│   ├── assets
│   ├── components
│   ├── layout
│   └── lib
├── common
│   ├── model
│   └── validation
├── public 
│   └── fonts
├── server
│   ├── app.js
│   ├── config
│   ├── lib
│   ├── methods
│   └── publishers
├── settings.json
└── tests
    ├── acceptance  
    │   ├── pre and post functions.js
    │   └── feature1
    │       ├── ... .feature  
    │       └── support
    │           └── ... 
    └── jasmine
        ├── client
        │   ├── integration
        │   │   └── ...
        │   └── unit
        │       ├── helpers 
        │       └── ...
        └── server
            └── integration
                └── ... 
```
pre and post functions.js:
```

module.exports = function () {

    this.Before(function (scenario) {       
        server.execute(function () {
            var cleaner = Package['xolvio:cleaner'];          
            cleaner.resetDatabase();
        });
    });

    this.beforeAll(function() {
          var imageDiffer = require('imagediff');
          jasmine.addMatchers(imageDiffer.jasmine);
      });
}
```

**Comment by samhatoum** [comment]
Let make sure I understand, you want to use custom matchers inside cucumber steps using the jasmine assertion library, correct?

**Comment by tahaykNSM** [comment]
yes that's correct

**Comment by Sanjo** [comment]
In your config, set the option `jasmine: true` to run in Jasmine mode, instead of Cucumber mode.

**Comment by samhatoum** [comment]
@Sanjo I think @tahaykNSM would like to use custom jasmine matchers using the Jasmine assertion library we created but inside Cucumber

**Comment by tahaykNSM** [comment]
please forgive my lack of informations, I'm new to all the testing concept and I can't express myself clearly.
yes what @samhatoum  said is correct, I'm trying to use custom jasmine matchers (for assertions) inside Cucumber.

**Comment by Sanjo** [comment]
Oh I see. The jasmine-expect package exports [addMatchers](https://github.com/xolvio/jasmine-expect/blob/master/__tests__/index-spec.js#L148-L167) to do this. This function is currently [not added to the global scope](https://github.com/xolvio/chimp/blob/b4c382dfe41765987884f8ae2f8666158e2ccf85/src/lib/chimp-helper.js#L35). So we need to expose this to the global scope.

**Comment by tahaykNSM** [comment]
That's would be great :smiley: 
Thank you very much for your efforts :+1:

**Comment by lgandecki** [comment]
@Sanjo @samhatoum 
Would you prefer having this exposed as:
    `  global.jasmine = require('xolvio-jasmine-expect');`
and then someone could do 
`jasmine.addMatchers()`
or more like:
`global.addMatchers = require('xolvio-jasmine-expect').addMatchers 
`?

**Comment by samhatoum** [comment]
I think we should expose the jasmine object and let users do what they want

**Comment by lgandecki** [comment]
This is tweaked in the PR #416 , but it would be nice if someone ( @tahaykNSM ? ;) ) wanted to take that branch and see whether this is solving the problem. 
You should be able to use jasmine.addMatchers() now in your code.

**Comment by tahaykNSM** [comment]
@lgandecki , ok I will gladly try it :smiley: 
thank you very much :D

**Comment by samhatoum** [comment]
tracking in #416

**Comment by samhatoum** [comment]
@tahaykNSM please let us know if that worked

**Comment by samhatoum** [comment]
@tahaykNSM looking forward to that update so we can close this PR
https://github.com/xolvio/chimp/pull/416

thanks :)

**Comment by tahaykNSM** [comment]
I'm so sorry @samhatoum , I have too many urgent tasks to solve, I'll gladly test this update ASAP.

**Comment by PavliyVitaliy** [comment]
@samhatoum I'm facing the same problem as @samhatoum. 
I also use: chimp - cucumber-jasmine(expect () only). I added " jasmine.addMatchers (customMatchers);". And it worked on my local machine when I used "expect(8).toBeLog (8);" in my tests! But when I run this on a remote machine via jenkins, I get the error " TypeError: expect(...).to Be Logged not a function".

The code in which I add customMatchers:
const jasmine = require('xolvio-jasmine-expect');

const customMatchers = {
  toBeLog(value) {
    return {
      compare(actual, expec, message) {
        let expected = expec;
        expected = (expected === undefined) ? '' : expected;
        const result = {};
        result.pass = value.equals(actual, expected);
        if (result.pass) {
          result.message = `expected = actual : '${expected}' = '${actual}'`;
        } else {
          result.message = logger.errStr(`${message}: expected '${expected}' but got it '${actual}'`);
        }
        return result;
      },
    };
  },
};
const hooks = function hook() {
  this.registerHandler('BeforeFeatures', () => {
     jasmine.addMatchers(customMatchers);
  });
};
module.exports = hooks;

Please help me to understand this problem. What dependencies I'm missing, which are required.

**Comment by Sanjo** [comment]
@PavliyVitaliy Make sure that the file is actually executed on Jenkins (console.log something from hook()). If it is not executed, then you just need to find out the reason, to fix it.
