### ISSUE TITLE
Import `browser` Global via ES6 import Syntax

### ISSUE THREAD

**Issue by joncursi** [xolvio/chimp#365]
I want to import the global browser variable to be more modular / ES6-like. From the Chimp documentation, browser is imported from webdriverio via:

```
var webdriverio = require('webdriverio'); var options = {}; var browser=webdriverio.remote(options)
```

However, adding this to the top of my padding `test.js` file makes the tests fail, as browser does not get defined properly. How can I import browser using ES6 modules?

**Comment by Sanjo** [comment]
There is currently no way to do this. In the Chimp environment `browser` is always available, like other JavaScript runtime globals (e.g. Math).
