### ISSUE TITLE
Using cucumber in Meteor 1.3

### ISSUE THREAD

**Issue by lorensr** [xolvio/chimp#368]
#####  Expected behaviour

Chrome should open and console should output results (or in this case a message telling me to implement steps)

#####  Actual behaviour

No Chrome, no results, and a node process is started that takes up 100% CPU and doesn't stop (it's been 30 min so far)

##### Steps to reproduce the problem

Add this file: `tests/cucumber/features/foo.feature`

```
Feature: App loads
  Background:
    Given I am not signed in

  @watch
  Scenario: Opening app should bring user to home screen
    When I open the app
```

run `meteor` in one process and `chimp` in another

#####  Used version

* Meteor: 1.3.2.4
* Chimp: 0.34.1
* Node.js: 6.0.0
* Operation system: 10.11.4

#####  Console / Log Output

```sh
> chimp --ddp=http://localhost:3000 --watch --cucumber --path=tests/cucumber
[chimp] Watching features with tagged with @focus,@dev,@watch

[chimp] Running...
```

**Comment by lorensr** [comment]
Repro: https://github.com/lorensr/chimp-368

**Comment by Sanjo** [comment]
Can you try to run Chimp with Node.js 5 or 4 please and see if that fixes the issue.

**Comment by lorensr** [comment]
Works w/ v5.4.1! Perhaps could output a warning saying chimp doesn't support v6.

**Comment by lorensr** [comment]
Fixed the guide: https://github.com/meteor/guide/commit/2185442facdc1a56dbdbd55038434e85419d0e4c

**Comment by Sanjo** [comment]
Thanks. Closing this one in favor of https://github.com/xolvio/chimp/issues/349.
