### ISSUE TITLE
Command-line documentation

### ISSUE THREAD

**Issue by lorensr** [xolvio/chimp#369]
It would be helpful if one of these worked:

``` sh
chimp help
chimp -h
chimp --help
man chimp
```

**Comment by ramijarrar** [comment]
Duplicate #175

**Comment by deanius** [comment]
#175 has been closed. I'll start a PR for this

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
