### ISSUE TITLE
How to handle asynchronous Alert-Boxes?

### ISSUE THREAD

**Issue by Mumpitz** [xolvio/chimp#370]
I would like to know how i have to handle Alert-Boxes in my Chimp tests.

I got a Checkbox on the Website to activate and deactivate a feature. Changeing the Checkbox is triggering an AJAX-Call that changes a Flag in the Database. When the Call returns, it pops um an alert with the information "Feature is now active" or "Feature is deactivated".

For my test, i need to check if the Feature is active, and if not activate it and check that the alert has the correct value.

I've tried to create an synchronous alert to find the correct functions with the `browser.execute(function(){alert("Test");});`.
I could close the alert with `browser.alertDismiss();` or `browser.alertAccept();`
To check the Text, i've written it to a var before: `var alertText = browser.alertText();`

But this is not working when the alert is triggered asynchronous and i need to wait for the alert to appear. I don't know how to wait for it.
Assuming `waitUntil` is the right Function to use, i've played around with it, but did not get it to run.

#####  Used version

* Chimp: 0.9.4 (`chimp --version`)
* Node.js: v4.4.3 (`node --version`)
* Operation system: Mac OS X 10.10.5

**Comment by Sanjo** [comment]
To wait for the alert you can probably do this:

```js
browser.waitUntil(() => browser.alertText() != null)
```

See http://webdriver.io/api/protocol/alertText.html

**Comment by Mumpitz** [comment]
The Test fails with the message:
`Error: Promise was rejected with the following reason: Error: no alert open`

Seems to me like alertText() throws an error instantaneously instead of waiting for an alert to appear.

I can also use a Condition where i ask for `browser.alertText() != null`, but it also fails with the same message.

**Comment by Sanjo** [comment]
Then maybe:

```js
browser.waitUntil(() => {
  try {
    return browser.alertText() != null;
  } catch (error) {
    return false;
  }
});
```

**Comment by Mumpitz** [comment]
Yes, thanks. This works perfectly. I would have never been able to come up with this solution.
My test now looks as follows and works fine.

```javascript
  this.When(/^activating the Checkbox$/, function () {
    if (browser.isSelected("input[name='my_checkbox']")) {
      expect(true).toBe(true);
    } else {
      browser.click("input[name='my_checkbox']");
      browser.waitUntil(() => {
        try {
          return browser.alertText() != null;
        }
        catch (error) {
          return false;
        }
      }, 5000);
      expect(browser.alertText()).toMatch("My Alert Text");
      browser.alertAccept();
    }
  });
```

BTW: `browser.alertDismiss();` was causing my Chrome to crash.
