### ISSUE TITLE
Cucumber hooks cannot use the driver on 0.34.1

### ISSUE THREAD

**Issue by jmflaherty** [xolvio/chimp#371]
##### Expected behaviour

Cucumber hooks are able to interact with the driver without an issue.
##### Actual behaviour

On Chimp 0.34.1 the Cucumber hooks cannot use the driver, as in 

```
var myHooks = function () {
    this.Before(function () {
        driver.windowHandleMaximize([driver.windowHandle]);
    });

    this.After(function () {
        driver.deleteCookie();
    });
};
module.exports = myHooks;
```

Showing the following error when executed.

> ```
> Before                                      # features\steps\hooks.js:4
>   Error: Couldn't connect to selenium server
> ```
##### Steps to reproduce the problem

Clone /master from [my repo](https://github.com/jmflaherty/selenium-selectors-speed),
run 'npm install',
then execute it with './node_modules/chimp/bin/chimp.js config-chimp.js'.
##### Used version
- Chimp: 0.34.1
- Node.js: 5.11.1
- Operation system: Windows 10
##### Extra info and comments

This same code works perfectly with Chimp 0.30.0. I'll try to find which version introduced the bug.
Back on 0.34.1 the hooks themselves seems to work, but they fail only when the driver is called. If you comment/delete the lines that uses it the hooks run without errors.
I've used hooks in previous projects with older Chimp versions and I've never had any kind of issue. This is the first time.

https://www.npmjs.com/package/cucumber#hooks

Thanks!

**Comment by samhatoum** [comment]
thanks for the report. Is this on a clean repo?

**Comment by jmflaherty** [comment]
I was just pushing the code. Didn't expect you to be so fast haha

**Comment by samhatoum** [comment]
Thank god for slack integration!

**Comment by jmflaherty** [comment]
It still happens with the same repo, changing Chimp to v0.41.1 and Node to 6.6.0.

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
