### ISSUE TITLE
Tagged Hooks are not working

### ISSUE THREAD

**Issue by celador** [xolvio/chimp#372]
#####  Expected behaviour
Given I've included an options object with a tags property as an array of strings in a Before function
And I've tagged a scenario with a tag
When I run Chimp
Then I expect the Before function to execute before the tagged scenario

#####  Actual behaviour
When I run chimp
I receive an error on the command line saying that `tagGroupString.split is not a function`

##### Steps to reproduce the problem
Create a Before Hook, and provide it an options object with a tags property with an array of strings 
https://github.com/celador/ChimpBrokenTags

#####  Used version

* Chimp: 0.9.4
* Node.js: 5.7.1
* Operation system: OSX 10.11.4

#####  Console / Log Output

(Upload long logs to [Gist](https://gist.github.com/) and link it here)

**Comment by tmolina-pbx** [comment]
Facing this same issue at the moment. Any news ?

**Comment by lgandecki** [comment]
This just moved to the top of my team's priority list for chimp, sorry for the delay - will get to it as soon as possible, should be fixed during the next two weeks.

**Comment by tmolina-pbx** [comment]
Very much appreciated guys :)

**Comment by lgandecki** [comment]
This works with the updated version of cucumber. 
<img width="710" alt="screen shot 2016-07-11 at 3 13 59 pm" src="https://cloud.githubusercontent.com/assets/4002543/16731765/20f4172a-477a-11e6-8b93-508036d7fd5a.png">

We will release new chimp that uses the newer cucumber in the next few days. Till then if you want you can clone https://lgandecki@github.com/xolvio/cucumber-js.git branch chimp1.0.0 to the chimp/node_modules/cucumber (first remove/move the cucumber folder that's already there).
