### ISSUE TITLE
Upgrade Cucumber.js to 0.10.2

### ISSUE THREAD

**Issue by samhatoum** [xolvio/chimp#374]
As per the title

**Comment by lgandecki** [comment]
https://github.com/xolvio/cucumber-js/pull/1
you'd have to tag the chimp branch after merge and then update package.json 
line:
    "cucumber": "xolvio/cucumber-js#v0.9.4-chimp.3",
in chimp accordingly

**Comment by lgandecki** [comment]
I was going to finalize this now (on the chimp side), but I can see that there is already 1.2.0 version around, should we merge to that one or would you prefer to stay with 0.10.* ? 
The changes don't seem breaking: https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md
We could also merge and do some limited testing

**Comment by samhatoum** [comment]
latest is better for sure

**Comment by lgandecki** [comment]
updated to 1.0.0 for now, 1.1.0 introduces new hooks system and will require some extra work.
