### ISSUE TITLE
Document how to use a test DB with meteor

### ISSUE THREAD

**Issue by queso** [xolvio/chimp#379]
Where are the docs at and how do I contribute to them @samhatoum? It seems that Chimp's docs mention an `IS_MIRROR` flag. From everything I can gather, there is `WITH_MIRROR` support from the start.js script that is advocated by the Automated best practices repo. It might make sense to talk about using a separate test DB in the Chimp.js meteor integration docs.

**Comment by samhatoum** [comment]
Would this page work: https://chimp.readme.io/docs/getting-started-with-meteor-cucumber

I can create a new one if not. Let me know

**Comment by queso** [comment]
Yeah, that page would be fine. Happy to help if you let me know how to contrib to docs.

**Comment by samhatoum** [comment]
Awesome, would love the help. You can click on make suggestions on that page, or if you like I can add you as a contributor?
