### ISSUE TITLE
It is possible to use another phantomjs bin?

### ISSUE THREAD

**Issue by artem-russkikh** [xolvio/chimp#38]
Version of the phantomjs in the repository https://github.com/eugeneware/phantomjs-bin is 1.9.8

In my system (OSX) `phantomjs -v` is 2.0.0

I would like the opportunity to use system phantomjs bin

**Comment by Sanjo** [comment]
Not yet.

**Comment by samhatoum** [comment]
It is now. you can set `--phantom_path`
