### ISSUE TITLE
saveScreenshot triggers rerun with phantom js

### ISSUE THREAD

**Issue by thebarty** [xolvio/chimp#380]
Hi guys,

when running chimp like ``chimp --ddp=http://localhost:3300 --mocha --path=tests --browser=phantomjs --watchTags="@watch" --watch;`` and using a ``browser.saveScreenshot(path)`` chimp will trigger a rerun ``[chimp] Running...`` after saving the screenshot.

I guess this is not what we want...

**Comment by samhatoum** [comment]
it's not. We should ignore them for sure. You can set the screenshot path as a workaround in the config

**Comment by samhatoum** [comment]
Duplicate of #197
