### ISSUE TITLE
How to install ``chai-string`` Matchers?

### ISSUE THREAD

**Issue by thebarty** [xolvio/chimp#381]
Hi guys,

I'd love to use `chai-string`-Matchers, in order to do something like

```
// chai string is cool (!!)
expect('abcdef').to.startWith('abc');

// which is much better than using underscore.string
// expect(s.startsWith('abcdef', 'abc')).to.be.true
```

A simple `npm install --save-dev chai-string` did NOT work for me...

Any ideas how to make this work with chimp?

**Comment by jirikrepl** [comment]
I installed it like you `npm install --save-dev chai-string`

seems to me that `chai` is a global in mocha/chimp tests. So I added chai-string plugin like in docs: http://chaijs.com/plugins/chai-string/

In my before block I added

    before(() => {
        chai.use(require('chai-string'));
        ...
    }

then I used it:

    it('string should start with', function () {
        ...
        someString.should.startWith('some string');
        ...
    });

**Comment by domi41** [comment]
I'd love to have these extra assertions in Chimp by default. They make too much sense.

Thanks @jirikrepl for the tip !

For those using Cucumber, here's the related hook snippet :

``` js
// Load Chai extensions, because life is simpler with them.
this.BeforeFeatures(() => {
    if (typeof chai == 'undefined') throw new Error("We're using Chai ; please run Chimp with the --chai option.");
    chai.use(require('chai-string'));
});
```

**Comment by gabrieldarezzo** [comment]
I try here and works like a charm:

First install in your project:
```npm install --save-dev chai-string```
After go in your test 

```js
import chai, { expect } from 'chai';
chai.use(require('chai-string'));


describe('StringTestRocks', () => {
  it('should abcdef same of abcde f  ', () => {    
    expect('abcdef').to.equalIgnoreSpaces('a\nb\tc\r d  ef');
  });
}); 
```

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
