### ISSUE TITLE
Stacktrace NOT shown for ``expect().to.be.*``

### ISSUE THREAD

**Issue by thebarty** [xolvio/chimp#382]
Hi guys,

now this is weird: I am NOT seing a stacktrace when a test fails with ``to.be``, p.e.
```
it('failing test @watch', () => {
    expect(true).to.be.false
 }
```

all I am getting is  a
```
Uncaught AssertionError: expected true to be false
```

Any ideas whats going on?

**Comment by samhatoum** [comment]
I'm not sure if that's standard mocha behviour or not. We don't do anything funky with it

**Comment by pscheit** [comment]
At least in cucumber I have the same problem. I think you're doing something fancy with it:
https://github.com/xolvio/chimp/blob/master/dist/lib/cucumberjs/cucumber.js#L219

It's only added if the basePath is found in the line of the backtrace. But in cucumber the path seems already to be cleaned up from absolute paths

**Comment by thebarty** [comment]
just stumbled upon this again... with complex tests this is a pain in the ass cause you end up writing ``console.logs()`` for debugging...

**Comment by samhatoum** [comment]
are you using cucumber? do you have some reproducible steps I could use?

**Comment by pscheit** [comment]
should fail with any step. Yes cucumber. Just write a cucumber step that fails?

**Comment by samhatoum** [comment]
The output conditioning has been fixed to show the right step failures, and you can now also set a `conditionOutput` option to false if you want the direct cucumber.js output

from v0.37.1

**Comment by thebarty** [comment]
Hi guys,

sorry for coming back so late. I stumbled upon this beast again and found a good reference - it seems to be a mocha problem: https://github.com/chaijs/chai/issues/425.

**It seems like a workaround might be to pass ``--full-trace`` option to mocha.
Can you guys add this option to https://github.com/xolvio/chimp/blob/master/src/bin/default.js#L98??**

In my setup I run chimp like this
```
chimp ./tests/_circle-ci-chimp-config.js --ddp=http://localhost:3000 --path=tests --mocha
```

**Comment by pscheit** [comment]
this is mocha. I see the exception trace in mocka. But not in cucumber

**Comment by thebarty** [comment]
Yeah I guess it is better to go on with this topic in the "configure mocha"-topic. Thanks for the quick response
