### ISSUE TITLE
Problem with chimp and fsevents and ‘lazy symbol binding failed’ on OSX

### ISSUE THREAD

**Issue by sirganya** [xolvio/chimp#383]
When I run

`meteor npm run chimp-test`

I get.

`dyld: lazy symbol binding failed: Symbol not found: _node_module_register
Referenced from: /usr/local/lib/node_modules/chimp/node_modules/fsevents/build/Release/fse.node
Expected in: dynamic lookup`

Anyone come across this before?

**Comment by cesarve77** [comment]
same issue here

**Comment by cesarve77** [comment]
same issue here
I fixed using:

 meteor npm install chimp

No global!!

This error happen because chimp was instaled using the node version of your machine and not the version of your meteor (and not are the sames)

sorry for my english
