### ISSUE TITLE
how to do a copy/paste ?

### ISSUE THREAD

**Issue by tahaykNSM** [xolvio/chimp#385]
Hello everyone,
I'm trying to paste some text in a text area in order to trigger a "onPaste" function but I can't figure out a way to do it, can any one hemp me please ?

**Comment by hartaaron** [comment]
Here is some raw javascript to trigger a paste event:

```
function triggerPasteEvent(element) {
    var pasteEvent = document.createEvent('ClipboardEvent')
    event.initEvent('paste', true, true)
    element.dispatchEvent(pasteEvent)
}
```

You can then call [client.execute()](http://webdriver.io/api/protocol/execute.html) and it will fire the paste event.

However, it won't actually paste from the clipboard.  That's restricted by the browser for security reasons. 

As far as I can figure out, you can't populate clipboardData (though it might be possible to implement a DataTransfer object, but you won't be able to mark event.isTrusted = true)

A workaround is to call client.setValue() with the text you want to paste and then call client.execute() to trigger the paste event.  Of course that won't work for pasting non-text data.

**Comment by tahaykNSM** [comment]
Thank you @hartaaron this was very helpful :smile:
