### ISSUE TITLE
Long gherkin lines = screenshot crashes chimp due to filename too long

### ISSUE THREAD

**Issue by ShockiTV** [xolvio/chimp#386]
##### Expected behaviour

Chimp should shorten screenshot filenames to prevent whole chimp crashing on I/O for reaching filename filesystem limit
##### Actual behaviour

Chimp crash when you put too long Gherkin line on which step fail - app try to save screenshot with too long name
Our management requested SQL queries without special formatting to be part of Gherkin
##### Steps to reproduce the problem

(Preferably a repository and easy reproduction steps)
##### Used version
- Chimp: 
- Node.js:
- Operation system: 
##### Console / Log Output

(Upload long logs to [Gist](https://gist.github.com/) and link it here)

**Comment by samhatoum** [comment]
Thanks for reporting. Do you have the logs for us to look at?

**Comment by samhatoum** [comment]
Could I also please see some of the source feature files?

**Comment by samhatoum** [comment]
@ShockiTV ☝️

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
