### ISSUE TITLE
Forked version of cucumber-js is causing issue to use chimp.js as enterprise (private) npm repository

### ISSUE THREAD

**Issue by dilipkumar2k6** [xolvio/chimp#390]
##### Expected behaviour

Use chimp.js in enterprise npm repository 
##### Actual behaviour

Not able to use chimp.js in enterprise npm repository because cucumber is used as forked version as below
`"cucumber": "xolvio/cucumber-js#v0.9.4-chimp.3",`
Since enterprise NPM repo doesn't have connectivity to github.com therefore it fails here. 
##### Steps to reproduce the problem
1. Setup local npm repo
2. Publish chimp.js and its dependencies in the local repo
3. Block connectivity to github.com
4. Try to install chimp.js using local npm repo
   Issue: It fails to install due to dependency on `xolvio/cucumber-js#v0.9.4-chimp.3` hosting on github.com
##### Used version
- Chimp: 0.35.0
- Node.js: 4.4.1
- Operation system: MAC
##### Console / Log Output

```
npm ERR! Command failed: git clone --template=/Users/REDACTED/.npm/_git-remotes/_templates --mirror git@github.com:xolvio/cucumber-js.git /Users/REDACTED/.npm/_git-remotes/git-github-com-xolvio-cucumber-js-git-ac9d35ff
npm ERR! Cloning into bare repository '/Users/REDACTED/.npm/_git-remotes/git-github-com-xolvio-cucumber-js-git-ac9d35ff'...
npm ERR! ssh_exchange_identification: Connection closed by remote host
npm ERR! fatal: Could not read from remote repository.
```
##### What I see as possible solution

Can we take any of following approach?
1. Can we do pull request for changes in cucumber-js needed by chimp.js in cucumber-js repository? 
2. If  option 1 is not possible, can we publish forked copy of cucumber-js as chimp-cucumber-js and use this? 

Please let me know if I have any other options to solve this problem.

**Comment by samhatoum** [comment]
I guess the 3rd option would be to host our fork of cucumber-js on your private npm repository, as well as a modified version of Chimp that points to your_npm/cucumber-js 

I don't think option 1 is possible due to us using fibers and this is not the design of cucumber-js.

Option 2 is possible, we would just need to publish `xolvio-cucumber` or similar.

@lgandecki what are your thoughts?

**Comment by dilipkumar2k6** [comment]
Thanks @samhatoum, 3rd option could be ok for short term however will create problem in future to keep updating our git repository. 

Please see if option 2 is possible. I can assist if anything i can do for option 2.

**Comment by lgandecki** [comment]
I like the idea of having the fork on the npm the most. If I'm not missing anything it shouldn't add too much effort to publish new version on each update.

**Comment by dilipkumar2k6** [comment]
I understand, but having forked version of cucumber-js in local npm repository and updating package.json to use the local cucumber-js is tedious. 

I am thinking if we can go with option 2 to publish xolvio-cucumber as a separate module. This will make chimp.js installation on local npm repo very easy.

**Comment by lgandecki** [comment]
Sorry, yeah, I meant to express my support for option 2!

**Comment by dilipkumar2k6** [comment]
Great, seems this will help everyone in future. I am ready to help to move with option 2.

**Comment by Sanjo** [comment]
Yup, option 2 will work.

**Comment by samhatoum** [comment]
alright, #2 it is. coming in the next release

**Comment by dilipkumar2k6** [comment]
Thanks guys. You all are awesome!!!

**Comment by dilipkumar2k6** [comment]
@samhatoum, one of my team mate was exploring package.json options and came across bundledDependencies. Seems like you can update package.json to move "cucumber-js"  into bundledDependencies, it will take care of embedding the dependency on publishing. Following is stackoverflow link for your reference.

http://stackoverflow.com/questions/11207638/advantages-of-bundleddependencies-over-normal-dependencies-in-npm/25044361#25044361

Please have a look and see if this is easier option for you.

**Comment by dilipkumar2k6** [comment]
Hi @samhatoum,

I still see cucumber is referring as relative path to github.com. 

`"cucumber": "xolvio/cucumber-js#v1.0.0-chimp"`

It will be great if your team can help on this. Our team is not able to use it because of this problem. 

Thanks,
Dilip

**Comment by jezstephens** [comment]
Does anyone know how WebdriverIO's `wdio` test runner handles this using an unmodified cucumber-js? It uses fibers as well, I believe (via [wdio-sync](https://github.com/webdriverio/wdio-sync)).

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
