### ISSUE TITLE
Add support for Tape

### ISSUE THREAD

**Issue by alexbardas** [xolvio/chimp#391]
##### Expected behaviour

Able to use [Tape](https://github.com/substack/tape) for writing e2e tests.
##### Actual behaviour

Tape is one of the simplest and best testing frameworks, should probably be officially supported.

---

_Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others._

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
