### ISSUE TITLE
Upgrade to latest version of Mocha

### ISSUE THREAD

**Issue by duclet** [xolvio/chimp#392]
Currently Chimp relies of Mocha version 2.3.4. With version 2.4 of Mocha, they introduced a way to retry tests which is really helpful. I tried upgrading forcefully to 2.5.3 (the latest version as of writing this) and it seems like the tests are still running. Can we update the package.json file to upgrade to the new version?

**Comment by samhatoum** [comment]
sure. Would love a PR that shows passing tests :)

**Comment by samhatoum** [comment]
Done!
