### ISSUE TITLE
can't run chimp with browser=firefox

### ISSUE THREAD

**Issue by gferreri** [xolvio/chimp#396]
When I try to run a simple chimp test using `browser=firefox` I receive a timeout error. Running against chrome (the default option) works fine. I've tried against FF 46 and FF 47 with the same results. Firing up selenium standalone 2.53.0 directly, I can use the built in web interface to launch firefox 46.0 and interact with the browser with no errors.

#####  Expected behaviour

`chimp --ddp=http://localhost:3000 --browser=firefox` should be able to connect and run the tests.

#####  Actual behaviour

`chimp --ddp=http://localhost:3000 --browser=firefox` crashes after 45 seconds with a long stacktrace, which boils down to `Unable to connect to host localhost on port 7055 after 45000ms`

##### Steps to reproduce the problem

(Preferably a repository and easy reproduction steps)

#####  Used version

* Chimp: 0.35.0
* Node.js: 5.0.0
* Firefox: 46.0 and 47.0
* Operation system: OSX El Capitan 10.11.4

#####  Console / Log Output

https://gist.github.com/gferreri/19a4b26255a094d19baacb73483d66d8

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by Sanjo** [comment]
I think the reason is that Firefox is not in https://github.com/xolvio/chimp/blob/master/src/lib/selenium.js#L26-L47.

**Comment by jmflaherty** [comment]
@Sanjo, the Firefox driver is available out of the box with selenium-standalone:
https://www.npmjs.com/package/selenium-standalone#available-browsers
It doesn't needs to be specified where to get the driver as with IE or Chrome.

@gferreri, the problem is that Firefox itself dropped the Firefox driver on v47 in favor of the new Marionette driver, which ain't included in selenium-standalone:
https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver

This means that you'll be only able to run tests with the Firefox driver on Firefox up to the v46.
And if you want to run them in the v47 or upcoming versions, you'll have to use the Marionette driver.

**Comment by PierreCBSI** [comment]
@gferreri - as @jmflaherty  said - I was not able to get version older that 45.0 to work (not even 45.0.2) Get yours at https://ftp.mozilla.org/pub/firefox/releases/. Marionette should be included in future selenium releases (https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver) but meanwhile good ol 45.0.

**Comment by samhatoum** [comment]
@gferreri did this fix your issue?

**Comment by gferreri** [comment]
@samhatoum yes, downgrading to 45.0 seems to fix the issue. Not ideal, but at least it works for the time being. Thanks!

**Comment by samhatoum** [comment]
you can now add your own drivers here:
https://github.com/xolvio/chimp/blob/master/src/bin/default.js#L67

**Comment by jmatsushita** [comment]
FYI, this worked for me after both updating to geckodriver and bumping selenium standalone to 3.0.1 as well.

```
  // - - - - SELENIUM-STANDALONE
  seleniumStandaloneOptions: {
    // check for more recent versions of selenium here:
    // http://selenium-release.storage.googleapis.com/index.html
    version: '3.0.1',
    baseURL: 'https://selenium-release.storage.googleapis.com',
    drivers: {
      chrome: {
        // check for more recent versions of chrome driver here:
        // http://chromedriver.storage.googleapis.com/index.html
        version: '2.24',
        arch: process.arch,
        baseURL: 'https://chromedriver.storage.googleapis.com'
      },
      ie: {
        // check for more recent versions of internet explorer driver here:
        // http://selenium-release.storage.googleapis.com/index.html
        version: '2.50.0',
        arch: 'ia32',
        baseURL: 'https://selenium-release.storage.googleapis.com'
      },
     firefox: {
        // check for more recent versions of gecko  driver here:
        // https://github.com/mozilla/geckodriver/releases
        version: '0.11.1',
        arch: process.arch,
        baseURL: 'https://github.com/mozilla/geckodriver/releases/download'
      }
    }
  },
```
