### ISSUE TITLE
local chimp is erroring on missing selenium jar

### ISSUE THREAD

**Issue by legacyWork** [xolvio/chimp#397]
##### Expected behaviour

No errors
##### Steps to reproduce the problem

./node_modules/.bin/chimp

[chimp] Running...
selenium-standalone installation [=================== ] 97% 0.1s[Error: Missing /Users/myUser/AUTOMATION/AutomationDev/javascript_ui_test/node_modules/chimp/node_modules/selenium-standalone/.selenium/selenium-server/2.50.1-server.jar](Preferably a repository and easy reproduction steps)
##### Used version
- Chimp: 
- Node.js:
- Operation system: 
##### Console / Log Output

(Upload long logs to [Gist](https://gist.github.com/) and link it here)

---

_Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others._

**Comment by jmflaherty** [comment]
@legacyWork
Happened to me a few times as well.
I worked it around opening the folder where the server should be, and found that the server was downloaded but using a different version of the one that Chimp wants to run. So changing the name of the .jar file you got to the one that Chimp is looking for makes it work.
Ain't pretty, but works.

**Comment by samhatoum** [comment]
that's odd. Might have happened through an upgrade. Did you change Chimp version?

You can try to delete the `chimp/node_modules/selenium-standalone` directory and try again. It may be the way selenium-standalone tries to detect if it already downloaded Selenium.

**Comment by btburton42** [comment]
This happened to me today because of a client firewall blocking SSL connections. To test this out, make sure you can hit the selenium URL directly.
https://selenium-release.storage.googleapis.com/2.50/selenium-server-standalone-2.50.1.jar

**Comment by samhatoum** [comment]
thanks @btburton42

**Comment by thienphuoc** [comment]
+Remove nodejs v6 ($ sudo apt-get remove nodejs)
-> add nodejs v4 :
$ curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
$ sudo apt-get install -y nodejs

Link: https://nodejs.org/en/download/package-manager/

**Comment by btburton42** [comment]
@thienphuoc i think the node 6 issue is related to issues with fsevents and chokidar breaking in node 6 and @samhatoum is tracking it here https://github.com/xolvio/chimp/pull/393

**Comment by samhatoum** [comment]
I've fixed this issue in 0.37.0 by extracting the selenium / firefox drivers etc to the config file. So now you can set whatever you need to set for your needs in 

See here
https://github.com/xolvio/chimp/blob/improvements/src/bin/default.js#L62

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
