### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by legacyWork** [xolvio/chimp#398]
##### Expected behaviour

https://www.npmjs.com/package/chimp

talks about some chimp.js file in a bin folder (Usage in a gulp task).  This file does not exist anywhere. In fact the whole gulp process for chimp does not work as described.  It is related to the earlier bug I filed (which i manually fixed by going into some deep dive node_modules config file and changing a number to 2.53.0)

/Users/myUser/AUTOMATION/AutomationDev/javascript_ui_test/node_modules/chimp/lib/cucumberjs/cucumber.js:239
  if (features.indexOf(',') !== -1) {
              ^

TypeError: Cannot read property 'indexOf' of undefined
##### Steps to reproduce the problem

(Preferably a repository and easy reproduction steps)
##### Used version
- Chimp: 
- Node.js:
- Operation system: 
##### Console / Log Output

(Upload long logs to [Gist](https://gist.github.com/) and link it here)

---

_Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others._

**Comment by samhatoum** [comment]
Does this work for you:
`/my/path/to/my/project/node_modules/.bin/chimp.js`

**Comment by legacyWork** [comment]
That also does not work.  I ended up using a shell wrapper to manually execute command line commands in gulp.

**Comment by lucetius** [comment]
@samhatoum i think we should change
`/my/path/to/my/project/node_modules/.bin/chimp.js`
to
`/my/path/to/my/project/node_modules/.bin/chimp`

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
