### ISSUE TITLE
Noisy debug

### ISSUE THREAD

**Issue by zvictor** [xolvio/chimp#399]
##### Expected behaviour

To have the possibility of using chimp in `debug` mode but still be able to suppress excessive logging e.g. by setting `--log=silent`.
##### Actual behaviour

Debug mode forces logging into debug mode as well.

``` js
// src/lib/log.js:15

if (debug) {
  log.setLevel('debug');
} else {
  log.setLevel(argv.log);
}
```

**Comment by samhatoum** [comment]
Would love a PR :)

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
