### ISSUE TITLE
chimp is overriding the browser to '' if there is a deviceName set in the config

### ISSUE THREAD

**Issue by vpappula** [xolvio/chimp#400]
#####  Expected behaviour
browser and deviceName capabilities are required for browser based testing on mobile.

#####  Actual behaviour
chimp is overriding the browser to '' if there is a deviceName set in the config

##### Steps to reproduce the problem
I should be able to run tests on chrome from an Android device with the below config
 
// - - - - SELENIUM  - - - -
    browser: 'chrome',
    name: '',
    user: '',
    key: '',
    deviceName: 'Android Emulator',
    //- - -  - Appium connection - - - -
    host: 'localhost',
    port: 4723,

    // - - - - WEBDRIVER-IO  - - - -
    webdriverio: {
        desiredCapabilities: {
            platformVersion: '6.0',
            platformName: 'Android',
        },
        // logLevel: 'verbose',

I modified the code below to get it working
chimp-webdriverio/node_modules/chimp/dist/bin/chimp.js
// if (argv.deviceName) {
 if (argv.deviceName && !argv.browser) { //browser and deviceName are required to run tests on mobile browsers chrome/safari on iOS/Android   argv.browser = ''; } 

#####  Used version
* Chimp: 0.34.1
* Node.js: v5.8.0
* Operation system: MAC OS X

#####  Console / Log Output
./node_modules/chimp/bin/chimp.js android-chrome-chimp.js --tags @androidchrome

[chimp] Running...
[chimp][helper] setupBrowserAndDDP had error
{ [Error: An unknown server-side error occurred while processing the command. Original error: The desired capabilities must include either an app, package or browser]
  message: 'An unknown server-side error occurred while processing the command. Original error: The desired capabilities must include either an app, package or browser',
  type: 'RuntimeError',
  seleniumStack: 
   { status: 13,
     type: 'UnknownError',
     message: 'An unknown server-side error occurred while processing the command.',
     orgStatusMessage: 'An unknown server-side error occurred while processing the command. Original error: The desired capabilities must include either an app, package or browser',
     screenshot: null } }
Error: An unknown server-side error occurred while processing the command. Original error: The desired capabilities must include either an app, package or browser
    at Object.Future.wait (/Users/Chimp/chimp-webdriverio/node_modules/fibers/future.js:449:15)
    at Object.<anonymous> (/Users/Chimp/chimp-webdriverio/node_modules/wdio-sync/build/index.js:345:27)
    at initBrowser (/Users/Chimp/chimp-webdriverio/node_modules/chimp/dist/lib/chimp-helper.js:125:15)
    at Object.setupBrowserAndDDP (/Users/Chimp/chimp-webdriverio/node_modules/chimp/dist/lib/chimp-helper.js:200:7)
    at /Users/Chimp/chimp-webdriverio/node_modules/chimp/dist/lib/cucumberjs/hooks.js:21:24
    at /Users/Chimp/chimp-webdriverio/node_modules/meteor-promise/fiber_pool.js:33:40
    - - - - -
    at new RuntimeError (/Users/Chimp/chimp-webdriverio/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:115:12)
    at Request._callback (/Users/Chimp/chimp-webdriverio/node_modules/webdriverio/build/lib/utils/RequestHandler.js:246:32)
    at Request.self.callback (/Users/Chimp/chimp-webdriverio/node_modules/webdriverio/node_modules/request/request.js:373:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/Users/Chimp/chimp-webdriverio/node_modules/webdriverio/node_modules/request/request.js:1318:14)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/Users/Chimp/chimp-webdriverio/node_modules/webdriverio/node_modules/request/request.js:1266:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (node.js:377:13)
    at process._tickCallback (node.js:401:11)
Cucumber steps failed

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by Sanjo** [comment]
Your fix looks reasonable to me. Can you please do a pull-request with your fix, thanks.

**Comment by vpappula** [comment]
sure, will do it this weekend. Cheers

**Comment by yann-stepienik-cko** [comment]
@vpappula @samhatoum 

Isn't there an additional problem with that ? 

Mobile tests also require a browserName to be set in the desiredCapabilities to be set, but Chimp erase this value as well to "".

Here is the config that I use :

      "deviceName": "iPhone Simulator",
      browser: 'Safari', 

      webdriverio: {
            logLevel: 'verbose',
            desiredCapabilities: {
                "deviceName": "iPhone Simulator",
                'platformName': 'iOS',
                'platformVersion': '9.3',
                'appiumVersion': '1.5.3',
                "deviceOrientation": "portrait",
                'browserName': 'Safari'
            }
      }

And this is the outcome (with or without the  "browser") : 

    {"desiredCapabilities":    {"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"deviceName":"iPhone Simulator","platformName":"iOS","platformVersion":"9.3","appiumVersion":"1.5.3","deviceOrientation":"portrait","browserName":"","_":"3 more keys: [\"platform\",\"name\",\"requestOrigins\"]"}}

**Comment by vpappula** [comment]
Have you tried something like this?
    browser: 'safari',
    deviceName: 'iPhone 6s',

    //- - -  - Appium connection - - - -
    host: 'localhost',
    port: 4723,

    // - - - - WEBDRIVER-IO  - - - -
    webdriverio: {
        desiredCapabilities: {
            platformVersion: '9.3',
            platformName: 'iOS',
        },
        baseUrl: 'http://google.com',
        logLevel: 'verbose',
    },

**Comment by yann-stepienik-cko** [comment]
Yes I get this, which is the same error : 

     Error: No browserName or app specified in session request.

Having a mandatory browserName is probably due to the fact that I'm using SauceLabs ? But it's only with Appnium That the problem occurs.

**Comment by vpappula** [comment]
I have tested this behaviour using the code base from https://github.com/xolvio/chimp.git almost  couple of months ago and it worked. 
Can you see the fix in chimp-webdriverio/node_modules/chimp/dist/bin/chimp.js
if (argv.deviceName) { // before fix
should be
 if (argv.deviceName && !argv.browser) { // after fix

**Comment by yann-stepienik-cko** [comment]
It's because you're using Appnium manually which Fallback to 'browser' when 'browsername' is undefined (I guess) but SauceLabs force the usage of the correct BrowserName Argument. See those screenshot where I C/P your config (I replaced Iphone 6s by the simulator but I also tried with just Iphone 6s) :

![chimp_js_ __users_yann_dev_checkout-mobile-hub](https://cloud.githubusercontent.com/assets/17568523/17704587/6c877b5e-63cd-11e6-90b1-8f69d7a434ff.png)

![chimp_js_ __users_yann_dev_checkout-mobile-hub 2](https://cloud.githubusercontent.com/assets/17568523/17704589/6ca4b67e-63cd-11e6-8889-462732f3fb2d.png)



Also if I set it manually 
       
       browserName: 'Safari'

Chimp still does overwrite it to ''
