### ISSUE TITLE
No cucumber --fail-fast option in https://github.com/xolvio/chimp/blob/master/src/bin/default.js

### ISSUE THREAD

**Issue by 2hansen** [xolvio/chimp#404]
#####  Expected behaviour

Ability to set fail-fast flag for cucumber-js to stop test immediately after failing step (instead of completing scenario) as described here: https://github.com/cucumber/cucumber-js/blob/master/features/fail_fast.feature

e.g. chimp --fail-fast=true --browser=phantomjs ./featurePath

#####  Actual behaviour

If adding --fail-fast option chimp fails with something like

fs.js:691
  return binding.lstat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/projectPath/tests/true'

##### Steps to reproduce the problem

See above 

#####  Used version

* Chimp: 0.35.0
* Node.js: v0.10.44
* Operation system: Debian

#####  Console / Log Output

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by samhatoum** [comment]
Try putting `./featurePath` before all the other switches

**Comment by 2hansen** [comment]
Thanks for reply.

Unfortunately, if I put the ./featurePath before the the other options I get

fs.js:691
  return binding.lstat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/projectPath/tests/true'

(I.e. the same as in the original case)
