### ISSUE TITLE
Add flag to disable the automatic usage of babel to translate the spec files.

### ISSUE THREAD

**Issue by duclet** [xolvio/chimp#405]
For various reasons, we have our own configurations for Babel and also uses WebPack to do the build. The mocha-wrapper.js file will always register the Babel configurations. Would be nice if we can turn it off.

**Comment by samhatoum** [comment]
Thanks for the request, added to enhancements

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
