### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by legacyWork** [xolvio/chimp#408]
##### Steps to reproduce the problem
```
./node_modules/.bin/chimp --mocha -g "consoleErrors"
Error: ENOENT: no such file or directory, lstat '/Users/myuser/AUTOMATION/AutomationDev/javascript_ui_test/consoleErrors'
```

There is a test suite in my tests:

```
describe('consoleErrors',function() {
...
}
```
It appears that running tests by suite is unsupported in chimp.  This is a very major bug.
#####  Used version

* Chimp: 
* Node.js:
* Operation system: 

#####  Console / Log Output

(Upload long logs to [Gist](https://gist.github.com/) and link it here)

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by samhatoum** [comment]
Can you try `-g="consoleErrors"`

**Comment by legacyWork** [comment]
ReferenceError: describe is not defined

**Comment by samhatoum** [comment]
this is not information for me to help debug. If you create a repo that makes it easy for me to reproduce the error, I can try to help.

**Comment by samhatoum** [comment]
You can use `mochaGrep` as an option in the next version (0.35.0)
