### ISSUE TITLE
Support Screenshots for Mocha and Jasmine

### ISSUE THREAD

**Issue by radixhound** [xolvio/chimp#410]
##### Expected behaviour

On CI I would expect that you can save failure screenshots for Mocha or Jasmine tests so that you can some clue how to debug failures on UI tests.
##### Actual behaviour

Screenshot saving only works for Cucumber. 
Additionally, the [documentation here](https://chimp.readme.io/#section--automatically-takes-screenshots-on-failures-) is misleading since it doesn't support Mocha or Jasmine.
##### Steps to reproduce the problem

I was trying to enable screenshots for Mocha tests and was having no luck then I went looking [in the source repo](https://github.com/xolvio/chimp/blob/1456f7094db261c924e93087d7a32221f6b3ccad/src/bin/chimp.js#L27-L33) and found that it seems to be a Cucumber only feature.

See discussion here: https://github.com/xolvio/automated-testing-best-practices/issues/45

---

_Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others._

**Comment by samhatoum** [comment]
You're right. I've updated the docs and added this as a feature enhancement

**Comment by thebarty** [comment]
Plus one for screenshot-support in mocha 👍

**Comment by luzlab** [comment]
Is this feature merged into the latest version of Chimp (0.47.2)?
