### ISSUE TITLE
chimp grep runs everything

### ISSUE THREAD

**Issue by legacyWork** [xolvio/chimp#412]
#####  Expected behaviour
 ./node_modules/.bin/chimp --mocha  --grep whatthefawefawefeack

or

 ./node_modules/.bin/chimp --mocha  --g whatthefawefawefeack
 should not run anything

#####  Actual behaviour
 ./node_modules/.bin/chimp --mocha  --grep whatthefawefawefeack

all tests tests start running

##### Steps to reproduce the problem

(Preferably a repository and easy reproduction steps)

#####  Used version

* Chimp: 
* Node.js:
* Operation system: 

#####  Console / Log Output

(Upload long logs to [Gist](https://gist.github.com/) and link it here)

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by samhatoum** [comment]
You can use `mochaGrep` as an option in the next version (0.35.0)

**Comment by legacyWork** [comment]
"chimp": "^0.35.0",  is in my node_modules

I npm installed, ran 

./node_modules/.bin/chimp --mocha --mochaGrep "foewijfweoifjw"

And all the tests are still running.

**Comment by legacyWork** [comment]
It might be a testrunner issue.  Don't reopen yet

**Comment by legacyWork** [comment]
I noticed the test that is running has this:

describe('Asr Links To Ecom @watch ' , function() {

Do annotations do anything with mochaGrep option?

**Comment by legacyWork** [comment]
It appears it's still an issue

describe('App Pool test cases ', function() {

is in AppPoolTestRunner.js file and this test is running.

**Comment by samhatoum** [comment]
try `./node_modules/.bin/chimp --mocha --mochaGrep="foewijfweoifjw"`

**Comment by legacyWork** [comment]
./node_modules/.bin/chimp --mocha --mochaGrep="bfawefaewfawfawefawefaew"

[chimp] Running...
Test output follows

I don't think it is doing what it should be doing.
