### ISSUE TITLE
How to request http header using chimp

### ISSUE THREAD

**Issue by dxdeidara** [xolvio/chimp#419]
Hi guys, I am really new to chimp. I am trying to request http header using chimp in my projects. I noticed that Selenium and webdriverIO doesn't have this feature. Is there a way to do this in chimp? 

Thank you!

#####  Used version

* Chimp: 0.9.4
* Node.js: 4.4.7
* Operation system: OS X El Capitan

#####  Console / Log Output

(Upload long logs to [Gist](https://gist.github.com/) and link it here)

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by dxdeidara** [comment]
I figured it out by using request module in the npm.

**Comment by samhatoum** [comment]
that's the best way, yes :)
