### ISSUE TITLE
Error on Node 6.x when running a fresh install of Chimp

### ISSUE THREAD

**Issue by tomitrescak** [xolvio/chimp#426]
#####  Expected behaviour

Chimp starts normally with node 6.x

[EDIT] Found out that it works on node 4.x

#####  Actual behaviour

Massive error in the console

##### Steps to reproduce the problem

mkdir chimp-tutorial
cd chimp-tutorial
npm install chimp
mkdir features
./nodme_modules/.bin/chimp --watch

#####  Used version

* Chimp: Latest
* Node.js: 6.2.1
* Operation system: Mac 

#####  Console / Log Output

[https://gist.github.com/tomitrescak/4ab5567bb6c07aa98a47e4f679fe3a5d](https://gist.github.com/tomitrescak/4ab5567bb6c07aa98a47e4f679fe3a5d)

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by duclet** [comment]
Does this still happen on master? I actually upgraded chokidar to version 1.6.0 on my version and it seems to fix this issue. Master currently is using 1.5 and I haven't checked that.

**Comment by lgandecki** [comment]
@tomitrescak could you please verify the chimp version you are using? We've recently fixd both this error output and chimp not starting in node 6

**Comment by samhatoum** [comment]
let us know if you need this reopened @tomitrescak
