### ISSUE TITLE
No mocha tests run when not --watch

### ISSUE THREAD

**Issue by damonmaria** [xolvio/chimp#430]
Chimp is working fine with `--watch`. But when not watching no tests are run. I am using mocha as the test runner. 

Is there anyway to debug the finding of tests that chimp does? 

#####  Expected behaviour

Chimp finds and runs all tests in the path specified. 

#####  Actual behaviour

`0 passing` (no tests are run)

##### Steps to reproduce the problem

For me it works fine when I `--watch` a test with `@focus`. But when I try and run all tests (by not passing --watch) then Chimp doesn't find/run any tests. 

#####  Used version

* Chimp: 0.39.0
* Node.js: 4.4.7 and 6.3.0 (I've tried both)
* Operation system: Mac OS X 10.11.5

#####  Console / Log Output

```
[chimp] Running...


  0 passing (2ms)
```

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by duclet** [comment]
This issue here seems to be because `mochaGrep` is a nullable string value but it isn't checked as such in `mocha-wrapper.js`.

**Comment by duclet** [comment]
I've added a pull request for the fix.
