### ISSUE TITLE
Open file in new browser tab with phantomjs

### ISSUE THREAD

**Issue by markusschlebusch** [xolvio/chimp#438]
On our webpage we have a link which opens a PDF file in a new browser tab. After a click on this link we are able to access this new tab with client.switchTab(client.getTabIds()[1]); on Firefox and Chrome to get the correct file URL (via client.getUrl()).
With phantomjs the URL of the new tab is "about:blank" and the file is not opened in the new tab.

Are there any ideas why this happens?

#####  Used version

* Chimp: 0.35.0
* Node.js: 4.4.7
* Operation system: Ubuntu 14.04 / Windows 7
* phantomjs 1.9.8 and 2.1.1

**Comment by samhatoum** [comment]
Sorry not really sure and generally we don't support these sorts of issues. Try the Webdriver.io gitter channel 👍
