### ISSUE TITLE
Interactive debugging of scenarios

### ISSUE THREAD

**Issue by intron** [xolvio/chimp#45]
Would be really nice to be able to step through the tests and have the DOM available for inspection, as it can be difficult to predict the state of a page as it loads and executes its many scripts.

**Comment by Sanjo** [comment]
Available in 0.12.3 (just released).
__Documentation:__ http://chimp.readme.io/v1.0/docs/debugging

**Comment by Sanjo** [comment]
I forgot something :D Will release 0.12.4 now.

**Comment by Sanjo** [comment]
Now it works in 0.12.4.
