### ISSUE TITLE
waitForVisible works but then click complains element isn't visible

### ISSUE THREAD

**Issue by abcd-ca** [xolvio/chimp#451]
#####  Expected behaviour
Should be able to call waitForVisible for an element then click it

#####  Actual behaviour
complains element isn't visible

#####  Used version

* Meteor 1.3.3
* Chimp
* Chrome

http://stackoverflow.com/questions/39049267/cant-click-an-ion-side-menu-button-in-chimp-acceptance-test

**Comment by abcd-ca** [comment]
I answered my own question on the SO post above – I think Ionic Framework is probably to blame for the duplication but some better errors from chimp/webdriverio (not clear on the separation) would have saved some trouble. I think it's worth a read to see what I had to do and why.

Good job and thanks for making Chimp, aside from this it's working super well and I'm excited to move ahead!

**Comment by samhatoum** [comment]
fantastic, thanks for reporting back @abcd-ca 

It's a webdriver thing btw. Chimp is really the thing that make all the different tools "hang" together
