### ISSUE TITLE
"Error: Couldn't connect to selenium server" halfway through test run when testing with phantomjs

### ISSUE THREAD

**Issue by abecks** [xolvio/chimp#454]
#####  Expected behaviour
Tests should continue to run until all tests have passed or failed.

#####  Actual behaviour
Some of my tests run successfully, then suddenly they will all start to fail with the error:
``
Error: Couldn't connect to selenium server
``

##### Steps to reproduce the problem
I am unable to put my whole application's code online, but I will try to drill down and reproduce. 

Edit: This only occurs when testing with phantomjs, using the following syntax:
`chimp --ddp=http://localhost:3000 --cucumber --path=tests/cucumber --chai --browser=phantomjs`

Using `chimp --ddp=http://localhost:3000 --cucumber --path=tests/cucumber --chai --browser=chrome` works fine.

#####  Used version

* Chimp: 0.40.0
* Node.js: 4.5.0
* Operation system: OS X 10.11.3

#####  Console / Log Output

```
2) Scenario: Clients can edit pathways for their company - tests/cucumber/features/pathways.feature:54
   Step: Before
   Step Definition: hooks.js:3
   Message:
     Error: Couldn't connect to selenium server
         at World.beforeScenario (hooks.js:10:13)
         - - - - -
         at emitOne (events.js:77:13)
         at Request.emit (events.js:169:7)
         at emitOne (events.js:77:13)
         at ClientRequest.emit (events.js:169:7)
         at Socket.socketErrorListener (_http_client.js:269:9)
         at emitOne (events.js:77:13)
         at Socket.emit (events.js:169:7)
         at emitErrorNT (net.js:1269:8)
         at nextTickCallbackWith2Args (node.js:442:9)
         at process._tickCallback (node.js:356:17)
```

`hooks.js` contains:

```js
/* globals browser server */
module.exports = function () {
  this.Before(function beforeScenario(scenario) {
    server.call('resetDatabase');
    server.call('createAdminUser');
    server.call('createTestUser');
    server.call('captureEmailOutput');
    server.call('captureHTTPPosts');
    driver.timeouts('script', 10000);
    browser.url(process.env.ROOT_URL);
    browser.waitForExist('#__blaze-root', 5000);
    browser.pause(250);
  });
};
```

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by samhatoum** [comment]
Are you connecting to a local selenium or remote?

**Comment by samhatoum** [comment]
ah, you updated the title to say "phantom". So my guess is your phantom is dying due to an overly complex app or similar :)

**Comment by abecks** [comment]
Local selenium, as I just saw it download selenium-standalone when I updated to 0.40.0. Would it be a JS error halting phantomjs? Is there anyway to enable debugging so I could tell?

**Comment by abecks** [comment]
Interesting, forcing chimp to use phantomjs 2.1.1 vs the 2.0.0 that it downloads seems to work. Overriding with `--phantom_path`. Must be halting on 2.0.0 for some reason. Sorry for taking up your time. Loving chimp btw!

**Comment by samhatoum** [comment]
awesome! Maybe we'll upgrade phantom then.

Out of interest, what are you using it with?

**Comment by abecks** [comment]
I am using it to do Cucumber based end-to-end tests for a fairly complex Meteor 1.4.1 application. Do you know of any way I could enable debugging for phantomjs? Would that be done via Chimp or do I need to compile a debug binary of phantom?

**Comment by samhatoum** [comment]
you can either do:

`chimp --debug`

or you can start phantom in debug mode separately, and tell chimp to connect to that selenium server using --host and --port
