### ISSUE TITLE
Chimp does not work on TravisCi with Node6

### ISSUE THREAD

**Issue by MoeSattler** [xolvio/chimp#457]
It works fine locally with Node6 and on travis with Node4.

On Node6, Chimp throws on Travis:

```
/home/travis/build/travelperk/traveldesk/node_modules/fibers/fibers.js:16
	throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibers`?');
```

I use chimp@^0.40.4

**Comment by samhatoum** [comment]
This issue was caused due to the latest version of node (6.5) did not have a version of fibers that supports it yet. Downgrading to node 6.4 solved it

**Comment by danielbayerlein** [comment]
@samhatoum See https://github.com/laverdet/node-fibers/issues/306 or https://github.com/laverdet/node-fibers/issues/304 - v1.0.14 support Node v6.5.0
