### ISSUE TITLE
Selenium processes hanging around in OSX 10.9.5

### ISSUE THREAD

**Issue by intron** [xolvio/chimp#46]
If Chimp exits a few times with

> [chimp] Finished running async processes with errors

`ps ax | grep java` yields this sort of thing:

> 2128 s000  S      0:02.27 /Users/myuser/tools/java -jar /Users/myuser/.npm-packages/lib/node_modules/chimp/node_modules/selenium-standalone/.selenium/selenium-server/2.46.0-server.jar -Dwebdriver.chrome.driver=/Users/myuser/.npm-packages/lib/node_modules/chimp/node_modules/selenium-standalone/.selenium/chromedriver/2.16-x64-chromedriver -port 49850
> 3116 s000  S      0:01.99 /Users/myuser/tools/java -jar /Users/myuser/.npm-packages/lib/node_modules/chimp/node_modules/selenium-standalone/.selenium/selenium-server/2.46.0-server.jar -Dwebdriver.chrome.driver=/Users/myuser/.npm-packages/lib/node_modules/chimp/node_modules/selenium-standalone/.selenium/chromedriver/2.16-x64-chromedriver -port 50325
> 4381 s000  S      0:04.11 /Users/myuser/tools/java -jar /Users/myuser/.npm-packages/lib/node_modules/chimp/node_modules/selenium-standalone/.selenium/selenium-server/2.46.0-server.jar -Dwebdriver.chrome.driver=/Users/myuser/.npm-packages/lib/node_modules/chimp/node_modules/selenium-standalone/.selenium/chromedriver/2.16-x64-chromedriver -port 50969
> 4744 s000  S      0:02.82 /Users/myuser/tools/java -jar /Users/myuser/.npm-packages/lib/node_modules/chimp/node_modules/selenium-standalone/.selenium/selenium-server/2.46.0-server.jar -Dwebdriver.chrome.driver=/Users/myuser/.npm-packages/lib/node_modules/chimp/node_modules/selenium-standalone/.selenium/chromedriver/2.16-x64-chromedriver -port 51160

The processes don't seem to hang around if Chimp is stopped before it hits the error

**Comment by samhatoum** [comment]
should be fixed in recent versions, let me know if not
