### ISSUE TITLE
Possible to use with Cloud IDE?

### ISSUE THREAD

**Issue by maxfi** [xolvio/chimp#472]
Is it possible to run chimp on a remote machine, like [Cloud9](http://c9.io/), and have the tests run in a local browser? If so, could someone point me in the right direction about how I might be able to set this up? Thanks!

---

#####  Expected behaviour

Run `chimp --watch` on a remote machine and watch the test run in a local browser.

#####  Actual behaviour

`Error: unknown error: cannot find Chrome binary`. Makes sense, there isn't one...

##### Steps to reproduce the problem

Run `chimp --watch` on a cloud server without a desktop environment.

#####  Used version

* Chimp: 0.40.7
* Node.js: v4.5.0
* Operation system: Ubuntu 14.04.3 LTS

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by samhatoum** [comment]
So your app code is running remotely. The test code is also running remotely. You want to use a browser on your machine. The answer is yes it's possible :)

You need to run selenium on your local machine, open a tunnel to localhost using something like [ngrok](https://ngrok.com/), then tell chimp to connect to the tunnel to your localhost using `--host`

**Comment by maxfi** [comment]
Nice one! Thanks @samhatoum!

If it helps anyone else, below is the setup that I'm now using.

### Network overview:

```
[Cloud9 workspace] --- ssh local forward --- [intermediary ssh server] --- ssh reverse forward --- [local machine]
```

### Setup:

1. Install the [selenium-standalone npm package](https://www.npmjs.com/package/selenium-standalone) on your local machine (where you want the selenium tests to execute):

	```shell
	npm install selenium-standalone@latest -g
	selenium-standalone install
	```

2. Start the selenium server on the local machine:

	```sh
	selenium-standalone start
	```

3. Setup up a local ssh forward from your remote dev machine (in my case this is a Cloud9 workspace) to an intermediary ssh server:

	```
	ssh -L 4444:localhost:4444 SOME_INTERMEDIARY_SERVER
	```

	**Note**: Obviously you'll need to setup ssh keys, etc.

4. Setup up a reverse ssh tunnel from your local machine to the intermediary server:

	```
	ssh -R 4444:localhost:4444 SOME_INTERMEDIARY_SERVER
	```

5. Start chimp with some extra arguments on your remote dev machine:

	```
	chimp --watch --host=localhost --port=4444
	```
6. Run some tests! 😀
