### ISSUE TITLE
[chimp --watch] Upon changing code, Meteor crashes if Chimp mirror is running

### ISSUE THREAD

**Issue by wizonesolutions** [xolvio/chimp#473]
Is there any good way to run a Meteor mirror that does not crash upon hot code reload and works consistently? I found a gist for this somewhere, but the script didn't always work quite right, which was frustrating...

Ideally I would be able to re-run tests whenever code changed and without the two Meteors fighting over the `.meteor` directory.

**Comment by samhatoum** [comment]
YEs, you can use the `fullapp` test mode
https://guide.meteor.com/testing.html#running-full-app-tests

**Comment by wizonesolutions** [comment]
Would that not involve Chimp at all? I was uncertain how to use Cucumber
like that.

22. sep. 2016 02:47 je oseba "Sam Hatoum" <notifications@github.com>
napisala:

**Comment by samhatoum** [comment]
Chimp is not at fault, it's that when you don't use the `fullapp` mode, the two meteor apps will compete for the `.meteor` directory.

The `fullapp` mode uses the same codebase but outputs to a different directory, which is exactly what you're wanting to do. Chimp can then just point at the second app

**Comment by wizonesolutions** [comment]
Ah alright. Sounds like a mirror script could use that then. Thanks Sam!

22. sep. 2016 20:28 je oseba "Sam Hatoum" <notifications@github.com>
napisala:

Chimp is not at fault, it's that when you don't use the fullapp mode, the
two meteor apps will compete for the .meteor directory.

The fullapp mode uses the same codebase but outputs to a different
directory, which is exactly what you're wanting to do. Chimp can then just
point at the second app

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/xolvio/chimp/issues/473#issuecomment-248987386>, or mute
the thread
