### ISSUE TITLE
Issues with selenium-standalone + chromedriver 2.24 + OSX

### ISSUE THREAD

**Issue by billyvg** [xolvio/chimp#474]
So the issue is with `selenium-standalone`, specifically this https://github.com/vvo/selenium-standalone/issues/220

On OSX with chromedriver 2.24, it tries to download using the wrong URL. chromedriver < 2.24 doesn't seem to work with chrome 54. What are some alternatives short of upgrading `selenium-standalone` dependency in `chimp`?

#####  Used version

* Chimp: 0.40.7
* Node.js: 5, 6
* Operation system: OSX El Capitan

#####  Console / Log Output

(Upload long logs to [Gist](https://gist.github.com/) and link it here)

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by samhatoum** [comment]
You can set the download URL here:
https://github.com/xolvio/chimp/blob/master/src/bin/default.js#L76

**Comment by billyvg** [comment]
The problem is not the baseURL - it's that `selenium-standalone` will try to download the 32bit version of chromedriver, but for chromedriver >= 2.23, it only has 64 bit version (`chromedriver_mac64.zip`).

**Comment by samhatoum** [comment]
Can you please try 0.41.1 - I just upgraded to the latest `selenium-standlone`

**Comment by billyvg** [comment]
0.41.1 works, thanks!
