### ISSUE TITLE
How to run chimp tests in a single command for CI?

### ISSUE THREAD

**Issue by yogiben** [xolvio/chimp#485]
I'm using Codeship for CI.

After setting up meteor, I must run it so that it installs the packages and start serving on `localhost:3000`.

After it's available, I need to run chimp.

The problem is the timing. the `meteor` command runs forever and the subsequent tasks are not executed.

### Current solution
```
meteor --settings settings.json &
sleep 100
chimp --path=tests --ddp=http://localhost:3000 --chrome
```

Is there a better solution that doesn't involve using sleep?

**Comment by fermuch** [comment]
This is what I'm doing right now, but it's a little bit hacky:

```sh
#!/bin/sh
trap 'kill $(jobs -p)' EXIT
meteor --settings settings.json &
while ! curl 127.0.0.1:3000 > /dev/null 2>&1; do sleep 3; done
chimp --path=tests --ddp=http://localhost:3000 --chrome
```

* The trap is so I can cancel the script in my local machine and it kills the background meteor process.
* the `while` waits until meteor answers. This way, we can wait until meteor is ready.

**Comment by schmidsi** [comment]
I created a script, which starts two processes: One with the Meteor server and one with the tests, and merges them together, so that after the tests are run, the Meteor server will be killed also:

```javascript
// Inspired from: https://github.com/xolvio/qualityfaster/blob/master/.scripts/
import { exec } from 'child_process';

const meteorCommand = process.argv[2];
const chimpCommand = process.argv[3];

const meteorProcess = exec(meteorCommand); // 'npm start'

meteorProcess.stdout.pipe(process.stdout);
meteorProcess.stderr.pipe(process.stderr);

// Wait until Meteor is started and the start the chimp tests
meteorProcess.stdout.on('data', (data) => {
  if (data.toString().match('App running at')) {
    const chimpProcess = exec(chimpCommand); // 'npm run test:chimp:phantomjs'

    chimpProcess.stdout.pipe(process.stdout);
    chimpProcess.stderr.pipe(process.stderr);

    chimpProcess.on('close', (code) => {
      console.log(`Chimp exited with code ${code}`);
      meteorProcess.kill();
      process.exit(code);
    });
  }
});
```

This file is in the `.scripts/` directory and then I have the following commands in `package.json`:

```
"start": "meteor run --settings secrets.json",
"test:chimp:standalone": "babel-node .scripts/subprocess.js 'npm start' 'npm run test:chimp:phantomjs'",
"test:chimp:phantomjs": "chimp --mocha --ddp=http://localhost:3000 --path=tests --browser=phantomjs",
```

Hope that helps.

**Comment by samhatoum** [comment]
@schmidsi's solution is what I recommend

**Comment by pvmeijel** [comment]
@schmidsi, thanks for your script. When we ran about 260 Cucumber scenarios, Chimp exited unexpectedly. It turned out that Chimp exceeded the maximum buffer. The solution was to increase the maximum buffer:
`const chimpProcess = exec(chimpCommand, {maxBuffer: 20480000});`
