### ISSUE TITLE
webdriver execute() fails due to babel require hook

### ISSUE THREAD

**Issue by acthp** [xolvio/chimp#489]
It's a bit hard to tell, but it looks to me like chimp is loading babel-register, which invokes babel on all the test modules. I can tell that the test modules are being transpiled by calling toString() on a function in a test module that has babel language features: the string has babel symbols embedded in it.

This becomes a problem when calling execute(), because the function is sent to the browser for evaluation, and the babel symbols are undefined in that context.

In the example below, chrome already has Object.keys(), so it should work, but it fails because Object.keys has been rewritten to a babel function which is undefined in the browser.

Fixes might be 1) inject the babel functions in the browser context that injects the execute() function, or 2) some way to prevent babel from transforming the argument to execute().
##### Expected behaviour

webdriver execute() runs js in the browser.
##### Actual behaviour

Errors thrown in browser due to undefined babel symbols.
##### Steps to reproduce the problem

Something like

browser.execute(function () { return Object.keys({foo: 'bar'}); })
##### Used version
- Chimp: 0.41.1
- Node.js: 4.0.0
- Operation system: linux / osx
##### Console / Log Output

(Upload long logs to [Gist](https://gist.github.com/) and link it here)

---

_Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others._

**Comment by Sanjo** [comment]
The babel transform-runtime plugin needs to be removed and babel-polyfill required instead. See https://babeljs.io/docs/usage/polyfill/.
