### ISSUE TITLE
need way to configure mocha

### ISSUE THREAD

**Issue by acthp** [xolvio/chimp#491]
##### Expected behaviour

mocha is configurable via mocha.opts, or chimp config.
##### Actual behaviour

The mocha wrapper ignores mocha.opts, and chimp config supports only a small subset of mocha options.
##### Steps to reproduce the problem

(Preferably a repository and easy reproduction steps)
##### Used version
- Chimp: 0.41.1
- Node.js: 4.0.0
- Operation system: linux
##### Console / Log Output

(Upload long logs to [Gist](https://gist.github.com/) and link it here)

---

_Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others._

**Comment by Sanjo** [comment]
For Jasmine there is the [jasmineConfig](https://github.com/xolvio/chimp/search?utf8=%E2%9C%93&q=jasmineConfig) option. We can do the same for Mocha with a mochaConfig option.

**Comment by lnmunhoz** [comment]
I need to pass `--delay` to mocha.

+1 for mocha config.

**Comment by thebarty** [comment]
+1 one - this is related to https://github.com/xolvio/chimp/issues/382.

I'd love to pass ``--full-trace``

**Comment by samhatoum** [comment]
check it out:
https://github.com/xolvio/chimp/blob/master/src/bin/default.js#L100
