### ISSUE TITLE
How to test Meteor with production flag?

### ISSUE THREAD

**Issue by yogiben** [xolvio/chimp#494]
Often bugs will show up when you run with `--production`.

However,  many of the example packages (for good reason) have `debugOnly: true`.

Is there a recommended way to run Chimp on a Meteor application running in production?

**Comment by samhatoum** [comment]
It should work all the same, just use Chimp against a running Meteor instance. Chimp does not care what mode Meteor is in

**Comment by yogiben** [comment]
Ideally, I want to avoid all fixture and database code being built along with production deploys.

This is why `debugOnly: true` seems like a good practise.

Is there a recommended way to do this or is the only option to remove the `debugOnly: true` in your fixtures package?

**Comment by samhatoum** [comment]
I see. debugOnly is a good option but not the only one.

Another option would be to have the build test automation remove the debugOnly flag at build time. That way you can control when it's enabled.

Yet another option would be to have a separate app running that's pointing at the same database that hosts your fixtures.

Choose the right one for you :)
