### ISSUE TITLE
Unable to Initialize Browsers on Codeship Docker Infrastructure

### ISSUE THREAD

**Issue by jermspeaks** [xolvio/chimp#495]
#####  Expected behaviour

Running Chimp on Codeship with the Docker infrastructure should hook browsers automatically.

#####  Actual behaviour

Session-manager unable to sync webdriver with chrome browser

##### Steps to reproduce the problem

- Build app with Docker container on Codeship
- I use a script taken from [this comment](https://github.com/xolvio/chimp/issues/485#issuecomment-252580543) that runs my test cases while starting the app process that has been built on Codeship
  - Run tests with `chimp --browser=chrome`

#####  Used version

* Chimp: 0.41.1
* Node.js: 4.5.0 (docker node:4.5-onbuild)
* Operation system: Ubuntu 14.04.5 (docker ubuntu:trusty)
* Chrome: version: 54.0.2840.59-1 / Chrome driver version 2.19
* Java version: jdk1.8.0_74

#####  Console / Log Output

Link to [gist log file](https://gist.github.com/jermspeaks/0da0c8f3b2f2d69c619ef3a247f40e09)

I submitted this to the Slack channel as well 😄

**Comment by samhatoum** [comment]
Which version of Java is installed on the container? Which version of Chrome?

**Comment by samhatoum** [comment]
You can also try to add the `seleniumDebug` option to get a deeper look

**Comment by jermspeaks** [comment]
Initially forgotten to add chrome to the Dockerfile. I added the selenium debug tag. Updated my gist linked in the OP. Also added chrome and Java version.

**Comment by jermspeaks** [comment]
Going to close this issue. Seems to be something wrong with the chrome driver on our version on linux.

Temporary solution: using phantomjs instead, which works for us.
