### ISSUE TITLE
chrome driver 2.22 not working with chrome 54

### ISSUE THREAD

**Issue by maximchouinard** [xolvio/chimp#500]
Hi,

when trying to start acceptance test, chrome fail with the following error
```
Error: session not created exception
'session not created exception\nfrom unknown error: Runtime.executionContextCreated has invalid \'context\'
```

chrome=54.0.2840.59
chromedriver=2.22.397929

Need to increase chrome driver to 2.24

Thanks

**Comment by maximchouinard** [comment]
https://github.com/xolvio/chimp/pull/501
https://circleci.com/gh/xolvio/chimp/427

**Comment by maximchouinard** [comment]
it would be useful for local testing to have a release for that.

Thanks

**Comment by samhatoum** [comment]
will do shortly

**Comment by bjarketrux** [comment]
We added
```
    seleniumStandaloneOptions: {
        drivers: {
            chrome: {
                version: "2.24"
            }
        }
    }
```

to our chimp-config.js and it works.

**Comment by samhatoum** [comment]
Done, thanks!
