### ISSUE TITLE
Unable to use correct ChromeDriver version OS X

### ISSUE THREAD

**Issue by abecks** [xolvio/chimp#512]
Chrome Version:  54.0.2840.71
Chimp version: 0.40.7

After updating my Chrome, I can no longer run Chimp. I receive the same error as seen in #500.

I tried to put

```
  seleniumStandaloneOptions: {
    drivers: {
      chrome: {
        version: "2.24",
        arch: process.arch
      }
    }
  }
```

into my Chimp config, but I receive the error:

```
[chimp] Running...
[selenium] [Error: Could not request headers from https://chromedriver.storage.googleapis.com/2.24/chromedriver_mac32.zip: ]
[Error: Could not request headers from https://chromedriver.storage.googleapis.com/2.24/chromedriver_mac32.zip: ]
```

It seems like it's trying to download the 32 bit driver, which does not exist. What value of `arch` would cause it to download the right driver? I can't find any documentation on those configs. I've tried values of `process.arch`, `x86_64`, `x64`, `64`, etc. 

Any ideas would be greatly appreciated.

**Comment by kyleian** [comment]
Don't think they released the chromedriver 2.24 with an x32 distributable  ([http://chromedriver.storage.googleapis.com/index.html?path=2.24/]). Try updating your getChromeDriverPlatform() function in your `selenium-standalone/lib/compute.download-urls.js` and see where that gets you?

**Comment by abecks** [comment]
Why is it looking for the x32 in the first place?

**Comment by kyleian** [comment]
I suspect it's something to do with `selenium-standalone/lib/install.js` pulling in the data from your `selenium-standalone/lib/default-config.js` in the following:

`if (!opts.version) {
    opts.version = defaultConfig.version;
  }

  if (opts.drivers) {
    // Merge in missing driver options for those specified
    opts.drivers = mapValues(opts.drivers, function(config, name) {
      return merge({}, defaultConfig.drivers[name], config);
    });
  } else {
    opts.drivers = defaultConfig.drivers;
  }`

Here's what I have as my seleniumStandaloneOptions which I believe is out of the box with chimp 0.41.2 containing the chromedriver update, if you're flexible to update your version (released as a result of the other bug you linked). Elsewise I'd try using the below in chimp as well as updating your `selenium-standalone/lib/default-config.js` versioning to 2.24 / hardcode your compute-download-urls.js to only use x64 in those strings.
https://gist.github.com/kyleian/17975ee07b5f0912c57223f01ad0f2c2

**Comment by lgandecki** [comment]
working on this! We've learned that it's not chimp version related - a few different chimp versions started doing that in the last few days. 
Seems like the newest chrome might be causing an issue like that. Will let you know when we find out more.

**Comment by lgandecki** [comment]
@abecks are you able to upgrade to the newest chimp version and try again?

**Comment by samhatoum** [comment]
release in 0.45.1
