### ISSUE TITLE
Fresh install breaks. Babel complains about Unknown option: base.Children

### ISSUE THREAD

**Issue by gCardinal** [xolvio/chimp#514]
#####  Expected behaviour
Running `node_modules/.bin/chimp --mocha --path ./tests/Acceptance`, Chimp should run my tests

#####  Actual behaviour
Chimp breaks, with Babel complaining that `base.Children` is not an option. [Full output here](https://gist.github.com/gCardinal/abe4401de8b5190964518ff49e0b3645).

##### Exact steps to reproduce / repository that demonstrates the problem
Can't provide a repository (project is closed source and under NDA), but I have this [package.json](https://gist.github.com/gCardinal/dc57508eded182f298547285b5aa8972) file. With this, once everything is installed by npm version 3.3.6 under node 5.0.0, chimp will produce the above error.

#####  Version & tools:

* Chimp command line used: node_modules/.bin/chimp --mocha --path ./tests/Acceptance
* Chimp config file: None
* Chimp: 0.41.2
* Node.js: 5.0.0
* Java: 1.7.0_111
* Operation system: 143-Ubuntu SMP Mon Aug 29 20:15:20 UTC 2016

#####  Console / Log Output

[Console output](https://gist.github.com/gCardinal/abe4401de8b5190964518ff49e0b3645)

* * *

I imagine there's a simple problem I'm not seeing, but I'm really scratching my head with this. I don't really have a complex configuration, I just run simple test written in ES6. For reference, the test mentioned in the output looks like this: 

```
import chai from 'chai'

let expect = chai.expect

describe('The application', () => {
    beforeEach(() => {
        browser.url('localhost:3000')
    })

    it('should be loaded', () => {
        let rootTag = browser.getHTML('#root', false)
        expect(rootTag).to.not.be.empty
    })
})
```

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by lgandecki** [comment]
Do you have a .babelrc file in your project?

**Comment by lgandecki** [comment]
@gCardinal Ping. :-) 
Hey there! Without looking at your babelrc file it might be impossible to help.

**Comment by gCardinal** [comment]
Oh, sorry I was never notified of your answer.

As it turns out, I do have a `.babelrc` file (which I didn't realize, since I'm using TypeScript and not Babel). I have deleted it and now Chimp works without a itch.

I'm not too sure how Babel works, but I'm not sure I understand how a file at the root of my project could affect how a node module behaves. Either way, I guess it's fixed now, so I'll close this.

Maybe there should be a "Did you check this" section in the doc to help with problems like this?
