### ISSUE TITLE
Error: unknown error: cannot determine loading status bubbled up from Chromedriver 2.24

### ISSUE THREAD

**Issue by kyleian** [xolvio/chimp#516]
Filing an issue in case others experience this / to track for a future chimp build with driver increase - Chromedriver 2.24 is bubbling up the following error through webdriver.io in situations where (in my case) when clicking an element on a page using wdio's `elementIdClick()` method, although the element being clicked is valid and is actually clicked (can see this on the page), it seems to become lost to Chromedriver and kills the test suite / any successive scenario. 

```
{ [Error: unknown error: cannot determine loading status
from unknown error: missing or invalid arg value]
  message: 'unknown error: cannot determine loading status
from unknown error: missing or invalid arg value',
  type: 'RuntimeError',
  seleniumStack: 
   { status: 13,
     type: 'UnknownError',
     message: 'An unknown server-side error occurred while processing the command.',
     orgStatusMessage: 'unknown error: cannot determine loading status
from unknown error: missing or invalid arg value
}
```

Increasing Chromedriver 2.25 resolves this issue on my end.

**Comment by lgandecki** [comment]
Interesting. Did you see this problem on every run, or was it happening "randomly"?

**Comment by kyleian** [comment]
The problem occurred on every run when interacting(tried clicking/keys/input methods) with an element that had two classes belonging to it; one class elements were clicked and steps progressed fine --this is the only difference I can tell between the success/fail; both interactions are performed by line 28 of this gist: https://gist.github.com/kyleian/cfb6c66351e54d5a7225121c8cc4e99e

It looks to be captured with some more context by [chromedriver bug 1547](https://bugs.chromium.org/p/chromedriver/issues/detail?id=1547) - in my case each successive scenario being run in the suite after receiving the `cannot determine loading status` error dies with the `Error communicating with the remote browser. It may have died."` error during any wdio method use.

**Comment by samhatoum** [comment]
will be in next release

**Comment by Napster158** [comment]
I can still see this issue with Chromedriver 2.25.

WebDriverException: Message: unknown error: cannot determine loading status
from unknown error: missing or invalid 'entry.level'
  (Session info: chrome=63.0.3239.84)
  (Driver info: chromedriver=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed),platform=Windows NT 10.0.14393 x86_64)

**Comment by burylov-artem** [comment]
help please

org.openqa.selenium.WebDriverException: unknown error: cannot determine loading status
from unknown error: missing or invalid 'entry.level'
  (Session info: chrome=63.0.3239.84)
  (Driver info: chromedriver=2.28.455520 (cc17746adff54984afff480136733114c6b3704b),platform=Windows NT 10.0.14393 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.56 seconds
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'ProgrP01', ip: '192.168.58.103', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
selenide.url: http://192.168.58.198:8081
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.28.455520 (cc17746adff54984afff480136733114c6b3704b), userDataDir=C:\Users\admin\AppData\Local\Temp\scoped_dir9776_6496}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=63.0.3239.84, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
selenide.baseUrl: http://localhost:8080
Session ID: e3c472312dedc762e8f5cd2ada347649

**Comment by burylov-artem** [comment]
обновите chromedriver.exe

**Comment by kyleian** [comment]
[Looks like the master branch of chimp is on 2.28 at the moment](https://github.com/xolvio/chimp/blob/master/src/bin/default.js#L76) which is pretty out of date, and chromedriver is now up to [2.34](https://chromedriver.storage.googleapis.com/index.html?path=2.34/).

Advising y'all to bump up your local deployments to 2.34 from your 2.25 and 2.29 runs since they both have their own swath of issues with newer chrome versions and see if you still run into this.

**Comment by ashu05may** [comment]
I am getting below error - 

WebDriverException: Message: unknown error: cannot determine loading status
from unknown error: missing or invalid 'entry.level'
(Session info: chrome=63.0.3239.111)
(Driver info: chromedriver=2.28.455520
I am running scripts in my android mobile browser, how chrome driver is required for the same

**Comment by prabhakaranautomation** [comment]
I am getting same error 
org.openqa.selenium.WebDriverException: unknown error: cannot determine loading status
from unknown error: missing or invalid 'entry.level'
  (Session info: chrome=63.0.3239.84)
  (Driver info: chromedriver=2.29.461591

**Comment by dips1995** [comment]
I am getting same error 
org.openqa.selenium.WebDriverException: unknown error: cannot determine loading status
from unknown error: missing or invalid 'entry.level'
(Session info: chrome=63.0.3239.84)
 (Driver info: chromedriver=2.27.440175
 sometime it is working fine and without change in code it shows this error.

**Comment by samhatoum** [comment]
I've updated all the drivers and the original issue has been fixed. 

@dips1995 and @prabhakaranautomation @ashu05may can you please post a new issue with the bug report template filled out properly? this looks like a different issue.

many thanks

**Comment by Stefan2142** [comment]
Nope, still happening:
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status
from unknown error: missing or invalid 'entry.level'
  (Session info: chrome=63.0.3239.132)
  (Driver info: chromedriver=2.28.455520

**Comment by samhatoum** [comment]
can you please post a new issue with the bug report template filled out properly? this looks like a different issue.

**Comment by Jie317** [comment]
Updating the chromedriver to 2.34 solved the problem, thanks @kyleian

**Comment by lauraalvarezzz1** [comment]
Same issue using chrome=64.0.3282.140) and chromedriver=2.26.436421

**Comment by samhatoum** [comment]
hi @lauraalvarezzz1 

please post a new issue and make sure we have all the logs. we have released a new version since this bug was reported and this issue is now closed

**Comment by lauraalvarezzz1** [comment]
@samhatoum thank you so much.

**Comment by automation311** [comment]
Was this issue fixed? what was the solution?
I am running scripts in my android mobile browser until yesterday it was working fine but now it throws the below error

WebDriverException: Message: unknown error: cannot determine loading status
from unknown error: missing or invalid 'entry.level'
(Session info: chrome=64.0.3239.111)
(Driver info: chromedriver=2.28.455520
