### ISSUE TITLE
Add Geckodriver to default config

### ISSUE THREAD

**Issue by matheus-vieira** [xolvio/chimp#517]
##### Expected behavior

Execute all my features files using firefox browser, chrome (54) and phantomjs works fine
##### Actual behavior

Got this error:
[chimp][helper] setupBrowserAndDDP had error
{ Error: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
##### Exact steps to reproduce / repository that demonstrates the problem

Execute this command on a Windows 10 pc:

You can find the full terminal output [here](https://gist.github.com/matheus-vieira/ddd7ee5c9f565aa8779a049eb0c55574)
##### Version & tools:
- Chimp command line used: _The exact command you used_
  `.\node_modules\.bin\chimp --watch --path=.\source\e2e\features --browser=firefox`
- Chimp config file: _Please provide a Gist if you use a config file_
- Chimp: _type `chimp -v`_
  0.41.2
- Node.js: _type `node -v`_
  v6.9.1
- Java: _type `java -version`_
  java -version
  java version "1.8.0_111"
  Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
  Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
- Operation system: _type `uname -v`_
  Microsoft Windows [versão 10.0.10586]
##### Console / Log Output

A --debug version of output is [here](https://gist.github.com/matheus-vieira/18b19c7e7378af557ff91c40cf7fb900)

Please put long logs in a [Gist](https://gist.github.com/) and provide a link here.

---

_Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others._

**Comment by IanVS** [comment]
It's not just Windows 10.  Firefox 49 is not working for me in osx either.

**Comment by danhounshell** [comment]
Getting same error on Firefox 50 on osx too.

**Comment by StephenDavidson** [comment]
Can you try adding geckodriver to your config file. Geckodriver/merionette is needed for firefox >47

See https://github.com/vvo/selenium-standalone/blob/776a8d165848286f2f7a6963fb7b25b5ccc9d018/lib/default-config.js

**Comment by samhatoum** [comment]
We'll put this in the default config

**Comment by samhatoum** [comment]
release in 0.45.1
