### ISSUE TITLE
Error running chimp in docker container using chrome headless

### ISSUE THREAD

**Issue by arcarocollo** [xolvio/chimp#519]
##### Expected behaviour

Chimp tests runs correctly using chrome headless in docker container.
##### Actual behaviour

I try to run tests in docker container (here dockerfile https://gist.github.com/arcarocollo/1b667b12e8101c525ce25831377757be) but they doesn't works, a cucumber handler(BeforeFeatures) is in timeout and all tests doesn't running.
Using phantomjs error does not appearing.
##### Exact steps to reproduce / repository that demonstrates the problem

1) build docker image
2) run docker image and go in with bash command (**docker build -it <imageName> /bin/bash**)
3) start chimp with **./node_modules/.bin/chimp --debug**
##### Version & tools:
- Chimp command line used: _/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x800x16 && sleep 3 && export DISPLAY=:99.0 && ./node_modules/.bin/chimp --debug_
- Chimp config file: _https://gist.github.com/arcarocollo/9b62ecccd503ed8bbbf2ada7dddade30_
- Chimp: _0.41.2_
- Node.js: _v6.9.1_
- Java: _1.8.0_111_
- Operation system: _Debian GNU/Linux 8_
##### Console / Log Output

https://gist.github.com/arcarocollo/8ee4b4f08f5bc4f74b607cee2821e50f

**Comment by arcarocollo** [comment]
I found the solution.
I run docker with **--privileged** attribute like this:
`docker run --privileged <imageName> ./node_modules/.bin/chimp --debug`

**Comment by SimonSimCity** [comment]
@arcarocollo could you please post your docker file? I'm also struggling with getting this going but I doubt it's the `--privileged` attribute I missed. Same to your chimp config ...

**Comment by SimonSimCity** [comment]
Got it working without `--privileged` :wink: See: Got it working. If anyone needs the steps it took me: https://github.com/SimonSimCity/bitbucket-meteor-headless-browsers - which is based on https://github.com/SimonSimCity/bitbucket-meteor/blob/master/Dockerfile (which in turn is based on Ubuntu 14.10)
