### ISSUE TITLE
Question with watch through vm's shared folder

### ISSUE THREAD

**Issue by SamMade** [xolvio/chimp#520]
I'm running chimp through vagrant which creates virtual machine (virtualbox) with a shared folder between host and guest machine.

I don't know if anyone else has a similar setup but when I do a 
`chimp --watch`
it runs great on the initial startup.  My problem is on the watch triggering.  When I manually save a file through the guest vm, it works perfectly.  The problem is, if I save a file through the host (thru the shared folder), it doesn't trigger the watch.  Chimp will still be running but it's as if nothing has happened, no errors. it just stays on:

> [chimp] Running...

has anyone dealt with this before?

**Comment by samhatoum** [comment]
Do you have a `--debug` output you could show us?

**Comment by samhatoum** [comment]
Also try to use polling:
https://github.com/xolvio/chimp/blob/master/src/bin/default.js#L13

**Comment by SamMade** [comment]
@samhatoum The polling works like a charm
