### ISSUE TITLE
multiple watchTags not supported anymore

### ISSUE THREAD

**Issue by SierraGolf** [xolvio/chimp#521]
#####  Expected behaviour
multiple --watchTags parameters should be allowed and if provided logically ANDed.

#####  Actual behaviour
```
/xxx/tests/cucumber/node_modules/chimp/dist/lib/chimp.js:222
      watched.push(self.options.watchTags.split(','));
                                          ^

TypeError: self.options.watchTags.split is not a function
    at FSWatcher.<anonymous> (/xxx/tests/cucumber/node_modules/chimp/dist/lib/chimp.js:222:43)
    at FSWatcher.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at FSWatcher.emit (events.js:166:7)
    at nextTickCallbackWith0Args (node.js:456:9)
    at process._tickDomainCallback (node.js:426:13)
```

##### Exact steps to reproduce / repository that demonstrates the problem
* have a feature file and annotate it with `@dev`
* annotate one scenario in that feature file with `@ignore`
* run chimp with `... --watchTags=@dev --watchTags=~@ignore`
* all scenarios in that feature file should be run except the one annotated with `@ignore`

#####  Version & tools:
* Chimp: 0.41.2
* Node.js: v5.4.0

##### Solution
change 
*https://github.com/xolvio/chimp/blob/master/src/lib/chimp.js#L207*
```
if (self.options.watchTags) {
     watched.push(self.options.watchTags.split(','));
}
```
to 

```
if (self.options.watchTags.constructor === Array) {
  self.options.watchTags.forEach(function (entry) {
    watched.push(entry.split(','));
  });
} else if (typeof self.options.watchTags === String) {
  watched.push(self.options.watchTags.split(','));
}
```

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by SierraGolf** [comment]
hey @samhatoum I would like to provide a pull request for that, are there any tests for this stuff I would need to extend?

**Comment by samhatoum** [comment]
Not for that file. I'm pending a refactor to modularize the **** out of it.

**Comment by samhatoum** [comment]
I spoke too soon. Check here:
https://github.com/xolvio/chimp/blob/master/src/__tests__/chimp-spec.js#L149

And thanks in advance!
