### ISSUE TITLE
pending is not defined

### ISSUE THREAD

**Issue by andrialexandrou** [xolvio/chimp#522]
#####  Expected behaviour

I expect to be able to use `pending()` in my step definitions and hooks.

#####  Actual behaviour

Steps skip any scenario with a hook containing `pending()`.

##### Exact steps to reproduce / repository that demonstrates the problem

Put `pending();` in any step definitions or hooks.

#####  Version & tools:

* Chimp command line used: *chimp*
* Chimp config file: [chimp.js](https://gist.github.com/andrialexandrou/19323f50cee5f5999dc34d79127b6442)
* Chimp: *0.41.2*
* Node.js: *6.9.1*
* Java: *1.8.0_92*
* Operation system: *Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64*

(Originally posed this question in #496.)

#####  Console / Log Output

[Console Output](https://gist.github.com/andrialexandrou/94608e63c11f3ee90a4df7cdf69cfb31)

*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by jperasmus** [comment]
As far as I know the `pending()` method has been replaced by just doing `return 'pending';` now.

**Comment by andrialexandrou** [comment]
That's it! replaced it with `return callback( null, "pending" );`.

Before:
```
	this.Before( "@bug", function() {
		// Pending until bug fixed in the UI
		pending();
	} );
```

After:
```
	this.Before( "@bug", function( scenario, callback ) {
		// Pending until bug fixed in the UI
		return callback( null, "pending" );
	} );
```
