### ISSUE TITLE
chimp/dist/lib/cucumberjs/hooks.js:19 function timed out after 60000 milliseconds

### ISSUE THREAD

**Issue by astanley86** [xolvio/chimp#526]
#####  Expected behaviour
Running `chimp --watch` as instructed in the [cucumber tutorial](https://chimp.readme.io/docs/tutorial) runs chimp in the console without any errors:

[chimp] Watching features with tagged with @dev,@watch,@focus
[chimp] Running...

0 scenarios
0 steps

#####  Actual behaviour

/home/ubuntu/.nvm/versions/node/v6.4.0/lib/node_modules/chimp/node_modules/cucumber/lib/cucumber/runtime/event_broadcaster.js:30
            throw error;
            ^
../../../../home/ubuntu/.nvm/versions/node/v6.4.0/lib/node_modules/chimp/dist/lib/cucumberjs/hooks.js:19 function timed out after 60000 milliseconds

##### Exact steps to reproduce / repository that demonstrates the problem

I run the following commands:
`mkdir chimp-tutorial`
`cd chimp-tutorial`
`npm install chimp -g`
`mkdir features`
`chimp --watch`

#####  Version & tools:

* Chimp command line used:  `chimp --watch`
* Chimp config file: not used
* Chimp: 0.41.2
* Node.js:  6.9.0
* Java: 
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

* Operation system: # 147-Ubuntu SMP Tue Oct 18 16:48:51 UTC 2016 .. 14.04 trusty

#####  Console / Log Output

https://gist.github.com/astanley86/9ae77803639fa8855f981befe0f151b3

------- 

*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by kyleian** [comment]
https://github.com/xolvio/chimp/issues/508

**Comment by astanley86** [comment]
@kyleian It is successfully starting the selenium grid at http://localhost:47777/wd/hub

https://gist.github.com/astanley86/2193559f23e8bb673a6f1fdbb5574d40

**Comment by samhatoum** [comment]
Did you install the Java JRE or JDK @astanley86?

**Comment by astanley86** [comment]
I think i must have just installed Java JRE.  Does it require JDK?

**Comment by samhatoum** [comment]
You do, as per the install instructions :) It's a common mistake

However, the newest version of Chimp doesnt' even need Selenium / Java to run chrome. So if you're only using chrome, just get latest
