### ISSUE TITLE
Unable to install Chimp on Windows OS

### ISSUE THREAD

**Issue by vishal0532** [xolvio/chimp#527]
#####  Actual behaviour
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use
@segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install th
e latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher
to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie h
ttps://nodesecurity.io/advisories/130
C:\Users
`-- chimp@0.41.2

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
})
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\pack
age.json'
npm WARN No description
npm WARN No repository field.
npm WARN No README data
npm WARN No license field.

##### Exact steps to reproduce / repository that demonstrates the problem
- Install node.js
- Verified by node -v command and found the version installed
- Tried the commands 
mkdir chimp-tutorial
cd chimp-tutorial
npm install chimp
mkdir features
chimp --watch
- After trying the command chimp --watch getting the below log in windows command line terminal
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use
@segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install th
e latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher
to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie h
ttps://nodesecurity.io/advisories/130
C:\Users
`-- chimp@0.41.2

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
})
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\pack
age.json'
npm WARN No description
npm WARN No repository field.
npm WARN No README data
npm WARN No license field.

#####  Version & tools:

* Chimp command line used: *npm install chimp*
* Chimp config file: *Please provide a Gist if you use a config file*
* Chimp: *getting error-chimp is not recognized command`*
* Node.js: *v6.9.1*
* Java: *1.8`*
* Operation system: *Windows 7*

#####  Console / Log Output

Please put long logs in a [Gist](https://gist.github.com/) and provide a link here.

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by samhatoum** [comment]
can you try an earlier version of node? The issue is that fibers isn't always released for the latest node.js release

**Comment by vishal0532** [comment]
Worked for me after trying the global chimp installation & re-installing node js version.
