### ISSUE TITLE
[Feature Request] Add `--bail` option for mocha

### ISSUE THREAD

**Issue by IanVS** [xolvio/chimp#529]
I understaind that cucumber has a `--fail-fast` option, but I can't find anything in chimp to have that same behavior for Mocha.  Mocha supports a [`--bail`](http://mochajs.org/#b---bail) flag.  Is there any chance this can be supported by Chimp (perhaps call it `--mochaBail`)?

#####  Expected behaviour
I would like to be able to instruct mocha to abort after the first failed test.

#####  Actual behaviour
I cannot find a way to do this.

##### Exact steps to reproduce / repository that demonstrates the problem
Please put long code snips in a [Gist](https://gist.github.com/) and provide a link here.

#####  Version & tools:

* Chimp command line used: *The exact command you used*
* Chimp config file: *Please provide a Gist if you use a config file*
* Chimp: *type `chimp -v`*
* Node.js: *type `node -v`*
* Java: *type `java -version`*
* Operation system: *type `uname -v`*

#####  Console / Log Output

Please put long logs in a [Gist](https://gist.github.com/) and provide a link here.

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by samhatoum** [comment]
check it out:
https://github.com/xolvio/chimp/blob/master/src/bin/default.js#L100

**Comment by IanVS** [comment]
Awesome, thanks!  So, how would I specify multiple `mochaCommandLineOptions` from the command line?  Do I need to just include multiple flags, like `--mocha-command-line-options --color --mocha-command-line-options --bail`?  I assume your argument parser is smart enough not to treat `--color` and `--bail` as arguments to chimp, or do I need to wrap them in quotes?

Thanks again!

**Comment by samhatoum** [comment]
Just use a set of comma separated values like:

`['--color', '--bail']`

Welcome

**Comment by IanVS** [comment]
Actually, that does not seem to work.  https://github.com/xolvio/chimp/commit/f9335ffad9900332c51a7a2fea5323454f8d4ecc#diff-87b77b876872d64e5ee1752de17b53c5R74 is attempting to perform a union between a string (`this.options.mochaCommandLineOptions`) and an array (`_specs`), which doesn't work.

**Comment by samhatoum** [comment]
The union is between 2 arrays. Did you try it and it failed?

**Comment by IanVS** [comment]
Yes, I tried it several ways, and added a log in `node_modules/chimp/dist/lib/mocha/mocha.js` to check the result:

```js
  self.child = cp.fork(path.join(__dirname, 'mocha-wrapper.js'), _.union(this.options.mochaCommandLineOptions, _specs), opts);
  console.log({
      mochaCommandLineOptions: this.options.mochaCommandLineOptions, 
      union: _.union(this.options.mochaCommandLineOptions, _specs)
  })
```

I have a script named `test:smoke` to run chimp, and here have been my attempts to set options:

```
❯ yarn test:smoke -- --mochaCommandLineOptions "['--color', '--bail']"

[chimp] Running...
{ mochaCommandLineOptions: '[--color,', union: [] }
```

```
❯ yarn test:smoke -- --mochaCommandLineOptions ['--color', '--bail']
zsh: bad pattern: [--color,
```

```
❯ yarn test:smoke -- --mochaCommandLineOptions ["--color,--bail"]

[chimp] Running...
{ mochaCommandLineOptions: '[--color,--bail]', union: [] }
```

Am I just using `mochaCommandLineOptions` incorrectly?

**Comment by samhatoum** [comment]
You're using it right. You're right, it's buggy. I'll fix it. in the meantime, this will work:

`mochaCommandLineOptions: ['--color --bail']`

**Comment by IanVS** [comment]
Thanks @samhatoum.  Is there an issue tracking that bug, or should I open a new one?

**Comment by samhatoum** [comment]
this is it, I just reopened since it's buggy

**Comment by IanVS** [comment]
Thanks, I wasn't able to get it working with `mochaCommandLineOptions: ['--color --bail']` or even `mochaCommandLineOptions: ['--bail']`, but adding `bail: true` to `mochaConfig` _does_ seem to work correctly.
