### ISSUE TITLE
waitForXXX does not throw an error / correct message in sync mode

### ISSUE THREAD

**Issue by samhatoum** [xolvio/chimp#53]
When waiting for a condition, such as `waitForExist('selector')`, WebdriverIO will do exactly what it's told to do. The synchronous flow will continue regardless of the value returned from waitForExist. The user intention will likely want the step to fail if the waitFor command fails.

The current workaround is to do this:

expect(browser.waitForExist(selector)).to.equal(true, selector + ' does not exist.');

We need a solution that respects the users original intention without the extra work. 

Options:
 
1) Make a list of methods that we know have this issue and patch them to fail in sync steps (all the waitForXXX and isXXX)
2) Provide a helper for users to use
3) others?

I'm leaning towards option 1 right now. @Sanjo what you think?

**Comment by Sanjo** [comment]
Jup. We can treat those special cases in https://github.com/xolvio/sync-webdriverio/blob/master/index.js

**Comment by Sanjo** [comment]
But I think the underlying problem is a problem with binding the promise callbacks to the fiber.

**Comment by Sanjo** [comment]
Reported to WebdriverIO: https://github.com/webdriverio/webdriverio/issues/702

**Comment by samhatoum** [comment]
Nice. Did you try isXxxx? Like isVisible?

**Comment by Sanjo** [comment]
isVisible is not supposed to throw. It just returns a boolean.

**Comment by Sanjo** [comment]
isVisible works correctly for me in sync mode and WebdriverIO. Did you have problems with it?

**Comment by samhatoum** [comment]
Oh you're correct!
