### ISSUE TITLE
jsonOutput creates file with "null" string when step is missing

### ISSUE THREAD

**Issue by jmatsushita** [xolvio/chimp#536]
#####  Expected behaviour

When a cucumber step is missing no jsonOutput file should be created.

#####  Actual behaviour

a jsonOutput file with "null" in it is crerated.

##### Exact steps to reproduce / repository that demonstrates the problem

Follow the tutorial cucumber steps, add `--jsonOutput=cucumber_report.json` before adding `step_defs.js`.

#####  Version & tools:

- Chimp: 0.43.0
- Node.js: v6.9.1
- Java: java version "1.8.0_91"
- Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
- Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
- Operation system: Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by samhatoum** [comment]
Thanks for reporting, this is indeed a bug
