### ISSUE TITLE
header Request time out

### ISSUE THREAD

**Issue by amarakgec** [xolvio/chimp#541]
hi when i start testing meteor appliacation cmd and node module cmd open then it throw error in cucumber log file error are given below--

=> Started your app.

=> App running at: http://localhost:51961/
   Type Control-C twice to stop.

[velocity] Mirror has established connection with Velocity.
[xolvio:cucumber] Cucumber is running
[selenium] [Error: Could not request headers from http://selenium-release.storage.googleapis.com/2.47/IEDriverServer_Win32_2.47.0.zip: Error: connect ETIMEDOUT]
[chimp] Finished running async processes with errors
[chimp] run complete with errors [Error: Could not request headers from http://selenium-release.storage.googleapis.com/2.47/IEDriverServer_Win32_2.47.0.zip: Error: connect ETIMEDOUT]
[chimp] Could not get Cucumber Results from run result:
[ undefined, [ undefined ] ]
[xolvio:cucumber] Bad response from Chimp server.
{ statusCode: 200,
  content: '',
  headers: 
   { 'content-type': 'application/json; charset=utf-8',
     'cache-control': 'no-cache',
     'content-length': '0',
     date: 'Tue, 13 Dec 2016 11:11:01 GMT',
     connection: 'keep-alive' },
  data: null }
[xolvio:cucumber] Cucumber is running

How to resolved it. thanx in advance

**Comment by samhatoum** [comment]
You are using Velocity. That project is dead. Remove your velocity based packages and follow the instructions on the Meteor guide for testing with Chimp
