### ISSUE TITLE
Chai webdriver

### ISSUE THREAD

**Issue by grichmond-mdsol** [xolvio/chimp#542]
Hi is it possible to use chai-webdriver with chimp? Really like the assertion syntax.

Instructions for use are with plain webdriver, can't seem to find anything on use with chimp

https://www.npmjs.com/package/chai-webdriver

**Comment by samhatoum** [comment]
That won't work unfortunately. `chai-webdriver` uses `selenium-webdriver` and Chimp uses `webdriver.io`. Chai-webdriver will not accept webdriver.io as the binding library
