### ISSUE TITLE
Basic documentation tutorial failed

### ISSUE THREAD

**Issue by verzola** [xolvio/chimp#550]
#####  Expected behaviour
[chimp] Running...

...

1 scenario (1 passed)
3 steps (3 passed)

#####  Actual behaviour
➜  chimptest chimp --watch                  
(node:16950) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

Master Chimp and become a testing Ninja! Check out our course: http://bit.ly/2btQaFu

[chimp] Watching features with tagged with @watch,@focus

[chimp] Running...
Feature: Search the Web

    As a human
    I want to search the web
    So I can find information

  @watch
  Scenario: Search for Xolv.io
  ✔ Given I have visited Google
  ✔ When I search for "Xolv.io"
  ✖ Then I see "Xolv.io"

Failures:

1) Scenario: Search for Xolv.io - features/search.feature:8
   Step: Then I see "Xolv.io" - features/search.feature:11
   Step Definition: features/support/step_defs.js:12
   Message:
     TypeError: Cannot read property 'trim' of undefined
         at World.<anonymous> (features/support/step_defs.js:13:10)

1 scenario (1 failed)
3 steps (1 failed, 2 passed)
0m06.400s

##### Exact steps to reproduce / repository that demonstrates the problem
Steps provided in documentation tutorial: https://chimp.readme.io/docs/tutorial

#####  Version & tools:

* Chimp command line used: chimp --watch    
* Chimp config file: No config
* Chimp: 0.45.1
* Node.js: v7.3.0
* Java:
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
* Operation system: #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19)

#####  Console / Log Output
Provided in "actual behaviour"
------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by verzola** [comment]
I fixed it using the LTS version of Node. Maybe it is a good idea to put the required node version in the Prerequisite session of Installation: https://chimp.readme.io/docs/installation.

**Comment by timbrandin** [comment]
Doesn't work with latest version of node:
https://hub.docker.com/r/ryanhanwu/docker-meteor/~/dockerfile/
