### ISSUE TITLE
How to configure multiple cucumber 'tags' parameters in chimp.js configuration file?

### ISSUE THREAD

**Issue by xywang68** [xolvio/chimp#558]
Hi, thank you for reading my question.

I have a question about providing multiple ignore tags in the cucumber configuration section of the chimp config file. What I want to achieve is to have a configuration file that can take multiple exclude tags (multiple ~@ignore tags).

I am able to achieve my goal by passing these tags parameters in command line:

`chimp <chimp run parameters> --tags ~@ignore1 --tags ~@ignore2
`

How can I achieve the same goal in the chimp.js configuration file?

My env:
ubuntu version 16.04
chimps-js version 0.35.0
cucumber-js version 0.9.4

I tried the following attempt but could not achieve the same goal:
attempt 1:

`tags: '~@ignore1',`

~@ignore1 worked as expected, but this is not exactly what I want;

attempt 2:

```
tags: '~@ignore1',
tags: '~@ignore2',
```

only ~@ignore2 worked but ~@ignore1 does not;

attempt 3:

`tags: '~@ignore1 --tags ~@ignore2',`

This attempt appear correct in the ps -ef table which shows the command line as "--tags ~@ignore1 --tags ~@ignore2", but the actual outcome is not the same as directly from the command line. None of these tags are ignored.

I have also tried other attempts by using parentheses to form logic that complies with this cucumber tag reference: https://github.com/cucumber/cucumber/wiki/Tags, but again, none of the tags are ignored.

Is there a work around or is this a limitation of the current code?

**Comment by mmcculloch15** [comment]
I've had success with using an array for this 

Ex:
`tags: ['~@ignore1', '~@ignore2', '@ignore3']`

**Comment by xywang68** [comment]
@mmcculloch15 's solution works for me. Thank you!
