### ISSUE TITLE
Cannot use webdriver REPL with chimp

### ISSUE THREAD

**Issue by tiagolr** [xolvio/chimp#560]
To speed up test development I'm trying to get a REPL to work with chimp and access webdriver api.

I tried the following: 
* `node debug -p node_pid` followed by `repl`: cannot access the browser object
* `node_modules/.bin/wdio --port chimp_port` actually works but have to get the current port from debug logs  and opens a new session and chrome window instead of just connecting to the existing chimp window.
* `browser.debug()` this one is pretty close to what I'm looking for, unfortunately I'm having the problem described here: https://forums.meteor.com/t/debugging-cucumber-steps-via-chimp/30343

Suggestions? Thank you very much for your help.

**Edit:** the problem with `browser.debug()` is that it the repl opens a new line when I press enter instead of sending the command.

**Comment by samhatoum** [comment]
Challange accepted :)

**Comment by tiagolr** [comment]
Fixed this one, PR comming soon.

**Comment by rohithb** [comment]
Any info about how to use webdriverio REPL using chimp?

**Comment by tiagolr** [comment]
its working well

**Comment by rohithb** [comment]
`browser.debug()` is working fine, but it continues execution after few seconds even after I set `timeout` in wdio.conf.js for cucumber as a very large number. So how can I execute equivalent of `wdio repl chrome` using chimp?

**Comment by tiagolr** [comment]
I set a high value with `setDefaultTimeout` function on my hooks.js file.

```
if (process.env['chimp.watch'] || process.env['chimp.debugOnError']) {
      this.setDefaultTimeout(60 * 60 * 1000); // cucumber step timeout
    }
```

I then also use a hook to enter debug mode on errors:

```
this.After((scenario) => {
    if (process.env['chimp.debugOnError'] && scenario.isFailed()) {
      browser.debug();
    }
  });
```
