### ISSUE TITLE
Should we standardize location of steps?

### ISSUE THREAD

**Issue by dandv** [xolvio/chimp#58]
In [the tutorial](https://chimp.readme.io/docs/tutorial), the steps definitions file is `step_defs.js` in `features/support/`. [In Letterpress, step definitions](https://github.com/xolvio/Letterpress/tree/master/app/tests/cucumber/features/Users/step_definitions) are in a `step_definitions` subdirectory of `features`.

**Comment by samhatoum** [comment]
Sorry this took so long, I'm just looking at chimp again a bit. I'm not sure this is required. Different users can choose where to put step defs.

Can you convince me or shall I close this? :)
