### ISSUE TITLE
Can no longer access baseUrl from the config

### ISSUE THREAD

**Issue by skewis6** [xolvio/chimp#580]
#####  Expected behaviour
Being able to access the `browser.options.baseUrl` within a test suite. This worked perfectly for me before when I was on version `0.42.0`, now it no longer works.

#####  Actual behaviour
Chimp throws an exception error. If I try to log out the baseUrl with`console.log(browser.options.baseUrl)` it returns undefined

##### Exact steps to reproduce / repository that demonstrates the problem
Have a chimp config with webdriverio properties defined, pointing the baseUrl to localhost. Then create a test suite (I'm using Jasmine), and in the beforeEach() function:
`browser.newWindow(browser.options.baseUrl);`
An example test suite is here:
https://gist.github.com/skewis6/6872cdebd9a486fa38b550cd7b9a5ecf

#####  Version & tools:

* Chimp command line used: 
`chimp ./test/selenium/config/chimp.local.config.js --jasmine --path='./test/selenium/`
* Chimp config file: 
https://gist.github.com/skewis6/abaecc584f197301922be5f8467bbcb0
* Chimp: 
`0.47.2`
* Node.js: 
`v6.9.1`
* Java: 
`1.8.0_111`
* Operation system: 
`Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64`
#####  Console / Log Output
https://gist.github.com/skewis6/275c4682c239b5c6a4d098bbec7e375d

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by kyleian** [comment]
Just out of curiosity, since you have `console.log(browser.options.basseUrl)` written in your issue, is that the way you have it in your code? `basse` versus `base`

**Comment by skewis6** [comment]
@kyleian Haha! Sadly not, that's just a typo! Good spot though
