### ISSUE TITLE
[ Question ] Adding additonal tools

### ISSUE THREAD

**Issue by Pushplaybang** [xolvio/chimp#582]
Hi there,

I'd like to know if its possible to include additional libraries with the chimp setup, such as the chai-webdriver library (https://github.com/goodeggs/chai-webdriver) for better dom related assertions.

there setup instructions specify:

```js
// Start with a webdriver instance:
var sw = require('selenium-webdriver');
var driver = new sw.Builder()
  .withCapabilities(sw.Capabilities.chrome())
  .build()

// And then...
var chai = require('chai');
var chaiWebdriver = require('chai-webdriver');
chai.use(chaiWebdriver(driver));

```

Where would one do this? Is it possible to use additional third party libraries, and my apologies if this is documented, but I haven't seen anything in your docs so far.

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
