### ISSUE TITLE
Expose `--snippet-syntax` cucumber option in chimp.js config file

### ISSUE THREAD

**Issue by jperasmus** [xolvio/chimp#587]
#####  Expected behaviour
A config option `snippetSyntax` to exist in the chimp.js config file to enable me to specify the relative path to a custom snippet syntax javascript file.

#####  Actual behaviour
Option not available in the chimp config file, but is passed through to cucumber if set as a flag (`--snippet-syntax=./path/to/file.js`

##### Exact steps to reproduce / repository that demonstrates the problem
This is an enhancement request, so no problem to demonstrate. The gist of the issue is that I would like to be able to specify the `snippetSyntax` cucumber option in the chimp config instead of having to pass it along as a terminal flag

#####  Version & tools:

* Chimp command line used: `chimp ./chimp.js` and `chimp ./chimp.js --snippet-syntax=./es6-syntax.js` where `es6-syntax.js` is my custom syntax file
* Chimp config file: *N/A*
* Chimp: *0.47.2*
* Node.js: *v7.5.0*
* Java: *java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)*
* Operation system: *Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64*

#####  Console / Log Output

Please put long logs in a [Gist](https://gist.github.com/) and provide a link here.

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
