### ISSUE TITLE
Empty sessionId in multi-browser (CUCUMBER_BROWSERS=n) setting on reload

### ISSUE THREAD

**Issue by convexset** [xolvio/chimp#590]
I'm using
```
CUCUMBER_BROWSERS=3 chimp --ddp=http://localhost:8080 --watch --mocha --path=tests
```
and am getting empty sessionId's when my tests rerun in response to code changes.

#####  Expected behaviour

Tests run and run again when code reloads.

#####  Actual behaviour

First test run works, but subsequent runs fail on each `browser.url(...)` call (and others) with the following exception:

```
{ [Error: A session id is required for this command but wasn't found in the response payload]
  type: 'NoSessionIdError',
  message: 'A session id is required for this command but wasn\'t found in the response payload' }
```

Here is what `browser.sessions()` looks like:
```
{ browser0: 
   { sessionId: '',
     status: 0,
     value: [ [Object], [Object], [Object] ] },
  browser1: 
   { sessionId: '',
     status: 0,
     value: [ [Object], [Object], [Object] ] },
  browser2: 
   { sessionId: '',
     status: 0,
     value: [ [Object], [Object], [Object] ] } }
```

Any clue as to how to fix things?

I have a really shitty work around that allows me to work without having to restart Chimp. I wipe out all sessions when I catch the above exception:
```
const currentSessions = currentBrowser.sessions();
console.log('Clearing all sessions. Save again and see how things go...');

currentSessions.value
    .forEach(session => currentBrowser.session('delete', session.id));
```
... then I incur another load when the browser instances start up again. =(

**Comment by naiquevin** [comment]
I am facing this exact issue. Did you manage to solve it?

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
