### ISSUE TITLE
Send test result and mark builds as passed/failed on browserstack

### ISSUE THREAD

**Issue by twilczek** [xolvio/chimp#592]
This is enhancement proposition.

It is possible to mark builds on browserstack as 'passed' or 'failed' depending on the result of tests ran. It would make easier identifying builds with failed tests.

In current Chimp version (v0.47) we only mark builds as 'complete' and do not pass test result.

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
