### ISSUE TITLE
How to wait for Meteor started?

### ISSUE THREAD

**Issue by yourse1f-yourorg** [xolvio/chimp#595]
Hi Sam,

My circle.yml looks like this : 

     post:
         - ${METEOR_CMD} --production --settings=settings.json >> ${CIRCLE_ARTIFACTS}/meteor.log 2>&1 & :
            background: true

     test:
       post:
         - sleep 4m
         - ${CHIMP_CMD} .e2e_tests/chimp-config.js --ddp=http://localhost:3000 --path=.e2e_tests

Do you have a way to avoid the 4 minute sleep?  Without it testing fails immediatel.y

**Comment by mmazur122** [comment]
You could try running meteor as a child process which would then run chimp once your app has started. An example can be found [here](https://github.com/xolvio/qualityfaster/blob/master/.scripts/start.js). You might have to tweak this script to get it to work.
Another way is to run meteor using gulp as shown [here](https://github.com/xolvio/qualityfaster/blob/dev/gulpfile.js) but I don't have much experience with this solution.

**Comment by Sanjo** [comment]
Replace the `- sleep 4m` with `- ./waitForAppStart.sh`.

waitForAppStart.sh:

```sh
#!/bin/bash

FILE_TO_WATCH="$CIRCLE_ARTIFACTS/meteor.log"
SEARCH_PATTERN='App running'

tail -f "$FILE_TO_WATCH" -n +1 | while read LOGLINE
do
   [[ "${LOGLINE}" == *"$SEARCH_PATTERN"* ]] && pkill -P $$ tail && exit 0
done
```

**Comment by martinhbramwell** [comment]
@Sanjo, long delay, but I finally got around to looking at this.

Your very sensible suggestion made me realize I did not need to depend on Chimp to do this for me, and that it's pretty much a generic problem; so there's sure to be a generic solution.

After a couple of missteps I hit on:

     dependencies:
       pre:
         - sudo apt install -y httping

       post:
         - ${METEOR_CMD} --production --settings=settings.json >> ${CIRCLE_ARTIFACTS}/meteor.log 2>&1 & :
             background: true

     test:
       pre:
         - export IDX=10; while printf "."; ! httping -qc1 http://localhost:3000 && ((IDX-- > 0)); do sleep 5 ; done;

       post:
         - ${CHIMP_CMD} .e2e_tests/chimp-config.js --ddp=http://localhost:3000 --path=.e2e_tests

**Comment by bloudermilk** [comment]
I iterated on the creative answers from @martinhbramwell and @Sanjo to come up with a one-liner that doesn't require any dependencies:

```bash
until curl --max-time 300 http://localhost:3000/; do sleep 1; done
```

All together, the `test` block from my `circle.yml` looks like this:

```bash
```

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
