### ISSUE TITLE
I am unable to update the cucumnber timeout for xolvio/cucumber-js

### ISSUE THREAD

**Issue by asanchezgiraldo** [xolvio/chimp#598]
#####  Expected behaviour
I should be able to follow the steps from https://github.com/xolvio/cucumber-js/blob/v1.3.0-chimp.1/docs/support_files/timeouts.md and update the time out with 
```
var configure = function () {
  this.setDefaultTimeout(90 * 1000);
};

module.exports = configure;
```

#####  Actual behaviour
After I add the code provided in my `world.js` file or my `hooks.js` file the time out remains the same and I get the below error message

```
node_modules/chimp/node_modules/cucumber/lib/cucumber/runtime/event_broadcaster.js:30
            throw error;
            ^
node_modules/chimp/dist/lib/cucumberjs/hooks.js:19 function timed out after 60000 milliseconds
Cucumber steps failed

```
I have also try to add the code to update the timeout to my `chimp.js` config and I get the same response.

Currenlty running node `6.1.0` and chimp `0.41.2`

**Comment by tiagolr** [comment]
I am able to change the cucumber default timeout, I only do it once before all tests though.

```
this.BeforeFeatures(() => {
    helper.api._login();

    if (process.env['chimp.watch']) {
      this.setDefaultTimeout(60 * 60 * 1000); // cucumber step timeout
    }
}
```

Also note that setDefaultTimeout is for cucumber steps timeout (not waits or asyncscripts), not sure I get the problem, hope it helps.

**Comment by asanchezgiraldo** [comment]
@tiagolr I have try to do as you have mentioned above as well and I still get the same error

```
node_modules/chimp/dist/lib/cucumberjs/hooks.js:19 function timed out after 60000 milliseconds
```

The only way I have been able to resolve this issue is by Manually going to the below path and updating the hook.js file. (but I can not do this in my TeamCity build)

path `./node_modules/chimp/dist/lib/cucumberjs/hooks.js` 

line 17

from 
`  this.setDefaultTimeout(60 * 1000);` to `  this.setDefaultTimeout(90 * 1000);`

**Comment by tiagolr** [comment]
Maybe you should create a demo repository for this, no idea why it happens.

using:
```
node 4.8.0
chimp 0.47.2
ubuntu 16.04
```

**Comment by tiagolr** [comment]
Can also be related to #508

**Comment by asanchezgiraldo** [comment]
Sorry I have not been able to create a sample repo to test.
will do in the next couple of days

**Comment by asanchezgiraldo** [comment]
The issue seems to be that the browser is not loading within the timeout set, so none of the other timeouts apply.

I have created a [gist](https://gist.github.com/asanchezgiraldo/14323bde09b809ab30af785f451fc2fd) with my console output

also the below is an example repo with the error
[repo](https://github.com/asanchezgiraldo/chimp-trouble-shooting)

**Comment by eliezercazares** [comment]
same issue here

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
