### ISSUE TITLE
using page object pattern with chimp

### ISSUE THREAD

**Issue by Kabalas** [xolvio/chimp#60]
Hello, 
I'm trying to use chimpjs with page object pattern.
In my BDD spec I'd like to have something like:
```
this.Given(I login to app, function () {
  loginPageObject.loginToApp();
}
```
e.g.
loginPageObject - an object having methods available on login page
loginToApp() - a method with webdriverIO API 

Could you provide an example how to do this?
Thank you.

**Comment by DominikGuzei** [comment]
Hey @Kabalas!
Chimp comes with a small extension called [chimp-widgets](https://github.com/xolvio/chimp-widgets) that enables you to define page objects and use their API in your step definitions. If you follow the link you can take a look at the documentation.

For your example it would work something like this:
```javascript
module.exports = function() {
  // Define your page object before running any steps
  this.Before(function(done) {
    this.LoginPage = this.widgets.Widget.extend({
      selector: '.login-page',
      loginToApp: function(email, password) {
        var emailField = this.find('input.email'),
              passwordField = this.find('input.password')
              loginButton = this.find('button.login');
        // Use the promise-based API of chimp-widgets
        emailField.setValue(email)
        .then(function() { passwordField.setValue(password); })
        .then(function() { loginButton.click() });
      }
    });

    // Specify the URL of the login page, so you can visit it in your steps
    this.ProjectsPage.url = process.env.ROOT_URL + 'login';
    // Tell the before step that we are done!
    done();
  });

  this.Given(I login to app, function () {
    new LoginPage().loginToApp('my-email', 'my-password');
  }
};
```

Hope this helps :wink:
If you have any questions, or feel that the documentation of chimp-widgets lacks some important details, please file issues there and I will be glad to improve!

**Comment by samhatoum** [comment]
@domink does chimp-widgets still work with our latest synchronous update that uses fibers?

**Comment by samhatoum** [comment]
@Kabalas I you can use chimp-widgets if you run chimp with `--sync=false`. The latest version of chimp is synchronous. We haven't updated chimp-widgets to be synchronous - yet! (Dominik has been away so he hasn't seen the latest version :) )

If you want to use page objects today with the new sync mode, you can do this:

* Make sure you have this file with the underscores as shown since loading order matters at the moment:
`features/_support/_widgets.js`
```javascript
global.widgets = {};
```

* Create your widget (page object)
`features/_support/page-objects/login-widget.js`
```javascript
var rootSelector = '.login-page ';
var selectors = {
  emailField : rootSelector + 'input.email',
  passwordField : rootSelector + 'input.password',
  loginButton : rootSelector + 'button.login'
};

widgets.login = {
  loginToApp: function(email, password) {
    browser.setValue(selectors.emailField, email);
    browser.setValue(selectors.passwordField, email);
    browser.click(selectors.loginButton);
  }
}
```

* Use your widget
```javascript
this.Given(I login to app, function () {
  widgets.login.loginToApp('my-email', 'my-password');
}
```

@DominikGuzei I think the above can be made a lot nicer using chimp-widgets syntax
