### ISSUE TITLE
Your tutorials page is broken on readme.io JSON error

### ISSUE THREAD

**Issue by dubbya** [xolvio/chimp#602]
##### Exact steps to reproduce / repository that demonstrates the problem
Please put long code snips in a [Gist](https://gist.github.com/) and provide a link here.

#####  Version & tools:

* Chimp command line used: *The exact command you used*
* Chimp config file: *Please provide a Gist if you use a config file*
* Chimp: *type `chimp -v`*
* Node.js: *type `node -v`*
* Java: *type `java -version`*
* Operation system: *type `uname -v`*

#####  Console / Log Output

Please put long logs in a [Gist](https://gist.github.com/) and provide a link here.

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by maxmckenzie** [comment]
common @dubbya you can put more effort into a ticket than that :D

**Comment by dubbya** [comment]
[sigh] you are right @maxmckenzie :)

So hit the URL **https://chimp.readme.io/docs/tutorial**

The tutorial used to show (because I followed it once a few weeks back), but there is a blank frame now instead. 

Chrome developer tools (F12) shows this error:

SyntaxError: Unexpected token , in JSON at position 156
    at JSON.parse (<anonymous>)
    at eval (webpack:///./_legacy/public/js/directives/content.js?:85:20)
    at Function.forEach (webpack:///./bower_components/lodash/dist/lodash.compat.js?:3640:15)
    at parseBlocks (webpack:///./_legacy/public/js/directives/content.js?:50:7)
    at link (webpack:///./_legacy/public/js/directives/content.js?:166:26)
    at invokeLinkFn (webpack:///./bower_components/angular/angular.js?:8281:9)
    at nodeLinkFn (webpack:///./bower_components/angular/angular.js?:7791:11)
    at eval (webpack:///./bower_components/angular/angular.js?:8021:13)
    at processQueue (webpack:///./bower_components/angular/angular.js?:13318:27)
    at eval (webpack:///./bower_components/angular/angular.js?:13334:27) <div class="content block-content">

Diagnosis = its broke (same for firefox)

Expected behaviour = see tutorial instead of blank page

**Comment by maxmckenzie** [comment]
hmmm, you are indeed correct. i'll go check it out and have a fiddle

**Comment by maxmckenzie** [comment]
ok well, it's on readme.io rather than a repo in github, so forget the checking it out thing.

@samhatoum This is probably your remit no? i can suggest edits and the page is still blank.

**Comment by maxmckenzie** [comment]
@dubbya is this holding you back at all or are you simply highlighting the issue? If it is for the moment you can join the slack channel and ask some questions there.

**Comment by dubbya** [comment]
Not holding me back. But that was the most valuable page on the site. 

I also tried to send a suggestion through readme.io and had troubles, hence why its in github.  I know probably not the ideal spot. Thanks guys.

**Comment by dubbya** [comment]
Fixed thanks

**Comment by dubbya** [comment]
sorry closed accidently - not fixed

**Comment by toja83** [comment]
Is there a plan to get this up and running soon again?
I am new to Chimp, and wanted to read the tutorial... or can I find it somewhere else?!

**Comment by maxmckenzie** [comment]
to be fair the cucumber tutorial was brief anyway. Install chimp, make a features dir, then a `something.feature` file. Run chimp. It'll output suggested steps you can then add them to a steps sub-directory in the features directory and your off.

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
