### ISSUE TITLE
Configuring WebdriverIO desiredCapabilities on the command-line?

### ISSUE THREAD

**Issue by QuangNguyen-fsoft** [xolvio/chimp#603]
Hi guys,

I know we can pass Chimp a configuration file containing the options and desiredCapabilities we need for WebdriverIO to work. But is there anyway to do that on the command-line?

What I am looking to achieve is to dynamically execute test cases with chimp with different environments and platforms (desktop browsers and mobile devices). We can do that just fine with manually editing the configuration file, but I want to automate that part as well.

Maybe something along the line of how we can pass desiredCapabilities to Appium server?
`--default-capabilities '{"app": "myapp.app", "deviceName": "iPhone Simulator"}'`

**Comment by maxmckenzie** [comment]
hmmm, i'm not sure if this is a good idea to do it via the command line.

To dynamically execute test cases as you describe i would suggest using multiple config files. For example

```
/config
  chimp-config-appium.js
  chimp-config-macosx.js
  chimp-config-chrome.js
```
etc etc, the nameing is up to you.

Then in your package.json you can define run scripts for npm.

```
"scripts": {
    "lint": "eslint .",
    "test:appium": "chimp chimp-config-appium.js",
    "test:macosx": "chimp chimp-config-macosx.js"
  },
```

Then you can use `npm run test:appium` from the command line

The naming structure of the config file is up to you

**Comment by septuagint** [comment]
To answer your question directly, this is what I do when I know that I don't want to duplicate a config for a few options for whatever reason, just use env vars wherever you see fit.

`"webdriverio": {
    "waitforTimeout": 10000,
    "waitforInterval": 250,
    "protocol": 'https',
    "host": 'us1.appium.testobject.com',
    "port": '443',
    "path": '/api/appium/wd/hub',
    "desiredCapabilities": {
      "testobject_api_key": process.env.TESTOBJECT_API_KEY,
      "testobject_app_id": process.env.TESTOBJECT_APP_ID,
      "testobject_device": process.env.TESTOBJECT_DEVICE,
      "testobject_appium_version": process.env.TESTOBJECT_APPIUM_VERSION,
...`

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
