### ISSUE TITLE
setViewportSize fails w latest Meteor

### ISSUE THREAD

**Issue by Azeures** [xolvio/chimp#607]
It seems like setViewportSize fails on chimp with the latest Meteor update.

Seems like it might have caused problems previously as well? I see it referenced by @samhatoum in an older issue: https://github.com/xolvio/chimp/issues/249

#####  Expected behaviour
* Chrome opens and is routed to http://localhost:3000
* Tests begin to run

#####  Actual behaviour
* Chrome opens but shows a blank screen with 'data:,' in address bar
* Tests cannot begin

##### Exact steps to reproduce / repository that demonstrates the problem

Run chimp-watch with the following in hooks.js:

```
1  (function() {
2    module.exports = function() {
3      this.Before(function() {
4       client.setViewportSize({ width: 1500, height: 800 }, false);
5        // go to the page first so we have access to the Meteor object
6        client.url(process.env.ROOT_URL);
7        // Set timeout limit to 20 seconds.
8        client.timeoutsAsyncScript(20000);
9        client.timeoutsImplicitWait(5000);
10       // Ensure client is logged out before resetting fixtures
11       client.executeAsync(function(done) {
12         // Logout
13         Meteor.logout(function(logoutError) {
14           if (logoutError) done();
15           else {
16             Meteor.call('fixtures/reset', done);
17           }
18         });
19       });
20     });
21   };
22 })();
```
Chimp runs successfully but when the Chrome browser opens, it fails to navigate to http://localhost:3000

<img width="927" alt="blank chrome screen" src="https://cloud.githubusercontent.com/assets/12486225/25012887/cf5b97ae-203f-11e7-8534-2fdbc5b0f2a6.png">

Removing the setViewportSize function on line 4 currently resolves this issue but this is necessary for testing.

#####  Version & tools:

* Chimp command line used: `export ROOT_URL='http://localhost:3000/' && chimp --ddp=http://localhost:3000 --watch --browser=chrome --path=tests/features`
* Chimp: 0.47.2
* Node.js: v7.8.0
* Meteor: 1.4.4.1
* Operation system: MacOS Sierra 10.12.4 / Darwin Kernel Version 16.5.0

Any help would be appreciated, thank you!

**Comment by bubbafett1936** [comment]
I was getting this exact behavior. To resolve the error, I had to use the most recent chromedriver for selenium. There was some w/ version 57+ of Chrome that disabled automation.

**Comment by Azeures** [comment]
Thank you for your input @bubbafett1936! 

I was running chromedriver 2.27 and updated it to the latest version 2.29. This did not resolve the issue for me.

**Comment by andreluizbellon** [comment]
I'm having this problem as well. Everytime i try to execute `setViewportSize`, it gives me the following error:
```
Uncaught GET /session/2916126d-09a3-4f80-b269-4860fa3cc019/window/rect
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: '<host>', ip: '192.168.99.1', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_101'
Driver info: driver.version: unknown
  Error: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource.
      at Object.wait (node_modules\fibers\future.js:449:15)
      at Object.<anonymous> (node_modules\wdio-sync\build\index.js:344:27)
      at node_modules\chimp\dist\lib\utils\fiberize.js:29:22
      at windowHandleSize() - node_modules\webdriverio\build\lib\commands\setViewportSize.js:72:17
```

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
