### ISSUE TITLE
Failures not being reported in the output

### ISSUE THREAD

**Issue by bubbafett1936** [xolvio/chimp#608]
#####  Expected behaviour
After the tests finish running, any failures should be printed, w/ the default reporting format, detailing the specific step of each scenario that failed, and on which line of the step definition the faulty code can be found, followed by the number of scenarios and how many passed/failed, the number of steps and how many passed/failed/were skipped, and the amount of time the tests took.

#####  Actual behaviour
After the tests finish running, the log does not report any failure details.

##### Exact steps to reproduce / repository that demonstrates the problem
Run any tests that have steps that fail

#####  Version & tools:
* Chimp config file: https://gist.github.com/bubbafett1936/f718d66d709042bcac63be9918596a25
* Chimp: 0.47.2
* Node.js: 5.11.1
* Java: 1.8.0_91
* Operation system: OS X 10.11.6

#####  Console / Log Output
```
Failures:

Cucumber steps failed
```

##### Note
I was able to get the log to report correctly by downgrading Chimp to 0.47.1. Otherwise, I wouldn't be reporting this here

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
