### ISSUE TITLE
npm install chimp is throwing an error

### ISSUE THREAD

**Issue by ashokdudhade** [xolvio/chimp#61]
I'm getting below error when tried to install chimp.

   npm http 404 https://registry.npmjs.org/xolvio/sync-webdriverio
   npm ERR! 404 Not Found
   npm ERR! 404
   npm ERR! 404 'xolvio/sync-webdriverio' is not in the npm registry.
   npm ERR! 404 You should bug the author to publish it
   npm ERR! 404 It was specified as a dependency of 'chimp'
   npm ERR! 404
   npm ERR! 404 Note that you can also install from a
   npm ERR! 404 tarball, folder, or http url, or git url.

  npm ERR! System Darwin 14.4.0
  npm ERR! command "node" "/usr/local/bin/npm" "install" "chimp"

**Comment by Sanjo** [comment]
You need to update your npm with `npm install -g npm`

**Comment by ashokdudhade** [comment]
Thanks it solved the problem
