### ISSUE TITLE
unable to use device as config for browser stack 

### ISSUE THREAD

**Issue by asanchezgiraldo** [xolvio/chimp#610]
#####  Expected behaviour

I should be able to use the option `device` to connect to browser stack (this will use selenium)

#####  Actual behaviour

Currenlty I get an error as `deviceName` is not set

```
[chimp][helper] setupBrowserAndDDP had error
Error: [chimp][session-manager-factory] options.browser or options.deviceName is required
    at new SessionManagerFactory (/Users/alejandro/dolly-site/automation/node_modules/chimp/dist/lib/session-factory.js:30:9)
    at setupBrowser (/Users/alejandro/dolly-site/automation/node_modules/chimp/dist/lib/chimp-helper.js:111:31)
    at Object.setupBrowserAndDDP (/Users/alejandro/dolly-site/automation/node_modules/chimp/dist/lib/chimp-helper.js:263:7)
    at /Users/alejandro/dolly-site/automation/node_modules/chimp/dist/lib/cucumberjs/hooks.js:22:24
```
I want to be able to use `device` as an option instead of `deviceName` as browser stack uses APPIUM for deviceName and selenium for device.

and APPIUM has not implemented scroll

##### Exact steps to reproduce / repository that demonstrates the problem
Please put long code snips in a [Gist](https://gist.github.com/) and provide a link here.

#####  Version & tools:

* Chimp: version 0.48
* Node.js: *node 6.1.0
* Operation system: MAC sierra

*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
