### ISSUE TITLE
unable to update the chimp to 0.47.2

### ISSUE THREAD

**Issue by Mustang1985** [xolvio/chimp#615]
@samhatoum 
Please help in resolving the below error, I am trying to update to chimp 0.47.2 from 0.41.
nodejs version is v6.10.3
git version 2.11.0
Windows 7 -64 bit

>npm install chimp@0.47.2
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config -
-get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:204:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:886:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child
_process.js:226:5)
npm WARN addRemoteGit  xolvio/cucumber-js#v1.3.0-chimp.2 resetting remote C:\Use
rs\111065\AppData\Roaming\npm-cache\_git-remotes\git-github-com-xolvio-cucumber-
js-git-v1-3-0-chimp-2-26e1b4f2 because of error: { Error: Command failed: git -c
 core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:204:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:886:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child
_process.js:226:5)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.ori
gin.url' }
npm ERR! git clone --template=C:\Users\111065\AppData\Roaming\npm-cache\_git-rem
otes\_templates --mirror git://github.com/xolvio/cucumber-js.git C:\Users\111065
\AppData\Roaming\npm-cache\_git-remotes\git-github-com-xolvio-cucumber-js-git-v1
-3-0-chimp-2-26e1b4f2: Cloning into bare repository 'C:\Users\111065\AppData\Roa
ming\npm-cache\_git-remotes\git-github-com-xolvio-cucumber-js-git-v1-3-0-chimp-2
-26e1b4f2'...
npm ERR! git clone --template=C:\Users\111065\AppData\Roaming\npm-cache\_git-rem
otes\_templates --mirror git://github.com/xolvio/cucumber-js.git C:\Users\111065
\AppData\Roaming\npm-cache\_git-remotes\git-github-com-xolvio-cucumber-js-git-v1
-3-0-chimp-2-26e1b4f2: fatal: unable to connect to github.com:
npm ERR! git clone --template=C:\Users\111065\AppData\Roaming\npm-cache\_git-rem
otes\_templates --mirror git://github.com/xolvio/cucumber-js.git C:\Users\111065
\AppData\Roaming\npm-cache\_git-remotes\git-github-com-xolvio-cucumber-js-git-v1
-3-0-chimp-2-26e1b4f2: github.com[0: 192.30.253.113]: errno=No error
npm ERR! git clone --template=C:\Users\111065\AppData\Roaming\npm-cache\_git-rem
otes\_templates --mirror git://github.com/xolvio/cucumber-js.git C:\Users\111065
\AppData\Roaming\npm-cache\_git-remotes\git-github-com-xolvio-cucumber-js-git-v1
-3-0-chimp-2-26e1b4f2: github.com[1: 192.30.253.112]: errno=No error

> chromedriver@2.29.0 install C:\temp\FolderName\node_modules\chromedriver
> node install.js

Downloading https://chromedriver.storage.googleapis.com/2.29/chromedriver_win32.
zip
Saving to C:\Users\111065\AppData\Local\Temp\chromedriver\chromedriver_win32.zip

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 172.217.26.80:443
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
C:\temp\FolderName
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm WARN enoent ENOENT: no such file or directory, open 'C:\temp\FolderName\package.jso
n'
npm WARN FolderName No description
npm WARN FolderName No repository field.
npm WARN FolderName No README data
npm WARN FolderName No license field.
npm WARN In chimp@0.47.2 replacing bundled version of cucumber with cucumber@1.3
.0
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "chimp@0.47.2"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! chromedriver@2.29.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromedriver@2.29.0 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the chromedriver package,

npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\temp\FolderName\npm-debug.log
npm ERR! code 1

**Comment by bjarketrux** [comment]
I've got the same for a Linux buildagent:
```
Downloading https://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip
Saving to /home/sysadm/BuildAgent/temp/buildTmp/chromedriver/chromedriver_linux64.zip
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 216.58.207.112:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
```
Chimp version 0.48.0
Works with Chimp 0.41.1
Note that we are using `http_proxy` and `https_proxy` environment variable

**Comment by Mustang1985** [comment]
@bjarketrux any workaround for the above issue, lemme know

**Comment by bjarketrux** [comment]
@Mustang1985 sorry no. We downgraded to 0.41.1 for now. Will write if I find a solution.
