### ISSUE TITLE
Json output crash when no tests found

### ISSUE THREAD

**Issue by tiagolr** [xolvio/chimp#616]
Running chimp without tests causes the error:

```
node_modules/chimp/dist/lib/cucumberjs/cucumber.js:115
var noTestsFound = JSON.parse(jsonResults).length === 0;
                                                    ^
TypeError: Cannot read property 'length' of null
```

looking at the code the new lines for `'fail-when-no-test-run'` including parsing JSON output are outside the validations checking if JSON output exists.

```js
      // /dist/lib/cucumberjs/cucumber.js: 99
      this.cucumberChild.on('close', function (code) {
        log.debug('[chimp][cucumber] Closed with code', code);

        if (!_this.cucumberChild.stopping) {
          log.debug('[chimp][cucumber] Cucumber not in a stopping state');

          if (_this.options.jsonOutput && jsonResults && JSON.parse(jsonResults).length) {
            var dir = path.dirname(_this.options.jsonOutput);
            log.debug('[chimp][cucumber] Ensuring directory exists', dir);
            fs.mkdirsSync(dir);
            log.debug('[chimp][cucumber] Writing json results to', _this.options.jsonOutput);
            fs.writeFileSync(_this.options.jsonOutput, jsonResults);
            log.debug('[chimp][cucumber] Finished writing results');
          }

          var failWhenNoTestsRun = booleanHelper.isTruthy(_this.options['fail-when-no-tests-run']);
          var noTestsFound = JSON.parse(jsonResults).length === 0;

          callback(code !== 0 || code === 0 && noTestsFound && failWhenNoTestsRun ? 'Cucumber steps failed' : null, jsonResults);
        }
      });
```

**Comment by lgandecki** [comment]
@twilczek @lucetius

**Comment by lgandecki** [comment]
Thanks for reporting, good catch, will be fixed shortly :)

**Comment by defionscode** [comment]
I'm being hit by this

**Comment by RubyGemTSL** [comment]
I also see a crash when failures are found in a test run. Could this be related?

`[chimp] Detected an unhandledRejection:
[chimp][hooks] RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at /Users/ian/Desktop/foo/_tests/e2e/node_modules/meteor-promise/fiber_pool.js:43:40
Unable to parse cucumberjs output into json: './reports/json/cucumber.json' SyntaxError: ./reports/json/cucumber.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.readFileSync (/Users/ian/Desktop/foo/_tests/e2e/node_modules/cucumber-html-reporter/node_modules/jsonfile/index.js:69:17)
    at isValidJsonFile (/Users/ian/Desktop/foo/_tests/e2e/node_modules/cucumber-html-reporter/lib/reporter.js:404:48)
    at Object.generate (/Users/ian/Desktop/foo/_tests/e2e/node_modules/cucumber-html-reporter/lib/reporter.js:426:9)
    at Object.generateReport [as generate] (/Users/ian/Desktop/foo/_tests/e2e/node_modules/cucumber-html-reporter/index.js:30:21)
`

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
