### ISSUE TITLE
[Question]How to use existing saucelab tunnel with chimp?

### ISSUE THREAD

**Issue by vinayak63** [xolvio/chimp#617]
I am able to connect to the saucelab through chimp.But the application under test is an internal application and we have a shared tunnel in saucelab. I am trying to run the tests but I am unable to use saucelab tunnel.Here is my config:

```browser: "chrome",
  platform: "ANY",
  name: "vinny",
  user: "sso-fmi.com-victor",
  key: ""6398aeb9-c8c4-4161-9f47-df4e93e0526b",
  port: 80,
  host: "ondemand.saucelabs.com",
  tunnelIdentifier:"vnari / PACT-TEST29_VNARI",
  parentTunnel:"vnari",
  sauceConnect: true,

  // deviceName: null,
  // - - - - WEBDRIVER-IO  - - - -
  webdriverio: {
    desiredCapabilities: {},
    logLevel: "silent",
    // logOutput: null,
    user: "sso-fmi.com-victor",
    key: "6398aeb9-c8c4-4161-9f47-df4e93e0526b",
    port: 80,
    host: "ondemand.saucelabs.com",
    tunnelIdentifier:"vnari / PACT-TEST29_VNARI",
    parentTunnel:"vnari",
    sauceConnect: true,
  //  path: "/wd/hub",
    baseUrl: null,
    coloredLogs: true,
    screenshotPath: null,
    waitforTimeout: 500,
    waitforInterval: 250,
  } ```

**Comment by billyvg** [comment]
FYI you have your saucelabs key listed.

Try putting your tunnel options inside a `sauceConnectOpts` block, and it appears you need ` wdio-sauce-service` package.

See:
http://webdriver.io/guide/services/sauce.html and 
https://github.com/bermi/sauce-connect-launcher#advanced-usage

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
