### ISSUE TITLE
Update test status on saucelabs if test fails

### ISSUE THREAD

**Issue by feedm3** [xolvio/chimp#618]
#####  Expected behaviour
If a run a test and execute it on saucelabs and it fails I want to mark the test as "failed" in the saucelabs dashbaord.

#####  Actual behaviour
All tests get marked as "success" in the saucelabs dashboard even when they fail.

##### Exact steps to reproduce / repository that demonstrates the problem
I'm using webdriver + mocha to run the tests. The all work as expected even when I run them on saucelabs. But whats not working is that when the assertions fail or an element cannot be found on a page the tests are finishing but don't update the tests status on saucelabs. So all tests are marked as "success" although they did fail.

#####  Version & tools:

* Chimp command line used: `chimp --mocha`
* Chimp config file: Default with saucelabs credentials added ([docs](https://chimp.readme.io/docs/using-saucelabs-browserstack-seleniumgrid))
* Chimp: 0.48.0
* Node.js: 7.9.0
* Java: 1.8.0_92

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
