### ISSUE TITLE
When running long cucumber features, chimp becomes progressively slower

### ISSUE THREAD

**Issue by true-agility** [xolvio/chimp#619]
#####  Expected behaviour
Total execution time of a feature containing multiple scenarios should roughly equal the sum of time running the scenarios separately

#####  Actual behaviour
Execution becomes progressively slower.  After 4 minutes of execution, it can become 3 to 5 times slower.  Heap dump reveals there is memory leak.  Are there known issues with memory leak with any component in the Chimp + Cucumber + WebDriverIO stack?

##### Exact steps to reproduce / repository that demonstrates the problem
Please put long code snips in a [Gist](https://gist.github.com/) and provide a link here.

#####  Version & tools:

* Chimp command line used: 
* Chimp config file: *Please provide a Gist if you use a config file*
* Chimp: 0.47.2
* Node.js: 6.9.4
* Java: 1.8.0_91
* Operation system: OS X El Capitain 10.11.6 (15G1421), Windows 7

#####  Console / Log Output

Nothing abnormal in the log or output

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by workflow** [comment]
Thx for reporting! Possible duplicate: https://github.com/xolvio/chimp/issues/524

**Comment by lgandecki** [comment]
@true-agility could you try with chimp 0.49.0 ? Just released it

**Comment by lgandecki** [comment]
I believe this is fixed, if not, please reopen.

**Comment by true-agility** [comment]
Sorry for the late reply.  Our security tightened proxy and laptop traffic monitoring, and I had problem installing and running 0.49.0.  But yes, I can confirm at last that the latest release speeds up execution quite a bit.  Now longer specs are taking a fraction of what it used to take.

A big thanks for taking care of this.  It will have a big impact on adoption at our company.
