### ISSUE TITLE
How to attach screenshot to json output?

### ISSUE THREAD

**Issue by ashokdudhade** [xolvio/chimp#62]
I have requirement to show cucumber report and display screenshot for failed scenarios. Is there any option in chimp to attach the screenshot to scenario.

**Comment by samhatoum** [comment]
not yet, but we'll add it soon, thanks for the suggestion

**Comment by samhatoum** [comment]
if the screenshot is in the json report as base64, is this enough for you to get going?

**Comment by samhatoum** [comment]
Note to self, this would need to go into the failure capture step

```
var png = global.browser.screenshotSync();
var decodedImage = new Buffer(png, 'base64').toString('binary');
scenario.attach(decodedImage, 'image/png');
```

**Comment by ashokdudhade** [comment]
Yes, base64 in JSON report would help. Thanks

**Comment by samhatoum** [comment]
@ashokdudhade you can now use either `--captureAllStepScreenshots` or `--screenshotsOnError` to get the all/failed steps in the scenario inside the JSON report.

I'm working on a html reporter next

**Comment by samhatoum** [comment]
@ashokdudhade just a heads up, this is no longer default behavior. you need to set `--attachScreenshotsToReport` for screenshots to be added to the json report

**Comment by StephenDavidson** [comment]
Was just playing around with this and the screenshots have to be saved to the same directory as the report or else the cucumber json becomes null when setting the `attachScreenshotsToReport` flag
