### ISSUE TITLE
@critical scenarios are run under both domain scenarios and e2e scenarios

### ISSUE THREAD

**Issue by dkoo761** [xolvio/chimp#621]
#####  Expected behaviour

Scenarios tagged with @critical are only run as e2e tests.

#####  Actual behaviour

Scenarios tagged with @critical are run as both domain tests and e23 tests causing warnings of "undefined" step definitions under the domain tests section.

##### Exact steps to reproduce / repository that demonstrates the problem

1) create a Cucumber feature file with at least 1 scenario tagged with @critical

2) in /path/to/project/tests/step_definitions/critical, add step definitions

3) do NOT add any step definitions in /path/to/project/tests/step_definitions/domain

3) start chimp with these options: 

```
--ddp=http://localhost:3000
--watchSource=/path/to/project/tests
--singleSnippetPerFile=1
--no-source
--path=/path/to/project/tests/features
--domainSteps=/path/to/project/tests/step_definitions/domain
--e2eSteps=/path/to/project/tests/step_definitions/critical
--watch
```

4) Under "[chimp] domain scenarios..." there will be warnings of undefined step definitions. Why is Chimp trying to run the critical scenario here?

#####  Version & tools:

* Chimp command line used:

`NO_METEOR=1 /path/to/project/.scripts/node_modules/.bin/chimp [with options above]`

* Chimp config file: N/A

* Chimp: 0.49.0

* Node.js: v5.2.0

* Java: 
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

* Operation system:
Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64

#####  Console / Log Output

https://gist.github.com/dkoo761/26b301bebb491e6d5de3a5156fa72610

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
