### ISSUE TITLE
Chimp + Docker w/ Ubuntu image requires installing git-all, not just git

### ISSUE THREAD

**Issue by dkoo761** [xolvio/chimp#623]
#####  Expected behaviour

When building a Dockerfile for use with Chimp on an Ubuntu image, I would expect the following Docker command to be sufficient to install git as part of the builder as this is how most people would install git on an Ubuntu image:

`RUN apt-get install git -y`

#####  Actual behaviour

When the command above is used to install git, running the subsequent image generated by the Dockerfile in a Docker container results in Chimp exiting with code 0 before running any tests.

Instead, the following command is needed to install git via the Dockerfile in order for Chimp tests to run:

`RUN apt-get install git-all -y`

##### Exact steps to reproduce / repository that demonstrates the problem

Unfortunately, I can't share code for this project due to a confidentiality agreement but I can paraphrase what's in the Dockerfile:

- FROM ubuntu:14.04
- mkdir and add code from the current Meteor app to that directory
- do basic apt-get update
- install python and python tools
- install git
- install curl
- install Node.js 5.2.0
- "npm install" to install Chimp 0.49 and it's dependencies from package.json
- CMD to start Chimp via npm script

Build the Docker image:

`docker build -t my-project:latest .`

Start Meteor server locally on http://localhost:3000.

Run the Docker image:

`docker run --network=host -e TEST_URL="http://<MY_IP_ADDR>:3000" my-project`

#####  Version & tools:

* Chimp command line used:

```
/path/to/project/.scripts/node_modules/.bin/chimp [with following options...]

--ddp=http://localhost:3000
--watchSource=/path/to/project/tests
--singleSnippetPerFile=1
--no-source
--browser=phantomjs
--path=/path/to/project/tests/features
--e2eSteps=/path/to/project/tests/step_definitions/critical
```

* Chimp config file: N/A

* Chimp: 0.49.0

* Node.js: v5.2.0

* Java: 
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

* Operation system:
Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64

#####  Console / Log Output

```
> my-project@ start /path/to/app
> .scripts/start.js

Master Chimp and become a testing Ninja! Check out our course: http://bit.ly/2btQaFu

[chimp] Running...
Chimp exited with code 0
```

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
