### ISSUE TITLE
When Chimp error out it does not continue onto the next test.

### ISSUE THREAD

**Issue by kwongr** [xolvio/chimp#624]
#####  Expected behaviour
Test should continue after test case fail

#####  Actual behaviour
All test case start failing after one fail.

##### Exact steps to reproduce / repository that demonstrates the problem
Please put long code snips in a [Gist](https://gist.github.com/) and provide a link here.

Here is a simple code just to visit a slow site .  I have three of the same file under one directory.  When the first one fail,  it will skip page 2 3 and 4 of the test.  When it goes to the next file,  it will also timeout.
code
-------------------------------------------------------------------------------------

describe('Go to Serp Content', function () {
  beforeEach(() => {
    browser.url('http://www.dictionary.com');
    browser.pause(2000);
  });

  describe('Go to page 1 time', () => {

    it('Go to page 1', () => {
      const cardTitle = browser.getUrl();
    });

    it('Go to page 2 time', () => {
      const content = browser.getUrl();
    });

    it('Go to page 3 time', () => {
      const cardTitle = browser.getUrl();
    });

    it('Go to page 4 time', () => {
      const content = browser.getUrl();
    });

  });

});

--------------------------------------------------------------------

#####  Version & tools:

* Chimp command line used: *The exact command you used*
./node_modules/.bin/chimp ./chimp-regressionnowatch.js --path=./report-bug --mocha

* Chimp config file: *Please provide a Gist if you use a config file*
* Chimp: *type `chimp -v`*
./node_modules/.bin/chimp -v
0.49.0
* Node.js: *type `node -v`*
node -v
v6.9.1
* Java: *type `java -version`*
 java -version
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)
* Operation system: *type `uname -v`*
uname -v
Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64
#####  Console / Log Output

Please put long logs in a [Gist](https://gist.github.com/) and provide a link here.

----------------------------------------------------------
 Go to Serp Content
    Go to page 1 time
      ✓ Go to page 1
      1) "before each" hook for "Go to page 2 time"

  Go to Serp Content
    Go to page 1 time
      2) "before each" hook for "Go to page 1"

  Go to Serp Content
    Go to page 1 time
      3) "before each" hook for "Go to page 1"

  1 passing (3m)
  3 failing

  1) Go to Serp Content "before each" hook for "Go to page 2 time":
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  

  2) Go to Serp Content "before each" hook for "Go to page 1":
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  

  3) Go to Serp Content "before each" hook for "Go to page 1":
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  

Mocha failed

npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/KwongR/.nvm/versions/node/v6.9.1/bin/node" "/Users/KwongR/.nvm/versions/node/v6.9.1/bin/npm" "run" "reportbug"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! @ reportbug: `./.scripts/start-chimp-reportbug.sh`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ reportbug script './.scripts/start-chimp-reportbug.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./.scripts/start-chimp-reportbug.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/KwongR/githost-mweb-serp/regression-suite/npm-debug.log
-----------------------------------------------------------------

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
