### ISSUE TITLE
Question: I have tons of _xxx.js files showing under my main project folder. Do not know if I need them  or where they belog?

### ISSUE THREAD

**Issue by mpourali-FMI** [xolvio/chimp#627]
##### Exact steps to reproduce / repository that demonstrates the problem
Please put long code snips in a [Gist](https://gist.github.com/) and provide a link here.

#####  Version & tools:

* Chimp command line used: *The exact command you used*
* Chimp config file: *Please provide a Gist if you use a config file*
* Chimp: *type `chimp -v`*
* Node.js: *type `node -v`*
* Java: *type `java -version`*
* Operation system: *type `uname -v`*

#####  Console / Log Output

Please put long logs in a [Gist](https://gist.github.com/) and provide a link here.

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by samhatoum** [comment]
Please read the instructions for posting an issue
