### ISSUE TITLE
Chimp Global install suddenly failing on circle CI

### ISSUE THREAD

**Issue by Pushplaybang** [xolvio/chimp#629]
I've had this working just fine for months, and without changes to my setup scripts chimp is now failing to install.  I've largely copied the meteor todo app testing setup and customized from there.  Chimp install seems to fail on a number of dependencies,   with "module not found".

#####  Expected behaviour
It should install chimp globally.

#####  Actual behavior
it can't find, presumably, dependencies, and fails to install making it impossible to run the chimp command. 

##### Exact steps to reproduce / repository that demonstrates the problem
`npm install chimp -g` on circle CI.

#####  Version & tools:
from my circle CI file:

```yml
machine:
  node:
    version: 4.6.2

<!-- please leave the content below this line as it helps others find help -->
------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by mikecentiq** [comment]
I'm having the same issue on Travis. Which I have replicated below. The issue goes away if I use node v6 instead of v4, but meteor wants me to use v4.

```
mike@pc-mcard-03:~$ node --version
v4.8.0
mike@pc-mcard-03:~$ npm --version
2.15.11
mike@pc-mcard-03:~$ npm i -g chimp
npm WARN optional dep failed, continuing fsevents@1.1.2
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
 
> fibers@1.0.15 install /home/mike/.nvm/versions/node/v4.8.0/lib/node_modules/chimp/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-46` exists; testing
Binary is fine; exiting
 
> chromedriver@2.30.1 install /home/mike/.nvm/versions/node/v4.8.0/lib/node_modules/chimp/node_modules/chromedriver
> node install.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'json-stable-stringify'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/mike/.nvm/versions/node/v4.8.0/lib/node_modules/chimp/node_modules/request/node_modules/har-validator/node_modules/ajv/lib/compile/util.js:19:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
/
> phantomjs-prebuilt@2.1.13 install /home/mike/.nvm/versions/node/v4.8.0/lib/node_modules/chimp/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Verified checksum of previously downloaded file
Extracting tar contents (via spawned process)
Removing /home/mike/.nvm/versions/node/v4.8.0/lib/node_modules/chimp/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1499772119706/phantomjs-2.1.1-linux-x86_64 -> /home/mike/.nvm/versions/node/v4.8.0/lib/node_modules/chimp/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /home/mike/.nvm/versions/node/v4.8.0/lib/node_modules/chimp/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
npm ERR! Linux 4.4.0-83-generic
npm ERR! argv "/home/mike/.nvm/versions/node/v4.8.0/bin/node" "/home/mike/.nvm/versions/node/v4.8.0/bin/npm" "i" "-g" "chimp"
npm ERR! node v4.8.0
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! chromedriver@2.30.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chromedriver@2.30.1 install script 'node install.js'.
npm ERR! This is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mike/npm-debug.log
mike@pc-mcard-03:~$ 
```

**Comment by Redroest** [comment]
It now works for me on Windows using node version 6.10.3

**Comment by mikecentiq** [comment]
Meteor 1.5 uses Node 4. People typically test their code with the same version of node that they use to run their code.

**Comment by samhatoum** [comment]
Hey @mikecentiq. It's totally fine to run chimp on a different version of node as it's a separate process.

**Comment by samhatoum** [comment]
None of the code that chimp runs is (nor should be) application code from Meteor

**Comment by mikecentiq** [comment]
What about my application code? The code that I write for my Meteor applications, runs under Node 4, because that's what Meteor requires. Testing my code using Node 6 is not a good solution.

**Comment by Pushplaybang** [comment]
updating circle to 6.1.0 solves this, and works perfectly with the rest of the test suite / meteor @mikecentiq

**Comment by mikecentiq** [comment]
The Circle CI problem was a side effect of the problem with Chimp. The problem also existed with Travis. We have taken the time to remove Chimp from our projects now, so this is no longer an issue for us.

**Comment by samhatoum** [comment]
@mikecentiq 
> is there an intention to make chimp work under Node 4 again, or are you going to tell people to use Node 6 from now on?

Yes there is, we're rewriting chimp as we speak. 2.0 beta is expected to be released in the next 1-3 weeks. This is an unbundled version of Chimp so you can pick and choose what you want to use for each use-case.

> We have taken the time to remove Chimp from our projects now, so this is no longer an issue for us.

Sorry to hear that, hope the next version will solve the issues. Out of interest, what are you using now instead? Are you still using Cucumber?
