### ISSUE TITLE
IEDriverServer version 

### ISSUE THREAD

**Issue by dehamilton** [xolvio/chimp#63]
When I installed Chimp to follow the tutorial, I received an error on startup that prevented the Selenium server from installing/starting. The error was:

[selenium] [Error: Could not request headers from http://selenium-release.storage.googleapis.com/2.47/IEDriverServer_x64_2.47.1.zip: ]

I edited the chimp\lib\selenium.js file line 75, replacing: version: '2.47.1' with version: '2.47.0' and that resolved the problem.

There isn't yet a file at the Google API location referenced above.

**Comment by ejlofgren** [comment]
:+1: @dehamilton Thank you so much for sharing this. I tried many things to get chimp working on Windows 10 yesterday and this simple fix was all that was needed.

**Comment by tunght13488** [comment]
:+1: @dehamilton
