### ISSUE TITLE
Watch mode doesn't work when running tests via `.run()` (Node API)

### ISSUE THREAD

**Issue by williamboman** [xolvio/chimp#630]
#####  Expected behaviour

```js
const Chimp = require('chimp')
const defaultChimpConfig = require('chimp/dist/bin/default')
const chimp = new Chimp({
    ...defaultChimpConfig,
    watch: true,
    '_': [
        process.execPath,
        path.resolve(__dirname, '..', 'node_modules', '.bin', 'chimp'),
    ],
})
chimp.run((err, res) => {
    // this shouldn't be called unless err !== null
})
```

#####  Actual behaviour

The callback to `chimp.run()` is invoked, and chimp doesn't respect `{watch: true}`.

##### Exact steps to reproduce / repository that demonstrates the problem
Please put long code snips in a [Gist](https://gist.github.com/) and provide a link here.

#####  Version & tools:

* Chimp command line used: use node api, see code snippet
* Chimp config file: see code snippet
* Chimp: `0.49.0`
* Node.js: `6.11.0`
* Java: `1.8.0_131`
* Operation system: `Darwin Kernel Version 16.6.0`

#####  Console / Log Output

Please put long logs in a [Gist](https://gist.github.com/) and provide a link here.

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

I initially ran tests via `.init` but later used `.run` as all examples used it and I assumed `.init` was just an alias.

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
