### ISSUE TITLE
All steps are undefined if step definition folder is a sibling to features folder

### ISSUE THREAD

**Issue by Windso** [xolvio/chimp#632]
#####  Expected behaviour
Chimp runs everything just fine

#####  Actual behaviour
Chimp cannot locate the step definitions if the step_definitions folder is outside of the feature folder, so all features are undefined and get skipped.

#####  This directory setup works:
- features
- - look.feature
- - login.feature
- - step_definitions
- - - look.js
- - - login.js
- report

#####  This directory setup fails:
- features
- - look.feature
- - login.feature
- step_definitions
- - look.js
- - login.js
- report

I would like to keep my step_definitions folder outside of my features folder. How do I do this?

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by samhatoum** [comment]
You can use the `-r` switch to add folders

**Comment by Windso** [comment]
This worked for me:
`require: './tests/automation/step_definitions'`
