### ISSUE TITLE
Getting Chimp to configure Chrome not ask to save passwords

### ISSUE THREAD

**Issue by rsshilli** [xolvio/chimp#635]
Hello,

Thank you for creating Chimp!  Very useful.  

When I run my tests, especially after every login (which happens a lot), chrome pops up asking "Do you want Chrome to save your password?".  I'm trying to avoid that popup.

Webdriver IO [already has a solution to this](https://stackoverflow.com/questions/16301457/webdriver-chrome-browser-avoid-do-you-want-chrome-to-save-your-password-pop-u), but I can't figure out how to configure those options in my chimp.js file.  [Selenium has a solution too](https://sqa.stackexchange.com/questions/26275/how-to-disable-chrome-save-your-password-selenium-java?newreg=831c1f595fad458e80bd98088ec416e4), but again, I don't see any way to configure that either :-(.

Anybody have any ideas? 

I'm using Chimp 0.46.0 if that matters.  I'm happy to change versions for this.

Ryan

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by wuthiago** [comment]
Hello Ryan,
I believe you need to create a config file, add that solution you found for Webdriver.io in it and pass it as the first parameter when you run chimp. What I usually do is to copy the default.js config file that comes with chimp (chimp/dist/bin) and add the desired capabilities options in its section under WEBDRIVER.IO. When I run chimp the very first parameter is path/chimp_new_config.js. Try it out and let us know.

**Comment by rsshilli** [comment]
Thanks @wuthiago .  I already have a chimp.js file but I should have posted before what I've tried inside of it.  Here it is:

    module.exports = {
      path: "build/test/features",
      watchSource: "build/main/webapp/*.js,build/main/nodejs",
      showXolvioMessages: false,
      webdriverio: {
        waitforTimeout: 30000,
        chromeOptions: {
          prefs: {
            "credentials_enable_service": false,
            "profile": {
              "password_manager_enabled": false
            }
          }
        }
      },
    };

Adding the chromeOptions doesn't seem to help any.  Looks like it's being ignored :-(.

**Comment by rsshilli** [comment]
I figured it out!  Here it is:

    module.exports = {
      path: "build/test/features",
      watchSource: "build/main/webapp/*.js,build/main/nodejs",
      showXolvioMessages: false,
      webdriverio: {
        waitforTimeout: 30000,
        desiredCapabilities: {
          chromeOptions: {
            prefs: {
              "credentials_enable_service": false,
              "profile": {
                "password_manager_enabled": false
              }
            }
          }
        }
      },
    };
