### ISSUE TITLE
Not able to run Chimp on windows 7 using Internet Explorer

### ISSUE THREAD

**Issue by wuthiago** [xolvio/chimp#636]
#####  Expected behaviour
I expect to be able to run chimp in Windows 7 with Internet Explorer 11.0

#####  Actual behaviour
I am getting an error message saying the best matching driver provider org.openqa,selenium.edge.EdgeDriver can't create a new driver instance for Capabilites...

##### Exact steps to reproduce / repository that demonstrates the problem
Please put long code snips in a [Gist](https://gist.github.com/) and provide a link here.
1. Download IEDriver from seleniumHQ website.
2. Unzip it and add the location of the .exe file to the PATH sys variable.
3. Create an exact copy of the default config file and add the following Desired Capabilities under WEBDRIVER-IO section:
// - - - - WEBDRIVER-IO  - - - -
  webdriverio: {
    desiredCapabilities: {
		browserName: "internet explorer",
		version: "11.0"
	},
    logLevel: 'silent',
    // logOutput: null,
    host: '127.0.0.1',
    port: 4444,
    path: '/wd/hub',
    baseUrl: null,
    coloredLogs: true,
    screenshotPath: null,
    waitforTimeout: 500,
    waitforInterval: 250
  },
4. Run chimp with the following command:
node ./node_modules/chimp/bin/chimp.js node_modules/chimp/dist/bin/chimp-ie.js --browser=ie --saveScreenshotsToDisk=false --saveScreenshotsToReport=true --screenshotsOnError=true -f pretty -f json:e2e.json

#####  Version & tools:

* Chimp command line used: node ./node_modules/chimp/bin/chimp.js ./node_modules/chimp/dist/bin/chimp-ie.js --browser=ie --saveScreenshotsToDisk=false --saveScreenshotsToReport=true --screenshotsOnError=true -f pretty -f json:e2e.json
* Chimp config file: https://gist.github.com/wuthiago/3a58502a41eaf6de1e91baf2650adf13
* Chimp: 0.45.0
* Node.js: v4.2.3
* Java: java version "1.8.0._121"
* Operation system: Windows 7 Professional / 64 bits

#####  Console / Log Output
http://imgur.com/a/PVeFt

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by vuongngolg** [comment]
I guess you should run with **--browser=internet explorer** instead of **--browser=ie**

**Comment by wuthiago** [comment]
I tried that and a couple of other combinations. It didn't work.

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
