### ISSUE TITLE
How do I run Chimp with Headless Chrome, without Phantomjs?

### ISSUE THREAD

**Issue by Windso** [xolvio/chimp#637]
I currently am running Chimp with Phantomjs. It works for the most part, but Phantomjs has always been buggy and has recently been officially depreciated in favor of headless chrome. 

I'm running Chimp with Grunt, and my Gruntfile has this: `browser:'phantomjs'`. Would I change it to something like `browser:'chrome-headless'`? Or would it be in a chimp config file? A webdriverio config file?

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by grekinsky** [comment]
There are plenty of headless browser docker images you can use, here is one I built for running chimp.js on headless chromium: https://hub.docker.com/r/grekinsky/chromium-headless-testing/

Cheers!

**Comment by Windso** [comment]
I found the solution. My Chimp config file (`chimp.js`) looks like this:
```
// - - - - WEBDRIVER-IO  - - - -
    webdriverio: {
        desiredCapabilities: {
            chromeOptions: {
                args: ["headless", "disable-gpu"]
            },
            isHeadless: true
        }
    },
```

**Comment by samhatoum** [comment]
thank you for posting the solution here. Be sure to check out the [chimp2.0 branch](https://github.com/xolvio/chimp/tree/chimp2.0)

**Comment by rooch84** [comment]
Thanks @Windso, I was on the right lines, but couldn't get the syntax right until I saw your example.

**Comment by jag-tus** [comment]
Thanks @Windso, I didn't know PhantomJS was officially deprecated. This helps explain the bugginess.
