### ISSUE TITLE
ability to add jasmine reporters

### ISSUE THREAD

**Issue by WickyNilliams** [xolvio/chimp#640]
#####  Expected behaviour

Allow jasmine reporters to be added through chimp config. I would expect there to be a `jasmineReporters` array field in the chimp config, which is looped through and `jasmine.getEnv().addReporter(...)` called for each item in the array.

#####  Actual behaviour

Cannot do so.

##### Exact steps to reproduce / repository that demonstrates the problem

I want to use `jasmine-spec-reporter` npm package, but the only option is for configuring the default reporter. I should be able to add new reporters.

#####  Version & tools:

n/a

#####  Console / Log Output

n/a

**Comment by Marqui-be** [comment]
Same here, hacking my way to a solution.

**Comment by paul-ihnatolia** [comment]
Can you post your current solution ?

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
