### ISSUE TITLE
Chimp running.... (and doesnn't do anything at all)

### ISSUE THREAD

**Issue by Gobliins** [xolvio/chimp#641]
I have a meteor app and want to setup some tests. The chosen components for now are chimp and mocha.

In my Meteor folder i have inlcuded a tests/mocha/directory.

And included my first test (got this from a tutorial) in a file mochatest.js

`describe('Chimp Mocha', function() {   `
`  describe('Page title', function () {   `
`    it('should be set by the Meteor method @watch', function () {   `
`      browser.url('http://www.google.com');   `
`      expect(browser.getTitle()).to.equal('Google');   `
`    });   `
`  });   `
`});`  

So now i tried using chimp to run my mochatest with this command:

`chimp --ddp=http://localhost:8080 --mocha —path=tests/mocha`

i got this output:

`Master Chimp and become a testing Ninja! Check out our course:  http://shortenedurl/...`

`[chimp] Running... `

And after that chimp exited or doing nothing.

I also tried different setups with chimp and meteor config files 

`module.exports = {`
`  path: 'mochaaaaaa',`
`  mocha: true,`
`  mochaCommandLineOptions: ['--color'],`
`  mochaConfig: {`
`    // tags and grep only work when watch mode is false`
`    tags: '',`
`    grep: null,`
`    timeout: 40000,`
`    reporter: 'spec',`
`    slow: 100,`
`    //retries: 3,`
`    bail: true, // bail after first test failure`
`  },`
`  ddp: 'http://localhost:24000',`
`};`

and running chimp over meteor 

`meteor npm run chimp-test`

but i always end up with the same result.

When running mocha without chimp, the tests are executed.

What have i done wrong?

**Comment by samhatoum** [comment]
try with the `--debug` flag

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
