### ISSUE TITLE
webdriverio plugins

### ISSUE THREAD

**Issue by joscha** [xolvio/chimp#644]
#####  Expected behaviour

Loading a webdriverio plugin (https://github.com/percy/percy-webdriverio).

#####  Actual behaviour

Plugins seem to be ignored, e.g.  a `chimp.js` with:
```
module.exports = {
  jsonOutput: 'target/cucumber/report.json',
  path: 'src',
  profile: 'integration-tests',
  saveScreenshotsToReport: true,
  screenshotsPath: 'target/cucumber/screenshots',
  showXolvioMessages: false,
  webdriverio: {
    plugins: {
      'percy-webdriverio': {}
    }
  }
};
```
doesn't seem to load `percy-webdriverio`.

##### Exact steps to reproduce / repository that demonstrates the problem
Please put long code snips in a [Gist](https://gist.github.com/) and provide a link here.

#####  Version & tools:

* Chimp command line used:
```
chimp conf/chimp.js "$@"
```
via a `yarn` task

* Chimp config file: _see above_
* Chimp: `0.49.1`
* Node.js: `8.2.1`
* Java: `openjdk version "1.8.0_112"`
* Operation system: OSX Sierra `Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64`

#####  Console / Log Output

```
1) Scenario: Layer opens - src/ui/layer/features/layer.feature:4
   Step: Before
   Step Definition: src/features/step_definitions/general.steps.ts:17
   Message:
     TypeError: browser.percyUseAssetLoader is not a function
         at World.<anonymous> (src/features/step_definitions/general.steps.ts:25:15)

2) Scenario: Layer opens - src/ui/layer/features/layer.feature:4
   Step: After
   Step Definition: src/features/step_definitions/general.steps.ts:29
   Message:
     TypeError: browser.percyFinalizeBuild is not a function
         at World.<anonymous> (src/features/step_definitions/general.steps.ts:31:15)
```

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by samhatoum** [comment]
this won't work with chimp as you need to use the wdio runner to use plugins AFAIK

percy looks awesome though. I'll look into integrating it to chimp 2.0
