### ISSUE TITLE
multiple instances launched w/ Jasmine in watch mode

### ISSUE THREAD

**Issue by hexsprite** [xolvio/chimp#645]
#####  Expected behaviour

A single instance of the browser is launched when running jasmine tests in watch mode

#####  Actual behaviour

Multiple instances are launched

##### Explanation

I did some further debugging and found that the issue is initial chokidar events are triggering for each existing file. Also in subsequent runs multiple chokidar events may be generated. I will provide a PR that solves this.

**Comment by hexsprite** [comment]
oops, looks like 2 tests are failing, presumably because they trigger a callback within the 500ms debounce period and they test for number of invocations of `chimp.run`.

not sure the best way to solve this, some ideas:

- use something like `lolex` to simulate the duration of time so that the debounce is also tested as part of this
- just wrap it so that chimp.run is the debounced function so debouncing is bypassed

also seems like I should add a test for the bug I fixed, something along the lines of multiple watch events within a short period of time only result in a single invocation of `chimp.run`.

**Comment by hexsprite** [comment]
@samhatoum note my questions above, wasn't sure what the best fix was, care to chime in ?

**Comment by samhatoum** [comment]
hey man. I'm about to take all the changes in and them make them work locally. Debouncing is definitely the right answer to the multiple instance problems. Test wise, I think we can simulate it and lolex sounds good
