### ISSUE TITLE
Tutorial page invisible

### ISSUE THREAD

**Issue by jrpool** [xolvio/chimp#649]
-- keep all the text below this line, but feel free to remove everything fro this line up before you post -->
#####  Expected behaviour
https://chimp.readme.io/docs/tutorial will be visible.

#####  Actual behaviour
It is invisible in in Safari, Chrome, and Firefox on OS X 10.12.6.

##### Exact steps to reproduce / repository that demonstrates the problem
Visit the page with a browser.

#####  Version & tools:

* Chimp command line used: N/A
* Chimp config file: N/A
* Chimp: N/A
* Node.js: N/A
* Java: N/A
* Operation system: OS X 10.12.6.

#####  Console / Log Output
N/A

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
