### ISSUE TITLE
Add cucumber defineParameterType support to Chimp.

### ISSUE THREAD

**Issue by Aracturat** [xolvio/chimp#650]
I want to use defineParameterType ( https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/api_reference.md ) from Cucumber to preprocess parameters.

This is realized in Cucumber project here https://github.com/cucumber/cucumber-js/blob/master/src/support_code_library_builder/define_helpers.js .

Is it possible to include this functionality to your cucumber fork?

**Comment by samhatoum** [comment]
this will be available in the upcoming Chimp 2.0. The current version of chimp does not support the latest cucumber. Chimp 2.0 is currently in alpha and will be in beta in a week or two.

**Comment by Aracturat** [comment]
Does current code of Chimp 2.0 support cucumber now?

**Comment by samhatoum** [comment]
yes it does. see the examples in the chimp2.0 branch

**Comment by Aracturat** [comment]
Does cucumber in chimp 2.0 support watch mode?

**Comment by samhatoum** [comment]
not yet, at least not out of the box. You can use gulp.js or similar to do watching. We will have a watch mode soon
