### ISSUE TITLE
V8 deprecation causes 'make' crash when installing Chimp with Meteor 1.6-beta

### ISSUE THREAD

**Issue by martinhbramwell** [xolvio/chimp#652]
#####  Expected behaviour

Can install Chimp without error

#####  Actual behaviour

```make``` crash when installing Chimp

    you@yours:~/projects/yours$ 
    you@yours:~/projects/yours$ meteor npm install chimp
    npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

    > fibers@1.0.15 install /home/you/projects/yours/node_modules/chimp/node_modules/fibers
    > node build.js || nodejs build.js

    make: Entering directory '/home/you/projects/yours/node_modules/chimp/node_modules/fibers/build'
      CXX(target) Release/obj.target/fibers/src/fibers.o
    ../src/fibers.cc: In function ‘v8::Handle<v8::String> uni::NewLatin1String(v8::Isolate*, const char*)’:
    ../src/fibers.cc:122:64: warning: ‘static v8::Local<v8::String> v8::String::NewFromOneByte(v8::Isolate*, const uint8_t*, v8::String::NewStringType, int)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
       return String::NewFromOneByte(isolate, (const uint8_t*)string);
                                                                    ^
    In file included from /home/you/.meteor/packages/meteor-tool/.1.6.0-beta.30.cdfxxa++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:26:0,
                     from /home/you/.meteor/packages/meteor-tool/.1.6.0-beta.30.cdfxxa++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/node.h:63,
                     from ../src/coroutine.h:1,
                     from ../src/fibers.cc:1:
    /home/you/.meteor/packages/meteor-tool/.1.6.0-beta.30.cdfxxa++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8.h:2626:21: note: declared here
           Local<String> NewFromOneByte(Isolate* isolate, const uint8_t* data,
                         ^
    /home/you/.meteor/packages/meteor-tool/.1.6.0-beta.30.cdfxxa++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/include/node/v8config.h:329:3: note: in definition of macro ‘V8_DEPRECATED’
       declarator __attribute__((deprecated(message)))
       ^      
              :             :             :
              :             :             :
              :             :             :
              
    you@yours:~/projects/yours$ meteor npm --version
    5.4.1
    you@yours:~/projects/yours$ meteor --version
    Meteor 1.6-beta.30                            
    you@yours:~/projects/yours$ meteor node --version
    v8.5.0

**Comment by samhatoum** [comment]
We don't support node 8.x versions yet
