### ISSUE TITLE
When a selector matches more than 100 elements, errors occur: connect ECONNRESET 127.0.0.1:63127, write EPIPE, read ECONNRESET

### ISSUE THREAD

**Issue by Windso** [xolvio/chimp#653]
These errors have been occurring during my tests at random and it has been very frustrating. They seem to happen at random, and it causes ALL proceeding tests to fail. 

I did some tests to try to isolate the issue, and found that when a selector matches a ton of elements it causes these errors. Here is the actual test I did.

I have an HTML file that consists purely of empty paragraph tags. I tested it in increments of 5. So `100 p tags`, `105 p tags`, `110 p tags`, .... `200 p tags`
```html
<p></p>
<p></p>
<p></p>
<!-- a lot more <p> tags... -->
```

And here is the code from the step definition that I was using: 
```javascript
for (var i = 1; i < 501; i++) {
    console.log(browser.isVisible("p").length + ": " + i);
}
```
What it does is it tries to log the number of elements that are on the page (and which iteration its on). It tries to log it 500 times, but it fails. Here are some of the error messages I got:

```
Error: connect ECONNRESET 127.0.0.1:58881
Error: connect ECONNRESET 127.0.0.1:63127
Error: connect ECONNRESET 127.0.0.1:63427
Error: write EPIPE
Error: connect ECONNRESET 127.0.0.1:65240
Error: write EPIPE
Error: connect ECONNRESET 127.0.0.1:49866
Error: connect ECONNRESET 127.0.0.1:52942
Error: read ECONNRESET
Error: write EPIPE
Error: connect ECONNRESET 127.0.0.1:61475
Error: read ECONNRESET
Error: connect ECONNRESET 127.0.0.1:57277
Error: connect ECONNRESET 127.0.0.1:58126
Error: write EPIPE
Error: read ECONNRESET
Error: connect ECONNRESET 127.0.0.1:50770
Error: read ECONNRESET
Error: connect ECONNRESET 127.0.0.1:56693
Error: connect ECONNRESET 127.0.0.1:61033
```
And here are my test results. I did it with both Phantomjs and Chrome headless and both had the same errors, but Chrome seemed to handle the data much better.
![My data](https://i.imgur.com/ZgeKi5J.png)
I'm not sure if this is an issue with Webdriverio, Selenium Webdriver, or what, but I'm really stuck. Does anyone have any ideas?

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by Windso** [comment]
I found the cause of this. It was just PhantomJS crashing because I have a lot of tests and Phantom sucks. My solution is to use Google Chrome instead of PhantomJS.

**Comment by samhatoum** [comment]
thank you for reporting back, this one had me baffled!
