### ISSUE TITLE
Is chimp dead?

### ISSUE THREAD

**Issue by bjarketrux** [xolvio/chimp#655]
Sorry for the click-bait title but it seems that there is very little activity on the issues and pull requests.

Anyone has a status on chimp?

Basically I have a very simple pull request from back in august that no one looked at since.
Thanks

**Comment by samhatoum** [comment]
Hi @bjarketrux 

Thank you for the kick up the backside. You're right to call it out. Chimp is not dead, I've been super busy working on my startup (almost ready) and consulting hence the slow-down. But let me and @lgandecki get back on these ASAP.

**Comment by lgandecki** [comment]
We are using in production, one of my projects we run:
~600 tests multiple times a day on CI:
<img width="1100" alt="screen shot 2017-10-09 at 13 20 37" src="https://user-images.githubusercontent.com/4002543/31337770-ae4efbc2-acf4-11e7-91bf-4b1b6bb6ffe1.png">

As long as we are using it, chimp has no chance of dying ;-)
At the same time, it doesn't mean that we will have time to review and apply fixes in matters of weeks, especially if they don't affect us... If waiting a month for a merge is a sign of Open Source project to be dead, then 99% of OS is dead ;-)

Having said that, sorry for the delay, we will get take a look at it soon, as Sam said, super busy, but anytime we get busy, that means, we get more funds to, also, do more OS stuff :)

**Comment by lgandecki** [comment]
And most importantly - thanks A LOT for creating PR :) Instead of just complaining and waiting for us to fix. Really appreciate that!
