### ISSUE TITLE
Packaging error - 0.50 includes all node_modules

### ISSUE THREAD

**Issue by jbblanchet** [xolvio/chimp#657]
#####  Expected behaviour

The npm package should not include the node_modules folder.

#####  Actual behaviour

If you open the tarball from `https://registry.npmjs.org/chimp/-/chimp-0.50.0.tgz` you'll notice that the node_modules folder is included, which should not happen. It is especially problematic for Fibers, which contains an executable for specific os/node versions. It doesn't appear to be a new problem, as previous packages had the exact same behavior (except for 0.49, which strangely had way less stuff in its `node_modules`), but right now it makes v0.50 unusable on my particular setup because the right executable `linux-x64-57` is missing from `/node_modules/chimp/node_modules/fibers/bin`.

##### Exact steps to reproduce / repository that demonstrates the problem

Look inside the tar at `https://registry.npmjs.org/chimp/-/chimp-0.50.0.tgz`

#####  Version & tools:

N/A

#####  Console / Log Output

N/A

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by samhatoum** [comment]
Fixed in 0.50.2
