### ISSUE TITLE
Documentation for local testing with Browserstack - Chimp & WebdriverIO

### ISSUE THREAD

**Issue by Windso** [xolvio/chimp#659]
I wanted to run my automation tests using a browser provided by Browserstack but had a lot of trouble with it. There is no documentation for setting up Chimp with Browserstack, and it's different from just using WebdriverIO. Here is what worked for me.

My chimp config file (`chimp.js`) looks like this:
```
module.exports = {

    // - - - - CHIMP - - - -
    user: "My Browserstack Username",
    key: "My Browserstack Access Key",
    port: 80,
    host: "hub-cloud.browserstack.com",
    browser: "Chrome",

    // - - - - WEBDRIVER-IO  - - - -
    webdriverio: {
        desiredCapabilities: {
            'browserstack.local': true,
            'build': 'My Build',
            'project': 'My Project Name',
            'os' : 'Windows',
            'os_version' : '7'
        }
    },

};
```
Please note, do not set the chimp `name` property. I'm not sure why, but doing this caused Cucumber to skip all the tests. It ran the `BeforeFeatures` function successfully, but it never ran any of the actual features. It logged this message:
```
0 scenarios
0 steps
0m00.000s
```

Can we get an official documentation page for Browserstack going? I saw [this thread](https://github.com/xolvio/chimp/issues/223), but it was closed just point to the [Chimp cloud services page](https://chimp.readme.io/docs/using-saucelabs-browserstack-seleniumgrid) which offers no useful information. 

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by samhatoum** [comment]
Super appreciate you posting this here

I've added your configuration to the docs. Do bear in mind that we're working on Chimp 2.0 and will soon put Chimp 1.0 into support mode so I'm not paying too much attention to chimp 1 at the moment as I'm focussing our limited time on the second coming!
