### ISSUE TITLE
--debugMocha not working with node 8.7

### ISSUE THREAD

**Issue by brucejo75** [xolvio/chimp#660]
Trying to debug my mocha scripts.  Used to work with node-inspector, but now with chrome debugging it does not work for me.  Any workarounds?

Unless I hear better: I will fork chimp and submit a PR for `--inspectMocha` && `--inspectBrkMocha` options.

### Environment
- command line: `chimp --debugMocha --ddp=http://localhost:3080 --mocha --chai --path=tests`
- chimp v0.50.2
- node v8.7.0
- java v1.8.0_144
- OS Windows 10 1703 (OS Build 15063.674)

### Results
```
>npm run chimp-dbg

> MERIS@1.0.0 chimp-dbg E:\mroot\meris
> chimp --debugMocha --ddp=http://localhost:3080 --mocha --chai --path=tests

(node:19168) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

Master Chimp and become a testing Ninja! Check out our course: http://bit.ly/2btQaFu


[chimp] Running...
(node:9412) [DEP0062] DeprecationWarning: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` or `node --inspect-brk` instead.
Mocha failed
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! MERIS@1.0.0 chimp-dbg: `chimp --debugMocha --ddp=http://localhost:3080 --mocha --chai --path=tests`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the MERIS@1.0.0 chimp-dbg script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bruce\AppData\Roaming\npm-cache\_logs\2017-10-25T20_32_02_748Z-debug.log
```

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by samhatoum** [comment]
Thank you for doing this, I'll accept the PR

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
