### ISSUE TITLE
Offtopic: HOW to use chimp as a pre-configured webdriverio setup?

### ISSUE THREAD

**Issue by thebarty** [xolvio/chimp#662]
# Question:
**Is there a way to use chimp's pre-configured webdriver-instance OUTSIDE of tests?**

I'd love to use it for a non-test usecase and love the sync-style-api.

# Background
Webdriverio does NOT make it easy to use it's sync-api in standalone mode (see https://github.com/webdriverio/webdriverio/issues/2383), so I am wondering if anyone knows a quick hack based on chimp.

PLUS a lot of work has been put into chimp, for easy chrome support etc...

**Comment by lgandecki** [comment]
why don't you want to use await/async ? :) that way you get rid of a middle-man, that needs to be maintained, and can have bugs lurking around ;) (statistics - the more code you have, the more bugs there are)

**Comment by lgandecki** [comment]
( spoiler: with chimp 2.0 you will be able to just import a browser, with webdriverio api, but you will have to use await/async )

**Comment by samhatoum** [comment]
@thebarty not with the current version but in 2.0 yes. you can start using that now by installing `npm i chimp@next`

**Comment by samhatoum** [comment]
See the chimp2.0 branch for docs
