### ISSUE TITLE
How should I configure chimp?

### ISSUE THREAD

**Issue by Saravana9210** [xolvio/chimp#664]
I'm planning to use chimp with cucumber.js, WebdriverIO and Chai for assertions. Also, I need to configure this as Jenkins project to automate my testing.

How should I configure chimp for this? Which is the configuration file for chimp and where can I find it?

1. where should I mention the location of feature files and step definition files. 
2. Chai configurations
3. WebdriverIO configurations

Any kind of help would be appreciated. Thanks in advance!!!

**Comment by Aracturat** [comment]
@Saravana9210 
It is example of my config (WebdriverIO + Cucumberjs + typescript). I hope it can help you.

```ts
module.exports = {
    path: './tests/e2e/features',
    compiler: 'ts:ts-node/register',
    browser: process.env.BROWSER ? process.env.BROWSER : 'chrome',
    chai: true,
    timeout: 2000,
    e2eTags: '@focus',
    e2eSteps: './tests/e2e/step_definitions',
    format: 'pretty',

    // - - - - CHIMP - - - -
    watch: true,
    watchTags: '@focus',
    watchWithPolling: false,
    sync: true,
    offline: false,

    // - - - - CUCUMBER - - - -
    tags: '@focus',
    conditionOutput: true,

    // - - - - SESSION-MANAGER  - - - -
    noSessionReuse: false,

    // - - - - DEBUGGING  - - - -
    log: 'info',
    debug: true,
    debugCucumber: true,
    debugBrkCucumber: false,
    seleniumStandaloneOptions: {
        drivers: {
            chrome: {
                version: "2.33",
                arch: process.arch
            }
        }
    },
    webdriverio: {
        logLevel: 'silent',
        coloredLogs: true
    }
};

```

**Comment by Saravana9210** [comment]
Hi Aracturat,

Thank you for your reply!

1. My question was **where can I find this config file** and what are these json keys(watch, watchTags, Sync - description of all these)? I couldn't find chimp.config.js anywhere inside /chimp directrory

2. But, there is a default config file called **default.js** under _/chimp/dist/bin/default.js_

3. ANs, if I've to use **cucumber-html-report** (or any other reporting library for example) for reporting, how should I configure that in the config file?

**I basically want to understand deeply about how chimp integrates cucumber.js, selenium webdriver, feature files, reports and jenkins.**


Thanks in advance.

- Saravana

**Comment by Ziinc** [comment]
1. you can find the full chimp config [here](https://github.com/xolvio/chimp/blob/master/src/bin/default.js). Most of the keys are self explanatory, such as watchTags are the tags that chimp will look for in watch mode.  Unfortunately, not all keys are documented.

2. you should create your own config file as recommended in the docs. Whatever options is passed will override the default config options.

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
