### ISSUE TITLE
Chimp 2.0

### ISSUE THREAD

**Issue by casey1111** [xolvio/chimp#667]
We're using Chimp, Cucumber, Chai for acceptance testing on Meteor 1.6 / Node 8+
We've been having trouble with this environment..  odd failures when waiting*, possible timing issues.

Wanted to try Chimp@Next, but we're used to calling chimp as an executable (node_modules/.bin/) which doesn't exist with 2.0. 

I'm not sure how to kick-off these tests now.

Any documentation available on how to get up and running with 2.0 / headless Chrome?

README reads, "No command line runner, no complex tools to setup, you simply import the Chimp browser into your test and it just works"

But, the "just works" part has me baffled.

**Comment by samhatoum** [comment]
Hi @casey1111 

Thank you for the feedback.

I guess we have assumed that users already know how to run their tests using standalone mocha/jasmine/jest. The idea is that you use these frameworks as they were intended to be used without using Chimp to launch them.

The current version of Chimp is a test runner. The @next version is a library that is used inside testing frameworks. 

Have a look at this guide for mocha:
http://alebelcor.github.io/2013/an-introduction-to-mocha/

Where you can see how to use test frameworks without a test runner.

I'll be sure to update the docs.

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
