### ISSUE TITLE
How do I capture the expected image or text on the page using cucumber chimp

### ISSUE THREAD

**Issue by neville4529** [xolvio/chimp#672]
I am very new the chimp, how can capture the image or text on the page using cucumber chimp.
Here is my code:
module.exports = function() {
 this.Give(/^user navigate to bct-test website$/, function () {
    var my_url='https://bct-test.ucdavis.edu/bct_nation/home.seam';
    browser.url('my_url');
  });
 this.When(/^user click Browse Trials$/, function () {
      browser.clickl('#HomeBrowserButton');
  });
//having problem with code below:
this.Then(/^user see All Trials page$/, function () {
      var my_search_result_xpath = '//a[contains(See All Trials", "'searchResult+'")]';
});

**Comment by samhatoum** [comment]
See webdriver.io's API here: http://webdriver.io/api/protocol/screenshot.html
