### ISSUE TITLE
ExpectationFailed: Expected 'BRCA1/2' to contain 'AC Chemo'.   at World.<anonymous> (features/step_definitions/step_defs.js:87:32)

### ISSUE THREAD

**Issue by neville4529** [xolvio/chimp#674]
Having a problem with my code:

Feature file:
Feature: Browse Trials on Web
  As a breast cancer patient
  I want to browse trials on web
  So I can find information

Background:
  Given I have visited bct
  When I click Browse Trials

   
Scenario: Browse Trials
  Then I see "All Trials" link
  Then I see "All Metastatic Trials" link

Scenario: Search negative AND Trials
  When I enter "breast cancer treatments" AND "man" and hit search
  Then I should see "0 trials contain the search term(s):" in the result

Scenario: Search negative OR Trials
  When I enter "breast cancer treatments" OR "man" and hit search
  Then I should see "Women can choose to undergo in vitro fertilization" in the result

Scenario: Sort by zip code
  When I enter "94122" as zip code and hit go
  Then I should see "miles from 94122" in the result

Scenario: Verify the "BRCA1/2" link
  When I click the "BRCA1/2" link
  Then I should see "BRCA1/2"

Scenario: Verify the "Chemotherapy" link
  When I click the "Chemotherapy" link
  Then I should see "AC Chemo"

Step_definations file
module.exports = function() {

  this.Given(/^I have visited bct$/, function () {
    browser.url('https://bct-test.ucdavis.edu/bct_nation/home.seam');
    //browser.pause(30000);
  });

  this.When(/^I click Browse Trials$/, function () {
   	 browser.click('#HomeBrowseButton');
  });

  this.Then(/^I see "([^"]*)" link$/, function (linkName) {
         // Write code here that turns the phrase above into concrete actions
        var my_expected_text = linkName;
	var my_target_xpath = '//div[@class="BrowseTrialsTestEmphasizedLink"]/a[contains(text(),"' + linkName + '")]';
	browser.waitForVisible(my_target_xpath, 10000);
	var my_target_text = browser.getText(my_target_xpath);
	console.log(my_target_text);
   	expect(my_target_text).toContain(my_expected_text);
  });

  this.When(/^I enter "([^"]*)" (AND|OR) "([^"]*)" and hit search$/, function (searchText1, andOr, searchText2) {
         // Write code here that turns the phrase above into concrete actions
         var my_search_term1 = searchText1;
         var my_search_term2 = searchText2;
         var my_andOr = andOr;
         var my_form_xpath = '//form[contains(normalize-space(), "Search ALL trials")]';
         var my_search1_xpath = '(' + my_form_xpath + '//input)[1]';
         var my_search2_xpath = '(' + my_form_xpath + '//input)[2]';
         var my_searchButton_xpath = '(' + my_form_xpath + '//input)[3]';
         var my_andor_xpath = my_form_xpath + '/select';

	 browser.waitForVisible(my_search1_xpath, 10000);
         browser.setValue(my_search1_xpath, my_search_term1);
         console.log(my_andor_xpath);
         console.log(my_andOr);
         browser.click(my_andor_xpath);
         browser.selectByVisibleText(my_andor_xpath, my_andOr);
         browser.setValue(my_search2_xpath, my_search_term2);
         browser.pause(1000);
         browser.click(my_searchButton_xpath);
         browser.pause(1000);
       });

  this.Then(/^I should see "([^"]*)" in the result$/, function (expectedText) {
         // Write code here that turns the phrase above into concrete actions
         var my_expcted_text = expectedText;
         var my_result_xpath = '//div[@class="ContentFramedBox"]';
	 browser.waitForVisible(my_result_xpath, 5000);
         var displayed_text = browser.getText(my_result_xpath);

         expect(displayed_text).toContain(my_expcted_text);
       });

 this.When(/^I enter "([^"]*)" as zip code and hit go$/, function (searchText1) {
        // Sort the zipcode
        var my_search_term1 = searchText1;
	var my_search1_xpath = '//input[@id="Ecom_ReceiptTo_Postal_PostalCode"]';
	var my_searchButton_xpath = '//*[@id="zipGo"]';

	
	browser.waitForVisible(my_search1_xpath, 5000);
	browser.setValue(my_search1_xpath, my_search_term1);
	browser.click(my_searchButton_xpath);
       });

  this.When(/^I click the "([^"]*)" link$/, function (searchText1) {
         // click BRCA1/2 link
	var my_search_term1 = searchText1;
        var my_search1_xpath = '//a[contains(text(), "BRCA")]';

	browser.waitForVisible(my_search1_xpath, 5000);
	browser.click(my_search1_xpath);
       });

  this.Then(/^I should see "([^"]*)"$/, function (expectedText) {
         // Write code here that turns the phrase above into concrete actions
	 // expected result = "BRCA1/2"
        var my_expcted_text = expectedText;
	var my_result_xpath = '//div[@class="ContentHeaderText"]';
	browser.waitForVisible(my_result_xpath, 5000);
        var displayed_text = browser.getText(my_result_xpath);

        expect(displayed_text).toContain(my_expcted_text);
	//expect(displayed_text).toContain(my_expcted_text1);
       });

  this.When(/^I click the ""Chemotherapy" link$/, function (searchText1) {
         // click Chemotherapy link
	var my_search_term1 = searchText1;
        var my_search1_xpath = '//a[contains(text(), "Chemotherapy")]';

	browser.waitForVisible(my_search1_xpath, 5000);
	browser.click(my_search1_xpath);
     });

  this.Then(/^"I should see "AC Chemo"$/, function (expectedText1) {
         // expected result = "Chemothrapy"
	var my_expcted_text = expectedText1;
        var my_result_xpath = '//div[@id="u-1"]';
	browser.waitForVisible(my_result_xpath, 5000);
        var displayed_text = browser.getText(my_result_xpath);

	console.log(my_expcted_text);
        expect(displayed_text).toContain(my_expcted_text);
      });

}
Run Log:
Feature: Browse Trials on Web

    As a breast cancer patient
    I want to browse trials on web
    So I can find information

  Scenario: Browse Trials
  ✔ Given I have visited bct
  ✔ When I click Browse Trials
All Trials (644)
  ✔ Then I see "All Trials" link
All Metastatic Trials (308)
  ✔ Then I see "All Metastatic Trials" link

  Scenario: Search negative AND Trials
  ✔ Given I have visited bct
  ✔ When I click Browse Trials
//form[contains(normalize-space(), "Search ALL trials")]/select
AND
  ✔ When I enter "breast cancer treatments" AND "man" and hit search
  ✔ Then I should see "0 trials contain the search term(s):" in the result

  Scenario: Search negative OR Trials
  ✔ Given I have visited bct
  ✔ When I click Browse Trials
//form[contains(normalize-space(), "Search ALL trials")]/select
OR
  ✔ When I enter "breast cancer treatments" OR "man" and hit search
  ✔ Then I should see "Women can choose to undergo in vitro fertilization" in the result

  Scenario: Sort by zip code
  ✔ Given I have visited bct
  ✔ When I click Browse Trials
  ✔ When I enter "94122" as zip code and hit go
  ✔ Then I should see "miles from 94122" in the result

  Scenario: Verify the "BRCA1/2" link
  ✔ Given I have visited bct
  ✔ When I click Browse Trials
  ✔ When I click the "BRCA1/2" link
  ✔ Then I should see "BRCA1/2"

  Scenario: Verify the "Chemotherapy" link
  ✔ Given I have visited bct
  ✔ When I click Browse Trials
  ✔ When I click the "Chemotherapy" link
  ✖ Then I should see "AC Chemo"

Failures:

1) Scenario: Verify the "Chemotherapy" link - features/browsetrial.feature:31
   Step: Then I should see "AC Chemo" - features/browsetrial.feature:33
   Step Definition: features/step_definitions/step_defs.js:79
   Message:
     ExpectationFailed: Expected 'BRCA1/2' to contain 'AC Chemo'.
         at World.<anonymous> (features/step_definitions/step_defs.js:87:32)

6 scenarios (1 failed, 5 passed)
24 steps (1 failed, 23 passed)
1m13.299s

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
