### ISSUE TITLE
Chimp on windows 10 problem

### ISSUE THREAD

**Issue by MacroS88** [xolvio/chimp#676]
Hello I am having a problem with my chimp.js setup on Windows 10, I never used chimp on Windows env however this time I am forced to do so. While I am trying to run my first scenario which I prepared there is weird error message in the console:
![przechwytywanie1](https://user-images.githubusercontent.com/35797069/35378383-e50d88dc-01b2-11e8-9a40-05573bda589a.PNG)

My chimp config is there
https://gist.github.com/MacroS88/2235bc657fcb5740548c9c434fce8307

My support hook (which is not even running actually - checked using console.log)

```
module.exports = function () {
  this.registerHandler('BeforeFeature', () => {
    console.log('stepHook');
    browser.url('http://localhost:8888');
    browser.pause(1000);
  });
};

```

Any help will be highly appreciated

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
