### ISSUE TITLE
Chimp.js Chromedriver version configuration not being applied

### ISSUE THREAD

**Issue by KristianWindsor** [xolvio/chimp#686]
From my chimp.js configuration file
```
// - - - - SELENIUM-STANDALONE
    seleniumStandaloneOptions: {
        drivers: {
            chrome: {
                version: '2.37'
            }
        }
    },
```
but when running `npm install`, the latest version of Chromedriver is installed rather than the version I specified. How can I choose to install a specific version of Chromedriver?

**Comment by xywang68** [comment]
@Windso , to install different versions of selenium and drivers, you can modify the lib/default-config.js file in your selenium-standalone module. The module is either inside your base node_modules/ if you installed it as your base module, or inside chimp's node_modules/ as its dependency.
After that, you can run "selenium-standalone install" to get them installed.
Without updating the default-config.js file, you can provide your own config.js and do "selenium-standalone install --config=<path to your config.js>.
obvious you need to provide full path to selenium-standalone script. Normally it is in node_modules/.bin if you install it yourself, or inside chimp/node_modules if it is installed as a dependency.
Hope this information helps.

**Comment by samhatoum** [comment]
This issue is being tracked in Chimpy 
https://github.com/TheBrainFamily/chimpy/issues
