### ISSUE TITLE
Security vulnerability

### ISSUE THREAD

**Issue by rodrigok** [xolvio/chimp#692]
#####  Expected behaviour
No security vulnerabilities

#####  Actual behaviour
GitHub alert us about security vulnerability and we could find the source been chimp package.

| DEPENDECY | USED BY |
|--------------|----------|
hoek | boom, sntp, hawk, hapi
boom | hapi, hawk, xolvio-ddp
sntp | hawk
hawk | phantomjs-prebuilt, xolvio-ddp
phantomjs-prebuilt | chimp
hapi | chimp
xolvio-ddp | chimp

#####  Version & tools:

* Chimp: *type `chimp -v`* 0.51.1

![image](https://user-images.githubusercontent.com/234261/41100487-e3175aba-6a37-11e8-9c74-26041dc0f2be.png)

*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by JoeRattanamaneesilp** [comment]
I'm having this issue as well. 
The version of `hapi` in `Chimp v.0.51.1` is `8.8.0`. 

Would it be possible to update the version of `hapi` to be the latest one which is [`17.5.2`](https://www.npmjs.com/package/hapi)?
 
![image](https://user-images.githubusercontent.com/14726381/43117019-fb1f1432-8f4d-11e8-90fa-3061739af785.png)
