### ISSUE TITLE
Error while installing chimp in meteor

### ISSUE THREAD

**Issue by hridyansh68** [xolvio/chimp#695]
#####  Expected behaviour
Chimp getting installed using "sudo npm install -g chimp"

#####  Actual behaviour
Error regarding fibers@1.0.15

#####  Version & tools:

* Chimp command line used: sudo npm install -g chimp
* Node.js: v10.4.0
* Java: java version "10.0.1" 2018-04-17

#####  Console / Log Output

/Users/hridyansh/.nvm/versions/node/v10.4.0/bin/chimp -> /Users/hridyansh/.nvm/versions/node/v10.4.0/lib/node_modules/chimp/bin/chimp.js

> fibers@1.0.15 install /Users/hridyansh/.nvm/versions/node/v10.4.0/lib/node_modules/chimp/node_modules/fibers
> node build.js || nodejs build.js

gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/hridyansh/.nvm/versions/node/v10.4.0/lib/node_modules/chimp/node_modules/fibers/build'
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/hridyansh/.nvm/versions/node/v10.4.0/bin/node" "/Users/hridyansh/.nvm/versions/node/v10.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/hridyansh/.nvm/versions/node/v10.4.0/lib/node_modules/chimp/node_modules/fibers
gyp ERR! node -v v10.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
sh: nodejs: command not found
npm WARN chai-as-promised@6.0.0 requires a peer of chai@>= 2.1.2 < 4 but none is installed. You must install peer dependencies yourself.

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fibers@1.0.15 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the fibers@1.0.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hridyansh/.npm/_logs/2018-06-18T06_59_52_456Z-debug.log

------- 
*Join our Slack [xolv.io/community](http://xolv.io/community) #chimp channel, where you can find help and help others.*

**Comment by lgandecki** [comment]
You might have messed up permissions in your folder structure, this line suggests so:

gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/hridyansh/.nvm/versions/node/v10.4.0/lib/node_modules/chimp/node_modules/fibers/build'

you should probably do something like

chown -R hirdyansh /Users/hridyansh/.nvm/

**Comment by hridyansh68** [comment]
There was a problem with the version of node that I was using. Resolved now.

**Comment by lgandecki** [comment]
Please leave at least some very short explanation of the solution so people that get here can get some helpful information. 

I'm sure you googled things before where the description of the problem is similar to yours, just to find, to your frustration, that the answer is "google it!" or "I figured it out". :-)
