### ISSUE TITLE
Global and save-dev instalation. Which should I use?

### ISSUE THREAD

**Issue by gustawdaniel** [xolvio/chimp#700]
In README there is suggested manner of installation

    npm install -g chimp

but what do you think about

    npm install --save-dev chimp

It is not recommended? Has installation as developing dependency any advantages or drawbacks in comparison to global installation?

**Comment by samhatoum** [comment]
you're right @gustawdaniel. Saving local is better, that documentation is old!

**Comment by samhatoum** [comment]
This should be posted in chimpy now
https://github.com/TheBrainFamily/chimpy
Thanks!
