### ISSUE TITLE
Unclear status of documentation.

### ISSUE THREAD

**Issue by gustawdaniel** [xolvio/chimp#701]
In description of this project there is written

> Develop acceptance tests & end-to-end tests with realtime feedback http://chimp.readme.io

but link:

http://chimp.readme.io

presents:

![screenshot from 2018-11-08 16-22-29](https://user-images.githubusercontent.com/16663028/48208180-8a3f9600-e372-11e8-883d-bbb85f114fcb.png)

After clicking on "PROJECT HAS MOVED HERE" I am redirected to 

https://github.com/TheBrainFamily/chimpy

that contains first version of this project and some explanations about splitting.

But in readme of this repository I can find this part:

```
Documentation
Read the full documentation site.

(Thank you to Readme.io for the OSS <3)
```

with link to mentioned:

https://chimp.readme.io/docs

There is not full documentation or I cant find it. But in README.md I see:

```
Having trouble? See the installation documentation.
```

with link to:

https://chimp.readme.io/docs/installation

where I can see command `npm install chimpy` but `chimpy` if I correctly understand explanations on page https://github.com/TheBrainFamily/chimpy is first version of this project, but this repo should contain `Chimp 2.0`. Anyway package.json contains "version": "0.51.1"...

There is also link to page that gave me some hope

> https://www.qualityfaster.com/?utm_source=XolvOSS&utm_medium=OSSGitHub&utm_content=ChimpGitHubReadme&utm_campaign=QFLaunch

And I wanted to learn this but after typing my email I see only:

```
We are still working on it :)

The guide will contain a lot of free content, and full access will be priced $79.

If you give us your email address, we promise not to send you spam and we will notify you as soon as we're ready.
You're in! Why not follow us out on Twitter and Medium too?
```

I totally confused. I did not obtained any email, I do not want to follow nothing nowhere, only get docs of this pacage.

Finally I found in package.json dependency "deep-extend": "^0.4.1", that is known from "Prototype Pollution" that was pathed in ">=0.5.1". Similar problem I observed in `chimpy` and it is reported there:

https://github.com/TheBrainFamily/chimpy/issues/118

But `chimpy` in comparison with this package has clearly indicated documentation

> https://thebrainfamily.github.io/chimpy/

**Comment by samhatoum** [comment]
Thank you for posting this and giving me the kick up the backside I needed to tidy this mess up. The docs site and the main Chimp github page have both been updated. Appreciate it :)
