### ISSUE TITLE
Error Running Internet Explorer Driver

### ISSUE THREAD

**Issue by sudsy** [xolvio/chimp#71]
{ [Error: The best matching driver provider org.openqa.selenium.edge.EdgeDriver
can't create a new driver instance for Capabilities [{rotatable=true, locationCo
ntextEnabled=true, name=, loggingPrefs=org.openqa.selenium.logging.LoggingPrefer
ences@49f264be, browserName=IE, javascriptEnabled=true, handlesAlerts=true, vers
ion=, platform=ANY, requestOrigins={name=webdriverio, version=3.2.1, url=http://
webdriver.io}}]
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
System info: host: 'MBP-WINDOWS', ip: '172.16.66.130', os.name: 'Windows 7', os.
arch: 'amd64', os.version: '6.1', java.version: '1.8.0_60'
Driver info: driver.version: unknown]

I can successfully test against Chrome and Firefox

**Comment by samhatoum** [comment]
can you provide a little more context please?

**Comment by sudsy** [comment]
I managed to find the answer to this it seems I needed to specify --browser="internet explorer" rather than browser=ie in my particular situation. For more background see:

https://github.com/SeleniumHQ/selenium/issues/906

It seems that the browser names have changed since MS released the new edge browser.

**Comment by samhatoum** [comment]
thanks for reporting back, and the PR

**Comment by SindhuGupta** [comment]
Hello,

I am facing the same error for safari browser.

Please find the details below:
E/launcher - The best matching driver provider org.openqa.selenium.edge.EdgeDriver can't create a new driver instance for Capabilities [{count=1, browserName=safari}]
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: 'BLRL36257', ip: '172.22.240.106', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_17'
Driver info: driver.version: unknown

Here is my config:

multiCapabilities: [
 {
            browserName: 'safari'
        }
]

Please provide solution.

Thanks,
Sindhu
