### ISSUE TITLE
[xolvio:cucumber] Bad response from Chimp server.

### ISSUE THREAD

**Issue by zeroasterisk** [xolvio/chimp#72]
```
[velocity] Established connection with Velocity.
[xolvio:cucumber] Cucumber is running
[chimp] Finished running async processes with errors
[chimp] run complete with errors [Error: Another Selenium process is already running]
[chimp] Could not get Cucumber Results from run result:
[ undefined, [ undefined ] ]
[xolvio:cucumber] Bad response from Chimp server.
```

![ss](http://puu.sh/k6LE5/d34b6467ee.png)

```
alan            80627   0.0  0.7  3147416 121272   ??  S     4:01PM   0:01.55 /Users/alan/.meteor/packages/velocity_meteor-tool/.1.1.4_2.12re4pp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node /Users/alan/.meteor/packages/xolvio_cucumber/.0.13.8.17ci1po++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/bin/chimp -r /Users/alan/Dev/AHM/GFF/prototype1/admin/tests/cucumber/features --snippets --ddp=http://localhost:64569/ --log=error --screenshotsPath=/Users/alan/Dev/AHM/GFF/prototype1/admin/tests/cucumber/.screenshots --tags=@dev --server --serverPort=8866
alan            80626   0.0  0.1  3065476  14656   ??  Ss    4:01PM   0:00.05 /Users/alan/.meteor/packages/velocity_meteor-tool/.1.1.4_2.12re4pp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node /private/var/folders/_q/8jh0f25s4xd5wj0h6p0zd0hr0000gn/T/meteor-test-run1frn2f4/.meteor/local/build/programs/server/assets/packages/sanjo_long-running-child-process/lib/spawnScript.js 80577 Chimp_8866 /Users/alan/.meteor/packages/velocity_meteor-tool/.1.1.4_2.12re4pp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node /Users/alan/.meteor/packages/xolvio_cucumber/.0.13.8.17ci1po++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/chimp/bin/chimp -r /Users/alan/Dev/AHM/GFF/prototype1/admin/tests/cucumber/features --snippets --ddp=http://localhost:64569/ --log=error --screenshotsPath=/Users/alan/Dev/AHM/GFF/prototype1/admin/tests/cucumber/.screenshots --tags=@dev --server --serverPort=8866
```

This is a pretty simple meteor application, fresh install of `xolvio:cucumber` and using the sample specifications files.

**Comment by samhatoum** [comment]
Do you have Java installed on the machine?

**Comment by luccamordente** [comment]
I'm also having this problem after upgrading to node 4.0.0

**Comment by samhatoum** [comment]
do you have Java installed on the machine?

**Comment by luccamordente** [comment]
Now I do. It's working, thanks!

**Comment by samhatoum** [comment]
@zeroasterisk does this fix it for you too?

**Comment by samhatoum** [comment]
@luccamordente you're welcome!

**Comment by samhatoum** [comment]
@zeroasterisk I was able to see this error. It happens when you have an older version of java. You should be using Java 1.7 or above. If you have trouble upgrading on OSX, try installing the JDK instead of the JRE. I'll add these instructions to the http://chimp.readme.io site. Let me know if this doesn't work for you, closing for now

**Comment by borisfeldmann** [comment]
@samhatoum Hi there, I still have the same problem after following the tips in this post carefully. I removed Java 6 from Yosemite (Mac OS X 10.10) and installed the latest Java 8 Update 60. My application is the tutorial Letterpress from your book Meteor testing. So just a new meteor app with xolvio:cucumber package added and one first test created through the velocity-html button.

After all I get the error:
```
[xolvio:cucumber] Cucumber is running
[chimp] Finished running async processes with errors
[chimp] run complete with errors [Error: Another Selenium process is already running]
[chimp] Could not get Cucumber Results from run result:
[ undefined, [ undefined ] ]
[xolvio:cucumber] Bad response from Chimp server.
{ statusCode: 200,
  content: '',
  headers: 
   { 'content-type': 'application/json; charset=utf-8',
     'cache-control': 'no-cache',
     'content-length': '0',
     date: 'Sat, 03 Oct 2015 05:57:19 GMT',
     connection: 'keep-alive' },
  data: null }
```
Any ideas?
Thanks, Boris

**Comment by samhatoum** [comment]
when you type `java -version` in a command prompt, what do you see?

**Comment by borisfeldmann** [comment]
java version "1.6.0_65"

So it seems, I did not get rid of Java 6?

**Comment by samhatoum** [comment]
you need to install the JDK not the JRE ;)

**Comment by borisfeldmann** [comment]
Great! Everything works as expected. Thanks for your quick help and the book "Meteor Testing". I am looking forward to read the coming chapters ;-)
Boris

**Comment by lorensr** [comment]
This fixed the problem for me on OS X. JDK link:

http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by shiftux** [comment]
Hello 

I get the same error: 

[chimp] Could not get Cucumber Results from run result:
[ undefined, [ undefined, null ] ]
[xolvio:cucumber] Bad response from Chimp server.
{ statusCode: 200,
  content: '',
  headers: 
   { 'content-type': 'application/json; charset=utf-8',
     'cache-control': 'no-cache',
     'content-length': '0',
     date: 'Wed, 02 Dec 2015 09:35:47 GMT',
     connection: 'keep-alive' },
  data: null }

and my java -version is: 
java version "1.7.0_91"
OpenJDK Runtime Environment (rhel-2.6.2.2.el6_7-x86_64 u91-b00)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)

what else could cause this?
thanks

**Comment by borisfeldmann** [comment]
Hey,

Sometimes I could solve this error by quitting WebStorm and Chrome and then starting WebStorm and Meteor first before starting Chrome again.

Boris

Von meinem iPhone gesendet

Am 02.12.2015 um 11:36 schrieb shiftux <notifications@github.com<mailto:notifications@github.com>>:


Hello

I get the same error:

[chimp] Could not get Cucumber Results from run result:
[ undefined, [ undefined, null ] ]
[xolvio:cucumber] Bad response from Chimp server.
{ statusCode: 200,
content: '',
headers:
{ 'content-type': 'application/json; charset=utf-8',
'cache-control': 'no-cache',
'content-length': '0',
date: 'Wed, 02 Dec 2015 09:35:47 GMT',
connection: 'keep-alive' },
data: null }

and my java -version is:
java version "1.7.0_91"
OpenJDK Runtime Environment (rhel-2.6.2.2.el6_7-x86_64 u91-b00)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)

what else could cause this?
thanks

—
Reply to this email directly or view it on GitHub<https://github.com/xolvio/chimp/issues/72#issuecomment-161253059>.

---
Werkdigital GmbH
Boris Feldmann, Dipl.-Ing. (FH)
Geschäftsführender Gesellschafter

---
Fon: +49 2721 94925 20
Mob: +49 151 23042508
Fax: +49 2721 94925 90

---
Agathastraße 63
57368 Lennestadt
Germany

---
www.werkdigital.de

---
Sitz der Gesellschaft: Lennestadt
Amtsgericht Siegen / HRB 9350
Geschäftsführung: Dipl.-Inform. Dennis Conze / Dipl.-Ing. (FH) Boris Feldmann

**Comment by shiftux** [comment]
hey
thanks for the response, unfortunately it did not help... (I'm not using WebStorm though)
s.

**Comment by samhatoum** [comment]
which version of chrome do you use?

Also, openjdk is not advised, you should use the oracle version

**Comment by amarakgec** [comment]
Dear @samhatoum ,

i am getting error when run meteor application and i unable to find out where is problem please help me--



[velocity] Mirror has established connection with Velocity.
[xolvio:cucumber] Cucumber is running
[selenium] [Error: Could not request headers from http://selenium-release.storage.googleapis.com/2.47/IEDriverServer_Win32_2.47.0.zip: Error: read ECONNRESET]
[chimp] Finished running async processes with errors
[xolvio:cucumber] Bad response from Chimp server.
[chimp] run complete with errors [Error: Could not request headers from http://selenium-release.storage.googleapis.com/2.47/IEDriverServer_Win32_2.47.0.zip: Error: read ECONNRESET]
[chimp] Could not get Cucumber Results from run result:
[ undefined, [ undefined ] ]
{ statusCode: 200,
  content: '',
  headers: 
   { 'content-type': 'application/json; charset=utf-8',
     'cache-control': 'no-cache',
     'content-length': '0',
     date: 'Mon, 19 Dec 2016 06:09:55 GMT',
     connection: 'keep-alive' },
  data: null }

java version "1.8.0_111"

**Comment by samhatoum** [comment]
@amarakgec you need to stop using Velocity :) No support is available for it. Please see the meteor guide on testing and I kindly ask that you stop posting Velocity related issues on the chimp repo. Thanks
