### ISSUE TITLE
Using wdio.conf.js

### ISSUE THREAD

**Issue by bardt** [xolvio/chimp#77]
As Chimp is using webdriver.io internally, it would be great to use wdio.conf.js you probably already have. Is there a way to pass a configuration file instead of specify everything via command line parameters?

**Comment by richardruiter** [comment]
+1

**Comment by samhatoum** [comment]
This is not really possible. Chimp is a test runner and the wdio.conf.js file is used by the test-runner portion of wdio. I'm working on externalize the config to a `chimp.conf.js` file though as there are many many params now!
