### ISSUE TITLE
Chimp module file not created in node_modules folder after Installation

### ISSUE THREAD

**Issue by arif-globant** [xolvio/chimp#81]
After installing chimp using "npm install chimp" cmd, chimp module file "chimp\bin\chimp" is not created in node_modules folder.
NPM version: 3.3.6
Nodejs version: 4.2.0

**Comment by arif-globant** [comment]
On windows there are some dependencies with .Net framework and Python to download first, before installing chimp. After installing the dependencies, chimp got installed properly.

**Comment by brimstonejaq** [comment]
I appear to be having a problem with these dependencies, and can't find any documentation on them. I tried installing python, and still was getting "". I also tried updating npm, and haven't been able to make any progress. Could you tell me how you got it to install successfully?

**Comment by arif-globant** [comment]
Check if there are still any other dependencies that need to be installed like .Net framework or Microsoft Visual Studio or Python.

1) Install Python and set path in computer Environment variables.
2) Install MS build from https://www.microsoft.com/en-us/download/details.aspx?id=48159  
3) Install Visual Studio community edition 2015
   https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs.aspx 
4)Also install cl.exe from Visual Studio tool and set path. (Only If cl.exe is missing in VS installation)

Because chimp will not get installed till all the dependencies are installed properly.
