### ISSUE TITLE
after upgrading screenshots are saved and in wrong location

### ISSUE THREAD

**Issue by samhatoum** [xolvio/chimp#87]
_From @SierraGolf on October 11, 2015 18:32_

previous version: 0.8.9
new version: 0.14.6

after upgrading running ```meteor --test``` now saves screenshots in tests/cucumber. previously this did not save screenshots, only when running in "ci-mode".

currently I have to set SAVE_SCREENSHOTS=1 so that the screenshots are actually saved in the correct location (tests/cucumber/.screenshots) and regular .gitignore rules kick in.

_Copied from original issue: xolvio/meteor-cucumber#226_

**Comment by samhatoum** [comment]
We recently updated --test to also set VELOCITY_CI for Cucumber, it was a bug that it wasn't doing it before. Are you saying that the `.screenshots` dir is no longer being created in --test?

**Comment by samhatoum** [comment]
_From @SierraGolf on October 20, 2015 18:57_

I am saying that the screenshots are not saved in ```tests/cucumber/.screenshot``` dir if I do not set ```SAVE_SCREENSHOTS=1```. instead they are saved in ```tests/cucumber```

**Comment by SierraGolf** [comment]
I just upgraded from 0.14.10 to 0.19.3_1 and now every step creates a screenshot, even if it is not failing?! guys I really love what you are doing but recently every upgrade brings some new surprises with the configuration that behaves completely different than before.

I am pretty sure the reason for this behaviour is the now added env
```
'chimp.captureAllStepScreenshots': 'false'
```

and the broken "boolean" check (you gotta love javascript) [here](https://github.com/xolvio/chimp/blob/00dc0c1642f743d3ff89e350f52a0a4f551cee13/lib/cucumberjs/hooks.js#L28).

**Comment by samhatoum** [comment]
ha, yes. thanks. pushing new version now...

**Comment by SierraGolf** [comment]
hehe, I was just about to make a PR. thanks for pushing.

**Comment by samhatoum** [comment]
are you still having the .screnshots dir issue?

**Comment by SierraGolf** [comment]
yep. are you not able to reproduce it?

**Comment by SierraGolf** [comment]
actually, when I check the documentation it seems like this behaviour is now intentional: https://chimp.readme.io/docs/command-line-options. here it says the default path is ```.``` which truely is kind of relativ expression :) but it does not say inside the ```.screenshots``` folder anymore

**Comment by samhatoum** [comment]
for meteor though, this should happen:
https://github.com/xolvio/chimp/blob/master/meteor/src/mirror-server.js#L291

are you running chimp directly without meteor?

**Comment by SierraGolf** [comment]
nope.

**Comment by SierraGolf** [comment]
I mean you are right, it is called but only if I provide one of the following two envs: SAVE_SCREENSHOTS || VELOCITY_CI. Since I obviously do not set VELOCITY_CI when running locally with ```meteor run``` it does not set the path. so I set SAVE_SCREENSHOTS and it works as expected.
```
    if (process.env.SAVE_SCREENSHOTS || process.env.VELOCITY_CI) {
      args.push('--saveScreenshots=true');
      args.push('--screenshotsPath=' + _getScreenshotsDir());
    }
```

I guess the reason is, every unset property from the meteor "context" gets its default values from [here](https://github.com/xolvio/chimp/blob/88e7ad72f402e272f5d8499d8322eac7234793a9/bin/chimp#L25).

**Comment by SierraGolf** [comment]
or [here](https://github.com/xolvio/chimp/blob/00dc0c1642f743d3ff89e350f52a0a4f551cee13/chimp.json#L22)?

**Comment by nhantamdo** [comment]
@samhatoum @SierraGolf guys, how do I disable screenshots?

**Comment by SierraGolf** [comment]
I think sam is working on a fix. until then you can just rollback to a previous version I guess.

**Comment by SierraGolf** [comment]
this is not fixed. although I am also talking about always saving screenshots in dev (which is fixed), this issue is about the broken path problem. the path when running from meteor is still set to ```.``` as default instead of ```.screenshots```.

**Comment by SierraGolf** [comment]
@samhatoum can you re-open this issue?

**Comment by samhatoum** [comment]
we've decommissioned xolvio:cucumber - please update to chimp - this shouldn't happen using it
