### ISSUE TITLE
Allow users to specify mirror port for facbook auth etc.

### ISSUE THREAD

**Issue by samhatoum** [xolvio/chimp#90]
_From @samhatoum on October 4, 2015 20:55_

See here:

https://forums.meteor.com/t/how-can-i-enable-login-to-velocity-mirror-apps-that-have-varying-port-numbers-for-an-app-that-uses-oauth-login-with-a-fixed-redirect-uri/7185/2

_Copied from original issue: xolvio/meteor-cucumber#219_

**Comment by elijahlofgren** [comment]
I'd love to see this implemented soon as I'm using Chimp for automated testing of a Meteor app that uses Facebook for logins and the port number keeps varying whenever I restart the app. Thanks! I really appreciate your work on Chimp.

**Comment by workflow** [comment]
This is not the feature asked for here, but if you feel brave enough to stub your dependencies on external APIs like facebook (which I've come to believe is a good idea in acceptance testing), then maybe this could be for you: 

https://atmospherejs.com/dropz/facebook-fake
