### ISSUE TITLE
Help: Example Requested: submitForm()

### ISSUE THREAD

**Issue by samhatoum** [xolvio/chimp#92]
_From @zeroasterisk on October 2, 2015 4:41_

WebdriverIO allows `submitForm()` but I can not get it to work in any step definition.

```js
    this.When(/^I submit the form "([^"]*)"$/, function (selector) {
      // TODO this is not really working right now...
      return this.client.waitForVisible(selector).
        submitForm(selector).should.become(true);
        // submitForm(selector); // timeout
        // submitForm(selector).should.become(true); // expected { Object (state, sessionId, ...) } to deeply equal true
        // submitForm(selector).should.eventually.equal(true); // returns a promise object
        // submitForm(selector).should.eventually.exist(); // prop. exist is not a function
        // submitForm(selector).should.exist(); // prop. exist is not a function
        // submitForm(selector).should.eventually.exist; // timeout
    });
```

Honestly - I'd really appreciate some more examples, in this Meteor + Webdriver + Jasmine/Chai hybrid world you've got going on.  I'm unable to find many working patterns to follow.

* `click()`
* `submitForm()`
* `url()` _value_

I've figured out many of the WebdriverIO API commands, but some are just not working for me yet.

_Copied from original issue: xolvio/meteor-cucumber#218_

**Comment by samhatoum** [comment]
Hey @zeroasterisk 

Have you seen the [WebdriverIO gitter channel](https://gitter.im/webdriverio/webdriverio)?  it's the best place to get help for webdriver specific things

I notice that you're using the chained syntax. If you are on the latest chimp/meteor-cucumber build, you should read the migration guide on [chimp.readme.io](https://chimp.readme.io/docs/migrate-to-synchronous-style)

**Comment by samhatoum** [comment]
may I close this now?

**Comment by zeroasterisk** [comment]
This question was before I upgraded to the latest version, where you had switched to Jasmine and sync.  Things are now working a lot better now.

thank you very much, close away.

**Comment by samhatoum** [comment]
Welcome
