### ISSUE TITLE
Is this project using Git Flow workflow like Velocity core?

### ISSUE THREAD

**Issue by samhatoum** [xolvio/chimp#96]
_From @rhyslbw on September 27, 2015 5:49_

Currently there's no `develop` branch so I can only submit a PR against `master`. I want to patch the security issue where in debug mode [all env](https://github.com/xolvio/meteor-cucumber/blob/master/src/mirror-server.js#L257) vars are [logged](https://github.com/xolvio/meteor-cucumber/blob/master/src/mirror-server.js#L264).

_Copied from original issue: xolvio/meteor-cucumber#212_

**Comment by samhatoum** [comment]
_From @rhyslbw on September 27, 2015 6:47_

I've submitted #213 against `master`, but would be good to see a `develop` branch as the foundation for the next release

**Comment by samhatoum** [comment]
We were in the process of setting up continuous deployment - but that's not happened yet so I'll add gitflow until then

**Comment by rhyslbw** [comment]
:+1:

**Comment by samhatoum** [comment]
It is now!

**Comment by rhyslbw** [comment]
Nice one
