### ISSUE TITLE
Best Practice: Waiting until stuff is loaded/ready before proceeding

### ISSUE THREAD

**Issue by samhatoum** [xolvio/chimp#97]
_From @workflow on September 1, 2015 9:21_

Would love to know if you guys know of a way to

![allthethings](https://cloud.githubusercontent.com/assets/1276854/9600340/f11ff7ca-509a-11e5-8a00-82ab5fe8fb69.jpg)

In particular:

1. Wait for DOM, images and all JS libraries to be completely loaded

2. Wait for subscription(s) to be ready (something like Blaze's `Template.instance().subscriptionsReady()` or iron router's `ready()`)

...before executing the next step.

Right now, the best I can do is iteratively add `pause()`s that will keep scenarios from flickering when the environment becomes slow.

This does not prevent the occasional flickering on very slow machines or performance outliers, while slowing things down significantly for all the faster environments. A better way exist, there must!

_Copied from original issue: xolvio/meteor-cucumber#206_

**Comment by samhatoum** [comment]
Sorry I missed this. To answer your question, I would ask what is it that a user waits for before being able to use the app? That is, if I'm a user with a super slow machine, how would I know to start pressing buttons? Whatever that answer is, is the same answer you should get Webdriver to wait for :)

**Comment by samhatoum** [comment]
_From @workflow on September 21, 2015 21:37_

That's a great thought pattern and I'll try to adopt it, thx!

There's one case I'm still having that I don't really see as fitting the bill.
Since every scenario creates a fresh & clean database and factory data from scratch, sometimes there are some quite massive blocks of "setting up stuff" happening in our steps. This is mostly done on the server side, and will trigger some client side updates that are hard to wait for in an effective way. Since this amount of "inserting data at once" could never happen through the interface in a real-life situation, there are no client-side measures (such as loading screens) in place that I could leverage. See what I mean?
My current workaround is to wait for a couple of seconds, to be sure the subscription is ready - but this obviously leads to sleepy steps.
Is there a better way or am I missing something here?

Please do feel free to close the issue when you feel this gets out of bound. Thank you for your work!

**Comment by samhatoum** [comment]
if you use `server.call` then you can setup all you need using the server directly in the Given steps, then when the data is all loaded, you use the `browser.url` command in a When step, which would be the same as a user coming to your site when it already has data in it. So load the db then load the page and you should be good.

**Comment by workflow** [comment]
Thx Sam, together with your previous advice the timing on our tests is starting to look much better!

For the visible stuff: We now have a global loading indicator class (.loading) that we try to inject into the DOM whenever anything anywhere in the interface is still loading.
That means I can use a state helper: 

```
module.exports = function () {
    this.Before(function () {

        this.StateHelper = {

            /**
             *
             * Make sure everything in the app has loaded
             */
            waitForAllData: function () {
                var loadingIndicator = '.loading';

                browser.waitForExist(loadingIndicator, undefined, true);
            }

        };

    });
};
```

and simply call it whenever a step definition might have a chance of flickering:

```
        this.StateHelper.waitForAllData();
```

From my side, you can close this. Thx for the help!

**Comment by samhatoum** [comment]
Excellent!

You can also create a custom WebdriverIO command that does the above, then you can use:

```
client.addCommand('openApp', function() {
  this.url(process.env.ROOT_URL);
  this.waitForExists('.loading', true);
});
```

Then you can just use this whenever you want to open your app:
`client.openApp()`;
