### ISSUE TITLE
unable to load google map

### ISSUE THREAD

**Issue by samhatoum** [xolvio/chimp#98]
_From @nicolsondsouza on September 1, 2015 6:39_

Hi, I am unable to load google map, because google map loads another gmap file which is "https://maps.googleapis.com/maps-api-v3/api/js/22/2/main.js" but velocity tries to load this file himself and thus generates this error.

XMLHttpRequest cannot load https://maps.gstatic.com/maps-api-v3/api/js/22/2/main.js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

browser-source-map-support.js:82

http://localhost:3000/packages/velocity:source-map-support/.npm/package/node_modules/source-map-support/browser-source-map-support.js

http://devdiggadog.meteor.com
This is the app without velocity,

If I don't have velocity test, gmap loads fine.
Any suggestion or help?
Thanks

_Copied from original issue: xolvio/meteor-cucumber#205_

**Comment by samhatoum** [comment]
_From @BradRyan on September 21, 2015 17:57_

I'm having the same issue.  Any luck?

**Comment by samhatoum** [comment]
_From @nicolsondsouza on September 21, 2015 17:59_

Nope there is no luck here, you need to stimulate the app without gmap.
That's how I solved the test.

**Comment by samhatoum** [comment]
are you only using meteor cucumber or also using mocha/jasmine?

**Comment by samhatoum** [comment]
_From @nicolsondsouza on September 21, 2015 18:4_

Mainly meteor cucumber, and a little bit of Jasmine test.

**Comment by samhatoum** [comment]
_From @BradRyan on September 21, 2015 18:5_

Just cucumber for me.

**Comment by samhatoum** [comment]
_From @BradRyan on September 21, 2015 18:14_

Just confirmed.  If I remove xolvio:cucumber then the error goes away.

**Comment by samhatoum** [comment]
_From @nicolsondsouza on September 21, 2015 18:16_

What I suspected was, it was browser- support. js which was loading gmap
file instead of gmap itself, that lead to cors error and doesn't load the
map.

**Comment by samhatoum** [comment]
Thanks @BradRyan and @nicolsondsouza 

If you could create a simple repro somewhere it would help me focus some time on it.

**Comment by samhatoum** [comment]
_From @BradRyan on September 21, 2015 20:14_

@samhatoum Yep I just reproduced it on the leaderboard app.  I'll share in a minute.

**Comment by samhatoum** [comment]
_From @BradRyan on September 21, 2015 20:36_

@samhatoum Let me know if you have any questions on the error.  Currently have the package removed on my production app so it is functional.
https://github.com/BradRyan/issue-205-meteor-cucumber-reproduction

**Comment by samhatoum** [comment]
Thank you much, that's useful. I'll test it with the next release and see if I can get you a solution

**Comment by samhatoum** [comment]
_From @BradRyan on September 21, 2015 20:38_

Thanks!

**Comment by littleStudent** [comment]
any progress here?
I am having the same problem.

**Comment by nicolsondsouza** [comment]
Stimulate your app without Google map or use leaflet js a better
alternative of gmap.

**Comment by BradRyan** [comment]
... better perhaps if you aren't looking for directions services or traffic predictions.

**Comment by nicolsondsouza** [comment]
Leaflet js do have direction, time and distance.

We have built second version with leaflet js

**Comment by littleStudent** [comment]
what do you mean by `stimulate without Google maps`?
i need googles Autocomplete so i am not sure if leaflet is a good option.
can still someone explain what exactly the problem is here?

**Comment by littleStudent** [comment]
So it is not possible to use velocity for testing when you have google maps included?

**Comment by nicolsondsouza** [comment]
Now that's correct, as of now no.

**Comment by samhatoum** [comment]
we've decommissioned xolvio:cucumber - please update to chimp - this shouldn't happen using it since you can run the test app on port 3000

**Comment by littleStudent** [comment]
no more problems with chimp!
