### ISSUE TITLE
"cucumber - mirror starting" & "loading" messages are shown forever

### ISSUE THREAD

**Issue by samhatoum** [xolvio/chimp#99]
_From @yuri-martynov on August 26, 2015 13:51_

I was trying to setup Velocity & Cucumber following instruction at http://www.meteortesting.com/chapter/velocity but did not succeed. I only see "cucumber - mirror starting". I use Windows 7, WebStorm 10 & Chrome 44.0.2403.157 m

_Copied from original issue: xolvio/meteor-cucumber#201_

**Comment by samhatoum** [comment]
Hi

Can you please follow these instructions to get us some feedback? Thanks!

https://github.com/xolvio/meteor-cucumber/blob/master/CONTRIBUTING.md

**Comment by samhatoum** [comment]
_From @funkyeah on September 15, 2015 21:45_

I'm seeing really slow operation myself and wondering if it might be the same issue. It takes my system on the order of 2.5 minutes to startup Velocity, Cucumber, and get the Velocity modal to its loaded state.

When debugging the slow operation I started with doing
`meteor refresh`
`meteor update`
`meteor remove xolvio:cucumber`
`meteor add xolvio:cucumber`

Normally I'll run: `VELOCITY_DEBUG && meteor`

Takes about 50 seconds for the terminal to show:
```
App running at: http://localhost:3000/
[velocity] cucumber is starting a mirror at http://localhost:44023/.
[velocity] You can see the mirror logs at: tail -f /home/george/projects/humon/.meteor/local/log/cucumber.log
```

Takes 10-20 before cucumber.log shows the proxy has started:
```
=> Using velocity:METEOR@1.1.0.3_2 as requested (overriding Meteor 1.1.0.3)

[[[[[ ~/projects/humon ]]]]]

=> Started proxy.
```

More than a 1:30 for Cucumber.log to show:
```
=> App running at: http://localhost:57537/
[velocity] Established connection with Velocity.
[xolvio:cucumber] Cucumber is running
```

and then another 20+ seconds to get to:
```
0 scenarios
0 steps
[xolvio:cucumber] No features found. Be sure to annotate scenarios you want to run in watch mode with the @dev tag
```

And that is without it having actually run any tests cause I don't have anything marked with the @dev tag as shown in the warning.

**Comment by samhatoum** [comment]
_From @funkyeah on September 15, 2015 21:45_

packages
```
# Meteor packages used by this project, one per line.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

accounts-google
backbone
spiderable
jquery
coffeescript
nemo64:bootstrap
less
typeahead-js
standard-app-packages
mrt:moment
accounts-base
tsega:filter-collections
matb33:collection-hooks
service-configuration
cmather:handlebars-server
email
meteorhacks:fast-render
accounts-password
percolatestudio:percolatestudio-mixpanel
percolatestudio:percolatestudio-migrations
iron:router
zimme:iron-router-active
sacha:spin
ian:accounts-ui-bootstrap-3
meteorhacks:kadira
meteorhacks:npm
npm-container
meteorhacks:unblock
xolvio:cucumber
```

**Comment by samhatoum** [comment]
_From @funkyeah on September 15, 2015 21:46_

versions
```
accounts-base@1.2.0
accounts-google@1.0.4
accounts-oauth@1.1.5
accounts-password@1.1.1
amplify@1.0.0
anti:i18n@0.4.3
autoupdate@1.2.1
backbone@1.0.0
base64@1.0.3
binary-heap@1.0.3
blaze@2.1.2
blaze-tools@1.0.3
boilerplate-generator@1.0.3
callback-hook@1.0.3
check@1.0.5
chuangbo:cookie@1.1.0
cmather:handlebars-server@2.0.0
coffeescript@1.0.6
ddp@1.1.0
deps@1.0.7
ejson@1.0.6
email@1.0.6
fastclick@1.0.3
geojson-utils@1.0.3
google@1.1.5
handlebars@1.0.3
html-tools@1.0.4
htmljs@1.0.4
http@1.1.0
ian:accounts-ui-bootstrap-3@1.2.79
id-map@1.0.3
iron:controller@1.0.8
iron:core@1.0.8
iron:dynamic-template@1.0.8
iron:layout@1.0.8
iron:location@1.0.9
iron:middleware-stack@1.0.9
iron:router@1.0.9
iron:url@1.0.9
jquery@1.11.3_2
json@1.0.3
launch-screen@1.0.2
less@1.0.14
livedata@1.0.13
localstorage@1.0.3
logging@1.0.7
matb33:collection-hooks@0.8.0
meteor@1.1.6
meteor-platform@1.2.2
meteorhacks:async@1.0.0
meteorhacks:fast-render@2.10.0
meteorhacks:inject-data@1.4.1
meteorhacks:kadira@2.23.3
meteorhacks:meteorx@1.3.1
meteorhacks:npm@1.5.0
meteorhacks:picker@1.0.3
meteorhacks:unblock@1.1.0
minifiers@1.1.5
minimongo@1.0.8
mobile-status-bar@1.0.3
mongo@1.1.0
mongo-livedata@1.0.8
mrt:moment@2.8.1
nemo64:bootstrap@3.3.5_2
nemo64:bootstrap-data@3.3.5
npm-bcrypt@0.7.8_2
npm-container@1.2.0
oauth@1.1.4
oauth2@1.1.3
observe-sequence@1.0.6
ordered-dict@1.0.3
package-version-parser@3.0.3
percolatestudio:percolatestudio-migrations@0.7.2
percolatestudio:percolatestudio-mixpanel@0.5.0
practicalmeteor:chai@1.9.2_3
practicalmeteor:loglevel@1.1.0_3
random@1.0.3
reactive-dict@1.1.0
reactive-var@1.0.5
reload@1.1.3
retry@1.0.3
routepolicy@1.0.5
sacha:spin@2.3.1
sanjo:long-running-child-process@1.1.3
sanjo:meteor-files-helpers@1.1.0_7
sanjo:meteor-version@1.0.0
service-configuration@1.0.4
session@1.1.0
sha@1.0.3
simple:json-routes@1.0.4
spacebars@1.0.6
spacebars-compiler@1.0.6
spiderable@1.0.7
srp@1.0.3
standard-app-packages@1.0.5
stylus@1.0.7
templating@1.1.1
tracker@1.0.7
tsega:filter-collections@0.1.5
typeahead-js@0.0.0
ui@1.0.6
underscore@1.0.3
underscorestring:underscore.string@3.0.3_1
url@1.0.4
velocity:chokidar@1.0.3_1
velocity:core@0.9.3
velocity:html-reporter@0.7.3
velocity:meteor-internals@1.1.0_7
velocity:shim@0.1.0
velocity:source-map-support@0.3.2_1
webapp@1.2.0
webapp-hashing@1.0.3
xolvio:cucumber@0.13.8
zimme:iron-router-active@1.0.4

```

**Comment by samhatoum** [comment]
how long does your app take to refresh without cucumber?

**Comment by samhatoum** [comment]
_From @jorgeer on October 6, 2015 10:22_

Having the exact same issue. Started after I upgraded to meteor 1.2

It takes several minutes to start up the testing server, (between "Triggering queued startup functions" and "Mirror registered"), and my main server is just loading forever.

Without cucumber it starts i 15 seconds roughly.

**Comment by samhatoum** [comment]
_From @funkyeah on October 6, 2015 18:29_

Whoops missed the question... mine takes about 15-30s without Velocity.

Are there any additional steps I can take to get more verbose insight into what Velocity is doing and/or waiting for?

**Comment by samhatoum** [comment]
we've decommissioned xolvio:cucumber - please update to chimp - this shouldn't happen using it

**Comment by neil-s** [comment]
Thanks @samhatoum . It was previously unclear how to use ChimpJS with Meteor, but I see that you've added new documentation to the readme making this easy.
